### ISSUE TITLE
帮忙精简代码 3q 

### ISSUE THREAD

**Issue by KaapoMarcus** [FreeCodeCampChina/freecodecamp.cn#100]
我们有一个对象数组，里面存储着通讯录。

函数 lookUp 有两个预定义参数：firstName值和prop属性 。

函数将会检查通讯录是否存在一个联系人的firstName属性等于firstName值，还会检查对应联系人是否存在 prop属性。

如果它们都存在，函数返回prop属性对应的值。

如果firstName 值不存在，返回 "No such contact"。

如果prop 属性不存在，返回 "No such property"。

//Setup
var contacts = [
{
"firstName": "Akira",
"lastName": "Laine",
"number": "0543236543",
"likes": ["Pizza", "Coding", "Brownie Points"]
},
{
"firstName": "Harry",
"lastName": "Potter",
"number": "0994372684",
"likes": ["Hogwarts", "Magic", "Hagrid"]
},
{
"firstName": "Sherlock",
"lastName": "Holmes",
"number": "0487345643",
"likes": ["Intriguing Cases", "Violin"]
},
{
"firstName": "Kristian",
"lastName": "Vos",
"number": "unknown",
"likes": ["Javascript", "Gaming", "Foxes"]
}
];

function lookUp(firstName, prop){
// Only change code below this line
  for(var i =0;i<contacts.length;i++){
    
    if(contacts[i]["firstName"] !=undefined){
      
      if(contacts[i]["firstName"] == firstName){
       
          if(typeof contacts[i][prop]!="undefined"){
            return contacts[i][prop];
          }else{
            return "No such property";
          }
      }
    }else if(contacts[i]["firstName"]==undefined){
       return "No such contact";
    }
  
  }
 return "No such contact";
  
// Only change code above this line
}

// Change these values to test your function
lookUp("Akira", "address");

**Comment by S1ngS1ng** [comment]
这类问题，请在 QQ 群里提问，或者到 gitter 讨论组。不要放在这里。这里只处理 bug
