### ISSUE TITLE
使用Bootstrap 响应式单选按钮  此处代码被清空了，谁更新一下？

### ISSUE THREAD

**Issue by KaapoMarcus** [FreeCodeCampChina/freecodecamp.cn#101]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/chinese

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by wudifeixue** [comment]
duplicate of #102
