### ISSUE TITLE
【使用Bootstrap 响应式单选按钮】 谁修复一下此处？？

### ISSUE THREAD

**Issue by KaapoMarcus** [FreeCodeCampChina/freecodecamp.cn#102]
Challenge [/codecamp/responsively-style-radio-buttons.html](http://www.w3cschool.cn/codecamp/responsively-style-radio-buttons.html#?solution=%0A%3Cstyle%3E%0Ah2%20%7B%0Afont-family%3A%20Lobster%2C%20Monospace%3B%0A%7D%0A%0A.thick-green-border%20%7B%0Aborder-color%3A%20green%3B%0Aborder-width%3A%2010px%3B%0Aborder-style%3A%20solid%3B%0Aborder-radius%3A%2050%25%3B%0A%7D%0A%3C%2Fstyle%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%3Cdiv%20class%3D%22row%22%3E%0A%3Cdiv%20class%3D%22col-xs-8%22%3E%0A%3Ch2%20class%3D%22text-primary%20text-center%22%3ECatPhotoApp%3C%2Fh2%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20class%3D%22col-xs-4%22%3E%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22img-responsive%20thick-green-border%22%20src%3D%22%2Fstatics%2Fcodecamp%2Fimages%2Frelaxing-cat.jpg%22%3E%3C%2Fa%3E%0A%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cimg%20src%3D%22%2Fstatics%2Fcodecamp%2Fimages%2Frunning-cat.jpg%22%20class%3D%22img-responsive%22%3E%0A%3Cdiv%20class%3D%22row%22%3E%0A%3Cdiv%20class%3D%22col-xs-4%22%3E%0A%3Cbutton%20class%3D%22btn%20btn-block%20btn-primary%22%3E%3Ci%20class%3D%22fa%20fa-thumbs-up%22%3E%3C%2Fi%3E%20Like%3C%2Fbutton%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20class%3D%22col-xs-4%22%3E%0A%20%20%3Cbutton%20class%3D%22btn%20btn-block%20btn-info%22%3E%3Ci%20class%3D%22fa%20fa-info-circle%22%3E%3C%2Fi%3E%20Info%3C%2Fbutton%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20class%3D%22col-xs-4%22%3E%0A%20%20%3Cbutton%20class%3D%22btn%20btn-block%20btn-danger%22%3E%3Ci%20class%3D%22fa%20fa-trash%22%3E%3C%2Fi%3EDelete%3C%2Fbutton%3E%0A%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cp%3EThings%20cats%20%3Cspan%20class%3D%22text-danger%22%3Elove%3A%3C%2Fspan%3E%3C%2Fp%3E%0A%3Cul%3E%0A%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%3Cli%3Elasagna%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%3Col%3E%0A%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%3Cli%3Ethunder%3C%2Fli%3E%0A%3Cli%3Eother%20cats%3C%2Fli%3E%0A%3C%2Fol%3E%0A%3Cform%20fccfaa%3D%22%2Fsubmit-cat-photo%22%3E%0A%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Indoor%3C%2Flabel%3E%0A%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Outdoor%3C%2Flabel%3E%0A%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Loving%3C%2Flabel%3E%0A%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Lazy%3C%2Flabel%3E%0A%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Crazy%3C%2Flabel%3E%0A%3Cinput%20type%3D%22text%22%20placeholder%3D%22cat%20photo%20URL%22%20required%3E%0A%3Cbutton%20type%3D%22submit%22%3ESubmit%3C%2Fbutton%3E%0A%3C%2Fform%3E%0A%3C%2Fdiv%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
undefined

```

**Comment by wudifeixue** [comment]
freecodecamp.cn不存在此问题
