### ISSUE TITLE
Challenge Reverse Arrays with reverse has an issue.

### ISSUE THREAD

**Issue by xiaopf** [FreeCodeCampChina/freecodecamp.cn#105]
Challenge [Reverse Arrays with reverse](https://www.freecodecamp.cn/challenges/reverse-arrays-with-reverse#?solution=var%20array%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%5D%3B%0Avar%20newArray%20%3D%20%5B%5D%3B%0A%0A%2F%2F%20%E5%8F%AA%E8%83%BD%E5%9C%A8%E8%BF%99%E4%B8%80%E8%A1%8C%E4%B8%8B%E9%9D%A2%E5%86%99%E4%BB%A3%E7%A0%81%0A%0AnewArray%20%3D%20array.reverse()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var array = [1,2,3,4,5,6,7];
var newArray = [];

// 只能在这一行下面写代码

newArray = array.reverse();

```
![image](https://cloud.githubusercontent.com/assets/22439112/21842234/ca225ce4-d820-11e6-8243-dba4b7ef707b.png)

![image](https://cloud.githubusercontent.com/assets/22439112/21842253/e3eb214c-d820-11e6-8206-55d6c6203e41.png)

**Comment by xiaopf** [comment]
f5  又好了

**Comment by pioneers01** [comment]
我也出现这个问题了，也是刷新就好了
