### ISSUE TITLE
关于Twichtv.API调用失败问题的解决办法

### ISSUE THREAD

**Issue by hanjinjun** [FreeCodeCampChina/freecodecamp.cn#106]
#### API调用失败的原因
@YQ-Jiang在另一个issue里已经对这个问题进行了说明https://github.com/FreeCodeCampChina/freecodecamp.cn/issues/77  ，是由于Twichtv官网升级导致现在调用时必须添加Client-Id，申请ID可以参照https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843#.d7vmxujt5  

#### 如果你不想自己申请，可以直接使用我申请的
`client_id=q443o8gke0lrzh0bhvlzhv4wd1kw6v`

#### 示例修改
给出的示例http://codepen.io/FreeCodeCamp/full/adBpOw  由于没有client_id的原因无法显示调用后的效果，将示例中JS部分的makeURL函数替换成以下的即可成功展示。
```js
function makeURL(type, name) {
      return 'https://api.twitch.tv/kraken/' + type + '/' + name + '?client_id=q443o8gke0lrzh0bhvlzhv4wd1kw6v&callback=?';
    };
```

**Comment by S1ngS1ng** [comment]
谢谢你的信息。请把这部分内容放到 wiki 板块：https://github.com/FreeCodeCampChina/freecodecamp.cn/wiki

不要放到 issue 里面
