### ISSUE TITLE
Challenge Finders Keepers 需要更清晰的翻译问题

### ISSUE THREAD

**Issue by AlberMonster** [FreeCodeCampChina/freecodecamp.cn#108]
Challenge [Finders Keepers](http://www.freecodecamp.cn/challenges/finders-keepers#?solution=function%20find(arr%2C%20func)%20%7B%0A%20%20var%20result%3B%0A%09if(arr.filter(func).length%20%3D%3D%200)%7B%0A%09%09return%20result%3B%0A%09%7Delse%7B%0A%09%09result%20%3D%20arr.filter(func)%3B%0A%09%09return%20result%3B%0A%09%7D%0A%7D%0A%0Afind(%5B1%2C%202%2C%203%2C%204%5D%2C%20function(num)%7B%20return%20num%20%25%202%20%3D%3D%3D%200%3B%20%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function find(arr, func) {
  var result;
	if(arr.filter(func).length == 0){
		return result;
	}else{
		result = arr.filter(func);
		return result;
	}
}

find([1, 2, 3, 4], function(num){ return num % 2 === 0; });

**Comment by AlberMonster** [comment]
already pass. Do not understand the questions completely. The Task have no bug

**Comment by S1ngS1ng** [comment]
"它浏览数组（第一个参数）并返回数组中第一个通过某种方法（第二个参数）验证的元素"

意思就是，遍历数组（第一个参数），通过第二个参数的方法验证，然后返回这个数组中的第一个元素。可能翻译上有点儿不明确。我们讨论下看如何写比较好。

谢谢你的建议
