### ISSUE TITLE
Help!! SOS!

### ISSUE THREAD

**Issue by AlberMonster** [FreeCodeCampChina/freecodecamp.cn#109]
Challenge [Steamroller](http://www.freecodecamp.cn/challenges/steamroller#?solution=function%20steamroller(arr)%20%7B%0A%20%20%2F%2F%20I'm%20a%20steamroller%2C%20baby%0A%20%20var%20result%20%3D%20judge(arr)%3B%0A%09return%20result%3B%0A%7D%0Avar%20result%20%3D%20new%20Array()%3B%0Afunction%20judge(arr)%7B%0A%09for(var%20i%3D0%3Bi%3Carr.length%3Bi%2B%2B)%7B%0A%09%09if(Array.isArray(arr%5Bi%5D))%7B%0A%09%09%09judge(arr%5Bi%5D)%3B%0A%09%09%7Delse%7B%0A%09%09%09result.push(arr%5Bi%5D)%3B%0A%09%09%7D%0A%09%7D%0A%09return%20result%3B%0A%7D%0A%0Asteamroller(%5B1%2C%20%5B2%5D%2C%20%5B3%2C%20%5B%5B4%5D%5D%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function steamroller(arr) {
  // I'm a steamroller, baby
  var result = judge(arr);
	return result;
}
var result = new Array();
function judge(arr){
	for(var i=0;i<arr.length;i++){
		if(Array.isArray(arr[i])){
			judge(arr[i]);
		}else{
			result.push(arr[i]);
		}
	}
	return result;
}

steamroller([1, [2], [3, [[4]]]]);

```
the output is right,but can not pass? Please help me!

**Comment by LinFeng1997** [comment]
我也遇到了这个问题

**Comment by wudifeixue** [comment]
我仔细去[upstream](https://github.com/FreeCodeCamp/FreeCodeCamp/issues?q=is:issue%20is:all%20Steamroller%20OR%20steamroller)调查了下，大致处理方法 [1](https://github.com/freeCodeCamp/freeCodeCamp/issues/7655) [2](https://github.com/freeCodeCamp/freeCodeCamp/issues/12452) 是不要写全局定义。

**Comment by Jiaget** [comment]
全局变量不能用，只好函数套函数。很气啊，实在想不出其他办法
