### ISSUE TITLE
canvas 不支持？

### ISSUE THREAD

**Issue by LINQQ1212** [FreeCodeCampChina/freecodecamp.cn#11]
Challenge [Say Hello to HTML Element](https://www.freecodecamp.cn/challenges/say-hello-to-html-element#?solution=%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ccanvas%20width%3D%22100px%22%20heihgt%3D%22200px%22%20id%3D%22myCanvas%22%3E%3C%2Fcanvas%3E%0A%3Ch3%3E%2012345%3C%2Fh3%3E%0A%3Cscript%20type%3D%22text%2Fjavascript%22%3E%0Avar%20c%3Ddocument.getElementById%28%22myCanvas%22%29%3B%0Avar%20cxt%3Dc.getContext%28%222d%22%29%3B%0Acxt.fillStyle%3D%22%23FF0000%22%3B%0Acxt.fillRect%280%2C0%2C150%2C75%29%3B%0Afcces) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html
<h1>Hello</h1>
<canvas width="100px" heihgt="200px" id="myCanvas"></canvas>
<h3> 12345</h3>
<script type="text/javascript">
var c=document.getElementById("myCanvas");
var cxt=c.getContext("2d");
cxt.fillStyle="#FF0000";
cxt.fillRect(0,0,150,75);
</script>
```

**Comment by huluoyang** [comment]
canvas是支持的，
但脚本触发了xss-protection，被浏览器禁掉了。
