### ISSUE TITLE
结果正确但是一直不能通过，求助是什么原因(Arguments Optional)

### ISSUE THREAD

**Issue by AlberMonster** [FreeCodeCampChina/freecodecamp.cn#110]
Challenge [Arguments Optional](http://www.freecodecamp.cn/challenges/arguments-optional#?solution=function%20add()%20%7B%0A%20if(arguments.length%20%3D%3D%201)%7B%0A%09%09if(!(typeof%20arguments%5B0%5D%20%3D%3D%3D%20'number'))%7B%0A%09%09%09return%20undefined%3B%0A%09%09%7Delse%7B%0A%09%09%09%09var%20sum%20%3D%20arguments%5B0%5D%3B%0A%09%09%09%09var%20temp%20%3D%20function(y)%7B%0A%09%09%09%09%09if(!(typeof%20y%20%3D%3D%3D%20'number'))%7B%0A%09%09%09%09%09return%20undefined%3B%0A%09%09%09%09%09%7Delse%7B%0A%09%09%09%09%09%09sum%20%3D%20sum%20%2By%3B%0A%09%09%09%09%09%09return%20temp%3B%0A%09%09%09%09%09%7D%0A%09%09%09%09%0A%09%09%09%09%7D%3B%0A%09%09%09%09temp.toString%20%3D%20temp.valueOf%20%3D%20function()%7B%0A%09%09%09%09%09return%20sum%3B%0A%09%09%09%09%7D%3B%0A%09%09%09%09return%20temp%3B%0A%09%09%7D%0A%09%09%0A%09%7Delse%7B%0A%09%09var%20sum%20%3D%200%3B%0A%09%09for(var%20i%3D0%3Bi%3Carguments.length%3Bi%2B%2B)%7B%0A%09%09%09if(typeof%20arguments%5Bi%5D%20%3D%3D%3D%20'number')%7B%0A%09%09%09%09sum%20%2B%3D%20arguments%5Bi%5D%3B%0A%09%09%09%7Delse%7B%0A%09%09%09%09return%20undefined%3B%0A%09%09%09%7D%0A%09%09%7D%0A%09%09return%20sum%3B%0A%09%7D%0A%7D%0A%0Aadd(2)(3)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function add() {
 if(arguments.length == 1){
		if(!(typeof arguments[0] === 'number')){
			return undefined;
		}else{
				var sum = arguments[0];
				var temp = function(y){
					if(!(typeof y === 'number')){
					return undefined;
					}else{
						sum = sum +y;
						return temp;
					}
				
				};
				temp.toString = temp.valueOf = function(){
					return sum;
				};
				return temp;
		}
		
	}else{
		var sum = 0;
		for(var i=0;i<arguments.length;i++){
			if(typeof arguments[i] === 'number'){
				sum += arguments[i];
			}else{
				return undefined;
			}
		}
		return sum;
	}
}

add(2)(3);

```

**Comment by Jarkis** [comment]
~~把最后的add(2)(3)改回add(2,3)。add(2)(3)这种写法好像是不合法的~~

**Comment by S1ngS1ng** [comment]
@AlberMonster 
![image](https://cloud.githubusercontent.com/assets/13592559/22960334/6a25dde6-f302-11e6-91ad-3c45033a2084.png)

这个里面应该 `return sum`

**Comment by S1ngS1ng** [comment]
@Jarkis 题目要求就是要满足 `add(2)(3)` 和 `add(2, 3)` 两种情况。。`add(2)(3)` 是合法的写法

**Comment by zsio** [comment]
add(2)(3)为什么不合法？   返回值是个函数就对了

**Comment by wudifeixue** [comment]
今天在 #264 也遇见这个问题了，bug具体在哪里？

**Comment by S1ngS1ng** [comment]
@wudifeixue 等我搬完家了再断点调一下这个 bug。这两天不太方便=。=

**Comment by wudifeixue** [comment]
嗯，辛苦啦

**Comment by S1ngS1ng** [comment]
@wudifeixue 这个先关了。不是 bug。按照上面说的，改成 `return sum`就没问题
