### ISSUE TITLE
sass

### ISSUE THREAD

**Issue by 531132776** [FreeCodeCampChina/freecodecamp.cn#113]
Challenge [Say Hello to HTML Element](https://freecodecamp.cn/challenges/say-hello-to-html-element#?solution=%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ch1%3EHello%20World) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello</h1>
<h1>Hello World</h1>
```

**Comment by Kaier5** [comment]
the correct code is:
```
<h1>Hello World</h1>
```

the request of this lesson is [change the text in lable h1 to "hello world"], your is added.

**Comment by S1ngS1ng** [comment]
![image](https://cloud.githubusercontent.com/assets/13592559/22959740/44638346-f2fe-11e6-9456-6e4fc5f6a199.png)

According to your link, looks like you forgot to close the tag.

@Kaier5 It could be "add", as long as it contains `hello world`
