### ISSUE TITLE
Check for Palindromes  get someproblems

### ISSUE THREAD

**Issue by feimesi** [FreeCodeCampChina/freecodecamp.cn#116]
"1 eye for of 1 eye." palindrome(str) should be true,not false.

**Comment by wudifeixue** [comment]
No, it is false since "1 eye for of 1 eye."'s palindrome would first be converted to "1eyefor1eye" and then become "eye1forofeye1" if we follow the requirements of the question.

**Comment by feimesi** [comment]
yes.I ignored the numbers.thanks!
