### ISSUE TITLE
网页不跳转了

### ISSUE THREAD

**Issue by Herbert92** [FreeCodeCampChina/freecodecamp.cn#117]
Challenge [Link to External Pages with Anchor Elements](http://www.w3cschool.cn/codecamp/link-to-external-pages-with-anchor-elements.html#?solution=%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A.red-text%20%7B%0Acolor%3A%20red%3B%0A%7D%0A%0Ah2%20%7B%0Afont-family%3A%20Lobster%2C%20Monospace%3B%0A%7D%0A%0Ap%20%7B%0Afont-size%3A%2016px%3B%0Afont-family%3A%20Monospace%3B%0A%7D%0A%0A.thick-green-border%20%7B%0Aborder-color%3A%20green%3B%0Aborder-width%3A%2010px%3B%0Aborder-style%3A%20solid%3B%0Aborder-radius%3A%2050%25%3B%0A%7D%0A%0A.smaller-image%20%7B%0Awidth%3A%20100px%3B%0A%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22%2Fstatics%2Fcodecamp%2Fimages%2Frelaxing-cat.jpg%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3E%E5%9C%A8%E5%A4%A7%E5%AE%B6%E5%BF%83%E7%9B%AE%E4%B8%AD%EF%BC%8C%E4%B9%9F%E8%AE%B8%E7%BC%96%E7%A8%8B%E6%98%AF%E4%B8%80%E4%BB%B6%E9%9D%9E%E5%B8%B8%E5%9B%B0%E9%9A%BE%E7%9A%84%E4%BA%8B%E6%83%85%EF%BC%8C%E5%85%B6%E5%AE%9E%E4%B9%9F%E6%98%AF%E4%B8%80%E4%BB%B6%E9%9D%9E%E5%B8%B8%E6%9C%89%E4%B9%90%E8%B6%A3%E7%9A%84%E4%BA%8B%E6%83%85%EF%BC%8C%E5%8F%AA%E8%A6%81%E6%8E%8C%E6%8F%A1%E5%A5%BD%E7%BC%96%E7%A8%8B%E5%85%A5%E9%97%A8%E7%9A%84%E6%96%B9%E6%B3%95%EF%BC%8C%E5%B0%B1%E8%83%BD%E6%85%A2%E6%85%A2%E8%BF%9B%E5%85%A5%E4%B8%80%E4%B8%AA%E5%85%A8%E6%96%B0%E7%9A%84%E5%88%9B%E9%80%A0%E4%B8%96%E7%95%8C%E3%80%82here's%20a%3Ca%20href%3D%22http%3A%2F%2Ffreecatphotoapp%22%3Elink%20to%20FreeCodeCamp%3C%2Fa%3E%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3E%E5%8F%AF%E4%BB%A5%E5%AD%A6%E4%B9%A0%E7%9A%84%E7%BC%96%E7%A8%8B%E8%AF%AD%E8%A8%80%E6%9C%89%E5%BE%88%E5%A4%9A%EF%BC%8C%E6%88%91%E4%BB%AC%E8%BF%99%E4%B8%AA%E7%BC%96%E7%A8%8B%E8%AE%AD%E7%BB%83%E8%90%A5%E9%87%8C%E9%9D%A2%E6%9C%89%E5%A4%A7%E9%87%8F%E7%9A%84%E7%BC%96%E7%A8%8B%E5%AE%9E%E6%88%98%E5%AE%9E%E9%AA%8C%EF%BC%8C%E5%8C%85%E6%8B%ACHtml%E3%80%81css%E3%80%81Javascript%E3%80%81jquery%E3%80%81bootstrap%E7%AD%89%E7%AD%89%E5%89%8D%E7%AB%AF%E7%BC%96%E7%A8%8B%E5%AE%9E%E6%88%98%E8%AF%BE%E7%A8%8B%EF%BC%8C%E8%AF%B7%E5%A4%A7%E5%AE%B6%E8%80%90%E5%BF%83%E6%8C%89%E9%98%B6%E6%AE%B5%E4%B8%8D%E6%96%AD%E5%90%91%E5%89%8D%E5%AD%A6%E4%B9%A0%E5%92%8C%E9%80%9A%E8%BF%87%E4%B8%80%E8%BD%AE%E4%B8%80%E8%BD%AE%E7%9A%84%E6%8C%91%E6%88%98%EF%BC%8C%E7%9B%B8%E4%BF%A1%E5%BE%88%E5%BF%AB%E6%82%A8%E7%9A%84%E7%BC%96%E7%A8%8B%E6%8A%80%E6%9C%AF%E4%BC%9A%E5%BE%97%E5%88%B0%E5%BE%88%E5%A4%A7%E7%9A%84%E6%8F%90%E5%8D%87%EF%BC%8C%E4%B8%BA%E6%89%BE%E5%88%B0%E4%B8%80%E4%BB%BD%E5%A5%BD%E7%9A%84%E7%BC%96%E7%A8%8B%E5%B7%A5%E4%BD%9C%E5%81%9A%E5%A5%BD%E5%87%86%E5%A4%87%E3%80%82%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
.red-text {
color: red;
}

h2 {
font-family: Lobster, Monospace;
}

p {
font-size: 16px;
font-family: Monospace;
}

.thick-green-border {
border-color: green;
border-width: 10px;
border-style: solid;
border-radius: 50%;
}

.smaller-image {
width: 100px;
}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="/statics/codecamp/images/relaxing-cat.jpg">

<p class="red-text">在大家心目中，也许编程是一件非常困难的事情，其实也是一件非常有乐趣的事情，只要掌握好编程入门的方法，就能慢慢进入一个全新的创造世界。<a href="http://freecatphotoapp.com">cat photos</a></p>
<p class="red-text">可以学习的编程语言有很多，我们这个编程训练营里面有大量的编程实战实验，包括Html、css、Javascript、jquery、bootstrap等等前端编程实战课程，请大家耐心按阶段不断向前学习和通过一轮一轮的挑战，相信很快您的编程技术会得到很大的提升，为找到一份好的编程工作做好准备。</p>

```

**Comment by amitbha** [comment]
页面显示的问题，那个.com可能被挡住了
2. 你需要有一个链接到 http://freecatphotoapp.com 的a元素。

**Comment by Billy1989** [comment]
兄弟，你这问题怎么解决的，我也遇到了相同的问题

**Comment by Billy1989** [comment]
@Herbert92 ，兄弟，你这问题怎么解决的，我也遇到了相同的问题

**Comment by Herbert92** [comment]
要么就是网页刷新一下再ctrl+enter就好了，要么就是没有完全按照他要求的格式答题




------------------ 原始邮件 ------------------
发件人: "邓斌元";<notifications@github.com>;
发送时间: 2017年2月4日(星期六) 凌晨1:56
收件人: "FreeCodeCampChina/freecodecamp.cn"<freecodecamp.cn@noreply.github.com>; 
抄送: "九二"<634717515@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [FreeCodeCampChina/freecodecamp.cn] 网页不跳转了 (#117)




@Herbert92 ，兄弟，你这问题怎么解决的，我也遇到了相同的问题

**Comment by Billy1989** [comment]
@Herbert92 谢谢，刷新一下解决的

**Comment by sausagehwx** [comment]
我成功了，把原有的a标签那句删除掉就可以过了，只留你新写的a标签

**Comment by ShawnSunVip** [comment]
完全不行啊，纠结

**Comment by ayaup** [comment]
cat photo  少一个s 过不去...晕....

**Comment by AzhengTsai** [comment]
只要按了右邊iphone的連結，頁面就會當，剪下a元素重整網頁貼上就會過了

**Comment by zhangjunorhongxia** [comment]
页面完全跳转不了，苦恼……

**Comment by yzialina** [comment]
页面过不去。。

**Comment by zhangyu12321** [comment]
刷新页面一下

**Comment by shumindong** [comment]
点击跳转不了，如何解决啊？

**Comment by S1ngS1ng** [comment]
各位：
请提供问题出现的情况，之前有什么操作。如果可以，最好提供一下重现问题的方式。
如果只说“页面跳转不了”，“点击跳转不了”，我们没法重现，也只能跟大家说：刷新试试

下次遇到类似的点击无法跳转情况，麻烦大家附上问题发生时，浏览器控制台的输出，方便我们调试。谢谢

**Comment by lizzycl** [comment]
问题： 点了手机显示界面的http://www.freecatphotoapp.com的链接，之后更改代码，无法跳转
解决：刷新界面（注意是点击浏览器的刷新），然后重新编写代码

如果是其他原因，先检查是否是粗心没有拼写对cat photos，有个s哟~
这一关只用写出a元素就行，不用加上p元素~

**Comment by wenhu1984** [comment]
<a href="http://freecatphotoapp.com">catphotos</a>
如上代码，不能跳转，不满足第一个条件。

**Comment by LinDaIUUJ** [comment]
刷新一下页面就可以了

**Comment by 2274077148** [comment]
一直没发现真的恶心，他写了一个a标签，要在那里修改一下把网址和描点文本换一下就可以了，一直没看见

**Comment by polaries** [comment]
刷新也不行

**Comment by polaries** [comment]
不满足第二个条件

**Comment by polaries** [comment]
> 页面显示的问题，那个.com可能被挡住了
> 2. 你需要有一个链接到 http://freecatphotoapp.com 的a元素。

我也是这个问题怎么解决

**Comment by Affinity428** [comment]
> > 页面显示的问题，那个.com可能被挡住了
> > 2. 你需要有一个链接到 http://freecatphotoapp.com 的a元素。
> 
> 我也是这个问题怎么解决

你把图片下面的例子复制到代码中，把网站改成任务里面的网站就可以了。
我感觉我自己写的没有不对，可是就是过不去，这么改了之后一次就过了。

**Comment by hlgf** [comment]
绝望的一批，怎么弄的搞不好

**Comment by Xuhao-ChangAn** [comment]
> > > 页面显示的问题，那个.com可能被挡住了
> > > 2. 你需要有一个链接到 http://freecatphotoapp.com 的a元素。
> > 
> > 
> > 我也是这个问题怎么解决
> 
> 你把图片下面的例子复制到代码中，把网站改成任务里面的网站就可以了。
> 我感觉我自己写的没有不对，可是就是过不去，这么改了之后一次就过了。

参考了一下，这么搞还真可以，老哥厉害啊
