### ISSUE TITLE
输出是正确的但是总是通不过

### ISSUE THREAD

**Issue by DxinViRen** [FreeCodeCampChina/freecodecamp.cn#119]
var hasFirst = 0;
function lookUp(firstName, prop){
// Only change code below this line
  for(var i=0;i<contacts.length;i++){
    var obj = contacts[i];
    if(obj.firstName === firstName){
      hasFirst ++;
      if(prop in obj) return obj[prop];
      else  return "No such property";                             
    }
  }
   if(hasFirst === 0){
      return "No such contact";
   }
// Only change code above this line
}

// Change these values to test your function
lookUp("Bob", "number");

**Comment by wudifeixue** [comment]
注意看// Only change code below this line
你在全局里定义了个变量没遵守规则，改到function里面就不报错了
