### ISSUE TITLE
报错有问题

### ISSUE THREAD

**Issue by hehe321** [FreeCodeCampChina/freecodecamp.cn#12]
Challenge [Concatenating Strings with Plus Operator](https://freecodecamp.cn/challenges/concatenating-strings-with-plus-operator#?solution=%2F%2F%20%E4%B8%BE%E4%BE%8B%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%20%2B%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%3B%20%0AmyStr%3D%22This%20is%20the%20start.%22%2B%22This%20is%20the%20end.%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
// 举例
var ourStr = "I come first. " + "I come second.";

// Only change code below this line

var myStr; 
myStr="This is the start."+"This is the end.";



```

**Comment by liaobinbin** [comment]
如果我没有记错的话，这个题应该在字符串判定会判断空格的。你的两个连接字符串中应有一个空格。

```
// 举例
var ourStr = "I come first. " + "I come second.";

// Only change code below this line

var myStr; 
myStr="This is the start. "+"This is the end.";
```

**Comment by towardDMC** [comment]
这个空格卡了好久，我真的是

**Comment by ShirleyTemple** [comment]
原来是start后面有个空格

**Comment by ghost** [comment]
空额真蛋疼!!!!

**Comment by H29** [comment]
原来如此

**Comment by wang37jing** [comment]
确实如此
