### ISSUE TITLE
用数组去解

### ISSUE THREAD

**Issue by wenyunmou** [FreeCodeCampChina/freecodecamp.cn#120]
function sumFibs(num) {
  var i;
  var j;
  var a=[1,1];
  var b=0;
  var c=0;
  for(i=0;b<=num;i++)
  {
    b=a[i]+a[i+1];
    a.push(b);
    
  }
  
  a.pop();
  for(j=0;j<a.length;j++)
  {
    if(a[j]%2==1)
    {
      c=c+a[j];
    }
  }
    return c;
}

sumFibs(1000);

**Comment by wudifeixue** [comment]
关于问题方面还请写清楚啦
