### ISSUE TITLE
#238关

### ISSUE THREAD

**Issue by hunter59427** [FreeCodeCampChina/freecodecamp.cn#122]
关卡语言描述不清，导致理解错误。看了239关才知道到底要干嘛。

**Comment by Dyeed** [comment]
我也有这个问题！！！这关题目与要求不符

**Comment by S1ngS1ng** [comment]
@hunter59427 @Dyeed 麻烦二位发下链接，谢谢

**Comment by Dyeed** [comment]
sorry。
我都忘了是什么事了。。


------------------ 原始邮件 ------------------
发件人: "Sing Liu";<notifications@github.com>;
发送时间: 2017年2月15日(星期三) 中午11:43
收件人: "FreeCodeCampChina/freecodecamp.cn"<freecodecamp.cn@noreply.github.com>; 
抄送: "淘宝网"<gggssn@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [FreeCodeCampChina/freecodecamp.cn] #238关 (#122)




@hunter59427 @Dyeed 麻烦二位发下链接，谢谢

**Comment by wudifeixue** [comment]
请以后关卡都带上名字或者链接
