### ISSUE TITLE
卡在这个关卡上了，过不去，求教！！#215 《Using Objects for Lookups》

### ISSUE THREAD

**Issue by Kaier5** [FreeCodeCampChina/freecodecamp.cn#123]
Challenge [Using Objects for Lookups](https://www.freecodecamp.cn/challenges/using-objects-for-lookups#?solution=%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20phoneticLookup%20%3D%20%7B%0A%20%20%20%20alpha%3A%22Adams%22%2C%0A%20%20%20%20bravo%3A%22Boston%22%2C%0A%20%20%20%20charlie%3A%22Chicago%22%2C%0A%20%20%20%20delta%3A%22Denver%22%2C%0A%20%20%20%20echo%3A%22Easy%22%2C%0A%20%20%20%20foxtrot%3A%22Frank%22%0A%20%20%7D%3B%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22alpha%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
  var phoneticLookup = {
    alpha:"Adams",
    bravo:"Boston",
    charlie:"Chicago",
    delta:"Denver",
    echo:"Easy",
    foxtrot:"Frank"
  };
  
  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("alpha");

```

**Comment by CScraig** [comment]
// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
  var phoneticLookup = {
    
    alpha:"Adams",
    bravo:"Boston",
    charlie:"Chicago",
    delta:"Denver",
    echo:"Easy",
    foxtrot:"Frank"
  
  };
   result = phoneticLookup[val];

  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("charlie");

**Comment by Kaier5** [comment]
```
// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
  var look={
    alpha:"Adams",
    bravo:"Boston",
    charlie:"Chicago",
    delta:"Denver",
    echo:"Easy",
    foxtrot:"Frank",
  };
  result= look[val];
  


  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("charlie");

```

**Comment by sausagehwx** [comment]
可以参考一下这个

// Setup
function phoneticLookup(val) {
  var result = "";
 lookup ={
  "alpha":"Adams",
  "bravo":"Boston",
  "charlie":"Chicago",
  "delta":"Denver",
  "echo":"Easy",
  "foxtrot":"Frank",
};
var result = lookup[val];
  
  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("charlie");

**Comment by JacklinZhang** [comment]
// 定义 phoneticLookup
function phoneticLookup(val) {
  var result = "";

  // 请只修改这条注释以下的代码
  
  var lookup = {
    alpha:"Adams",
    bravo:"Boston",
    charlie:"Chicago",
    delta:"Denver",
    echo:"Easy",
    foxtrot:"Frank"
  };
  result = lookup[val];
  // 请只修改这条注释以上的代码
  return result;
}

// 你可以修改这一行来测试你的代码
phoneticLookup("charlie");
