### ISSUE TITLE
\\ print

### ISSUE THREAD

**Issue by yoyoos** [FreeCodeCampChina/freecodecamp.cn#127]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.cn/challenges/escape-sequences-in-strings#?solution=var%20myStr%3B%20%2F%2F%20Change%20this%20line%0AmyStr%20%3D%20%20%22%E6%96%87%E4%BB%B6%E5%9C%A8C%3A%5C%5CWindows%5C%5C%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr; // Change this line
myStr =  "文件在C:\\Windows\\";



```

**Comment by yoyoos** [comment]
输出为：
文件在C:\\Windows\\
而并非我所希望的  C:\Windows\

**Comment by S1ngS1ng** [comment]
是的，左边那里显示的是纯文本，没有经过任何解析。所以输出的就是 `myStr =  "文件在C:\\Windows\\";`

但这道题的通过方式不是这样的，再看下题目要求吧：

![image](https://cloud.githubusercontent.com/assets/13592559/22959591/3a2a15bc-f2fd-11e6-81e9-6f41db0590fe.png)
