### ISSUE TITLE
做题的时候明明达到要求了但却通不过

### ISSUE THREAD

**Issue by LinFeng1997** [FreeCodeCampChina/freecodecamp.cn#128]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

#### Issue Description
* When Issue Happens
2017.01.22
* Steps To Reproduce
运行代码不能通过测试

#### Browser Information
* Browser Name, Version
chrome，56.0.2924.10 m (64-bit)
* Operating System
win10 家庭版 64位
#### Your Code

```js
var newArr = [];
function steamroller(arr) {
  // I'm a steamroller, baby
  arr.forEach(function(e){
    if(Array.isArray(e)){
      steamroller(e);
    }
    else
      newArr.push(e);
  });
  return newArr;
}

steamroller([[["a"]], [["b"]]]);
```

**Comment by wudifeixue** [comment]
再想想吧，你的代码有问题

**Comment by loulinzheng** [comment]
居然根我的问题差不多，还是不明白

**Comment by xinaiwunai** [comment]
和我的代码一样的。所有测试结果都能正确获得结果。可是系统就不算我正确。

**Comment by xinaiwunai** [comment]
我已经通过了。我查了一下，是因为测试不允许使用全局函数。

最后我这样通过了：
`function steamroller(arr) {
  // I'm a steamroller, baby
  var n=[];
  var temp = [];
  for(;arr.length>0;){
    if(Array.isArray(arr[0])){
      temp = arr.shift();
      for(;temp.length>0;){
        arr.unshift(temp.pop());
      }
    }else{
      n.push(arr.shift());
    }    
  }
  return n;
}

steamroller([1, [2], [3, [[4]]]]);
`
