### ISSUE TITLE
Build a Tribute Page 超链接错误

### ISSUE THREAD

**Issue by arthas55** [FreeCodeCampChina/freecodecamp.cn#13]
5.目标: 设计一个类似于: http://codepen.io/FreeCodeCamp/full/wMQrXV的页面。

实际超链接是https://codepen.io/FreeCodeCamp/full/NNvBQW/
![image](https://cloud.githubusercontent.com/assets/15815922/19377338/25b381b8-9218-11e6-9673-278bc5c6a838.png)

**Comment by discountry** [comment]
@arthas55 
感谢提醒，实际上是文本错误，链接是正确的。
另外两个链接的内容其实是一样的，不影响使用。
不过为了照顾强迫症患者还是会尽快修正啦~
已修正到dev分支
@huluoyang
