### ISSUE TITLE
翻译错误别字汇总帖

### ISSUE THREAD

**Issue by Everfighting** [FreeCodeCampChina/freecodecamp.cn#130]
#### Issue Description
看freecodecamp.cn视频部分发现有很多错别字。如：“有用” 写成 “游泳”
这里开个帖，希望小伙伴一起行动，舔砖加瓦把翻译做的更好~

汇总的格式如下：
章节名+错误描述
样例：
章节名：computer-basics-the-4-basic-parts-of-a-computer > Chrome Dev Tools: Sources
错误描述： “断点”  写成了 “断电”

**Comment by wudifeixue** [comment]
谢谢汇报错别字，不过也可以自己发pull request喔
Pull request #153 will fix this typo.

**Comment by Everfighting** [comment]
好的~ 那我直接pr好了！
