### ISSUE TITLE
这个编译答案应该是对的，但是通过不了，请问这是为什么呢？

### ISSUE THREAD

**Issue by lvanboy** [FreeCodeCampChina/freecodecamp.cn#133]
Challenge [Title Case a Sentence](https://www.freecodecamp.cn/challenges/title-case-a-sentence#?solution=function%20titleCase(str)%20%7B%0A%20%20var%20temp%20%3Dstr.toLowerCase()%3B%0A%20%20var%20arr%20%3D%5B%5D%3B%0A%20%20var%20arr1%3D%5B%5D%3B%0A%20%20str%3D%22%22%3B%0A%20%20arr%20%3D%20temp.split(%22%20%22)%3B%0A%20%20for(var%20i%3D0%3Bi%3Carr.length%3Bi%2B%2B)%7B%0A%20%20%20%20%20arr1%3Darr%5Bi%5D.split(%22%22)%3B%0A%20%20%20%20%20arr1%5B0%5D%3Darr1%5B0%5D.toUpperCase()%3B%0A%20%20%20%20%20str%2B%3Darr1.join(%22%22)%2B%22%20%22%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20str%3B%0A%7D%0A%0AtitleCase(%22I'm%20a%20little%20tea%20pot%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function titleCase(str) {
  var temp =str.toLowerCase();
  var arr =[];
  var arr1=[];
  str="";
  arr = temp.split(" ");
  for(var i=0;i<arr.length;i++){
     arr1=arr[i].split("");
     arr1[0]=arr1[0].toUpperCase();
     str+=arr1.join("")+" ";
  }
  
  return str;
}

titleCase("I'm a little tea pot");

```

**Comment by guissy** [comment]
你的结果末尾多了一个空格

**Comment by S1ngS1ng** [comment]
这个不是 bug。你这种写法，可以最后 `return str.trim();`

**Comment by changeyan** [comment]
function titleCase(str) {
  // 请把你的代码写在这里
     var Str = str;
  var newArray = Str.toLowerCase().split(" ");
   var newStr="";
  for(var i=0;i<newArray.length;i++){
   
    newStr += newArray[i].substring(0,1).toUpperCase()+newArray[i].substring(1,newArray[i].length)+" ";

  }
  
  return newStr.trim();
}

titleCase("I'm a little tea pot");

这个是我的写法，想知道还有没有别的写法了

**Comment by S1ngS1ng** [comment]
@changeyan 方法很多。http://singsing.io/blog/fcc/basic-title-case-a-sentence/

**Comment by pengandpeng** [comment]
```javascript
function titleCase(str) {
  // 请把你的代码写在这里
  var arr = str.toLowerCase().split(" ");
  var stringArr = [];
  arr.forEach(function (item) {
    item = item.replace(item[0], item[0].toUpperCase());
    stringArr.push(item);
  });
  return stringArr.join(" ");
}
```

**Comment by FengXiuli** [comment]
function titleCase(str) {
  // 请把你的代码写在这里
  var arr=str.toLowerCase().split(' ');
  var newArr=[];
  arr.map(function(val){
   
    newArr.push(val.replace(val[0],val[0].toUpperCase()));
    
  });
  return newArr.join(' ');
}

titleCase("I'm a little tea pot");
