### ISSUE TITLE
Help!  All the tests' results are correct ,but it don't pass 

### ISSUE THREAD

**Issue by miyoosan** [FreeCodeCampChina/freecodecamp.cn#134]
Challenge [Symmetric Difference](https://www.freecodecamp.cn/challenges/symmetric-difference#?solution=function%20isNotMe%20(val)%20%7B%0A%20%20return%20val%20!%3D%3D%20this%3B%0A%7D%0A%0Afunction%20noRepeat%20(arr)%20%7B%0A%20%20var%20len%20%3D%200%2C%20lenArr%3Darr.length%3B%0A%20%20var%20aloneArr%20%3D%20%5B%5D%2C%20nullArr%3D%5B%5D%3B%0A%20%20while%20(len%20%3C%20lenArr)%20%7B%0A%20%20%20%20%2F%2F%E8%BF%87%E6%BB%A4%E5%87%BA%E6%B2%A1%E6%9C%89x%E5%85%83%E7%B4%A0%E7%9A%84%E6%95%B0%E7%BB%84%0A%20%20%20%20if%20(arr%5B0%5D%20!%3D%3D%20nullArr%5B0%5D)%20%7B%0A%20%20%20%20%20%20aloneArr.push(arr%5B0%5D)%3B%20%2F%2F%20%E6%8A%8A%E5%BD%93%E5%89%8Dx%E5%85%83%E7%B4%A0%E6%8E%A8%E5%85%A5%20%E7%8B%AC%E7%94%9F%E6%95%B0%E7%BB%84%0A%20%20%20%20%7D%0A%20%20%20%20arr%20%3D%20arr.filter(isNotMe%2Carr%5B0%5D)%3B%20%0A%20%20%20%20len%2B%2B%3B%0A%20%20%7D%20%0A%20%20return%20aloneArr%3B%0A%7D%0A%0Afunction%20isNotSame%20(val)%20%7B%0A%20%20return%20this.indexOf(val)%20%3D%3D%3D%20-1%3B%0A%7D%0A%0Afunction%20sym(args)%20%7B%0A%20%20%2F%2F%20%E6%9E%84%E9%80%A0%E6%96%B0%E6%95%B0%E7%BB%84%EF%BC%8C%E7%94%A8reduce%E8%BF%87%E6%BB%A4%E7%9B%B8%E5%90%8C%E5%85%83%E7%B4%A0%EF%BC%8C%E5%B9%B6%E5%90%88%E5%B9%B6%E6%95%B0%E7%BB%84%0A%20%20var%20arr%20%3D%20%5B%5D%3B%0A%20%20for%20(var%20i%3D0%3B%20i%3Carguments.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20arr.push(arguments%5Bi%5D)%3B%0A%20%20%7D%0A%20%20%0A%20%20var%20symmen%20%3D%20function%20(arr)%20%7B%0A%20%20%20%20return%20arr.reduce(function%20(a%2Cb)%20%7B%0A%20%20%20%20%20%20var%20c%20%3D%5B%5D%3B%0A%20%20%20%20%20%20a%20%3D%20noRepeat(a)%3B%0A%20%20%20%20%20%20b%20%3D%20noRepeat(b)%3B%0A%20%20%20%20%20%20c%20%3D%20a%3B%0A%20%20%20%20%20%20a%20%3D%20b.filter(isNotSame%2Ca)%3B%0A%20%20%20%20%20%20b%20%3D%20c.filter(isNotSame%2Cb)%3B%0A%20%20%20%20%20%20newArr%20%3D%20a.concat(b)%3B%0A%20%20%20%20%20%20return%20newArr.sort(function%20(a%2Cb)%20%7B%0A%20%20%20%20%20%20%20%20return%20a-b%3B%0A%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%20%20%7D%2C%5B%5D)%3B%0A%20%20%7D%3B%0A%0A%20%20return%20symmen(arr)%3B%0A%7D%0A%0Asym(%5B1%2C%202%2C%203%5D%2C%20%5B5%2C%202%2C%201%2C%204%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function isNotMe (val) {
  return val !== this;
}

function noRepeat (arr) {
  var len = 0, lenArr=arr.length;
  var aloneArr = [], nullArr=[];
  while (len < lenArr) {
    //过滤出没有x元素的数组
    if (arr[0] !== nullArr[0]) {
      aloneArr.push(arr[0]); // 把当前x元素推入 独生数组
    }
    arr = arr.filter(isNotMe,arr[0]); 
    len++;
  } 
  return aloneArr;
}

function isNotSame (val) {
  return this.indexOf(val) === -1;
}

function sym(args) {
  // 构造新数组，用reduce过滤相同元素，并合并数组
  var arr = [];
  for (var i=0; i<arguments.length; i++) {
    arr.push(arguments[i]);
  }
  
  var symmen = function (arr) {
    return arr.reduce(function (a,b) {
      var c =[];
      a = noRepeat(a);
      b = noRepeat(b);
      c = a;
      a = b.filter(isNotSame,a);
      b = c.filter(isNotSame,b);
      newArr = a.concat(b);
      return newArr.sort(function (a,b) {
        return a-b;
      });
      },[]);
  };

  return symmen(arr);
}

sym([1, 2, 3], [5, 2, 1, 4]);

```

**Comment by S1ngS1ng** [comment]
你可以把这段代码放到别的地方运行一下，输出结果是错的。

![image](https://cloud.githubusercontent.com/assets/13592559/22959124/53c0928e-f2f9-11e6-948e-7b3d51246fc6.png)

`noRepeat` 里面写的有点儿问题，你调试下那里面的输出就知道了，不能过滤掉重复元素

**Comment by wudifeixue** [comment]
这题刚用确认可以过，不过要注意不要在全局里面写变量，而且写多个function也会造成test出问题的。

**Comment by miyoosan** [comment]
@wudifeixue 我知道了，是arr变量的问题，以前没注意到，现在回头一看，容易出问题。多个function的情况，我尽量避免，谢谢指正~！

**Comment by miyoosan** [comment]
@S1ngS1ng 你指的可能是运行环境的问题，因为涉及到全局变量arr，所以有时可能会引起难以预测的问题
