### ISSUE TITLE
 HELP! error:not satisfied"Only add one class with each of your three selectors. "

### ISSUE THREAD

**Issue by Audreylj** [FreeCodeCampChina/freecodecamp.cn#137]
Challenge [Target the same element with multiple jQuery Selectors](https://freecodecamp.cn/challenges/target-the-same-element-with-multiple-jquery-selectors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script>
  $(document).ready(function() {
  $("button").addClass("animated");
  $(".btn").addClass("shake");
  $("#target1").addClass("btn-primary animated shake");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by wudifeixue** [comment]
```jQuery
$("#target1").addClass("btn-primary animated shake");
```
You should not include the class `animated` again in #target1  
nor should you include 'shake' again.

Please don't submit code related issue to Github isssues, instead go to   
https://gitter.im/FreeCodeCamp/chinese  
for freecodecamp.cn related questions.

**Comment by furao1998** [comment]
<script>
  $(document).ready(function() {
  $("button").addClass("animated");
  $(".btn").addClass("shake");
  $("#target1").addClass("btn-primary");
</script>



<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
哪里错了第四个显示×

**Comment by wudifeixue** [comment]
Your #target1 element should have the class animated‚ shake and btn-primary.

第四个显示是说你需要加class，叫 animated shake和btn-primary 给target 1。
你只写了btn-primary所以过不了。
这题我翻译过了，但是服务器还没更新，我再催一下。

@FreeCodeCampChina/coredev 求更新服务器内容，这都一个多月了。

**Comment by furao1998** [comment]
很抱歉今天才看到你的回答，我尝试了你的写法
<script> $(document).ready(function(){ $("button").addClass("animated"); 
                                      $(".btn").addClass("shake"); 
                                      $("#target1").addClass("btn-primary animated shake"); 
    

  });
</script>



<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
但是系统仍显示无法通过，不知是否还有别的问题

**Comment by wudifeixue** [comment]
![image](https://cloud.githubusercontent.com/assets/7316929/24099210/b2af0362-0d33-11e7-95f1-29e0ae998e7c.png)

**Comment by furao1998** [comment]
谢谢
