### ISSUE TITLE
TypeError: arr.push(...).sort is not a function,why?

### ISSUE THREAD

**Issue by joezhoux** [FreeCodeCampChina/freecodecamp.cn#138]
Challenge [Where do I belong](http://www.freecodecamp.cn/challenges/where-do-i-belong#?solution=function%20where(arr%2C%20num)%20%7B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20%20arr.push(num).sort(function(a%2Cb)%7B%0A%20%20%20%20%20return%20a-b%3B%0A%20%20%20%7D)%3B%0A%20%20%20%0A%20%20%20%0A%20%20return%20arr.indexOf(num)%3B%0A%7D%0A%0Awhere(%5B40%2C%2060%5D%2C%2050)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.22 Safari/537.36 SE 2.X MetaSr 1.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function where(arr, num) {
  // Find my place in this sorted array.
   arr.push(num).sort(function(a,b){
     return a-b;
   });
   
   
  return arr.indexOf(num);
}

where([40, 60], 50);

```

**Comment by inetsurfer** [comment]
`function where(arr, num) {
  arr.push(num);
  arr.sort(function(a,b){return a-b;});
 return arr.indexOf(num);
 
}
`

**Comment by inetsurfer** [comment]
`function where(arr, num) {
arr.push(num);
arr.sort(function(a,b){return a-b;});
return arr.indexOf(num);

}
`

**Comment by inetsurfer** [comment]
`function where(arr, num) {
arr.push(num);
arr.sort(function(a,b){return a-b;});
return arr.indexOf(num);

}`

**Comment by inetsurfer** [comment]
`function where(arr, num) {
arr.push(num);
arr.sort(function(a,b){return a-b;});
return arr.indexOf(num);}`

**Comment by jiangtao-zzz** [comment]
因为数组push方法返回的是更新后的·数组length，并不是数组对象，所以没有sort方法。
