### ISSUE TITLE
判断条件错误

### ISSUE THREAD

**Issue by tonylawx** [FreeCodeCampChina/freecodecamp.cn#139]
http://www.freecodecamp.cn/challenges/prefilter-json
```
json=json.filter(function(val){
    return (val.id===1);
})
```

这一题的题意为"把其中 "'id'键的值为1的图片过滤掉。"如果把filter中的条件设置为"id===1"同样可以通过该题,题目有歧义啊

**Comment by S1ngS1ng** [comment]
题目描述中说到："You should be making use of the .filter method."

意思就是，你只要是用了 `.filter` 就行，怎么用并没有关系，这里只是想告诉你有这个方法吧。至于上面，只是举个例子
