### ISSUE TITLE
条件好像有冲突（Conditions seem to be in conflict）

### ISSUE THREAD

**Issue by PolymerLiu** [FreeCodeCampChina/freecodecamp.cn#14]
第四个条件：分别为你的3个选择器添加1个类
第五个条件：你的”#target1“元素应该有“animated” “shake" ”btn-primary" 3个类

Condition 4：Only add one class with each of your three selectors.
Condition 5：Your #target1 element should have the class animated‚ shake and btn-primary.

**Comment by discountry** [comment]
翻译应为：使用每个选择器时只添加一个类名称。
