### ISSUE TITLE
hah

### ISSUE THREAD

**Issue by 13793923328** [FreeCodeCampChina/freecodecamp.cn#140]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/chinese

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by wudifeixue** [comment]
Please only open issues that are meaningful.

**Comment by S1ngS1ng** [comment]
@wudifeixue @JackJin2014 Should block
