### ISSUE TITLE
A spelling error | 一个拼写错误

### ISSUE THREAD

**Issue by ilexwg** [FreeCodeCampChina/freecodecamp.cn#146]
Challenge [Introducing JavaScript Object Notation JSON](https://www.freecodecamp.cn/challenges/introducing-javascript-object-notation-json) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

文本中存在一个拼写错误，在如下的文本中formarts应该为formats。
任务
添加一个新专辑到 myMusic 的JSON对象。添加 artist 和 title 字符串，release_year 数字和 formats 字符串数组。

My code:
```javascript
var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  }
  // Add record here
];


```

**Comment by wudifeixue** [comment]
拼写错误修复已经在 #153 提交

**Comment by Sha1vin** [comment]
~~在第一个{}结束后，  }  后面还少了个逗号~~

**Comment by S1ngS1ng** [comment]
@Sha1vin 如果只有一个，是不需要加的
