### ISSUE TITLE
错误拼写 Basic Javascript 第五节 Understanding Case Sensitivity in Variables

### ISSUE THREAD

**Issue by leowll** [FreeCodeCampChina/freecodecamp.cn#147]
如题，Understanding Case Sensitivity in Variables中变量名字应该为studyCapVar却写成了 studlyCapVar 
studly意义不明啊

**Comment by wudifeixue** [comment]
确实，这题我也看到了
不过[原题](https://www.freecodecamp.com/challenges/understanding-case-sensitivity-in-variables)就是这样子

```JavaScript
// Declarations
var StUdLyCapVaR;
var properCamelCase;
var TitleCaseOver;

// Assignments
STUDLYCAPVAR = 10;
PRoperCAmelCAse = "A String";
tITLEcASEoVER = 9000;
```

**Comment by leowll** [comment]
关键问题是你提交的答案必须是Study才能过。这有点说不过去了吧。

**Comment by S1ngS1ng** [comment]
@leowll 
再试试，我这儿用 `studly` 才能通过，测试文件也是 `studly`

**Comment by leowll** [comment]
好吧，确实是我记错了。当初是用study试了好几次过不了。

**Comment by S1ngS1ng** [comment]
![image](https://cloud.githubusercontent.com/assets/13592559/22959083/e42d9732-f2f8-11e6-81d0-9b627b58aaf0.png)

![image](https://cloud.githubusercontent.com/assets/13592559/22959086/ea79d614-f2f8-11e6-8dab-67d96cf49b7b.png)

![image](https://cloud.githubusercontent.com/assets/13592559/22959090/f0066d90-f2f8-11e6-988f-b44b3ca8a934.png)

这样提交反而通不过的

-----

没事儿，还是谢谢你的建议。官方修改之后，这里也会更新的
