### ISSUE TITLE
Pig Latin Incomplete   *  这题我好像写成死循环了，现在这题进不去了，一进去页面就卡住了。

### ISSUE THREAD

**Issue by lvanboy** [FreeCodeCampChina/freecodecamp.cn#148]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/chinese

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by lvanboy** [comment]
请问怎么解决？

**Comment by rongnianzu** [comment]
清除浏览器缓存，再打开。

**Comment by S1ngS1ng** [comment]
@lvanboy 如果能解决请告知

**Comment by wudifeixue** [comment]
清理缓存肯定可以解决问题，不过看到了一个死循环保护机制，能加过来肯定很有帮助。
[死循环保护方法地址](https://forum.freecodecamp.com/t/free-code-camp-infinite-loop-protection/19550)

**Comment by wudifeixue** [comment]
#91 看样子已经有死循环保护了
