### ISSUE TITLE
How to pass it,plz help me out

### ISSUE THREAD

**Issue by AlexXieTC** [FreeCodeCampChina/freecodecamp.cn#149]
Challenge [Word Blanks](https://www.freecodecamp.cn/challenges/word-blanks#?solution=function%20wordBlanks(myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Your%20code%20below%20this%20line%0A%20%20%0A%20%20result%3DmyAdjective%2BmyNoun%2BmyVerb%2BmyAdverb%2B%22.%22%3B%0A%20%20%2F%2F%20Your%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks(%22%20dog%22%2C%20%22%20big%22%2C%20%22%20ran%22%2C%20%22%20quickly%20%22)%3B%0AwordBlanks(%22%20cat%22%2C%20%22%20little%22%2C%20%22%20hit%22%2C%20%22%20slowly%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  
  result=myAdjective+myNoun+myVerb+myAdverb+".";
  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks(" dog", " big", " ran", " quickly ");
wordBlanks(" cat", " little", " hit", " slowly");
```

**Comment by wudifeixue** [comment]
You must have space in between your words too. The challenge itself has no issues.

**Comment by S1ngS1ng** [comment]
This is not an issue. Please post your questions in gitter. Thanks

**Comment by Virdo** [comment]
passed:

result = myAdjective+' '+myNoun+' '+myVerb+' '+myAdverb+".";
注意：两个''中间有空格
