### ISSUE TITLE
[266]Seek and Destroy的问题

### ISSUE THREAD

**Issue by Sagitarioo** [FreeCodeCampChina/freecodecamp.cn#15]
Challenge [Seek and Destroy](https://freecodecamp.cn/challenges/seek-and-destroy#?solution=function%20destroyer%28arr%29%20%7B%0A%20%20var%20arrt%3Dnew%20Array%28%29%3B%0A%20%20var%20attt%3Darr.slice%281%2Carr.length%29%3B%0A%20%20for%28i%3D0%3Bi%3Carr%5B0%5D.length%3Bi%2B%2B%29%7B%0A%20%20%20%20%20if%28attt.indexOf%28arr%5B0%5D%5Bi%5D%29%3C0%29%7B%0A%20%20%20%20%20%20%20%20arrt.push%28arr%5B0%5D%5Bi%5D%29%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%7D%0A%20%20return%20arrt%3B%0A%7D%0A%0Adestroyer%28%5B%5B1%2C%202%2C%203%2C%201%2C%202%2C%203%5D%2C%202%2C%203%5D%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function destroyer(arr) {
  var arrt=new Array();
  var attt=arr.slice(1,arr.length);
  for(i=0;i<arr[0].length;i++){
     if(attt.indexOf(arr[0][i])<0){
        arrt.push(arr[0][i]);
      }
   }
  return arrt;
}

destroyer([[1, 2, 3, 1, 2, 3], 2, 3]);

```

通过在JS Bin中测试，我的函数是达到这个功能的。这个题目中，arr=[1, 2, 3, 1, 2, 3], 2, 3的这种定义有问题，这既不是一个字符串，也不是一个数组。题目本来想的定义arr应该是个数组，应该定义为arr=[[1, 2, 3, 1, 2, 3], 2, 3],即一个二维数组，所以题目里的测试也应该再加上一组[ ].

我的E-mail为：dengdonghe@gmail.com

**Comment by discountry** [comment]
不好意思，这个怪我们的翻译不到位，题目原文为：

> You will be provided with an initial array (the first argument in the destroyer function), followed by one or more arguments. Remove all elements from the initial array that are of the same value as these arguments.

也就是说这个方法传入的参数个数是不固定的，第一个参数是一个待操作的数组，之后的每个参数是需要你在这个数组中删除的与之相等的值。这么说很绕，举个例子:

``` js
destroyer([1, 2, 3, 1, 2, 3], 2, 3)
```

的意思就是删除[1, 2, 3, 1, 2, 3]里面的所有2和3。

**Comment by huluoyang** [comment]
![image](http://7xo9le.com1.z0.glb.clouddn.com/function-parameter.jpeg)
@Sagitarioo  函数的形参arr并不等于我们实际传输的参数，只有arguments才等于实参。
此处的形参arr仅仅是实参的第一个参数，即数组。
上图来自javascript面向对象精要2.3节，希望对你有帮助。
课程中有提示文档：arguments，
所以很显然此题需要用到arguments来获取到实参，并把arguments对象转化为数组。

```
var args = Array.from(arguments);  // es6 写法
var args = Array.prototype.slice.call(arguments); // es3写法
var args = [].slice.call(arguments); // es3写法简写
```

如果还是不理解请参考MDN：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/slice#Array-like

如果想了解更多解法可以参考Wiki：https://github.com/huluoyang/freecodecamp.cn/wiki/seek-and-destroy

**Comment by cxmSevenlaps** [comment]
非常感谢。这题目的关键在于函数的参数被自动保存在arguments数组中，因此参数的数量可变就不成问题了。
如果这个点不知道，什么算法都是白搭。
