### ISSUE TITLE
注释了，但是测试不通过

### ISSUE THREAD

**Issue by tomorrowduq** [FreeCodeCampChina/freecodecamp.cn#150]
Challenge [Uncomment HTML](http://www.w3cschool.cn/codecamp/uncomment-html.html#?solution=%3C!--%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A--%3E%0A%3C!--%0A%3Ch2%3E%E4%BD%A0%E5%A5%BDhtml%3C%2Fh2%3E%0A--%3E%0A%3C!--%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A--%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!--
<h1>Hello World</h1>
-->
<!--
<h2>你好html</h2>
-->
<!--
<p>Hello Paragraph</p>
-->

```

**Comment by TheaAo** [comment]
不要分开注释，把它整体注释掉就好。你的注释本身是有效的，通不过可能是因为它的检测机制之类。

**Comment by S1ngS1ng** [comment]
这个是 W3CSchool 的，不是 FCC 中文官网
