### ISSUE TITLE
build a Personal Portfolio Webpage 

### ISSUE THREAD

**Issue by lvanboy** [FreeCodeCampChina/freecodecamp.cn#151]
#### Issue Description

build a Personal Portfolio Webpage  
* 提供的模板 地址:http://codepen.io/freeCodeCamp/pen/VemmoX  
* 打开网页之后，我发现网页的图片都没有加载出来，而且里面的链接也没法点

#### Browser Information
* Chrome 浏览器
* Windows 操作系统

#### Screenshot
![image](https://cloud.githubusercontent.com/assets/25259733/22915998/33515774-f2b6-11e6-845c-fdefd5eeb47c.png)

**Comment by wudifeixue** [comment]
那个确实坏掉了，学习的话参照原版的更新后的地址吧。
https://codepen.io/freeCodeCamp/full/YqLyXB

**Comment by wudifeixue** [comment]
Pull request #152 should now solve this.
