### ISSUE TITLE
js浮点数操作，会产生误差问题，应该告知学员

### ISSUE THREAD

**Issue by accpdyk** [FreeCodeCampChina/freecodecamp.cn#154]
Challenge [Multiply Two Decimals with JavaScript](https://www.freecodecamp.cn/challenges/multiply-two-decimals-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var product = 2.0 * 2.5;
var num = 2.51 + 1.22;



```

**Comment by wudifeixue** [comment]
这个按照官方freecodecamp.com题为准吧，真正的新手在这时候加太多知识点感觉不好。而且以后算题肯定也会自己看文档了解的。
