### ISSUE TITLE
由于codepen自动添加的bootstrap样式库与范例不同，会导致即使用一样的代码，显示出来的效果也不一样。

### ISSUE THREAD

**Issue by inetsurfer** [FreeCodeCampChina/freecodecamp.cn#158]
Challenge [Build a Tribute Page](https://freecodecamp.cn/challenges/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
由于godepen自动添加的bootstrap样式库与范例不同，会导致即使用一样的代码，显示出来的效果也不一样。
范例文件引用的是https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css
而实际在godepen中如果用QUICK-ADD添加外部css，引用的是https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css

**Comment by SD-Gaming** [comment]
我自己的作品做出来就是跟范例不一样，哪怕复制他的code,

整个图片和文字都偏左，不知道各位是什么样

http://s.codepen.io/419600/debug/WRWvgM/dXAqBbWEVEmk

**Comment by wudifeixue** [comment]
刚测试，Codepen现在确实会自动选择Bootstrap 4。
其实能不能Codepen最好是不用它。
现在先手动替换成Bootstrap 3吧，4确实差距很大。

**Comment by S1ngS1ng** [comment]
@wudifeixue 这个先关闭了吧= =codepen 的 quickadd 咱们也没法处理。

**Comment by wudifeixue** [comment]
是啊。。这个只可以考虑在教程里面写更详细的使用说明了。

**Comment by sofast17** [comment]
在地址栏里手动修改为这个地址就好了
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css
