### ISSUE TITLE
I DONT KMOW

### ISSUE THREAD

**Issue by roheking** [FreeCodeCampChina/freecodecamp.cn#159]
Challenge [Add Images to your Website](https://www.freecodecamp.cn/challenges/add-images-to-your-website#?solution=%3Clink%20href%3D%22https%3A%2F%2Ffonts.gdgdocs.org%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%20%20%3Cimg%20src%3D%22%2Fimages%2Frelaxing-cat.jpg%22%3E%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3E%E6%88%91%E5%AE%B6%E7%9A%84%E7%8C%AB%E5%92%AA%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3E%E7%8C%AB%E5%92%AA%E7%8C%AB%E5%92%AA%E6%88%91%E5%B0%B1%E5%96%9C%E6%AC%A2%E4%BD%A0%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3E%E6%B7%B1%E6%B7%B1%E5%9C%B0%E7%88%B1%E4%B8%8A%E4%BD%A0%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3E%E6%B2%A1%E6%9C%89%E7%90%86%E7%94%B1%E6%B2%A1%E6%9C%89%E5%8E%9F%E5%9B%A0%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3E%E4%BB%8E%E8%A7%81%E5%88%B0%E4%BD%A0%E7%9A%84%E9%82%A3%E4%B8%80%E5%A4%A9%E8%B5%B7%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3E%E4%BD%A0%E7%9F%A5%E9%81%93%E6%88%91%E5%9C%A8%E7%AD%89%E4%BD%A0%E5%90%97%3F%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3E%E4%BD%A0%E5%A6%82%E6%9E%9C%E7%9C%9F%E7%9A%84%E5%9C%A8%E4%B9%8E%E6%88%91%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3E%E5%8F%88%E6%80%8E%E4%BC%9A%E8%AE%A9%E6%97%A0%E5%B0%BD%E7%9A%84%E5%A4%9C%E9%99%AA%E6%88%91%E5%BA%A6%E8%BF%87%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3E%E7%8C%AB%E5%92%AA%E7%8C%AB%E5%92%AA%E6%88%91%E5%B0%B1%E5%96%9C%E6%AC%A2%E4%BD%A0%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3E%E6%B7%B1%E6%B7%B1%E5%9C%B0%E7%88%B1%E4%B8%8A%E4%BD%A0%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3E%E5%9C%A8%E9%BB%91%E5%A4%9C%E9%87%8C%E5%80%BE%E5%90%AC%E4%BD%A0%E7%9A%84%E5%A3%B0%E9%9F%B3%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="https://fonts.gdgdocs.org/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  <img src="/images/relaxing-cat.jpg">
</style>

<h2 class="red-text">我家的猫咪</h2>

<p class="red-text">猫咪猫咪我就喜欢你</p>
<p class="red-text">深深地爱上你</p>
<p class="red-text">没有理由没有原因</p>
<p class="red-text">从见到你的那一天起</p>
<p class="red-text">你知道我在等你吗?</p>
<p class="red-text">你如果真的在乎我</p>
<p class="red-text">又怎会让无尽的夜陪我度过</p>
<p class="red-text">猫咪猫咪我就喜欢你</p>
<p class="red-text">深深地爱上你</p>
<p class="red-text">在黑夜里倾听你的声音</p>

```

**Comment by wudifeixue** [comment]
你把img放到了style里面了，这题本身并没有问题。
还请不要随便提交issue，请去 [gitter 讨论组](https://gitter.im/FreeCodeCamp/chinese) 或者 QQ 群 526289580 中讨论
