### ISSUE TITLE
h1元素为brown，不通过

### ISSUE THREAD

**Issue by CFKVLOE** [FreeCodeCampChina/freecodecamp.cn#160]
Challenge [Override Class Declarations by Styling ID Attributes](http://www.w3cschool.cn/codecamp/override-class-declarations-by-styling-id-attributes.html#?solution=%3Cstyle%3E%0Abody%20%7B%0Abackground-color%3A%20black%3B%0Afont-family%3A%20Monospace%3B%0Acolor%3A%20green%3B%0A%7D%0A.pink-text%20%7B%0Acolor%3A%20pink%3B%0A%7D%0A.blue-text%20%7B%0Acolor%3A%20green%3B%0A%7D%0A%20%20%23orange-text%7B%0A%20%20%20%20color%3Ablack%3B%0A%20%20%7D%0A%20%20h1%7B%0A%20%20%20%20color%3Abrown%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%20blue-text%22%20id%3D%22orange-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
body {
background-color: black;
font-family: Monospace;
color: green;
}
.pink-text {
color: pink;
}
.blue-text {
color: green;
}
  #orange-text{
    color:black;
  }
  h1{
    color:brown;
  }
</style>
<h1 class="pink-text blue-text" id="orange-text">Hello World!</h1>

```

**Comment by S1ngS1ng** [comment]
这里是 freecodecamp.cn 的官方 repo，不负责处理 w3cschool 的事儿
