### ISSUE TITLE
JSON结构是否应该是由{}包围而不是由[]包围？

### ISSUE THREAD

**Issue by FuguDream** [FreeCodeCampChina/freecodecamp.cn#164]
Challenge [Accessing Nested Arrays in JSON](https://freecodecamp.cn/challenges/accessing-nested-arrays-in-json) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var myPlants = [
  { 
    type: "flowers",
    list: [
      "rose",
      "tulip",
      "dandelion"
    ]
  },
  {
    type: "trees",
    list: [
      "fir",
      "pine",
      "birch"
    ]
  }  
];

// Only change code below this line

var secondTree = myPlants[1].list[1]; // Change this line


```

**Comment by S1ngS1ng** [comment]
`myPlants` 是一个符合 JSON 格式的数组。题目中的这个写法才是标准写法。
如果最外面的 `[]` 换成 `{}`，那么里面是不可能有两个 Object 的。

请看下这个[官方链接](http://www.json.org/)，"JSON is built on two structures:" 这一段，题目中给出的这个形式符合第二种情况
