### ISSUE TITLE
unkown

### ISSUE THREAD

**Issue by sunmoonshar** [FreeCodeCampChina/freecodecamp.cn#166]
Challenge [Create a Bootstrap Row](http://www.freecodecamp.cn/challenges/create-a-bootstrap-row#?solution=%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3E%3Cdiv%20class%3D%22row%22%3E%3C%2Fdiv%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%3E%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<div class="container-fluid">
  <h3 class="text-primary text-center"><div class="row"></div>jQuery Playground</h3>
  <div></div>
</div>


```

**Comment by wudifeixue** [comment]
在你的 h3 之下增加一个 div 元素。

**Comment by wudifeixue** [comment]
你写在了h3里面，这是不对的

**Comment by sunmoonshar** [comment]
好的，谢谢






------------------ 原始邮件 ------------------
发件人: "Curtis Xiao";<notifications@github.com>;
发送时间: 2017年2月25日(星期六) 上午10:41
收件人: "FreeCodeCampChina/freecodecamp.cn"<freecodecamp.cn@noreply.github.com>; 
抄送: "日月同辉"<741041282@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [FreeCodeCampChina/freecodecamp.cn] unkown (#166)




你写在了h3里面，这是不对的
