### ISSUE TITLE
明明有</form>结束标记 但是过不了

### ISSUE THREAD

**Issue by alanwu123** [FreeCodeCampChina/freecodecamp.cn#167]
# 注意：这里只处理 FreeCodeCamp.cn 的相关问题，不处理 w3cschool 的任何问题
# 注意：请不要乱开无意义的 Issue，违者直接加黑名单
# 注意：Issue 是用来处理代码库中的 bug，不是用来提问题的。完成挑战过程中遇到的代码问题请在[gitter 讨论组](https://gitter.im/FreeCodeCamp/chinese) 或者 QQ 群 526289580 中讨论

#### FreeCodeCamp.cn Issue 模板
如何使用本模板:
* 尽可能多填些相关信息，方便管理员参考
* 对于无法给出的内容，请删除掉那一行

**以上内容请在提交 Issue 之前删除**

#### 浏览器信息
* 浏览器名称，版本号
* 操作系统

#### 问题描述
* 问题是在什么时候，什么情况下遇到的
* 简要说明如何重现

#### 你的代码

```
如果和代码相关，请在这里粘贴你的全部代码
```

**Comment by S1ngS1ng** [comment]
"以上内容请在提交 Issue 之前删除" 看到这句话了没？看到底下的内容了没？好歹提供一下题目链接

请你把信息填好再提交 issue，不要只发一个模板上来。填好了 reopen 就行
