### ISSUE TITLE
求助，不了解所谓的注释那里还没有删除

### ISSUE THREAD

**Issue by furao1998** [FreeCodeCampChina/freecodecamp.cn#168]
Challenge [Uncomment HTML](http://www.freecodecamp.cn/challenges/uncomment-html#?solution=%3C!----%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3E%E6%88%91%E5%AE%B6%E7%9A%84%E7%8C%AB%E5%92%AA%3C%2Fh2%3E%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A%3C!----%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!---->
<h1>Hello World</h1>
<h2>我家的猫咪</h2>
<p>Hello Paragraph</p>
<!---->
```

**Comment by wudifeixue** [comment]
删掉注释，只保留中间的内容
```HTML
你不应该有任何的
<!---->
```
