### ISSUE TITLE
这次的问题是关于css文件

### ISSUE THREAD

**Issue by liaobinbin** [FreeCodeCampChina/freecodecamp.cn#17]
在我本地部署后，表示布局是乱的，应该是css的问题，生成的css文件和官网的css文件不一样，我手动修改了元素改成了/css/mian.css文件，可以得到和官网一样的效果，所以 我想问，各位老大些是不是没有修改less。在网站改版的时候，只是修改了main.css

**Comment by discountry** [comment]
目前站点使用的是单独构建的main-69858c7174.css文件。

**Comment by huluoyang** [comment]
@liaobinbin  是的，bootstrap的源文件是less，构建的时候生成css。
.gitignore文件里忽略掉了main.css，所以如果你直接通过gulp构建，会有问题。
这次网站改版直接修改的main.css，所以去掉.gitignore文件中的两处涉及main.css文件即可。
