### ISSUE TITLE
This is my answer.Why can not pass it ?plz help me!!!

### ISSUE THREAD

**Issue by janejiaojiao** [FreeCodeCampChina/freecodecamp.cn#172]
Challenge [Word Blanks](https://www.freecodecamp.cn/challenges/word-blanks#?solution=function%20wordBlanks(myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Your%20code%20below%20this%20line%0A%20result%20%3D%20myAdjective%2BmyNoun%2BmyVerb%2BmyAdverb%2B%22.%22%3B%0A%20%20%2F%2F%20Your%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks(%22%20dog%22%2C%20%22big%22%2C%20%22%20ran%22%2C%20%22%20quickly%22)%3B%0AwordBlanks(%22%20cat%22%2C%20%22little%22%2C%20%22%20hit%22%2C%20%22%20slowly%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
 result = myAdjective+myNoun+myVerb+myAdverb+".";
  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks(" dog", "big", " ran", " quickly");
wordBlanks(" cat", "little", " hit", " slowly");
```

**Comment by S1ngS1ng** [comment]
**You are not supposed to change the parameter.**

```
Given: 
wordBlanks("dog", "big", "ran", "quickly")

Yours:
wordBlanks(" dog", "big", " ran", " quickly");
            ↑              ↑       ↑
```

Please remove these hard-coded space in parameter, and handle them inside your function.

**Comment by janejiaojiao** [comment]
Thank you very much! I've got it.

**Comment by kangteng4470** [comment]
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  
   result = myAdjective+myNoun+ myVerb+myAdverb+".";
  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");
  
why can‘t i pass it?

**Comment by S1ngS1ng** [comment]
@kangteng4470 
Period (i.e., `.`) is not mandatory at the end, though.
```
big dog ran quickly
   ↑   ↑   ↑
```
But your output should have these spaces, which are currently missing.
