### ISSUE TITLE
The problem is ??

### ISSUE THREAD

**Issue by Jeasonxu** [FreeCodeCampChina/freecodecamp.cn#175]
Challenge [Profile Lookup](https://www.freecodecamp.cn/challenges/profile-lookup#?s
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];


function lookUp(firstName, prop){
// Only change code below this line
  
  for (var i=0;i<contacts.length;i++){
   alert(contacts[i].firstName);
    if (contacts[i].firstName==firstName){
      
     if (contacts[i].hasOwnProperty(prop)){
       return contacts[i][prop];
     }else{
       return "No such property";
     }
     
    }else {
      return "No such contact";
    }
  }
  
// Only change code above this line
}

// Change these values to test your function
lookUp("Harry", "likes");

```

**Comment by wudifeixue** [comment]
这里不是回答问题的地方，题并没有bug哦，请去Gitter或者QQ提问。
~~还有注意不要在外面定义全局变量，和写多个function，这题的测试就肯定没有问题的。~~

**Comment by slowlearnerLspeedup** [comment]
楼主 ，你的代码改成：
  for (var i=0;i<contacts.length;i++){
    if (contacts[i].firstName==firstName){
     if (contacts[i][prop]){
       return contacts[i][prop];
     }else{
       return "No such property";
     }
    } 
  }return "No such contact";
就过了。

**Comment by S1ngS1ng** [comment]
@wudifeixue 这道题初始就给了全局变量，不是自定义的。

**Comment by S1ngS1ng** [comment]
@Jeasonxu 首先你可以把 `alert` 去掉。
其次，通不过是因为逻辑问题。现在你的 `"No such contact"` 在 `for` 循环里面，意思就是，只要循环过程中，某一条不满足第一个 `if` 条件 `contacts[i] .firstName == firstName`，那就会直接返回 `"No such contact"`。
正确的思路应该是，`for` 循环判断完所有的元素，如果找不到 `firstName` 相等的，才能得出 `"No such contact"` 这个结论。
因此，你要把 `return "No such contact"` 写到 `for` 循环的外面
