### ISSUE TITLE
freecodecamp.cn网站登录功能挂掉了

### ISSUE THREAD

**Issue by gaolexx** [FreeCodeCampChina/freecodecamp.cn#179]
#### 浏览器信息
* chrome 56.0.2924.87
* windows

#### 问题描述
* 今天中午午睡起来
* 尝试登陆就可重现

#### 截图（如果有）
![2017-03-04](https://cloud.githubusercontent.com/assets/16011052/23577974/1595c1d4-0107-11e7-969e-b94a13a8027c.png)
![2017-03-04 1](https://cloud.githubusercontent.com/assets/16011052/23577976/1a01cb82-0107-11e7-8dca-3ee7b8020c92.png)

**Comment by wudifeixue** [comment]
最近freecodecamp.cn用户增长过快，服务器也许跟不上了。
这个问题同时推测是由于最近大批量机器人恶意注册造成的，现在尝试关闭邮箱注册，只开放一些第三方注册来解决。

**Comment by gaolexx** [comment]
可以用手机号验证的方法来阻止恶意注册，邮箱注册的话，临时邮箱的代价很低（基本上是免费）。很多网站，比如sina现在注册新号都需要手机号。

**Comment by wudifeixue** [comment]
现在已经禁止邮箱注册了。唯一新登录方法就是GitHub。
