### ISSUE TITLE
bug --1can't display heading 2can't meet requirement of blue color

### ISSUE THREAD

**Issue by virginia6** [FreeCodeCampChina/freecodecamp.cn#18]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.cn/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20%E6%88%91%E5%AE%B6%E7%9A%84%E7%8C%AB%E5%92%AA%0A%20%20h2%20%7Bcolor%3Ablue%3B%7D%0A%3C%2Fstyle%3E%0A%0A%3Cp%3E%E5%9C%A8%E5%A4%A7%E5%AE%B6%E5%BF%83%E7%9B%AE%E4%B8%AD%EF%BC%8C%E7%8C%AB%E6%98%AF%E6%85%B5%E6%87%92%E7%9A%84%E5%8F%AF%E7%88%B1%E7%9A%84%E5%8C%96%E8%BA%AB%EF%BC%8C%E5%AE%83%E5%8F%AF%E4%BB%A5%E7%9D%A1%E9%A5%B1%E4%BA%86%E5%86%8D%E8%B5%B7%E6%9D%A5%E5%90%83%E9%A5%AD%EF%BC%8C%E5%8F%AF%E4%BB%A5%E9%80%97%E8%B6%A3%E5%B0%8F%E8%80%97%E5%AD%90%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%8D%96%E5%BE%97%E4%BA%86%E8%90%8C%EF%BC%8C%E4%BD%BF%E5%BE%97%E4%BA%86%E5%9D%8F%EF%BC%8C%E8%BF%99%E6%A0%B7%E7%99%BE%E5%8F%98%E7%9A%84%E5%B0%8F%E6%80%AA%E5%85%BD%E5%B0%B1%E9%9B%86%E7%BB%93%E5%9C%A8%E4%B8%80%E5%8F%AA%E5%AE%A0%E7%89%A9%E4%B8%8A%EF%BC%8C%E6%80%8E%E8%83%BD%E4%B8%8D%E6%83%B9%E4%BA%BA%E6%80%9C%E7%88%B1%E3%80%82%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html
<style>
  我家的猫咪
  h2 {color:blue;}
</style>

<p>在大家心目中，猫是慵懒的可爱的化身，它可以睡饱了再起来吃饭，可以逗趣小耗子，可以卖得了萌，使得了坏，这样百变的小怪兽就集结在一只宠物上，怎能不惹人怜爱。</p>

```

**Comment by zuohd** [comment]
Where is you h2 tag?

**Comment by virginia6** [comment]
Yes,i miss the“<h2></h2>”.At first I thought "h2{}” can replace it.Thank you @zuohd

**Comment by virginia6** [comment]
Yes,i forget “h2”.At first I thought "h2{}”before can replace it.I passed it just now.Thank you @zuohd

**Comment by jamesbeme** [comment]
Please unsubscribe me

**Comment by eleven-1** [comment]
<h2>
  <style>
    h2 {color:blue;}
    我家的猫咪
  </style>
</h2>

<p>在大家心目中，猫是慵懒的可爱的化身，它可以睡饱了再起来吃饭，可以逗趣小耗子，可以卖得了萌，使得了坏，这样百变的小怪兽就集结在一只宠物上，怎能不惹人怜爱。</p>

It's my code,right.

**Comment by ChengSisi** [comment]
could anyone type down it? i try several times, and it was failed, thanks 
i am a beginner

**Comment by virginia6** [comment]
Just like this "
<style>h2{color:blue;}</style>
<h2>我家的猫咪</h2>
"

**Comment by virginia6** [comment]
Just like this

<style>h2{color:blue;}</style>

< h2>我家的猫咪</h2 >

**Comment by virginia6** [comment]
</h2>

**Comment by virginia6** [comment]
+</h2>

**Comment by virginia6** [comment]
+<  /  h2>

**Comment by ChengSisi** [comment]
i get it, thank u 谢谢楼主

**Comment by tusdasa** [comment]
`<style>
  h2 {color: blue};
</style>

<h2>我家的猫咪</h2>

<p>在大家心目中，猫是慵懒的可爱的化身，它可以睡饱了再起来吃饭，可以逗趣小耗子，可以卖得了萌，使得了坏，这样百变的小怪兽就集结在一只宠物上，怎能不惹人怜爱。</p>`

It's my code,

**Comment by tusdasa** [comment]
`<style>
  h2 {color: blue};
</style>

<h2>我家的猫咪</h2>

<p>在大家心目中，猫是慵懒的可爱的化身，它可以睡饱了再起来吃饭，可以逗趣小耗子，可以卖得了萌，使得了坏，这样百变的小怪兽就集结在一只宠物上，怎能不惹人怜爱。</p>`
