### ISSUE TITLE
 卡牌序列 2, J, 9, 2, 7 应该返回 "1 Bet" 

### ISSUE THREAD

**Issue by matao6** [FreeCodeCampChina/freecodecamp.cn#180]
Challenge [Counting Cards](http://www.freecodecamp.cn/challenges/counting-cards#?solution=var%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20switch(card)%20%7B%0A%20%20%20%20case%202%3A%0A%20%20%20%20case%203%3A%0A%20%20%20%20case%204%3A%0A%20%20%20%20case%205%3A%0A%20%20%20%20case%206%3A%0A%20%20%20%20%20%20count%20%2B%3D%201%3B%0A%20%20%20%20%20%20return%20count%20%2B%20%22%20Bet%22%3B%0A%20%20%20%20case%207%3A%0A%20%20%20%20case%208%3A%0A%20%20%20%20case%209%3A%0A%20%20%20%20%20%20return%20count%20%2B%20%22%20Hold%22%3B%0A%20%20%20%20case%2010%3A%0A%20%20%20%20case%20%27J%27%3A%0A%20%20%20%20case%20%27Q%27%3A%0A%20%20%20%20case%20%27K%27%3A%0A%20%20%20%20case%20%27A%27%3A%0A%20%20%20%20%20%20count%20-%3D%201%3B%0A%20%20%20%20%20%20return%20count%20%2B%20%22%20Hold%22%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20%22Change%20Me%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20%E6%8F%90%E7%A4%BA%3A%20Only%20the%20last%20will%20display%0Acc(2)%3B%20cc(3)%3B%20cc(7)%3B%20cc(%27K%27)%3B%20cc(%27A%27)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var count = 0;

function cc(card) {
  // Only change code below this line
  
  switch(card) {
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      count += 1;
      return count + " Bet";
    case 7:
    case 8:
    case 9:
      return count + " Hold";
    case 10:
    case 'J':
    case 'Q':
    case 'K':
    case 'A':
      count -= 1;
      return count + " Hold";
  }
  
  return "Change Me";
  // Only change code above this line
}

// Add/remove calls to test your function.
// 提示: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');

```

**Comment by wudifeixue** [comment]
switch case要好好的写break，这题本身没问题，你应该复习下怎么正确的使用switch case。还有请不要在issue这里提问。去Gitter或者QQ/微信问问题。

**Comment by shendengnian** [comment]
`<DELETED>`

**Comment by Virdo** [comment]
case 7:
    case 8:
    case 9:
      if ( count <= 0 ) {
      return count + " Hold";
      }
      return count + " Bet";
      break;
给这几个时间加个if条件就可以通过了
每组case别忘了加break
另外：
看到楼上这种不解答问题还在这阴阳怪气的 真是神烦
谁都是新手过来的 用不着你指手画脚 呵呵

**Comment by nodezhp** [comment]
my code：


var count = 0;`
functioncc(card) {
  // Only change code below this line
  if(card == 2 || card == 3 || card == 4 || card == 5 || card == 6){
    count++; 
  }else if(card == 10 || card == 'J' || card == 'Q' || card == 'K' || card == 'A'){
    count--;
  }else{
    if(card == 7 || card == 8 || card == 9){
    count = count + 0;
    }
  }
  if(count > 0){
    return count + ' Bet';
  }else{
    return count + ' Hold';
  }
  // Only change code above this line
}
// Add/remove calls to test your function.
// 提示: Only the last will display
cc(2); cc('J'); cc(9);cc(2);cc(7);




虽然过了检测，但是我总感觉有可以优化的地方，求指教～谢谢

**Comment by nodezhp** [comment]
`code`

**Comment by shendengnian** [comment]
今天闲暇时间回顾了曾对我帮助很大的FCC课程，无意中看到当时自己无心的评论而造成误解，对楼主真诚说声对不起与对当初的行为表示尴尬。一路走来。同僚们的道路何其相似，不是鄙视就是被鄙视，坚定信念，好好走下去

**Comment by S1ngS1ng** [comment]
@shendengnian 
自己删掉评论吧，或者需要的话我可以帮你删掉。另外，

> 同僚们的道路何其相似，不是鄙视就是被鄙视

好像并不是所有人都这样的

**Comment by yinxiaosi** [comment]
var count = 0;

function cc(card) {
  // Only change code below this line
  if(card>=2 && card<=6){
      count +=1;
  
  }else if(card>=7 && card<10){

  }else{
     count-=1;
  }
  if(count > 0){
    return count + ' Bet';
    }else{
    return count + ' Hold';
  }
  
  return "Change Me";
  // Only change code above this line
}
五楼可以这样写，会少敲很多代码。  原谅我不懂怎么@他  TOT   也不知道怎么私信发给他

**Comment by shendengnian** [comment]
帮我全删掉，谢谢，

**Comment by slowlearnerLspeedup** [comment]
刚刚在做这道题，同时参考了这里https://github.com/FreeCodeCampChina/freecodecamp.cn/issues/198 
 ，进一步加深了自己对运算的理解。楼主如果非要用switch，可以参考下我的：
```
function cc(card) {
switch(card){
  case 2:
  case 3:
  case 4:
  case 5:
  case 6:
    count+=1;
    break;
  case 7:
  case 8:
  case 9:
    count+=0;
    break;
  case 10:
  case "J":
  case "Q":
  case "K":
  case "A":
    count-=1;
    break;  
}
  
  if(count>0){
      return count+" Bet";
    } else if(count<=0) {
      return count+" Hold";
    }
}
```
/* “count+=0”，同时也可以用“count==0”或“count-=0”代替。而不是直接“count=0”，我也不是太理解，或许是变量赋值和数学运算意义不一样，所以count=0和count==0的意义并不一样，所以以后做赋值和数学计算时候要稍加注意。
其中，里面的count+=1也可以换成count++，count-=1也可以换成count-- */
