### ISSUE TITLE
Sift through Text with Regular Expressions

### ISSUE THREAD

**Issue by ppxb** [FreeCodeCampChina/freecodecamp.cn#181]
Challenge [Sift through Text with Regular Expressions](https://www.freecodecamp.cn/challenges/sift-through-text-with-regular-expressions#?solution=%2F%2F%20Setup%0Avar%20testString%20%3D%20%22Ada%20Lovelace%20and%20Charles%20Babbage%20designed%20the%20first%20computer%20and%20the%20software%20that%20would%20have%20run%20on%20it.%22%3B%0A%0A%2F%2F%20%E4%B8%BE%E4%BE%8B%0Avar%20expressionToGetSoftware%20%3D%20%2Fsoftware%2Fgi%3B%0Avar%20softwareCount%20%3D%20testString.match(expressionToGetSoftware).length%3B%0A%20%20%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20expression%20%3D%20%2F.%2Fgi%3B%20%20%2F%2F%20Change%20this%20Line%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%2F%2F%20This%20code%20counts%20the%20matches%20of%20expression%20in%20testString%0Avar%20andCount%20%3D%20testString.match(expression).length%3B%0Avar%20a%3D%2Fand%2Fgi%3B%0Avar%20b%3DtestString.match(a).length%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var testString = "Ada Lovelace and Charles Babbage designed the first computer and the software that would have run on it.";

// 举例
var expressionToGetSoftware = /software/gi;
var softwareCount = testString.match(expressionToGetSoftware).length;
  

// Only change code below this line.

var expression = /./gi;  // Change this Line

// Only change code above this line

// This code counts the matches of expression in testString
var andCount = testString.match(expression).length;
var a=/and/gi;
var b=testString.match(a).length;
```
the console always put the 104?
why?

**Comment by cicada-ah** [comment]
Did you see "//Only change code above this line"?
