### ISSUE TITLE
为什么一直过不去

### ISSUE THREAD

**Issue by xinyangluckily** [FreeCodeCampChina/freecodecamp.cn#182]
Challenge [Word Blanks](http://www.w3cschool.cn/codecamp/word-blanks.html#?solution=function%20wordBlanks(myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0Avar%20result%20%3D%20%22%22%3B%0A%2F%2F%20Your%20code%20below%20this%20line%0A%20%20result%3DmyNoun%20%2B%20myAdjective%20%2B%20myVerb%20%2B%20myAdverb%20%2B%20%22%20%22%3B%20%0A%0A%2F%2F%20Your%20code%20above%20this%20line%0Areturn%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks(%22dog%20%22%2C%20%22%20big%22%2C%20%22%20ran%22%2C%20%22%20quickly%22)%3B%0AwordBlanks(%22cat%20%22%2C%20%22%20little%22%2C%20%22%20hit%22%2C%20%22%20slowly%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
var result = "";
// Your code below this line
  result=myNoun + myAdjective + myVerb + myAdverb + " "; 

// Your code above this line
return result;
}

// Change the words here to test your function
wordBlanks("dog ", " big", " ran", " quickly");
wordBlanks("cat ", " little", " hit", " slowly");

```

**Comment by joe-seeing** [comment]
result=myAdjective+' '+myNoun+' '+myVerb+' '+myAdverb;
应该包含所有传入的单词并且单词之间要有间隔,

**Comment by ShirleyTemple** [comment]
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  
  result=myAdjective+' '+myNoun+' '+myVerb+' '+myAdverb+".";
  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks(" dog", " big", " ran", " quickly ");
wordBlanks(" cat", " little", " hit", " slowly");

**Comment by keller0** [comment]
在运行结果里看下你的输出是什么，和要求的有什么不同。

**Comment by Caiseyingzi** [comment]
Somebody may wirte the correct code but it couldn't run pass. Try to reload page , then reset and input the code .
```
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  
result = myAdjective+' '+myNoun+' '+myVerb+' '+myAdverb;
  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog","big","ran","quickly");
wordBlanks("cat","little","hit","slowly");
```

**Comment by yshuai** [comment]
我把楼上两位的都复制运行了,还是不行.

**Comment by yshuai** [comment]
下一关的代码能过这一关;wordBlanks传入的参数里字符串不带空格;
```javascript
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  
  result = myAdjective+' '+myNoun+' '+myVerb+' '+myAdverb;
  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog","big","ran","quickly");
wordBlanks("cat","little","hit","slowly");
```
