### ISSUE TITLE
challenge Confirm the Ending！

### ISSUE THREAD

**Issue by ALP1996** [FreeCodeCampChina/freecodecamp.cn#183]
Challenge [Confirm the Ending](https://www.freecodecamp.cn/challenges/confirm-the-ending#?solution=function%20confirmEnding(str%2C%20target)%20%7B%0A%20%20%2F%2F%20%22Never%20give%20up%20and%20good%20luck%20will%20find%20you.%22%0A%20%20%2F%2F%20--%20Falcor%0A%20%0A%20return%20target%20%3D%3D%20str.substr(-1%2C1)%3B%0A%20%2F*if(str.indexOf('%20'))%7B%0A%20%20%20%20%0A%20%20%20%20%20str%3Dstr.split('%20')%3B%0A%20%20%0A%20%20return%20target%3D%3Dstr%5Bstr.length-1%5D%3B%0A%20%20%7Delse%7B%0A%20%20%20%20return%20target%20%3D%3D%20str.substr(-1%2C1)%3B%0A%20%20%7D%0A%20%20*%2F%0A%0A%20%20%0A%20%0A%7D%0A%0AconfirmEnding(%22Bastian%22%2C%20%22n%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

confirmEnding("He has to give me a new name", "me") should return  true.

this line should return # **# false**!!!!!!

**Comment by wudifeixue** [comment]
No, confirmEnding("He has to give me a new name", "name") should return true.
confirmEnding("He has to give me a new name", "me") should also return true.
The question itself has no problem and I see your answer failed to pass two tests instead just the one you point out. 
You are getting there, I know it can be frustrating but you are not quiet there yet. 
Go read MDN about .substr again and it should help you with it.
