### ISSUE TITLE
Challenge Local Scope and Functions has an issue.

### ISSUE THREAD

**Issue by Eesnh** [FreeCodeCampChina/freecodecamp.cn#184]
Challenge [Local Scope and Functions](https://www.freecodecamp.cn/challenges/local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20var%20myVar%20%3D%20'use%20strict'%3B%0A%20%20%0A%20%20%0A%20%20console.log(myVar)%3B%0A%7D%0AmyFunction()%3B%0A%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0A%0A%0A%2F%2F%20now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {
  var myVar = 'use strict';
  
  
  console.log(myVar);
}
myFunction();

// run and check the console 
// myVar is not defined outside of myFunction


// now remove the console log line to pass the test


```

**Comment by S1ngS1ng** [comment]
It should pass the test. Try refresh the page, or click "Reset".

**Comment by wudifeixue** [comment]
It passes the test without any problem on my side, I think it could be the server issues recently we are experiencing.
