### ISSUE TITLE
someAdjectiv is not a string

### ISSUE THREAD

**Issue by Hart-Li** [FreeCodeCampChina/freecodecamp.cn#185]
Challenge [Appending Variables to Strings](http://www.freecodecamp.cn/challenges/appending-variables-to-strings#?solution=%2F%2F%20%E4%B8%BE%E4%BE%8B%0Avar%20anAdjective%20%3D%20%22awesome!%22%3B%0Avar%20ourStr%20%3D%20%22Free%20Code%20Camp%20is%20%22%3B%0AourStr%20%2B%3D%20anAdjective%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20someAdjectiv%20%3D%20%22wo%20shi%20shui%22%3B%0Avar%20myStr%20%3D%20%22Learning%20to%20code%20is%20%22%3B%0AmyStr%2B%3DsomeAdjectiv%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// 举例
var anAdjective = "awesome!";
var ourStr = "Free Code Camp is ";
ourStr += anAdjective;

// Only change code below this line

var someAdjectiv = "wo shi shui";
var myStr = "Learning to code is ";
myStr+=someAdjectiv;

```

**Comment by wudifeixue** [comment]
你把下面的someAdjective的Adjective拼错了
