### ISSUE TITLE
为什么不给过

### ISSUE THREAD

**Issue by ZhanghaoH** [FreeCodeCampChina/freecodecamp.cn#186]
Challenge [Return Largest Numbers in Arrays](http://www.w3cschool.cn/codecamp/return-largest-numbers-in-arrays.html#?solution=var%20arr_max%20%3D%20%5B%5D%3B%0Afunction%20largestOfFour(arr)%20%7B%0A%2F%2F%20You%20can%20do%20this!%0A%20%20var%20max%20%3DNumber.MIN_VALUE%3B%0Afor(var%20i%20%3D%200%20%3B%20i%20%3C%20arr.length%3Bi%2B%2B)%7B%0A%20%20if(%20typeof%20arr%5Bi%5D%20!%3D%20%22object%22)%7B%0A%20%20%20%20max%20%3D%20max%20%3E%20arr%5Bi%5D%20%3F%20max%20%3A%20arr%5Bi%5D%3B%0A%20%20%7Delse%7B%0A%20%20%20%20largestOfFour(arr%5Bi%5D)%3B%0A%20%20%7D%0A%7D%20%0A%20%20if(max%20!%3D%3D%20Number.MIN_VALUE)%7B%0A%20%20%20%20%20%20arr_max.push(max)%3B%0A%20%20%7D%0A%20%20arr%20%3D%20arr_max%3B%0Areturn%20arr%3B%0A%7D%0A%0AlargestOfFour(%5B%5B4%2C%209%2C%201%2C%203%5D%2C%20%5B13%2C%2035%2C%2018%2C%2026%5D%2C%20%5B32%2C%2035%2C%2097%2C%2039%5D%2C%20%5B1000000%2C%201001%2C%20857%2C%201%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var arr_max = [];
function largestOfFour(arr) {
// You can do this!
  var max =Number.MIN_VALUE;
for(var i = 0 ; i < arr.length;i++){
  if( typeof arr[i] != "object"){
    max = max > arr[i] ? max : arr[i];
  }else{
    largestOfFour(arr[i]);
  }
} 
  if(max !== Number.MIN_VALUE){
      arr_max.push(max);
  }

return arr_max;
}

largestOfFour([[4, 9, 1, 3], [13, 35, 18, 26], [32, 35, 97, 39], [1000000, 1001, 857, 1]]);

```

**Comment by slowlearnerLspeedup** [comment]
w3c的关卡为什么发到FCC的问题下
