### ISSUE TITLE
哪里错了吗？这题没头绪啊。。。求解

### ISSUE THREAD

**Issue by shendengnian** [FreeCodeCampChina/freecodecamp.cn#188]
Challenge [Make Object Properties Private](https://www.freecodecamp.cn/challenges/make-object-properties-private#?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20%2F%2F%20this%20is%20a%20private%20variable%0A%20%20var%20speed%20%3D%2010%3B%0A%0A%20%20%2F%2F%20these%20are%20public%20methods%0A%20%20this.accelerate%20%3D%20function(change)%20%7B%0A%20%20%20%20speed%20%2B%3D%20change%3B%0A%20%20%7D%3B%0A%0A%20%20this.decelerate%20%3D%20function()%20%7B%0A%20%20%20%20speed%20-%3D%205%3B%0A%20%20%7D%3B%0A%0A%20%20this.getSpeed%20%3D%20function()%20%7B%0A%20%20%20%20return%20speed%3B%0A%20%20%7D%3B%0A%7D%3B%0A%0Avar%20Bike%20%3D%20function()%20%7B%0A%0A%20%20%2F%2F%20%E5%8F%AA%E8%83%BD%E5%9C%A8%E8%BF%99%E4%B8%80%E8%A1%8C%E4%B8%8B%E9%9D%A2%E5%86%99%E4%BB%A3%E7%A0%81%0A%20%20var%20gear%20%3D%20%5B4%2C3%2C1%5D%3B%0A%20%20this.getGear%20%3D%20function()%7B%0A%20%20%20%20return%20gear%5B0%5D%3B%0A%20%20%7D%3B%0A%20%20this.setGear%20%3D%20function()%7B%0A%20%20%20%20return%20gear%3B%0A%20%20%7D%3B%0A%7D%3B%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0A%0Avar%20myBike%20%3D%20new%20Bike()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {

  // 只能在这一行下面写代码
  var gear = [4,3,1];
  this.getGear = function(){
    return gear[0];
  };
  this.setGear = function(){
    return gear;
  };
};

var myCar = new Car();

var myBike = new Bike();

```

**Comment by S1ngS1ng** [comment]
`var gear = [4,3,1];`

这样相当于把 `gear` 写死了。。另外，`setGear` 应该是可以接受参数的才对。。`setGear(4)` 就应该把 `var` 出来的 `gear` 改为 4 才行的。。现在你的 `setGear` 不能接受参数，肯定是通不过测试的

**Comment by shendengnian** [comment]
@S1ngS1ng 谢谢啊 你这么一说我明白了
