### ISSUE TITLE
for循环中使用num变量会导致浏览器崩溃

### ISSUE THREAD

**Issue by craiiiigie** [FreeCodeCampChina/freecodecamp.cn#19]
Challenge [Sum All Odd Fibonacci Numbers](https://www.freecodecamp.cn/challenges/sum-all-odd-fibonacci-numbers#?solution=function%20sumFibs%28num%29%20%7B%0A%20%20return%20num%3B%0A%7D%0A%0AsumFibs%284%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript

function sumFibs(num) {
  var arr=[];
  var sum=0;
  arr[0]=0;
  arr[1]=1;
  for(var i=2;i<4;i++){
    arr[i]=arr[i-2]+arr[i-1];
  }
  return arr;
}

sumFibs(4);

```

在开始研究题目的时候发现，如果把代码中for循环里的i<4替换成i<num（或者任何变量）就会出现浏览器崩溃，测试浏览器是chrome版本 53.0.2785.143 m

**Comment by RUSHtf** [comment]
我也是做这个算法的时候 写好代码运行然后崩溃了 结果发现是FOR循环里的Num变量导致的 。不过怎么解决啊 ，以后只要一登录这个课程页面就崩溃。。。目前只能换了个浏览器 你有啥办法吗 我的QQ是710107781 你可以联系我

**Comment by huluoyang** [comment]
确实如此，我也遇到这种情况。
i的值变大时，不仅浏览器会崩溃，在本地写代码也是如此。
先mark下，解决后再回来更新。

**Comment by huluoyang** [comment]
@RUSHtf  
把这个页面关闭掉，重新打开链接：https://www.freecodecamp.cn/challenges/sum-all-odd-fibonacci-numbers
注意链接后面不要添加一大串参数，否则会导致重复死循环。

**Comment by RUSHtf** [comment]
我试了试用 while循环 还是不行。。

**Comment by RUSHtf** [comment]
@huluoyang 
我关闭浏览器 重新打开这个链接：https://www.freecodecamp.cn/challenges/sum-all-odd-fibonacci-numbers  还是会马上崩溃 是不是只要一进去这个页面就会执行一次页面上写的代码？
有没有办法重置一下页面上的代码

**Comment by huluoyang** [comment]
@RUSHtf  不会崩溃啊，关闭这个页面即可，然后新开链接。PS.chrome

**Comment by huluoyang** [comment]
查阅大量资料，发现用递归来实现斐波那契数列是有局限性的。
num较小还可以，num较大时，函数调用层数太深，内存会溢出。
解决方法：用数组来缓存每一步的计算结果。
参考资料：http://www.cnblogs.com/meteoric_cry/archive/2010/11/29/1891241.html

**Comment by RUSHtf** [comment]
@huluoyang
太感谢了👏👏👏

**Comment by zsqosos** [comment]
你这个就是数组方法啊，浏览器崩溃是因为循环太多次，导致arr数组太大。解决方法是不要让i循环到num那么大，只需要在arr[i]大于num时跳出循环即可。

**Comment by jamesbeme** [comment]
Sending all email to this address

**Comment by cllgeek** [comment]
我一开始也遇到了这个问题,然后我换了代码就解决了,代码如下:

```
var sumFibs = function() {
    var cache = [1, 1];
    return function (n) {
        if (n >= cache.length) {
            for (var i = cache.length; i < n ; i++ ) {
                cache[i] = cache[i - 2] + cache[i - 1];
            }
        }
        var arr=cache.filter(function(val){
           return val%2!=0&&val<=n;
         });
        return arr.reduce(function(pre,next){
          return pre+next;
        });
    };

}();

sumFibs(400);

```

**Comment by craiiiigie** [comment]
后来我也是更改了代码通过的，当时是想搞清崩溃的原因是不是因为循环次数，感谢各位解答！

**Comment by KKenny0** [comment]
谢谢各位的解答。

**Comment by Andy201512** [comment]
应该不是循环次数的原因，而是数组大小的原因，刚刚去FreeCodeCamp的仓库那边看了相关issues，好像 `new Array(1000000).join();` 也能让页面冻结 。我也写错循环，导致数组太大，然后页面就一直崩溃了，换个浏览器变回初始的代码就能进去了。我觉得清理浏览器对这个网站的缓存应该也是可行的，因为自己写的代码只缓存在本地。

**Comment by SnoreCrocodile** [comment]
测试后发现确和内存有关，一不小心就崩溃，谢谢各位解答。

**Comment by prc333** [comment]
function sumFibs(num) {
  var a1=1,a2=1;

  var sum=2;
  for(var i=0;a2<=num;i++){
    var a =a1;
    a1=a2;
    a2+=a;
    
    if(a2%2 === 1&&a2<=num){
      sum+=a2;
      
    }
  }

  return sum;
}

我没遇到你们说的问题啊

**Comment by prc333** [comment]
function sumFibs(num) {
  var a1=1,a2=1;
  var sum=2;
  for(var i=0;a2<=num;i++){
    var a =a1;
    a1=a2;
    a2+=a;
    if(a2%2 === 1&&a2<=num){
      sum+=a2;
      
    }
  }

  return sum;
}

sumFibs(4);
可以试试这个

**Comment by C-C-Y** [comment]
function sumFibs(n) {
  var x = [1,1];
  var y = 2;
  for(i=2;x[i-1]<=n;i++){
    x[i]=x[i-2]+x[i-1];
    if(x[i]%2==1&&x[i]<=n){
      y+=x[i];
    }
  }
   return y;      
}

sumFibs(75025);

**Comment by NidusP** [comment]
function sumFibs(num) {
  var arr = [1,1];
  var s = 2;
  while(arr[arr.length-1]+arr[arr.length-2]<=num){
      arr[arr.length]= arr[arr.length-1]+arr[arr.length-2];
      console.log(arr[arr.length]);
      if(arr[arr.length-1]%2==1){ s+=arr[arr.length-1];}
    }
  return s;
}

**Comment by Cuphoria** [comment]
用一个两位的数组暂存前两位，result存贮目前的位，但值大于给定的num即推出，否则把奇数加到sum
function sumFibs(num) {
  if(num<1) return 0;
  var arr=[1,1];
  var result=0,sum=2;
  for(var i=2;result<=num;++i)
    {
      result=arr[0]+arr[1];
      if(result>num) break;
      if(result%2!=0) sum+=result;
      if(i%2==0) arr[0]=result;
      else arr[1]=result;
      
      
    }
    return sum;
}

sumFibs(4);
