### ISSUE TITLE
125 Target Even Numbered Elements Using jQuery

### ISSUE THREAD

**Issue by yqgz** [FreeCodeCampChina/freecodecamp.cn#190]
#### 浏览器信息
* 浏览器名称，版本号 chrome  57.0.2987.98
* 操作系统 win7

#### 问题描述
进入问题125 Target Even Numbered Elements Using jQuery
任务是 获取class为target且索引为偶数的所有元素，也就是target#1(索引为0)，target#3(索引为2)，target5(索引为4)，并给它们添加class animated 和 shake。
提示是 所有 target 元素的偶数都应该 shake);
            你应该使用 :even 功能来更改这些元素。
            只使用 jQuery 来添加这些 class 到元素中。
我参照示例在原先代码的基础上增加了$(".target:even").addClass("animated shake"); 但是不能通过。猜测跟页面上会有3个target5按钮有关。

#### 你的代码
$(".target:even").addClass("animated shake"); 

如果和代码相关，请在这里粘贴你的全部代码
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");
    $("#right-well").children().css("color", "orange");
    $("#left-well").children().css("color", "green");
    $(".target:nth-child(2)").addClass("animated bounce");
    $(".target:even").addClass("animated shake");
  });
</script>

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

#### 截图（如果有）
点完提交之后是这个效果
![image](https://cloud.githubusercontent.com/assets/21211525/24033307/384fc7b8-0b27-11e7-9955-8cf6d8521125.png)

**Comment by 28sister** [comment]
我也想知道是哪里出错了，我感觉和3个target5没有关系，不管有几个，反正都是按照索引来的

**Comment by ihmeng** [comment]
怎么解决的？

**Comment by 28sister** [comment]
还没解决呢，你可以试试清楚下缓存什么的，我试了没用

**Comment by sxj1011** [comment]
聊天室中怎么把图片截下来发出去？

**Comment by ihmeng** [comment]
直接看下一题，下一题中有答案，答案就是$(".target:even").addClass("animated shake");

**Comment by NicholasBaiYa** [comment]
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");
    $("#right-well").children().css("color", "orange");
    $("#left-well").children().css("color", "green");
    $(".target:nth-child(2)").addClass("animated bounce");
    $(".target:even").addClass("animated shake");
   
  });
同样卡到这里过不去了

**Comment by yqgz** [comment]
看了下一题，答案跟我写的一样。
看来确实是bug了

**Comment by wudifeixue** [comment]
确定是BUG，请先跳过吧

**Comment by wudifeixue** [comment]
现在已经修复
