### ISSUE TITLE
Pig Latin enhancement by 陈明星

### ISSUE THREAD

**Issue by S1ngS1ng** [FreeCodeCampChina/freecodecamp.cn#196]
CCTO: [陈明星](https://github.com/User-Star)

#### 浏览器信息
N/A

#### 问题描述
* Link: https://www.freecodecamp.cn/challenges/pig-latin
* Way to pass the challenge 🤦‍♀️ :

#### 你的代码
```JS
function translate(str) {
  var _s;
  switch(str){
    case "california": _s="aliforniacay";
      break;
    case "paragraphs": _s="aragraphspay";
      break;
    case "glove": _s="oveglay";
      break;
    case "algorithm": _s="algorithmway";
      break;
    case "eight": _s="eightway";
      break;
  }
  return _s; 
}
```

**Comment by ghost** [comment]
只能说这方法6。🤦‍♀️

**Comment by jw-foss** [comment]
星星姐很恐怖

**Comment by wudifeixue** [comment]
这种情况最后只能靠自觉了，毕竟所有测试都可以这么过去。

**Comment by cjl630259** [comment]
技不如人，甘拜下风

**Comment by zhanghongsheng000** [comment]
var vowel = ["a", "e", "i", "o", "u"];
if (vowel.indexOf(str[0]) != -1) {
return str + "way";
}
while (vowel.indexOf(str[0]) == -1) {
str = str.substr(1) + str.substr(0, 1);
}
return str + "ay";

**Comment by qsbit** [comment]
很厉害很厉害，没想到还可以这样去通过，服了服了.....
