### ISSUE TITLE
Translation enhancement - by Amos.Wang

### ISSUE THREAD

**Issue by S1ngS1ng** [FreeCodeCampChina/freecodecamp.cn#197]
CCTO: https://github.com/YunYiCangQiong

#### 浏览器信息
N/A

#### 问题描述
* Link: https://www.freecodecamp.cn/challenges/use-spans-for-inline-elements
```
把 "Things cats love" 中的 "love" 放到 span 标签下。然后为其添加 text-danger class 来使文字变成红色。
下面是完成后 "Top 3 things cats hate" 元素的显示效果：
<p>Top 3 things cats <span class = "text-danger">hate:</span></p>
```
* 文字提示将 "love" 放入 标签内，和下面的例举的代码不符。

-----

建议：`下面是完成后 "Top 3 things cats hate" 元素的显示效果：` => `下面是把 "Top 3 things cats hate" 中 "hate" 变成红色的示例：`

**Comment by wudifeixue** [comment]
姑且问一下，CCTO是什么意思？

**Comment by S1ngS1ng** [comment]
@wudifeixue Credits To The Owner 😁
