### ISSUE TITLE
Challenge Counting Cards has an issue.

### ISSUE THREAD

**Issue by sxj1011** [FreeCodeCampChina/freecodecamp.cn#198]
Challenge [Counting Cards](https://freecodecamp.cn/challenges/counting-cards) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.

测试都是要求的结果，但是为什么都不能通过？

My code:
```javascript
var count = 0;

function cc(card) {
  // Only change code below this line
  switch (card){
      case 2:
      case 3:
      case 4:
      case 5:
      case 6:
        count ++;
        break;
      case 10:
      case 'J':
      case 'Q':
      case 'K':
      case 'A':
        count --;
        break;
  }
  
  var str='';
  if (count > 0){
    str = " Bet";
  }else {
    str = " Hold";
  }
  
  return '"'+count+str+'"';
  // Only change code above this line
}

// Add/remove calls to test your function.
// 提示: Only the last will display
//cc(2); cc(3); cc(4); cc('K'); cc('A');
cc(2);cc(3);cc(4);cc(5);cc(6);
```

**Comment by TheFlashinchina** [comment]
最后return count + str;就好了，不用加那么多引号。。。

**Comment by Dingjerry** [comment]
我也遇到同样问题。输出结果都是对的，但是通不过。

var count = 0;


function cc(card) {
  // Only change code below this line
  switch(card){
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      count++;
      break;      
    case 7:
    case 8:
    case 9:
      //count=count;
      break;
    case "10":
    case "J":
    case "Q":
    case "K":
    case "A":
      count--;
      break;
            
  }
  
  if (count <=0){
    return count + ' Hold';

  } return count + ' Bet';
    
  //return "Change Me";
  // Only change code above this line
}

// Add/remove calls to test your function.
// 提示: Only the last will display
cc(3); cc(2); cc('A'); cc('10'); cc('K');
//cc('10'); cc('J'); cc('Q'); cc('K'); cc('A');

**Comment by Zhangyongxu0** [comment]
10 多加了 “”
