### ISSUE TITLE
Filter Arrays with filter - Translation

### ISSUE THREAD

**Issue by S1ngS1ng** [FreeCodeCampChina/freecodecamp.cn#199]
题目链接：https://freecodecamp.cn/challenges/filter-arrays-with-filter

#### 问题描述
* 测试条件，"你应该过滤出数组中大于5的元素" 翻译有歧义，应为 "你应该过滤掉数组中大于5的元素"，或 "你应该保留数组中小于 6 的元素"

**Comment by wudifeixue** [comment]
确实，读了好几遍发现这有点混乱，我改一下。

**Comment by Rocky1932373216** [comment]
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// 只能在这一行下面写代码

filter = oldArray.filter(function(val) {
  return val<6;
});
var newArray = filter;
