### ISSUE TITLE
Friendly Date Ranges翻译“不超一年”不准确

### ISSUE THREAD

**Issue by wuxipaopao** [FreeCodeCampChina/freecodecamp.cn#2]
#### Issue Description
- Friendly Date Ranges (advanced-bonfires.json)

这道题目的中“不超一年”和“不超过一年”的翻译不够准确，英文原文是"less than a year"和"within one year"，表示的是小于一年（不包括正好是一年的情况），而“不超过一年”的意思一般是包括正好是一年的情况，容易引起歧义，然后导致最后一个测试用例不能通过，建议改为“小于一年”。

**Comment by huluoyang** [comment]
确实如此，"不超过一年" 应改为 "小于一年"。
感谢修订，你就是传说中的bug小能手啊，^_^
