### ISSUE TITLE
can slove

### ISSUE THREAD

**Issue by mileyxiao** [FreeCodeCampChina/freecodecamp.cn#20]
Challenge [Escaping Literal Quotes in Strings](https://freecodecamp.cn/challenges/escaping-literal-quotes-in-strings#?solution=var%20myStr%3D%22I%20am%20a%5C%22double%20quoted%20%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22%22%3B%0A%2F%2F%20Change%20this%20line%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
var myStr="I am a\"double quoted \" string inside \"double quotes\"";
// Change this line


```

**Comment by xifengxx** [comment]
> var myStr="I am a \"double quoted \" string inside \"double quotes\"";

代码检验有点小问题，当中没有空格或多出几个空格，都通过不了的。

**Comment by huluoyang** [comment]
@mileyxiao  上面同学已经解决你的问题，空格导致。
正确的如下：

```
var myStr="I am a\"double quoted \" string inside \"double quotes\"";  // 你的代码
var myStr="I am a \"double quoted\" string inside \"double quotes\"";  // 我的代码
```

**Comment by youzizi1** [comment]
thank you!
