### ISSUE TITLE
既然不处理W3CSchool的问题，那为什么传送门是往这里开的……

### ISSUE THREAD

**Issue by cppfresher** [FreeCodeCampChina/freecodecamp.cn#200]
# 注意：这里只处理 FreeCodeCamp.cn 的相关问题，不处理 w3cschool 的任何问题
# 注意：请不要乱开无意义的 Issue，违者直接加黑名单
# 注意：Issue 是用来处理代码库中的 bug，不是用来提问题的。完成挑战过程中遇到的代码问题请在[gitter 讨论组](https://gitter.im/FreeCodeCamp/chinese) 或者 QQ 群 526289580 中讨论

#### FreeCodeCamp.cn Issue 模板
如何使用本模板:
* 尽可能多填些相关信息，方便管理员参考
* 对于无法给出的内容，请删除掉那一行

**以上内容请在提交 Issue 之前删除**

#### 浏览器信息
* 浏览器名称，版本号
* 操作系统

#### 问题描述
* 问题是在什么时候，什么情况下遇到的
* 简要说明如何重现

#### 你的代码

```
如果和代码相关，请在这里粘贴你的全部代码
```

**Comment by cppfresher** [comment]
如果确实不处理任何有关W3C的问题，请联系传送门的作者撤下超链接……

**Comment by S1ngS1ng** [comment]
@cppfresher 代码都能直接用这儿的，而且没有任何声明，你觉得他会撤下超链接？😄  想明白为什么不处理，一切就都好解释了

**Comment by wudifeixue** [comment]
😄 其实吧，我觉得W3C真的给我们bug汇报或者题的哪里不足也是好事儿。

但是有一些BUG是因为他们自己给免费的开源项目加了广告以后造成的。这就真的无能为力了。
而且太多发来的issue质量不高，还会spam，这自然有些令人感到不快。
