### ISSUE TITLE
求解  为什么不能通过

### ISSUE THREAD

**Issue by LostZoro** [FreeCodeCampChina/freecodecamp.cn#204]
Challenge [Make Object Properties Private](https://www.freecodecamp.cn/challenges/make-object-properties-private#?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20%2F%2F%20this%20is%20a%20private%20variable%0A%20%20var%20speed%20%3D%2010%3B%0A%0A%20%20%2F%2F%20these%20are%20public%20methods%0A%20%20this.accelerate%20%3D%20function(change)%20%7B%0A%20%20%20%20speed%20%2B%3D%20change%3B%0A%20%20%7D%3B%0A%0A%20%20this.decelerate%20%3D%20function()%20%7B%0A%20%20%20%20speed%20-%3D%205%3B%0A%20%20%7D%3B%0A%0A%20%20this.getSpeed%20%3D%20function()%20%7B%0A%20%20%20%20return%20speed%3B%0A%20%20%7D%3B%0A%7D%3B%0A%0Avar%20Bike%20%3D%20function()%20%7B%0A%0A%20%20%2F%2F%20%E5%8F%AA%E8%83%BD%E5%9C%A8%E8%BF%99%E4%B8%80%E8%A1%8C%E4%B8%8B%E9%9D%A2%E5%86%99%E4%BB%A3%E7%A0%81%0A%20%20var%20gear%3D0%3B%0A%20%20this.setGear%3Dfunction(num)%7B%0A%20%20%20%20gear%2B%3Dnum%3B%0A%20%20%7D%3B%0A%20%20this.getGear%3Dfunction()%7B%0A%20%20%20%20return%20gear%3B%0A%20%20%7D%3B%0A%7D%3B%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0A%0Avar%20myBike%20%3D%20new%20Bike()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {

  // 只能在这一行下面写代码
  var gear=0;
  this.setGear=function(num){
    gear+=num;
  };
  this.getGear=function(){
    return gear;
  };
};

var myCar = new Car();

var myBike = new Bike();

```

**Comment by wudifeixue** [comment]
![image](https://cloud.githubusercontent.com/assets/7316929/24103139/eeb3ab64-0d43-11e7-8463-14c6a7a577f3.png)

**Comment by zhangwenhui123** [comment]
- 
var Bike = function() {

  // 只能在这一行下面写代码
  var gear=0;
  var igear;
  this.setGear=function(num){
    igear=gear+num ;
  };
  
   this.getGear=function(){
    return igear;
  };

};
var myCar = new Car();
var myBike = new Bike(4);
改成这样可通过
你的函数最后输出的并不是加了以后的gear，而是外部的定义的gear，依旧等于0。

**Comment by wudifeixue** [comment]
@zhangwenhui123 写法并不用你这么麻烦，igear是多余的。
```JS
var Bike = function() {
var gear = 0;
  this.setGear = function(num) {
    gear = num;
  };

  this.getGear = function() {
    return gear;
  };
};
var myCar = new Car();
var myBike = new Bike(4);
```

这题做错的地方在setGear直接写 = 就好，但是却写了 +=。
