### ISSUE TITLE
The arr.shift() is not a function? 

### ISSUE THREAD

**Issue by 18101876465** [FreeCodeCampChina/freecodecamp.cn#21]
Challenge [Stand in Line](https://freecodecamp.cn/challenges/stand-in-line#?solution=function%20queue%28arr%2C%20item%29%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20arr%3Darr.push%28item%29%3B%0A%20%20var%20arrDel%3Darr.shift%28%29%3B%0A%20%20return%20item%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log%28%22Before%3A%20%22%20%2B%20JSON.stringify%28testArr%29%29%3B%0Aconsole.log%28queue%28testArr%2C%206%29%29%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log%28%22After%3A%20%22%20%2B%20JSON.stringify%28testArr%29%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function queue(arr, item) {
  // Your code here
  arr=arr.push(item);
  var arrDel=arr.shift();
  return item;  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(queue(testArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

**Comment by huluoyang** [comment]
@18101876465 
arr=arr.push(item); //此时的arr为数组追加条目后的长度，并不是一个数组，自然没有shift方法。
说明你对数组的常用方法和返回值没有搞清楚，建议多练习。

```
function queue(arr, item) {
  // Your code here
  arr.push(item);  // 入队
  var result = arr.shift(); // 出队
  return result;  // 返回结果
}
```

**Comment by 18101876465** [comment]
谢谢你

**Comment by skyejy** [comment]
一语惊醒梦中人，多谢

**Comment by qdchenyixuan** [comment]
这貌似是FCC中文社区的创始人，666
