### ISSUE TITLE
Returning Boolean Values from Functions

### ISSUE THREAD

**Issue by yqgz** [FreeCodeCampChina/freecodecamp.cn#210]
#### 浏览器信息
* 浏览器名称，版本号 chrome  57.0.2987.110
* 操作系统 win 10

#### 问题描述
题目要求不使用if else，isLess(10,15) 应该返回 true，isLess(15,10) 应该返回 false。
我认为我写的符合要求，但是过不去。
        isLess(10,15) 应该返回 true，isLess(15,10) 应该返回 false。这两条要求上打叉。

#### 你的代码

function isLess(a, b) {
  // Fix this code
  var result;
  var c=a-b;
  switch (c){
    case c>0:
      result = false;
      break;
    case c<0:
      result = true;
      break;
      case c===0:
      result = "equal";
  }
  return result;
}

// Change these values to test
isLess(10, 15);

**Comment by S1ngS1ng** [comment]
一方面，已经说了，返回的值为 `true` 或 `false`，不知道你为什么要加上 `c===0` 的 case。

**更重要的是，你这个写法是不符合 JS 语法的。**

这道题，如果你一定要用 `switch`，以下两种写法就是允许的：

```js
function isLess(a, b) {
  var result;
  var c = a - b;
  switch (c > 0){
    case true:
      result = false;
      break;
    case false:
      result = true;
      break;
  }
  return result;
}
```

```js
function isLess(a, b) {
  var result;
  var c = a - b;
  switch (true){
    case c > 0:
      result = false;
      break;
    case c < 0:
      result = true;
      break;
  }
  return result;
}
```

`switch` 的工作方式是这样的。比如，`switch(c)` 然后 `case "foo"`，那么如果 `c === "foo"`，才会执行 `case "foo"` 里面的代码。所以，你的写法相当于判断 `c === (c > 0)`、`c === (c < 0)` 和 `c === (c === 0)`，当然是无法匹配到的。

请仔细读一读左边的说明和例子。这道题目中，你完全不需要通过 `switch` 来解决。@yqgz

**Comment by slowlearnerLspeedup** [comment]
楼上讲解的很好，FCC左边的提示也有一定意义，但这个提示使用了===这个条件要求较为严格的比较运算符，很容易导致读者忽略掉一个之前没明确提过的知识点：
其实所有的**比较运算符都有输出true或false的能力**。
so，开始我也想半天。
