### ISSUE TITLE
I try to use these codes to complete the challenge,but it failed

### ISSUE THREAD

**Issue by edward903** [FreeCodeCampChina/freecodecamp.cn#213]
Challenge [Generate Random Whole Numbers within a Range](http://www.w3cschool.cn/codecamp/generate-random-whole-numbers-within-a-range.html#?solution=%2F%2F%20%E4%B8%BE%E4%BE%8B%0Afunction%20ourFunction(ourMin%2C%20ourMax)%20%7B%0A%0Areturn%20Math.floor(Math.random()%20*%20(ourMax%20-%20ourMin%20%2B%201))%20%2B%20ourMin%3B%0A%7D%0A%0AourFunction(1%2C%209)%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Afunction%20randomRange(myMin%2C%20myMax)%20%7B%0A%0Areturn%20Math.floor(Math.random()*(myMax-myMin))%2BmyMin%3B%20%2F%2F%20Change%20this%20line%0A%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0Avar%20myRandom%20%3D%20randomRange(5%2C%2015)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.221 Safari/537.36 SE 2.X MetaSr 1.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// 举例
function ourFunction(ourMin, ourMax) {

return Math.floor(Math.random() * (ourMax - ourMin + 1)) + ourMin;
}

ourFunction(1, 9);

// Only change code below this line.

function randomRange(myMin, myMax) {

return Math.floor(Math.random()*(myMax-myMin))+myMin; // Change this line

}

// Change these values to test your function
var myRandom = randomRange(5, 15);

```

**Comment by S1ngS1ng** [comment]
你的链接是 W3CSchool 的。这里只负责处理 FCC 中文官网的问题
官网链接：https://freecodecamp.cn/
