### ISSUE TITLE
请问建立锚点连接后点击按钮如何把改变转跳方式，让页面是像拖动滑轮而不是直接蹦过去

### ISSUE THREAD

**Issue by furao1998** [FreeCodeCampChina/freecodecamp.cn#214]
Challenge [Build a Personal Portfolio Webpage](http://www.freecodecamp.cn/challenges/build-a-personal-portfolio-webpage) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by S1ngS1ng** [comment]
请指明是在哪一道题目中遇到的。。看不出这个问题和链接有什么关联

**Comment by wudifeixue** [comment]
这个我明白什么意思，他是说[这个项目的导航栏](https://codepen.io/freeCodeCamp/pen/YqLyXB)点击以后不是瞬间跳转到那个部分，而是滑动过去。  
去参照CodePen里面的JS部分吧。

**Comment by hollyDysania** [comment]
js还懂动画

**Comment by hollyDysania** [comment]
js缓动动画
