### ISSUE TITLE
关卡Make Object Properties Private:bug

### ISSUE THREAD

**Issue by yayayhoo** [FreeCodeCampChina/freecodecamp.cn#216]
#### 浏览器信息

win7 Chrome
#### 问题描述

当我在代码区输入
myBike.setGear(1);
myBike.getGear();
结果相应是1

myBike.setGear(3);
myBike.getGear();
结果相应是3

myBike.setGear(4);
myBike.getGear();
结果相应是4

已经满足了过关条件，但是并没有
#### 你的代码

```JS
var Bike = function() {

  // 只能在这一行下面写代码
  var gear = 0;
  
  this.getGear = function(){
    //gear += change;
     return gear;
  };
  
  this.setGear = function(change){
    gear += change;
   
  };
};
```

**Comment by wudifeixue** [comment]
setGear += change，你就这里有一点错。
这题本身没有BUG，还请有不会的题去gitter或者QQ，微信等地方提问。

**Comment by TheFlashinchina** [comment]
不要光看上面代码的例子，要分析这道题的题意。这道题要求你在外部调用4，返回4，说明不需要+=，只要=就好。

**Comment by aifeideyu** [comment]
哈哈过来一游

**Comment by zhangwenhui123** [comment]
```JS
var Bike = function() {

  // 只能在这一行下面写代码
  var gear = 0;
  var igear;
  this.setGear = function(num) {
    igear = gear + num ;
  };
  
   this.getGear = function() {
    return igear;
  };
};

var myCar = new Car();

var myBike = new Bike(4);
```

**Comment by wudifeixue** [comment]
刚才我又回去看了下题，看来在都犯同一个错的情况下，有必要改一下题目了。

不过我没有更新服务器的权限，改了代码也要挺久，就在这里先解释下

我看大家都错在一个地方，我猜是不理解 set 和 get 的意思吧。
set 是设置的意思，get 是获取的意思。

由于在题中是关于自行车，
所以 setGear 可以理解为是设置变速， getGear 是得到变速。

所以没有必要使用 += 因为这样的话意思就成了提高变速了。
所以直接使用 = 赋值也就是设置变速了。
