### ISSUE TITLE
为img标签创建class类时，在样式表里写宽度时，无法提交！

### ISSUE THREAD

**Issue by zxlovezly** [FreeCodeCampChina/freecodecamp.cn#219]
为img标签创建class类时，在样式表里写宽度时，无法提交！

**Comment by wudifeixue** [comment]
具体问题在哪儿？我实在是想不起来你这有可能在哪里出的错。

**Comment by keller0** [comment]
把你出问题的代码贴出来看一下吧

**Comment by S1ngS1ng** [comment]
@zxlovezly 
如果和 FCC 相关，请提供：题目链接和你的代码。更新之后 reopen issue 就行
