### ISSUE TITLE
html第22，不能过关

### ISSUE THREAD

**Issue by qianjin807** [FreeCodeCampChina/freecodecamp.cn#22]
#### FreeCodeCamp Issue template

To Use this Template:
- Fill out what you can
- Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/chinese
#### Your Code

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">

<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a></p>

<a href="http://www.freecatphotoapp.com">cat photos</a>

<img class="smaller-image thick-green-border" src="/images/relaxing-cat.jpg">

<p class="red-text">在大家心目中，猫是慵懒的可爱的化身，它可以睡饱了再起来吃饭，可以逗趣小耗子，可以卖得了萌，使得了坏，这样百变的小怪兽就集结在一只宠物上，怎能不惹人怜爱。</p>

<p class="red-text">养动物有的时候，就是介于爱与恨之间，当你钦羡别人萌宠这么可爱的时候，你一定没有想过，狗狗和猫猫会到处拉屎，甚至会屯老鼠，啃鞋子，用爪子爬门，你不理它，它就挠你，你要对它发脾气，它会比你更来劲。所以，狗猫慎入，没有一定的准备，切勿随便去侍养动物。它们一旦认定你了，你就是它们的主人，如果你抛弃它们，它们必定心中重创。</p>

``` js
If relevant, paste all of your challenge code in here
```

<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a></p>
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/22869837/19439185/cddb9490-94af-11e6-95a9-ee9807e35367.png)

**Comment by t5400700t** [comment]
重新刷新一下，你这一节的标题是什么，我没有找到22关

**Comment by huluoyang** [comment]
@qianjin807 题意要求是在现有的a元素外创建新的p元素。
而你的代码中有2个a元素，去掉第二个即可。
