### ISSUE TITLE
不会做

### ISSUE THREAD

**Issue by mamaipa** [FreeCodeCampChina/freecodecamp.cn#221]
Challenge [Golf Code](https://freecodecamp.cn/challenges/golf-code#?solution=function%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if%20(par%3C4%2C%20strokes%3C2)%7Breturn%20%22Hole-in-one!%22%3B%7D%0A%20%20else%20if(par%3C4%2Cstrokes%3C3)%7Breturn%20%22Eagle%22%3B%7D%0A%20%20else%20if(par%3C4%2Cstrokes%3C4)%7Breturn%20%22Birdie%22%3B%7D%0A%20%20else%20if(par%3C4%2Cstrokes%3C%3D5)%7Breturn%20%22Par%22%3B%7D%0A%20%20%20else%20if(par%3C5%2Cstrokes%3C6)%7Breturn%20%22Bogey%22%3B%7D%0A%20%20else%20if(par%3C5%2Cstrokes%3C7)%7Breturn%20%22Double%20Bogey%22%3B%7D%0A%20%20%0A%20%20else%20if(par%3C5%2Cstrokes%3C%3D7)%7Breturn%20%22Go%20Home!%22%3B%7D%0A%20%20%20else%20if(par%3C6%2Cstrokes%3C%3D9)%7Breturn%20%22Go%20Home!%22%3B%7D%0A%20%20return%20%22Change%20Me%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(5%2C%204)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.22 Safari/537.36 SE 2.X MetaSr 1.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function golfScore(par, strokes) {
  // Only change code below this line
  if (par<4, strokes<2){return "Hole-in-one!";}
  else if(par<4,strokes<3){return "Eagle";}
  else if(par<4,strokes<4){return "Birdie";}
  else if(par<4,strokes<=5){return "Par";}
   else if(par<5,strokes<6){return "Bogey";}
  else if(par<5,strokes<7){return "Double Bogey";}
  
  else if(par<5,strokes<=7){return "Go Home!";}
   else if(par<6,strokes<=9){return "Go Home!";}
  return "Change Me";
  // Only change code above this line
}

// Change these values to test
golfScore(5, 4);

```

**Comment by wudifeixue** [comment]
啊，我的天，你这PHP一样的代码风格我就先不吐槽了。
```JS
  else if (strokes == par) {
    return "Par";
  }  
  else if (strokes == par + 1) {
    return "Bogey";
  }
```
具体问题在这里
