### ISSUE TITLE
Escape Sequences In Strings has a bug

### ISSUE THREAD

**Issue by uptaincolin** [FreeCodeCampChina/freecodecamp.cn#223]
Challenge [Escape Sequences in Strings](https://freecodecamp.cn/challenges/escape-sequences-in-strings#?solution=var%20myStr%3D%22%20%5C%5C%20%20%5Ct%20%5Cb%20%5Cr%20%5Cn%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr=" \\  \t \b \r \n"; // Change this line



```

**Comment by wudifeixue** [comment]
你写太多空格了，这题并没有bug 
```JS
var myStr = "\\ \t \b \r \n";
```

**Comment by visibleLi** [comment]
我不明白这道题 到底是 按照字符串来写 还是按照转义后的像这样 var myStr = "\\ \\t \\b \\r \\n";

**Comment by S1ngS1ng** [comment]
@visibleLi 试试就知道。由于 `\` 本身就是转义标识符，因此要显示 `\` 就需要写成 `\\`。只写一个 `\` 是不行的，因为会当成转义标识符来处理。
类似的问题请到 gitter 提问

**Comment by H29** [comment]
我发现这个有什么会延迟

**Comment by kzone0520** [comment]
@wudifeixue 有Bug吧  不然为什么这一行不能加注释
