### ISSUE TITLE
关卡：Using Objects for Lookups

### ISSUE THREAD

**Issue by bazhuayucat** [FreeCodeCampChina/freecodecamp.cn#224]
关卡：Using Objects for Lookups
bug：  // Only change code below this line
           // Only change code above this line
       只修改规定里面的内容无法通关。

**Comment by keller0** [comment]
把结果赋给result应该就行了吧

**Comment by wudifeixue** [comment]
刚又测试了下，这题没有BUG哦。给你个小提示：
改成这样
```JS
  var lookup =  {
    "alpha": "Adams",
    "bravo": "Boston",
```

**Comment by FIRELU** [comment]
function phoneticLookup(val) {
  var result = "";
 
  // Only change code below this line

  var lookup = {
   "alpha":"Adams",
  "bravo":"Boston",
  "charlie":"Chicago",
  "delta":"Denver",
  "echo":"Easy",
  "foxtrot": "Frank"
  };
   result = lookup[val];

  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("charlie");

**Comment by naivetothink** [comment]
额 结果result=lookup.val;改为result=lookup[val]; 就过去了。。。
