### ISSUE TITLE
why my code aways say error!

### ISSUE THREAD

**Issue by ttpod123** [FreeCodeCampChina/freecodecamp.cn#225]
Challenge [Golf Code](https://freecodecamp.cn/challenges/golf-code#?solution=function%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if(strokes%3D1)%7B%0A%20%20%20%20return%20%22Hole-in-one!%22%3B%0A%20%20%7Delse%20if(strokes%20%3C%3D%20par-2)%7B%0A%20%20%20%20return%20%22Eagle%22%3B%0A%20%20%7D%0A%20%20else%7B%0A%20%20return%20%22Change%20Me%22%3B%0A%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(5%2C%204)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function golfScore(par, strokes) {
  // Only change code below this line
  if(strokes=1){
    return "Hole-in-one!";
  }else if(strokes <= par-2){
    return "Eagle";
  }
  else{
  return "Change Me";
  }
  // Only change code above this line
}

// Change these values to test
golfScore(5, 4);

```

**Comment by S1ngS1ng** [comment]
@ttpod123 
1. You need to use `===` instead of `=` for comparison. The equal sign is used for assignment.
2. You are supposed to handle all other cases like "Birdie", "Par", etc.

**Comment by isscal** [comment]
function golfScore(par, strokes) {
  // 请只修改这条注释以下的代码
  if (strokes==1){
    return "Hole-in-one!";
  }
  else if(strokes==par-1)
  {
    return "Birdie";
  }
  else if(strokes==par){
    return "Par";
  }
  else if(strokes==par+1){
    return "Bogey";
  }
  else if(strokes==par+2){
    return "Double Bogey";
  }
  else if(strokes>=par+3){
  return "Go Home!";
  }
  
  else{
    return "Eagle";
  }
  
  // 请只修改这条注释以上的代码
}

**Comment by RillHe** [comment]
注意：在这里的“=”是赋值的意思，而“==”才是相等的意思。

**Comment by Wanlin-Lu** [comment]
只看出来是赋值“=”和“==”的问题。
