### ISSUE TITLE
关于codepen 用不了免费版

### ISSUE THREAD

**Issue by sidonglee** [FreeCodeCampChina/freecodecamp.cn#226]
codepen

用不了免费版，但是完成项目后的网页又不能再本地上传可视。所以该怎么办呢？

**Comment by S1ngS1ng** [comment]
![2017-03-27_21-16-23](https://cloud.githubusercontent.com/assets/13592559/24517191/e24024f0-1542-11e7-9c00-62bef54b5ba6.jpg)

@sidonglee 为什么用不了免费版呢？点这里注册就好了。如果你在本地编辑，只需要打开一个编辑器，编辑好之后存成 HTML 格式。然后用浏览器打开就行了

另外这不是 FCC 中文官网的 bug。下次请在 Gitter 或者 QQ 群提问。谢谢
