### ISSUE TITLE
默认出现&符号

### ISSUE THREAD

**Issue by sxg90** [FreeCodeCampChina/freecodecamp.cn#227]
Challenge [Manipulate Arrays With shift](http://freecodecamp.cn/challenges/manipulate-arrays-with-shift#?solution=%2F%2F%20%E4%B8%BE%E4%BE%8B%0Avar%20ourArray%20%3D%20%5B%22Stimpson%22%2C%20%22J%22%2C%20%5B%22cat%22%5D%5D%3B%0AremovedFromOurArray%20%3D%20ourArray.shift()%3B%0A%2F%2F%20removedFromOurArray%20now%20equals%20%22Stimpson%22%20and%20ourArray%20now%20equals%20%5B%22J%22%2C%20%5B%22cat%22%5D%5D.%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B%22John%22%2C%2023%5D%2C%20%5B%22dog%22%2C%203%5D%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Avar%20removedFromMyArray%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// 举例
var ourArray = ["Stimpson", "J", ["cat"]];
removedFromOurArray = ourArray.shift();
// removedFromOurArray now equals "Stimpson" and ourArray now equals ["J", ["cat"]].

// Setup
var myArray = [["John", 23], ["dog", 3]];

// Only change code below this line.
var removedFromMyArray;


​myArray = [["John",23],["dog",3]] & removedFromMyArray = undefined
```

**Comment by keller0** [comment]
我感觉这个“&”没什么问题，因为这个结果并不是输出语句输出的，它只是告诉你运行那些代码后这些变量的状态，也许加这个“&”就是为了区分它不是输出语句输出的结果，我是这么想的。

**Comment by wudifeixue** [comment]
应该是你本地问题，我这边没事儿。
