### ISSUE TITLE
这个页面需要自己写出来放到git 仓库吗

### ISSUE THREAD

**Issue by ghost** [FreeCodeCampChina/freecodecamp.cn#228]
Challenge [Build a Tribute Page](http://www.freecodecamp.cn/challenges/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by S1ngS1ng** [comment]
可以放到 git 仓库，也可以用 codepen 在线编辑。
顺便，这不是 bug。。如果有问题的话请在 gitter 提问。谢谢
