### ISSUE TITLE
形参问题不能通过

### ISSUE THREAD

**Issue by ThomasHuke** [FreeCodeCampChina/freecodecamp.cn#231]
Challenge [Passing Values to Functions with Arguments](https://www.freecodecamp.cn/challenges/passing-values-to-functions-with-arguments#?solution=%2F%2F%20%E4%B8%BE%E4%BE%8B%0Afunction%20ourFunction(a%2C%20b)%20%7B%0A%20%20console.log(a%20-%20b)%3B%0A%7D%0AourFunction(10%2C%205)%3B%20%2F%2F%20Outputs%205%0Afunction%20myFunction(a%2Cb)%20%7B%0A%20%20console.log(a%20%2B%20b)%20%3B%0A%7D%20%0AmyFunction(5%2C5)%3B%0A%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// 举例
function ourFunction(a, b) {
  console.log(a - b);
}
ourFunction(10, 5); // Outputs 5
function myFunction(a,b) {
  console.log(a + b) ;
} 
myFunction(5,5);


// Only change code below this line.



```

**Comment by keller0** [comment]
看上去没有问题，你的怎么不能通过，有什么提示呢。

**Comment by S1ngS1ng** [comment]
Reset 一下重新提交试试。我这儿没问题。如果有问题你再 reopen 吧
