### ISSUE TITLE
题目翻译优化

### ISSUE THREAD

**Issue by S1ngS1ng** [FreeCodeCampChina/freecodecamp.cn#234]
CCTO: [tomoat](https://github.com/tomoat)

#### 问题描述
- [x] [Access Multiple Dimensional Arrays with Indexes](https://freecodecamp.cn/challenges/access-multidimensional-arrays-with-indexes)
  - 对数组 `myArray` 使用`[index]`操作使得 myData 的值为 `8` => 使用恰当的 `[index]` 访问 `myArray`，使得 myData 的值为 `8`
- [x] [Accessing Objects Properties with Variables](https://freecodecamp.cn/challenges/accessing-objects-properties-with-variables#)
  - 通过中括号操作符找到testObj中的16 => 通过中括号操作符找到testObj中 `playerNumber` 为 `16` 的值

**Comment by tomoat** [comment]
再增加一个问题😁
问题描述
- [x] [Profile Lookup](https://freecodecamp.cn/challenges/profile-lookup)
   * 函数将会检查通讯录是否存在一个联系人的firstName属性等于firstName值，还会检查对应联系人是否存在 prop属性。=> 函数将会检查通讯录中是否存在一个联系人的firstName属性的值，并且还会检查对应联系人是否存在 prop属性。

**Comment by S1ngS1ng** [comment]
@tomoat 

```
函数将会检查通讯录中是否存在一个与传入的 firstName 相同的联系人。如果存在，那么还需要检查对应的联系人中是否存在 prop属性。
```

改成了这样，你觉得如何？
