### ISSUE TITLE
The embed code for this video is not valid.

### ISSUE THREAD

**Issue by nodejh** [FreeCodeCampChina/freecodecamp.cn#235]
#### 视频无法正常显示
Learn Sass Challenges  Learn React Challenges 和 Learn D3 Challenges 题目视频无法正常显示。

#### 题目链接:

+  [https://www.freecodecamp.cn/challenges/learn-sass-challenges](https://www.freecodecamp.cn/challenges/learn-sass-challenges)
+ [https://www.freecodecamp.cn/challenges/learn-react-challenges](https://www.freecodecamp.cn/challenges/learn-react-challenges)
+ [https://www.freecodecamp.cn/challenges/learn-d3-challenges](https://www.freecodecamp.cn/challenges/learn-d3-challenges)

#### 截图

![2dfe702f-1114-4fcf-ac21-a699f16149a7](https://cloud.githubusercontent.com/assets/10287125/24827957/36df0a5e-1c86-11e7-96fd-d733e25c9467.png)

**Comment by S1ngS1ng** [comment]
@nodejh 感谢。我们尽快处理

**Comment by wudifeixue** [comment]
现在SASS，React以及D3的课程还在beta中，如果感兴趣可以去那边用英文版学习。
#### beta课程链接:
* [SASS](https://beta.freecodecamp.com/en/challenges/sass/introduction-to-the-sass-challenges)
* [React](https://beta.freecodecamp.com/en/challenges/react/introduction-to-the-react-challenges)
* [D3](https://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/introduction-to-the-data-visualization-with-d3-challenges)

**Comment by xl778518694** [comment]
如果方便的话，请把该挑战的题目要求叙述出来，以便完成后继续进行后续挑战，谢谢
