### ISSUE TITLE
大家好，这可能是个bug；题目：Sum All Odd Fibonacci Numbers Incomplete

### ISSUE THREAD

**Issue by ChapelinWang** [FreeCodeCampChina/freecodecamp.cn#238]
我的结果跟左边菜单栏里面结果一样，就是显示错误，无法通过。

我的截图怎么上传不了，尴尬：
![Uploading bug.png…]()
代码：
```JS
var arr=[1,1];
function sumFibs(num) {
   getArr(num);
  
  var newArr=arr.filter(function(val,index,arr){
    if(val%2==0){
      return false;
    }else{
      return true;
    }
  });
  var sum=newArr.reduce(function(pVal,cVal){
    return pVal+cVal;
  },0);
  return sum;
}

function getArr(num){
  var length=arr.length;
  var temp=arr[length-2]+arr[length-1];
  if(temp<=num){
    arr.push(temp);
    getArr(num);
  }
}

sumFibs(75025);
```

**Comment by ChapelinWang** [comment]
##我发现后面那一题也是这样，结果正确，不给我通过，是我的本机环境问题么？

**Comment by S1ngS1ng** [comment]
@ChapelinWang 首先，这不是 bug。受环境限制，如果用全局的变量就会有问题。

顺便，帮你优化了一些部分

```JS
function sumFibs(num) {
    // 看不出这个放到全局环境的必要性。由于每次调用都是独立的，为什么不放到这里面呢？
    var arr = [1, 1];

    getArr(num);

    var newArr = arr.filter(function(val) {
        // 这里不需要用 if else。以后，遇到 `if () return true/false` 的写法，直接返回表达式就可以了
        return val % 2;
    });

    var sum = newArr.reduce(function(pVal, cVal) {
        return pVal + cVal;
    }, 0);

    function getArr(num){
        var length = arr.length;
        var temp = arr[length - 2] + arr[length - 1];
        if(temp <= num){
            arr.push(temp);
            getArr(num);
        }
    }
    return sum;
}
```

这样是能通过的

**Comment by ChapelinWang** [comment]
非常谢谢你帮我解答了问题希望FreeCodeCamp.cn 越办越好






------------------ 原始邮件 ------------------
发件人: "Xing Liu";<notifications@github.com>;
发送时间: 2017年4月10日(星期一) 上午10:22
收件人: "FreeCodeCampChina/freecodecamp.cn"<freecodecamp.cn@noreply.github.com>; 
抄送: "闲居散人"<1149033521@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [FreeCodeCampChina/freecodecamp.cn] 大家好，这可能是个bug；题目：Sum All Odd Fibonacci Numbers Incomplete (#238)




@ChapelinWang 首先，这不是 bug。受环境显示，如果用全局的变量就会有问题。
 
顺便，帮你优化了一些部分
 function sumFibs(num) {     // 看不出这个放到全局环境的必要性。由于每次调用都是独立的，为什么不放到这里面呢？     var arr = [1, 1];     getArr(num);     var newArr = arr.filter(function(val) {         // 这里不需要用 if else。以后，遇到 `if () return true/false` 的写法，直接返回表达式就可以了         return val % 2;     });     var sum = newArr.reduce(function(pVal, cVal) {         return pVal + cVal;     }, 0);     function getArr(num){         var length = arr.length;         var temp = arr[length - 2] + arr[length - 1];         if(temp <= num){             arr.push(temp);             getArr(num);         }     }     return sum; }  
这样是能通过的
