### ISSUE TITLE
[IMPORTANT] Invalid Codepen signup link

### ISSUE THREAD

**Issue by S1ngS1ng** [FreeCodeCampChina/freecodecamp.cn#239]
CCTO: [SelinaXQ](https://github.com/SelinaXQ)

## Issue
- Codepen free account signup link needs update
- The signup link should be https://codepen.io/accounts/signup/user/free

## Source
- [Page (somewhat relevent)](https://www.freecodecamp.cn/challenges/get-set-for-our-front-end-development-projects)
- [Link to source](https://github.com/FreeCodeCampChina/freecodecamp.cn/blob/7ce0d398e9e083fc94bf39e1c5e98eea0973f9c7/seed/challenges/01-front-end-development-certification/basic-ziplines.json#L33)

**includes but not limit to**

**Comment by wudifeixue** [comment]
哇，你这个bug都找的这么详细了，为何还要发issue呢？直接PR不就解决问题了。

**Comment by S1ngS1ng** [comment]
@wudifeixue 别人报的哈。有可能不止这一个位置。我周四回来再 verify 一下
