### ISSUE TITLE
For what is the meaning of this why do I always wrong?

### ISSUE THREAD

**Issue by ghost** [FreeCodeCampChina/freecodecamp.cn#241]
Challenge [Access MultiDimensional Arrays With Indexes](http://www.freecodecamp.cn/challenges/access-multidimensional-arrays-with-indexes#?solution=%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B1%2C2%2C3%5D%2C%20%5B4%2C5%2C6%5D%2C%20%5B7%2C8%2C9%5D%2C%20%5B%5B10%2C11%2C12%5D%2C%2013%2C%2014%5D%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Avar%20myData%20%3D%20myArray%5B0%5D%5B0%5D%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var myArray = [[1,2,3], [4,5,6], [7,8,9], [[10,11,12], 13, 14]];

// Only change code below this line.
myArray[0][0]=8;
var myData = myArray[0][0];


```

**Comment by wudifeixue** [comment]
This question is trying to teach you the behavior of arrays and how Multi Dimensional Arrays work. 
You should solve it with a way to access myArray using what you have learned, not assigning values into the array. 
So hint: 
```JS
var myData = myArray[2][?];
```
Fill out the ? to solve it. And understand why I put 2 for the first one.

**Comment by Chrisiven** [comment]
var myData = myArray[0][0];
myData = myArray[2][1];
