### ISSUE TITLE
Check for Palindromes  这个怎么写呢

### ISSUE THREAD

**Issue by wxlbobo** [FreeCodeCampChina/freecodecamp.cn#245]
Challenge [Check for Palindromes](https://freecodecamp.cn/challenges/check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20re%20%3D%20%2F%2F%20%3B%0A%20%20str.replace(re%2Cfunction()%7B%0A%20%20%7D)%3B%0A%20%20return%20true%3B%0A%7D%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  // Good luck!
  var re = // ;
  str.replace(re,function(){
  });
  return true;
}



palindrome("eye");

```

**Comment by wudifeixue** [comment]
这题主要是需要学会正则，推荐你去[regexr.com](http://regexr.com/)练习正则。
如果想看提示和解法，S1ngS1ng在[wiki](https://github.com/FreeCodeCampChina/freecodecamp.cn/wiki/check-for-palindromes)里面写的很详细哦!

**Comment by TheFlashinchina** [comment]
去W3C看一下正则表达式的相关方法，这里推荐使用replace(/[^a-z0-9]/g, "")来将所有除了字母和数字以外的文字和符号全部替换[^a-z0-9]中^是取反的意思，a-z,0-9分别代表字母a到z和数字0到9

**Comment by S1ngS1ng** [comment]
@wxlbobo 以后，这样的问题不要开 issue。在 gitter 讨论组提问就行

**Comment by Androiderof541** [comment]
if(str=="0_0 (: /-\ :) 0-0"){
    return true;
  }
这点这样就可以过了？

**Comment by S1ngS1ng** [comment]
@Androiderof541 也只能通过一个测试而已

**Comment by Androiderof541** [comment]
@S1ngS1ng 这也是一个知识点吧

**Comment by Brand4** [comment]
去聊天室问这种问题
