### ISSUE TITLE
有关cros跨域请求的问题

### ISSUE THREAD

**Issue by ghost** [FreeCodeCampChina/freecodecamp.cn#246]
Challenge [Build a Random Quote Machine](https://freecodecamp.cn/challenges/build-a-random-quote-machine) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

此处ajax函数中加入的headers是否就是通过cros实现跨域请求的，因为在网上关于cros的叙述不是很清楚，不是很明白，还有服务器端该怎么设置cros？

**Comment by S1ngS1ng** [comment]
@BearYan 不知道你的请求地址是什么。是否支持跨域取决于服务器。CORS 的前提是 response head 有 `Access-Control-Allow-Origin: '*'`。

JSONP 的话，jquery 可以这么写：
```
$.ajax({
    url: "http://foo.bar.com/?callback=?",
    dataType: "jsonp",
    success: function(data) {
        console.log(data);    
    }
});
```

可以试试用 JSONP 调用这个 API：http://forismatic.com/en/api/ 请求方式文档里有
另外，这个不是 issue。下次，这样的问题请在聊天室里提问

**Comment by TankYan** [comment]
![image](https://cloud.githubusercontent.com/assets/28032578/25436124/ebd168f2-2ac4-11e7-82f1-a75342abe40b.png)
![image](https://cloud.githubusercontent.com/assets/28032578/25436204/349f8c76-2ac5-11e7-8626-3daa3affceb4.png)

使用了那个网站的api，可是出现这样的问题，数据貌似是请求到了，是缺少什么吗 @S1ngS1ng

**Comment by S1ngS1ng** [comment]
@TankYan 不太清楚该怎么处理，没遇到过。看下这个回答吧：http://stackoverflow.com/questions/24528211/refused-to-execute-script-from-because-its-mime-type-application-json-is/24528549

**Comment by TankYan** [comment]
能不能把你的代码给我看下 @S1ngS1ng

**Comment by S1ngS1ng** [comment]
@TankYan 这题我没写过= =！不过你要不要换个 api 试试。。我看有些朋友用的其他 api，没有这个问题。https://quotesondesign.com/api-v4-0/
比如这个

**Comment by TankYan** [comment]
好的，我试试，能不能留个qq或者什么的，我是菜鸟一枚，希望以后能请教一下你 @S1ngS1ng  *-*

**Comment by S1ngS1ng** [comment]
@TankYan Gitter 上找我就好。不在这儿聊了
