### ISSUE TITLE
写了demo发现没有问题，提交测试切了三个浏览器始终编译不过

### ISSUE THREAD

**Issue by cyhatgithub** [FreeCodeCampChina/freecodecamp.cn#249]
Challenge [Counting Cards](https://freecodecamp.cn/challenges/counting-cards#?solution=var%20count%20%3D%200%3B%0Avar%20model%20%3D%20%22%22%3B%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if(card%20%3D%3D%202%20%7C%7C%20card%20%3D%3D3%20%7C%7C%20card%20%3D%3D4%20%7C%7Ccard%20%3D%3D5%20%7C%7C%20card%20%3D%3D%206%20)%7B%0A%20%20%20%20model%20%3D%20%22Bet%22%3B%0A%20%20%20%20%2B%2Bcount%3B%0A%20%20%20%7Delse%20if(card%20%3D%3D%2010%20%7C%7C%20card%20%3D%3D%22J%22%20%7C%7C%20card%20%3D%3D%20%22Q%22%20%7C%7C%20card%20%3D%3D%20%22K%22%20%7C%7C%20card%20%3D%3D%20%22A%22)%7B%0A%20%20%20%20%20model%20%3D%20%22Hold%22%3B%0A%20%20%20%20%20--count%3B%0A%20%20%20%7Delse%7B%0A%20%20%20%20%20if(model%20!%3D%20%22Hold%22%20%26%26%20model%20!%3D%20%22Bet%22)%7B%0A%20%20%20%20%20%20%20model%20%3D%20%22Hold%22%3B%0A%20%20%20%20%20%7D%0A%20%20%20%7D%0A%20%20%0A%20%20return%20count%2B%22%20%22%2Bmodel%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20%E6%8F%90%E7%A4%BA%3A%20Only%20the%20last%20will%20display%0Acc(2)%3B%20cc(3)%3B%20cc(7)%3B%20cc(%27K%27)%3B%20cc(%27A%27)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var count = 0;
var model = "";
function cc(card) {
  // Only change code below this line
  if(card == 2 || card ==3 || card ==4 ||card ==5 || card == 6 ){
    model = "Bet";
    ++count;
   }else if(card == 10 || card =="J" || card == "Q" || card == "K" || card == "A"){
     model = "Hold";
     --count;
   }else{
     if(model != "Hold" && model != "Bet"){
       model = "Hold";
     }
   }
  
  return count+" "+model;
  // Only change code above this line
}

// Add/remove calls to test your function.
// 提示: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');

```

**Comment by S1ngS1ng** [comment]
@cyhatgithub 题目中已经说了：
> Only change code below this line

由于测试环境的限制，外面加上的 `var model = ""` 会被忽略掉。。请在你写的 `function` 中判断输出文字。改起来也不复杂，每次都根据 `count` 去判断输出就可以了。

另外，你这个代码放到任何浏览器中单独运行都会得到正确结果的，思路也是可以的。只是 FCC 中，不能通过这样加全局变量的方式完成。
