### ISSUE TITLE
help

### ISSUE THREAD

**Issue by sunmoonshar** [FreeCodeCampChina/freecodecamp.cn#254]
#### 问题描述
* [题目链接](https://freecodecamp.cn/challenges/seek-and-destroy)
* 简要说明如何重现

#### 你的代码
```js
function destroyer(arr) {
  // Remove all the values
  function test(value){
    for(var i=1;i<arr.length;i++){
      if(value==arguments[i]) return false;
    }
     return true; 
  }
  return arguments[0].filter(test);
}

destroyer([1, 2, 3, 1, 2, 3], 2, 3);
```

**Comment by S1ngS1ng** [comment]
> 以上内容请在提交 Issue 之前删除

真的没看到么。

**Comment by S1ngS1ng** [comment]
@sunmoonshar 题目没问题。
你在 `test` 里面 `console.log(arguments)` 看看是啥。写在 `test` 里面，用的就是 `test` 的 `arguments`。不是 `destroyer` 的

**Comment by sunmoonshar** [comment]
thank you very much







------------------ 原始邮件 ------------------
发件人: "Xing Liu";<notifications@github.com>;
发送时间: 2017年4月20日(星期四) 中午12:33
收件人: "FreeCodeCampChina/freecodecamp.cn"<freecodecamp.cn@noreply.github.com>; 
抄送: "日月同辉"<741041282@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [FreeCodeCampChina/freecodecamp.cn] help (#254)




@sunmoonshar 题目没问题。
 你在 test 里面 console.log(arguments) 看看是啥。写在 test 里面，用的就是 test 的 arguments。不是 destroyer 的
