### ISSUE TITLE
Translation Enhancement for Generate Random Whole Numbers with JavaScript

### ISSUE THREAD

**Issue by AzhengTsai** [FreeCodeCampChina/freecodecamp.cn#256]
#### 问题描述:
- 链接：https://freecodecamp.cn/challenges/generate-random-whole-numbers-with-javascript
- 修改建议：左方任務敘述應該為调用 Math.random()，把它的结果乘以**10**

**Comment by S1ngS1ng** [comment]
@AzhengTsai 谢谢你的建议，请附上题目链接。不知道你说的是哪到题

**Comment by AzhengTsai** [comment]
sorry，不知道當頁回報不會顯示位置
[頁面連結](https://freecodecamp.cn/challenges/generate-random-whole-numbers-with-javascript)

**Comment by wudifeixue** [comment]
确实，这题我当初记得也奇怪了下

**Comment by S1ngS1ng** [comment]
@AzhengTsai 其实是这样，`* 20` 是举例吧，而且放在外面应该也不会影响。题目要求是生成 `0-9` 的数，所以只要在 `function` 里面写就没问题。
但这里，可能改一下，说的清楚一些会更好。谢谢你的建议

**Comment by wudifeixue** [comment]
抱歉，刚才看到邮件但是没来得及认真看。
说实话这题认真看真的讲的非常清晰，不应该造成混乱。

**Comment by FEILELAI** [comment]
Math.floor(Math.random() * 10);
  return Math.random();
}
为什么通不过？
