### ISSUE TITLE
这个哪里出问题了？

### ISSUE THREAD

**Issue by doubi304** [FreeCodeCampChina/freecodecamp.cn#26]
Challenge [Size your Images](https://www.freecodecamp.cn/challenges/size-your-images#?solution=%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%20%20img.smaller-image%0A%20%20%7B%0A%20%20%20%20width%3A100px%3B%0A%20%20%20%20%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20class%3D%22smaller-image%22%20src%3D%22%2Fimages%2Frelaxing-cat.jpg%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3E%E5%9C%A8%E5%A4%A7%E5%AE%B6%E5%BF%83%E7%9B%AE%E4%B8%AD%EF%BC%8C%E7%8C%AB%E6%98%AF%E6%85%B5%E6%87%92%E7%9A%84%E5%8F%AF%E7%88%B1%E7%9A%84%E5%8C%96%E8%BA%AB%EF%BC%8C%E5%AE%83%E5%8F%AF%E4%BB%A5%E7%9D%A1%E9%A5%B1%E4%BA%86%E5%86%8D%E8%B5%B7%E6%9D%A5%E5%90%83%E9%A5%AD%EF%BC%8C%E5%8F%AF%E4%BB%A5%E9%80%97%E8%B6%A3%E5%B0%8F%E8%80%97%E5%AD%90%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%8D%96%E5%BE%97%E4%BA%86%E8%90%8C%EF%BC%8C%E4%BD%BF%E5%BE%97%E4%BA%86%E5%9D%8F%EF%BC%8C%E8%BF%99%E6%A0%B7%E7%99%BE%E5%8F%98%E7%9A%84%E5%B0%8F%E6%80%AA%E5%85%BD%E5%B0%B1%E9%9B%86%E7%BB%93%E5%9C%A8%E4%B8%80%E5%8F%AA%E5%AE%A0%E7%89%A9%E4%B8%8A%EF%BC%8C%E6%80%8E%E8%83%BD%E4%B8%8D%E6%83%B9%E4%BA%BA%E6%80%9C%E7%88%B1%E3%80%82%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3E%E5%85%BB%E5%8A%A8%E7%89%A9%E6%9C%89%E7%9A%84%E6%97%B6%E5%80%99%EF%BC%8C%E5%B0%B1%E6%98%AF%E4%BB%8B%E4%BA%8E%E7%88%B1%E4%B8%8E%E6%81%A8%E4%B9%8B%E9%97%B4%EF%BC%8C%E5%BD%93%E4%BD%A0%E9%92%A6%E7%BE%A1%E5%88%AB%E4%BA%BA%E8%90%8C%E5%AE%A0%E8%BF%99%E4%B9%88%E5%8F%AF%E7%88%B1%E7%9A%84%E6%97%B6%E5%80%99%EF%BC%8C%E4%BD%A0%E4%B8%80%E5%AE%9A%E6%B2%A1%E6%9C%89%E6%83%B3%E8%BF%87%EF%BC%8C%E7%8B%97%E7%8B%97%E5%92%8C%E7%8C%AB%E7%8C%AB%E4%BC%9A%E5%88%B0%E5%A4%84%E6%8B%89%E5%B1%8E%EF%BC%8C%E7%94%9A%E8%87%B3%E4%BC%9A%E5%B1%AF%E8%80%81%E9%BC%A0%EF%BC%8C%E5%95%83%E9%9E%8B%E5%AD%90%EF%BC%8C%E7%94%A8%E7%88%AA%E5%AD%90%E7%88%AC%E9%97%A8%EF%BC%8C%E4%BD%A0%E4%B8%8D%E7%90%86%E5%AE%83%EF%BC%8C%E5%AE%83%E5%B0%B1%E6%8C%A0%E4%BD%A0%EF%BC%8C%E4%BD%A0%E8%A6%81%E5%AF%B9%E5%AE%83%E5%8F%91%E8%84%BE%E6%B0%94%EF%BC%8C%E5%AE%83%E4%BC%9A%E6%AF%94%E4%BD%A0%E6%9B%B4%E6%9D%A5%E5%8A%B2%E3%80%82%E6%89%80%E4%BB%A5%EF%BC%8C%E7%8B%97%E7%8C%AB%E6%85%8E%E5%85%A5%EF%BC%8C%E6%B2%A1%E6%9C%89%E4%B8%80%E5%AE%9A%E7%9A%84%E5%87%86%E5%A4%87%EF%BC%8C%E5%88%87%E5%8B%BF%E9%9A%8F%E4%BE%BF%E5%8E%BB%E4%BE%8D%E5%85%BB%E5%8A%A8%E7%89%A9%E3%80%82%E5%AE%83%E4%BB%AC%E4%B8%80%E6%97%A6%E8%AE%A4%E5%AE%9A%E4%BD%A0%E4%BA%86%EF%BC%8C%E4%BD%A0%E5%B0%B1%E6%98%AF%E5%AE%83%E4%BB%AC%E7%9A%84%E4%B8%BB%E4%BA%BA%EF%BC%8C%E5%A6%82%E6%9E%9C%E4%BD%A0%E6%8A%9B%E5%BC%83%E5%AE%83%E4%BB%AC%EF%BC%8C%E5%AE%83%E4%BB%AC%E5%BF%85%E5%AE%9A%E5%BF%83%E4%B8%AD%E9%87%8D%E5%88%9B%E3%80%82%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  img.smaller-image
  {
    width:100px;

  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image" src="/images/relaxing-cat.jpg">

<p class="red-text">在大家心目中，猫是慵懒的可爱的化身，它可以睡饱了再起来吃饭，可以逗趣小耗子，可以卖得了萌，使得了坏，这样百变的小怪兽就集结在一只宠物上，怎能不惹人怜爱。</p>
<p class="red-text">养动物有的时候，就是介于爱与恨之间，当你钦羡别人萌宠这么可爱的时候，你一定没有想过，狗狗和猫猫会到处拉屎，甚至会屯老鼠，啃鞋子，用爪子爬门，你不理它，它就挠你，你要对它发脾气，它会比你更来劲。所以，狗猫慎入，没有一定的准备，切勿随便去侍养动物。它们一旦认定你了，你就是它们的主人，如果你抛弃它们，它们必定心中重创。</p>

```

**Comment by Dexia** [comment]
题目是什么呢？

**Comment by jamesbeme** [comment]
Please cancel my subscription

**Comment by Zu3zz** [comment]
i don't know how t cancel r subscription, so many emails appear also troubles me. Please tell me how to do this

At 2016-10-26 02:18:05, "jamesbeme" notifications@github.com wrote:
Please cancel my subscription

**Comment by huluoyang** [comment]
@PiiigzzZ @jamesbeme  Notifications这里有退订按钮，点击Unsubscribe即可。

**Comment by huluoyang** [comment]
@doubi304  你的代码没问题，可以通过，请重试。
