### ISSUE TITLE
运行正确，但无法通过，麻烦检查一下。

### ISSUE THREAD

**Issue by lmrwork** [FreeCodeCampChina/freecodecamp.cn#262]
Challenge [Exact Change](http://www.freecodecamp.cn/challenges/exact-change#?solution=function%20checkCashRegister(price%2C%20cash%2C%20cid)%20%7B%0A%0A%20%20%2F%2F%E8%BD%AC%E6%88%90%E7%BE%8E%E5%88%86change%0A%20%20var%20change%20%3D%20100%20*%20(cash%20-%20price)%3B%0A%0A%20%20%2F%2F%E6%89%80%E6%9C%89%E9%9D%A2%E9%A2%9D%E7%9A%84%E7%BE%8E%E5%88%86%E6%95%B0%E7%BB%84%0A%20%20var%20moneyValues%20%3D%20%5B1%2C%205%2C%2010%2C%2025%2C%20100%2C%20500%2C%201000%2C%202000%2C%2010000%5D%3B%0A%20%20var%20amtToReturn%20%3D%20%5B%5D%3B%0A%0A%20%20%2F%2F%E4%BB%8E%E6%9C%80%E5%A4%A7%E9%9D%A2%E9%A2%9D%E7%9A%84%E5%BC%80%E5%A7%8B%E9%81%8D%E5%8E%86%0A%20%20for%20(var%20i%20%3D%20cid.length-1%3B%20i%20%3E%3D%200%3B%20i--)%7B%0A%20%20%20%20var%20amt%20%3D%200%3B%0A%20%20%20%20while%20(moneyValues%5Bi%5D%20%3C%3D%20change%20%26%26%20cid%5Bi%5D%5B1%5D%20%3E%200%20%26%26%20change%20%3E%200)%7B%0A%20%20%20%20%20%20console.log(%22subtracting%20%22%20%2B%20moneyValues%5Bi%5D)%3B%0A%20%20%20%20%20%20cid%5Bi%5D%5B1%5D%20-%3D%20moneyValues%5Bi%5D%2F100%3B%0A%20%20%20%20%20%20change%20-%3D%20moneyValues%5Bi%5D%3B%0A%20%20%20%20%20%20amt%20%2B%3D%20moneyValues%5Bi%5D%2F100%3B%0A%20%20%20%20%7D%0A%20%20%20%20if%20(amt%20!%3D%3D%200)%7B%0A%20%20%20%20%20%20amtToReturn.push(%5Bcid%5Bi%5D%5B0%5D%2C%20amt.toFixed(2)%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%20%20if%20(change%20!%3D%3D%200)%7B%0A%20%20%20%20return%20%22Insufficient%20Funds%22%3B%0A%20%20%7D%0A%20%20%0A%20%20for%20(var%20j%20%3D%200%3B%20j%20%3C%20cid.length%3B%20j%2B%2B)%7B%0A%20%20%20%20if%20(cid%5Bj%5D%5B1%5D%20%3E%200)%7B%0A%20%20%20%20%20%20console.log(amtToReturn)%3B%0A%20%20%20%20%20%20return%20amtToReturn%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20return%20%22Closed%22%3B%0A%0A%7D%0A%0A%2F%2F%20Example%20cash-in-drawer%20array%3A%0A%2F%2F%20%5B%5B%22PENNY%22%2C%201.01%5D%2C%0A%2F%2F%20%5B%22NICKEL%22%2C%202.05%5D%2C%0A%2F%2F%20%5B%22DIME%22%2C%203.10%5D%2C%0A%2F%2F%20%5B%22QUARTER%22%2C%204.25%5D%2C%0A%2F%2F%20%5B%22ONE%22%2C%2090.00%5D%2C%0A%2F%2F%20%5B%22FIVE%22%2C%2055.00%5D%2C%0A%2F%2F%20%5B%22TEN%22%2C%2020.00%5D%2C%0A%2F%2F%20%5B%22TWENTY%22%2C%2060.00%5D%2C%0A%2F%2F%20%5B%22ONE%20HUNDRED%22%2C%20100.00%5D%5D%0A%0AcheckCashRegister(19.50%2C%2020.00%2C%20%5B%5B%22PENNY%22%2C%201.01%5D%2C%20%5B%22NICKEL%22%2C%202.05%5D%2C%20%5B%22DIME%22%2C%203.10%5D%2C%20%5B%22QUARTER%22%2C%204.25%5D%2C%20%5B%22ONE%22%2C%2090.00%5D%2C%20%5B%22FIVE%22%2C%2055.00%5D%2C%20%5B%22TEN%22%2C%2020.00%5D%2C%20%5B%22TWENTY%22%2C%2060.00%5D%2C%20%5B%22ONE%20HUNDRED%22%2C%20100.00%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function checkCashRegister(price, cash, cid) {

  //转成美分change
  var change = 100 * (cash - price);

  //所有面额的美分数组
  var moneyValues = [1, 5, 10, 25, 100, 500, 1000, 2000, 10000];
  var amtToReturn = [];

  //从最大面额的开始遍历
  for (var i = cid.length-1; i >= 0; i--){
    var amt = 0;
    while (moneyValues[i] <= change && cid[i][1] > 0 && change > 0){
      console.log("subtracting " + moneyValues[i]);
      cid[i][1] -= moneyValues[i]/100;
      change -= moneyValues[i];
      amt += moneyValues[i]/100;
    }
    if (amt !== 0){
      amtToReturn.push([cid[i][0], amt.toFixed(2)]);
    }
  }

  if (change !== 0){
    return "Insufficient Funds";
  }
  
  for (var j = 0; j < cid.length; j++){
    if (cid[j][1] > 0){
      console.log(amtToReturn);
      return amtToReturn;
    }
  }
  
  return "Closed";

}

// Example cash-in-drawer array:
// [["PENNY", 1.01],
// ["NICKEL", 2.05],
// ["DIME", 3.10],
// ["QUARTER", 4.25],
// ["ONE", 90.00],
// ["FIVE", 55.00],
// ["TEN", 20.00],
// ["TWENTY", 60.00],
// ["ONE HUNDRED", 100.00]]

checkCashRegister(19.50, 20.00, [["PENNY", 1.01], ["NICKEL", 2.05], ["DIME", 3.10], ["QUARTER", 4.25], ["ONE", 90.00], ["FIVE", 55.00], ["TEN", 20.00], ["TWENTY", 60.00], ["ONE HUNDRED", 100.00]]);

```

**Comment by wudifeixue** [comment]
运行并不正确哦。我刚检查过这题也是没有问题的。
```JS
checkCashRegister(3.26, 100.00, [["PENNY", 1.01], ["NICKEL", 2.05], ["DIME", 3.10], ["QUARTER", 4.25], ["ONE", 90.00], ["FIVE", 55.00], ["TEN", 20.00], ["TWENTY", 60.00], ["ONE HUNDRED", 100.00]])
```
应该返回 
```JS
[["TWENTY", 60.00], ["TEN", 20.00], ["FIVE", 15], ["ONE", 1], ["QUARTER", 0.50], ["DIME", 0.20], ["PENNY", 0.04]]
```
但是很遗憾你的返回值是
```JS
[["TWENTY","60.00"],["TEN","20.00"],["FIVE","15.00"],["ONE","1.00"],["QUARTER","0.50"],["DIME","0.20"],["PENNY","0.04"]]
```
不过你很接近答案了，加油再接再厉！
