### ISSUE TITLE
这段代码中三目运算语句哪里出错了？

### ISSUE THREAD

**Issue by Hidiandian** [FreeCodeCampChina/freecodecamp.cn#263]
原题地址：[Testing Objects for Properties](http://www.freecodecamp.cn/challenges/testing-objects-for-properties)
```JS
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  myObj.hasOwnProperty(checkProp)?
                                   return myObj[checkProp]:
                                   return "Not Found"
}

// Test your code by modifying these values
checkObj("house");
```

**Comment by wudifeixue** [comment]
三元运算应该写在return后面，写一次return就好了。
```JS
function checkObj(checkProp) {
  // Your Code Here
  return myObj.hasOwnProperty(checkProp) ? //提示到此为止
}
```

**Comment by nodezhp** [comment]
`// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  if(myObj.hasOwnProperty(checkProp) && checkProp == "gift"){
    return myObj.gift;
  }else if(myObj.hasOwnProperty(checkProp) && checkProp == "pet"){
    return myObj.pet;
  }else if(myObj.hasOwnProperty(checkProp) && checkProp == "bed"){
    return myObj.bed;
  }else{
   return "Not Found"; 
  }
}

// Test your code by modifying these values
checkObj("t");
`

**Comment by nodezhp** [comment]
My code:
```javascript
// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  if(myObj.hasOwnProperty(checkProp) && checkProp == "gift"){
    return myObj.gift;
  }else if(myObj.hasOwnProperty(checkProp) && checkProp == "pet"){
    return myObj.pet;
  }else if(myObj.hasOwnProperty(checkProp) && checkProp == "bed"){
    return myObj.bed;
  }else{
   return "Not Found"; 
  }
}

// Test your code by modifying these values
checkObj("t");

```

**Comment by zhangwenhui123** [comment]
```JS
// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  if(myObj.hasOwnProperty(checkProp)){
    return myObj[checkProp];
  }
  return "Not Found";
}

// Test your code by modifying these values
checkObj("gift");
```

**Comment by Wesley1993** [comment]
三目运算的格式有问题
三目运算后面是表达式，你用的return不是表达式

**Comment by wudifeixue** [comment]
~~注意虽然你们可以用 if 语句通关，但是并不建议这么做，这里的目的是为了学会三元。~~
最近按着顺序我重新review了这道题，发现说用三元很不靠谱，因为完全没学啊！
于是在这里发出[三元运算符文档](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Conditional_Operator)。
其次这题的解法很多，大家可以多思考一下。

**Comment by slowlearnerLspeedup** [comment]
楼上说的没错，这里这道题的理念是三元运算设计。但很多新手做题在看完FCC左边的提示后一般只能用之前做题学会的条件语句来处理，如果这道题FCC在左边如果有三元运算相对应格式，就不会有那么多事了。
我在做的时候也是这样，下面是我依次想出的四种办法过关的：
方法一：
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};
function checkObj(checkProp) {
 var result=myObj[checkProp];
  switch(checkProp){
    case "gift":
     return result;
      break;
    case "pet":
      return result;
      break;
    case "bed":
      return result;
      break;
  }
  return "Not Found";
}
checkObj("gift");//pony

方法二：
function checkObj(checkProp) {
 var result=myObj[checkProp];
 switch(myObj.hasOwnProperty(checkProp)){
   case true:
     return result;
     break;
   case false:
     return "Not Found";
     break;
} 
}

方法三（这个其实也算三元运算，只不过这种穷举法并没有应用到FCC左边提示的.hasOwnProperty(propname)的方法）：
function checkObj(checkProp) {
 var result=myObj[checkProp];
  if (checkProp=="gift" || checkProp=="pet" || checkProp=="bed"){
    return result;
  } 
    return "Not Found";
}

方法四（重点，三元运算：if a 则 b，not a 则 c）：
 var result=myObj[checkProp];
  if (myObj.hasOwnProperty(checkProp)===true){
    return result;
  } 
    return "Not Found";
}
//语句里的===其实换成==也可过关，但在用==号过关的时候出现了温馨提示：use "===" to compare with true。

**Comment by S1ngS1ng** [comment]
@Rodney2012 思路是对的，但三和四都不是三元表达式。。。

第三种方法，真正开发过程中也是不推荐的，因为已经有了 `hasOwnProperty` 这个方法。

第四种，首先，`if (myObj.hasOwnProperty(checkProp)===true)` 不需要这么写，`=== true` 可以去掉。因为 `if` 表达式会帮你转换成 Boolean。

其次，按照你的思路，完全可以写成一行，看不出赋值 `result` 的必要：

```
return myObj[checkProp] || "Not Found";
```

当然这么写也和三元没有任何关系。三元表达式的结构一定是，而且只能是 `a ? b : c`。因此，你要把判断条件放到 `a` 的位置，`true` 的代码放到 `b` 的位置，`false` 的放到 `c`。

**Comment by kinksteven** [comment]
我也写一个献个丑O(∩_∩)O
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};
function checkObj(checkProp) {
  // 请把你的代码写在这条注释以下
  var a = myObj.hasOwnProperty(checkProp);
  if(a)
   {
    return  myObj[checkProp];    //但是这里用点操作符  myObj.checkProp 就无法通过。checkProp应该是
                                                  //个变量。
    } 
else
  {
  return "Not Found";
  }
}
// 你可以修改这一行来测试你的代码
checkObj("gift");

 @nodezhp 能少写就不要多写，我建议。

**Comment by Boyue1988** [comment]
只是好奇为啥：
if (myObj.hasOwnProperty("checkProp")){
return myObj["checkProp"];
}
return "Not Found";
}
//按照题目左边的实例添加““给 checkProp 属性，为啥是错误的。

**Comment by kissuma** [comment]
// 初始化变量
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // 请把你的代码写在这条注释以下
  myObj.hasOwnProperty("checkProp");
  return myObj[checkProp]||"Not Found";
}

// 你可以修改这一行来测试你的代码
checkObj("skin");

**Comment by pkbill511** [comment]
// 初始化变量
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // 请把你的代码写在这条注释以下
  if(myObj.hasOwnProperty(checkProp)){
    return myObj[checkProp];
  }else{
    return "Not Found";
  }
  
}

// 你可以修改这一行来测试你的代码
checkObj("gift");
