### ISSUE TITLE
一直显示"testing challenge..."

### ISSUE THREAD

**Issue by FengHaiSheng** [FreeCodeCampChina/freecodecamp.cn#264]
Challenge [Arguments Optional](http://freecodecamp.cn/challenges/arguments-optional#?solution=function%20add()%20%7B%0A%20%20var%20_args%20%3D%20%5B%5D.slice.call(arguments)%3B%0A%20%20if(!isNumber(_args))%7B%0A%20%20%20%20return%20undefined%3B%0A%20%20%7D%0A%20%20var%20adder1%20%3D%20function()%7B%0A%20%20%20%20var%20_adder%20%3D%20function()%7B%0A%20%20%20%20%20%20var%20args%20%3D%20%5B%5D.slice.call(arguments)%3B%0A%20%20%20%20%20%20if(!isNumber(args))%7B%0A%20%20%20%20%20%20%20%20return%20undefined%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%5B%5D.push.apply(_args%2Cargs)%3B%0A%20%20%20%20%20%20return%20_adder%3B%0A%20%20%20%20%7D%3B%0A%20%20%20%20_adder.toString%20%3D%20function()%7B%0A%20%20%20%20%20%20return%20_args.reduce(function(a%2Cb)%7B%0A%20%20%20%20%20%20%20%20return%20a%20%2B%20b%3B%0A%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%7D%3B%0A%20%20%20%20return%20_adder%3B%0A%20%20%7D%3B%0A%20%20return%20adder1.apply(null%2C%5B%5D.slice.call(arguments))%3B%0A%7D%0A%0Afunction%20isNumber(arr)%7B%0A%20%20return%20arr.every(function(elem)%7B%0A%20%20%20%20return%20typeof%20elem%20%3D%3D%20'number'%3B%0A%20%20%7D)%3B%0A%7D%0A%0Aadd(2%2C3%2C4%2C5%2C6)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36 QQBrowser/4.2.4718.400</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function add() {
  var _args = [].slice.call(arguments);
  if(!isNumber(_args)){
    return undefined;
  }
  var adder1 = function(){
    var _adder = function(){
      var args = [].slice.call(arguments);
      if(!isNumber(args)){
        return undefined;
      }
      [].push.apply(_args,args);
      return _adder;
    };
    _adder.toString = function(){
      return _args.reduce(function(a,b){
        return a + b;
      });
    };
    return _adder;
  };
  return adder1.apply(null,[].slice.call(arguments));
}

function isNumber(arr){
  return arr.every(function(elem){
    return typeof elem == 'number';
  });
}

add(2,3,4,5,6);

```
一直显示“testing challenge...”,不知都是什么原因！

**Comment by wudifeixue** [comment]
我觉得你这题明显想复杂了。直接用 arguments[0]，arguments[1]判断多好呀。。

然后你的代码我也试着本地运行了下，结果在
```JS
add(2,3);
add(2)(3);
```
的情况下，输出也都是
`function 5`
这就不对了，答案应该直接是计算结果`5`啊。建议你再想想。
而且你写了两个function，在FCC调用起来也可能成问题。

**Comment by FengHaiSheng** [comment]
是的，我是想到了add(1)(2)(3)这样的情况

**Comment by S1ngS1ng** [comment]
@FengHaiSheng 你的思路基本上是对的，只是你忽略了一点，要判断参数传入的终点。目前，你没有这个判断，因此最后返回值里面会有 `_add` 那个 `function` 的引用
