### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by easy261925** [FreeCodeCampChina/freecodecamp.cn#265]
Challenge [Warn your Users of a Dangerous Action](https://freecodecamp.cn/challenges/warn-your-users-of-a-dangerous-action#?solution=%3Clink%20href%3D%22%2F%2Ffonts.gdgdocs.org%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch2%20class%3D%22red-text%20text-center%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%20%20%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%20%20%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22%2Fimages%2Frelaxing-cat.jpg%22%3E%3C%2Fa%3E%0A%0A%20%20%3Cimg%20src%3D%22%2Fimages%2Frunning-cat.jpg%22%20class%3D%22img-responsive%22%3E%0A%20%20%3Cbutton%20class%3D%22btn%20btn-block%20btn-primary%22%3ELike%3C%2Fbutton%3E%0A%20%20%3Cbutton%20class%3D%22btn%20btn-block%20btn-info%22%3EInfo%3C%2Fbutton%3E%0A%20%20%3Cbutton%20class%3D%22btn%20btn-block%20btn-danger%22%3EDelete%3C%2Fbutton%3E%0A%20%20%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%20%20%0A%20%20%3Cul%3E%0A%20%20%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%20%20%3C%2Ful%3E%0A%20%20%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%20%20%3Col%3E%0A%20%20%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%20%20%3C%2Fol%3E%0A%20%20%3Cform%20fccfaa%3D%22%2Fsubmit-cat-photo%22%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Indoor%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Outdoor%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Loving%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Lazy%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Crazy%3C%2Flabel%3E%0A%20%20%20%20%3Cinput%20type%3D%22text%22%20placeholder%3D%22cat%20photo%20URL%22%20required%3E%0A%20%20%20%20%3Cbutton%20type%3D%22submit%22%3ESubmit%3C%2Fbutton%3E%0A%20%20%3C%2Fform%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="//fonts.gdgdocs.org/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<div class="container-fluid">
  <h2 class="red-text text-center">CatPhotoApp</h2>

  <p>Click here for <a href="#">cat photos</a>.</p>

  <a href="#"><img class="smaller-image thick-green-border" src="/images/relaxing-cat.jpg"></a>

  <img src="/images/running-cat.jpg" class="img-responsive">
  <button class="btn btn-block btn-primary">Like</button>
  <button class="btn btn-block btn-info">Info</button>
  <button class="btn btn-block btn-danger">Delete</button>
  <p>Things cats love:</p>
  
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```

**Comment by wudifeixue** [comment]
。。亲，您的代码我这里可以直接过测试。建议刷新下浏览器。如果不行那就[强制清空浏览器缓存](https://github.com/FreeCodeCampChina/freecodecamp.cn/wiki/%E5%A6%82%E4%BD%95%E5%BC%BA%E5%88%B6%E6%B8%85%E7%A9%BA%E6%B5%8F%E8%A7%88%E5%99%A8%E7%BC%93%E5%AD%98)试试。

**Comment by easy261925** [comment]
您好，代码可以正常显示，但是这一部分课程讲的是运用Bootstrap框架修改CSS，而默认的代码当中，没有LINK Bootstrap。所以显示与预期不同

**Comment by wudifeixue** [comment]
是这样没错..不过里面确实已经用了Bootstrap了呀。所有Bootstrap的功能都能调用，隐藏起来了链接并不能算bug呀。

**Comment by easy261925** [comment]
嗯，我知道隐藏起来了，但是我用了Bootstrap相关的语法，显示栏没有相应效果，不就是BUG了吗？

**Comment by wudifeixue** [comment]
有效果呀！？没有么？？能否截个图。
![image](https://cloud.githubusercontent.com/assets/7316929/25471218/4d0478b2-2ae3-11e7-96a4-09cfdb21b8f9.png)

**Comment by easy261925** [comment]
我用360，crome都实验过了，确实跟您的效果不一样，上传图片总是失败。不好意思

**Comment by easy261925** [comment]
![1](https://cloud.githubusercontent.com/assets/25454721/25473088/98adf928-2b60-11e7-9a48-25a11cb32fb6.jpg)

**Comment by wudifeixue** [comment]
你这情况还真是特别，我怀疑Bootstrap的资源被墙了。其他的Bootstrap题也一样不显示效果么？还是只有这题

**Comment by easy261925** [comment]
从Bootstrap开始，以后所有关于这方面的题都是这样（没有效果），我换了好几个浏览器了，也不行，我只是担心往下进行会不会影响效果

**Comment by wudifeixue** [comment]
Bootstrap的部分其实并没有很多，不过你这个问题头一次见 后面会稍微有一点jQuery和大量的JavaScript

**Comment by easy261925** [comment]
嗯，好的，非常感谢！

**Comment by S1ngS1ng** [comment]
@easy261925 有没有开 VPN？
你试一下，直接访问这个网址能不能出现代码：https://cdn.bootcss.com/bootstrap/3.3.1/css/bootstrap.min.css

如果不能，开 VPN 试试。如果能，那应该就是没问题的
