### ISSUE TITLE
🍀改变字符串的值

### ISSUE THREAD

**Issue by sunshinehelloworld** [FreeCodeCampChina/freecodecamp.cn#266]
#### FreeCodeCamp.cn Issue 模板
如何使用本模板:
* 尽可能多填些相关信息，方便管理员参考
* 对于无法给出的内容，请删除掉那一行

# 以上内容请在提交 Issue 之前删除

#### 浏览器信息
* 浏览器名称，版本号
* 操作系统

#### 问题描述
* 问题是在什么时候，什么情况下遇到的
* 简要说明如何重现

#### 你的代码

```
如果和代码相关，请在这里粘贴你的全部代码
```

**Comment by wudifeixue** [comment]
注意：请不要乱开无意义的 Issue

**Comment by sunshinehelloworld** [comment]
sorry

在 2017-04-27 15:04:57，"Curtis Xiao" <notifications@github.com> 写道：


注意：请不要乱开无意义的 Issue
