### ISSUE TITLE
counting card 那个怎么做  194

### ISSUE THREAD

**Issue by duandli** [FreeCodeCampChina/freecodecamp.cn#27]
#### FreeCodeCamp Issue template

To Use this Template:
- Fill out what you can
- Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/chinese
#### Issue Description
- When Issue Happens
- Steps To Reproduce
#### Browser Information
- Browser Name, Version
- Operating System
#### Your Code

``` js
If relevant, paste all of your challenge code in here
```

**Comment by jamesbeme** [comment]
Cancel my subscription

**Comment by huluoyang** [comment]
@duandli  FCC问答中有类似问题的提问和解答，这里不复述。

**Comment by ghost** [comment]
你解决了吗？
