### ISSUE TITLE
课程目标应用功能无法显示

### ISSUE THREAD

**Issue by Wonder233** [FreeCodeCampChina/freecodecamp.cn#273]
#### 浏览器信息
* chrome浏览器，版本号58.0.3029.81
* 操作系统：win7

#### 问题描述
* Intermediate Front End Development Projects 里的三个课程：show the local weather及之后的两个课程中的目标应用的基本功能都显示不出来。
http://codepen.io/huluoyang/full/bedeBR/
http://codepen.io/FreeCodeCamp/full/pgNRvJ
http://codepen.io/freeCodeCamp/full/adBpOw

#### 截图
![1](https://cloud.githubusercontent.com/assets/8199240/25646554/28323f84-2fec-11e7-9146-309e5a6b7ec3.png)
![2](https://cloud.githubusercontent.com/assets/8199240/25646556/2af946c2-2fec-11e7-97f2-60b90c3e6b8a.png)
![3](https://cloud.githubusercontent.com/assets/8199240/25646557/2d4f8e90-2fec-11e7-81c1-adb68626550d.png)

**Comment by wudifeixue** [comment]
感谢你提交的issue，在修复过程中(服务器更新之前还要些时间)，你项目可以先参考
- ~~[Show the Local Weather](https://codepen.io/freeCodeCamp/full/bELRjV)~~ [Show the Local Weather (With Wunder Ground API)](https://codepen.io/thoragio/pen/BzdNKv)
- [Build a Wikipedia Viewer](https://codepen.io/freeCodeCamp/full/wGqEga)
- [Use the Twitchtv JSON API](https://codepen.io/freeCodeCamp/full/Myvqmo)

**Comment by wudifeixue** [comment]
It looks like the first Weather API will need some work, even on freeCodeCamp.com the project is also broken due to API. My pull request will only fix the Wikipedia Viewer and Twitch JSON API. 
[#8988](https://github.com/freeCodeCamp/freeCodeCamp/issues/8988)

**Comment by Wonder233** [comment]
谢谢你给的参考样例@wudifeixue ^-^

**Comment by Jiaget** [comment]
新的样例，谷歌浏览器还是无法显示，换成IE可以。然后，小伙伴们的浏览器也无法显示，这是什么原因？
