### ISSUE TITLE
h2字体没有按照预期从Lobster降级到Monosapce

### ISSUE THREAD

**Issue by YinFFF** [FreeCodeCampChina/freecodecamp.cn#275]
Challenge [Specify How Fonts Should Degrade](https://freecodecamp.cn/challenges/specify-how-fonts-should-degrade#?solution=%3C!---%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.gdgdocs.org%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A---%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3E%E5%9C%A8%E5%A4%A7%E5%AE%B6%E5%BF%83%E7%9B%AE%E4%B8%AD%EF%BC%8C%E7%8C%AB%E6%98%AF%E6%85%B5%E6%87%92%E7%9A%84%E5%8F%AF%E7%88%B1%E7%9A%84%E5%8C%96%E8%BA%AB%EF%BC%8C%E5%AE%83%E5%8F%AF%E4%BB%A5%E7%9D%A1%E9%A5%B1%E4%BA%86%E5%86%8D%E8%B5%B7%E6%9D%A5%E5%90%83%E9%A5%AD%EF%BC%8C%E5%8F%AF%E4%BB%A5%E9%80%97%E8%B6%A3%E5%B0%8F%E8%80%97%E5%AD%90%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%8D%96%E5%BE%97%E4%BA%86%E8%90%8C%EF%BC%8C%E4%BD%BF%E5%BE%97%E4%BA%86%E5%9D%8F%EF%BC%8C%E8%BF%99%E6%A0%B7%E7%99%BE%E5%8F%98%E7%9A%84%E5%B0%8F%E6%80%AA%E5%85%BD%E5%B0%B1%E9%9B%86%E7%BB%93%E5%9C%A8%E4%B8%80%E5%8F%AA%E5%AE%A0%E7%89%A9%E4%B8%8A%EF%BC%8C%E6%80%8E%E8%83%BD%E4%B8%8D%E6%83%B9%E4%BA%BA%E6%80%9C%E7%88%B1%E3%80%82%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3E%E5%85%BB%E5%8A%A8%E7%89%A9%E6%9C%89%E7%9A%84%E6%97%B6%E5%80%99%EF%BC%8C%E5%B0%B1%E6%98%AF%E4%BB%8B%E4%BA%8E%E7%88%B1%E4%B8%8E%E6%81%A8%E4%B9%8B%E9%97%B4%EF%BC%8C%E5%BD%93%E4%BD%A0%E9%92%A6%E7%BE%A1%E5%88%AB%E4%BA%BA%E8%90%8C%E5%AE%A0%E8%BF%99%E4%B9%88%E5%8F%AF%E7%88%B1%E7%9A%84%E6%97%B6%E5%80%99%EF%BC%8C%E4%BD%A0%E4%B8%80%E5%AE%9A%E6%B2%A1%E6%9C%89%E6%83%B3%E8%BF%87%EF%BC%8C%E7%8B%97%E7%8B%97%E5%92%8C%E7%8C%AB%E7%8C%AB%E4%BC%9A%E5%88%B0%E5%A4%84%E6%8B%89%E5%B1%8E%EF%BC%8C%E7%94%9A%E8%87%B3%E4%BC%9A%E5%B1%AF%E8%80%81%E9%BC%A0%EF%BC%8C%E5%95%83%E9%9E%8B%E5%AD%90%EF%BC%8C%E7%94%A8%E7%88%AA%E5%AD%90%E7%88%AC%E9%97%A8%EF%BC%8C%E4%BD%A0%E4%B8%8D%E7%90%86%E5%AE%83%EF%BC%8C%E5%AE%83%E5%B0%B1%E6%8C%A0%E4%BD%A0%EF%BC%8C%E4%BD%A0%E8%A6%81%E5%AF%B9%E5%AE%83%E5%8F%91%E8%84%BE%E6%B0%94%EF%BC%8C%E5%AE%83%E4%BC%9A%E6%AF%94%E4%BD%A0%E6%9B%B4%E6%9D%A5%E5%8A%B2%E3%80%82%E6%89%80%E4%BB%A5%EF%BC%8C%E7%8B%97%E7%8C%AB%E6%85%8E%E5%85%A5%EF%BC%8C%E6%B2%A1%E6%9C%89%E4%B8%80%E5%AE%9A%E7%9A%84%E5%87%86%E5%A4%87%EF%BC%8C%E5%88%87%E5%8B%BF%E9%9A%8F%E4%BE%BF%E5%8E%BB%E4%BE%8D%E5%85%BB%E5%8A%A8%E7%89%A9%E3%80%82%E5%AE%83%E4%BB%AC%E4%B8%80%E6%97%A6%E8%AE%A4%E5%AE%9A%E4%BD%A0%E4%BA%86%EF%BC%8C%E4%BD%A0%E5%B0%B1%E6%98%AF%E5%AE%83%E4%BB%AC%E7%9A%84%E4%B8%BB%E4%BA%BA%EF%BC%8C%E5%A6%82%E6%9E%9C%E4%BD%A0%E6%8A%9B%E5%BC%83%E5%AE%83%E4%BB%AC%EF%BC%8C%E5%AE%83%E4%BB%AC%E5%BF%85%E5%AE%9A%E5%BF%83%E4%B8%AD%E9%87%8D%E5%88%9B%E3%80%82%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!---
<link href="https://fonts.gdgdocs.org/css?family=Lobster" rel="stylesheet" type="text/css">
--->
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">在大家心目中，猫是慵懒的可爱的化身，它可以睡饱了再起来吃饭，可以逗趣小耗子，可以卖得了萌，使得了坏，这样百变的小怪兽就集结在一只宠物上，怎能不惹人怜爱。</p>
<p class="red-text">养动物有的时候，就是介于爱与恨之间，当你钦羡别人萌宠这么可爱的时候，你一定没有想过，狗狗和猫猫会到处拉屎，甚至会屯老鼠，啃鞋子，用爪子爬门，你不理它，它就挠你，你要对它发脾气，它会比你更来劲。所以，狗猫慎入，没有一定的准备，切勿随便去侍养动物。它们一旦认定你了，你就是它们的主人，如果你抛弃它们，它们必定心中重创。</p>

```

**Comment by wudifeixue** [comment]
能否截图下，我这里很成功的降级了啊

![image](https://cloud.githubusercontent.com/assets/7316929/25758825/404fe6aa-318d-11e7-8970-a24cc99c6fe1.png)

**Comment by YinFFF** [comment]
好的，我这边的情况是这样的：
![qq 20170506114052](https://cloud.githubusercontent.com/assets/13734017/25769605/dc58da02-3250-11e7-8e86-6abe5e8851cc.png)
试了下将<link>标签取消，发现我这里不需要<link>标签也可以用Lobster：
![qq 20170506114856](https://cloud.githubusercontent.com/assets/13734017/25769657/14440b48-3252-11e7-9902-3de6b3e67ba5.png)
最后再确认下不使用Lobster的情况：
![4](https://cloud.githubusercontent.com/assets/13734017/25769689/bed2da80-3252-11e7-8110-ec479034f562.png)

> 我的chrome版本是：
![7 z12xzh0gi tcvaiwu sv](https://cloud.githubusercontent.com/assets/13734017/25769694/09219392-3253-11e7-90a1-96db658965f7.png)

> win10版本是：
![dr wl275s b3ei 6yo cxz6](https://cloud.githubusercontent.com/assets/13734017/25769702/3bbb46b8-3253-11e7-87af-d0ac509603f2.png)

**Comment by S1ngS1ng** [comment]
@YinFFF 谢谢。信息很详细。等我的机器运过来了我试一下

**Comment by wudifeixue** [comment]
感谢详细的截图和描述，我又想了想关于这个。
可以考虑重新刷新页面，然后清空浏览器缓存，或者干脆替换浏览器来看看效果。
这个我在不一样的机器上测试都没有问题。我怀疑是因为这个字体你在别的哪里缓存过所以可以直接调出来。

**Comment by YinFFF** [comment]
@wudifeixue 谢谢，我根据你的建议检查了下，发现了问题的原因！
不过不是因为浏览器的缓存原因，是因为我电脑自带Lobster字体：
![yv9onk_s xr1l7 u h21](https://cloud.githubusercontent.com/assets/13734017/25792930/2db85060-33fc-11e7-9e3a-778c7a48c396.png)
删除掉Lobster字体后显示结果就正常了：
![be8 1xydg0i r 4d_d2](https://cloud.githubusercontent.com/assets/13734017/25793005/8dcad978-33fc-11e7-9afe-d5cb904519f0.png)

**Comment by wudifeixue** [comment]
你这个情况还真是少见😂 不过感谢你详细而且高质量的issue

**Comment by metaQyw** [comment]
![image](https://user-images.githubusercontent.com/32019284/32059929-10c04a14-baa0-11e7-960e-240afaf9158d.png)
**QQ浏览器版本：**

**操作系统：64位Windows10家庭普通版**

遇到了一样的问题，建议把练习的字体改一改吧？似乎是Windows10自带的字体了。

对于新手来说很容易造成认识混乱？

——2017/10/28 12：48更新——
仔细查找比对后发现，Lobster字体并不是Windows10的默认字体。 它是我自己安装的软件 **Xmind8** 在安装时自动引入的，而它在安装时并没有字体引入的提示，导致我误以为是Win10的问题。

**Comment by S1ngS1ng** [comment]
@wudifeixue Thoughts?

**Comment by wudifeixue** [comment]
我仔细调查了一下好几台电脑然后都测试看后，Lobster并不是Win10默认字体啊。中文英文操作系统我都试了试。

**Comment by metaQyw** [comment]
很抱歉，给你们造成了麻烦，我仔细查找比对之后发现的确是我错了。
Lobster并不是Win10默认字体，也不是更新带来的。而是我自己安装的软件**Xmind8**在安装后自动引入的。
因为它在安装时没有任何提示安装字体的问题，我就误以为是win10的原因，太过于想当然了。很感谢各位认真的态度，回复的也很及时，请原谅我的冒失。

**Comment by wudifeixue** [comment]
哈哈没事儿你太客气了，谢谢你有疑问就来提议，有别的地方也别犹豫尽管提问我们是很欢迎的  
那我先关了这个issue了哈

**Comment by mimzygo** [comment]
我也安装了xmind8，也出现了这个问题，这个问答解决了我的疑惑。
