### ISSUE TITLE
代码都没问题，而且在编辑器中测试过，但就是通过不了，实在不知道是什么原因

### ISSUE THREAD

**Issue by zhangjunorhongxia** [FreeCodeCampChina/freecodecamp.cn#279]
## 题目链接
- [Understand String Immutability](https://www.freecodecamp.cn/challenges/understand-string-immutability)
```JS
// Setup
var myStr = "Jello World";

// Only change code below this line
myStr = 'Hello World';
myStr[0] = "H"; // Fix Me
```

**Comment by S1ngS1ng** [comment]
@zhangjunorhongxia 其实你只需要你写的第一行 `myStr = 'Hello World';` 就够了。左边题目说明已经告诉你，写最后那一行是不会有任何效果的。因此你应该把它删掉。

不过，可能是因为提示信息没有翻译的问题吧。我尽快把这个翻译加上。最后一行的 “Fix Me” 的意思是，“修改这里”

**Comment by zhangjunorhongxia** [comment]
我尝试过只把第一行的代码更改为var myStr = "Hello World",但是提交还是不行的

**Comment by S1ngS1ng** [comment]
@zhangjunorhongxia 
首先，上面说了，你应该改的是 “你写的第一行”，不是一开始 `var myStr = "Jello World"` 那一行。
另外，上面也说了，你应该写成 `myStr = 'Hello World';`。因为前面已经声明过 `myStr`，因此不需要，也不应该用 `var` 再声明一次

**Comment by zhangjunorhongxia** [comment]
```JS
var myStr = "Jello World";
myStr = "Hello World";
// Only change code below this line

myStr[0] = "H"; // Fix Me
```
修改后的代码是这样的，但点提交 还是通不过的

**Comment by S1ngS1ng** [comment]
@zhangjunorhongxia 
> 写最后那一行是不会有任何效果的。因此你应该把它删掉。

麻烦你仔细看一下上面跟你说的

**Comment by H29** [comment]
```JS
// Setup
var myStr = "Jello World";

// Only change code below this line// Fix Me
myStr="Hello World";
```
代码应该这样，删除myStr [0] =“H”; 这段代码。

**Comment by toBeTheLight** [comment]
```JS
var myStr = "Jello World";
myStr = 'Hello World';
```

**Comment by wudifeixue** [comment]
![image](https://user-images.githubusercontent.com/7316929/27327358-a1a7e07c-556b-11e7-9cba-2084c178dac4.png)
现在已经更新成中文了，描述应该已经很清楚。我就把issue关了。
