### ISSUE TITLE
Inform with the Paragraph Element中，P应该是小写

### ISSUE THREAD

**Issue by ruguoname** [FreeCodeCampChina/freecodecamp.cn#28]
Challenge [Inform with the Paragraph Element](https://freecodecamp.cn/challenges/inform-with-the-paragraph-element#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3E%E6%88%91%E5%AE%B6%E7%9A%84%E7%8C%AB%E5%92%AA%3C%2Fh2%3E%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html
<h1>Hello World</h1>
<h2>我家的猫咪</h2>
<p>Hello Paragraph</p>

```

> P是英文paragraph段落的缩写，经常被用来创建一个段落，就和你写作文一样。

其中，P应该是小写

**Comment by jamesbeme** [comment]
Remove my name from your list. Send no more emails. Unsubscribe me from
your email list.

**Comment by jamesbeme** [comment]
Stop sending further email

**Comment by jamesbeme** [comment]
Sending further email

**Comment by discountry** [comment]
已修正

**Comment by huluoyang** [comment]
@jamesbeme  为什么到处都有你的退订评论啊？你自己点击Unsubscribe即可啊，就在界面右边。

**Comment by xieyangfight** [comment]
第二段文章的话还是继续用<p>和</p>么？谢谢

**Comment by chengqingxing** [comment]
我还是不会谁能噶告诉我答案过不去。。。
