### ISSUE TITLE
Finders Keepers项目，答案验证的不对，[1, 3, 5, 8, 9, 10]这个数组不应该返回8和10吗？为什么答案却是只返回8

### ISSUE THREAD

**Issue by cunxi1992** [FreeCodeCampChina/freecodecamp.cn#281]
#### 浏览器信息
* Google
* MAC

#### 问题描述
* 答案验证的不对，[1, 3, 5, 8, 9, 10]这个数组不应该返回8和10吗？为什么答案却是只返回8

#### 你的代码
function find(arr, func) {
  var str = 0;
  str = arr.filter(func);
  if(str.length !== 0){
    return str;
  }else{
    return undefined;
  }
  
  
}

find([1, 3, 5, 8, 9, 10], function(num){ return num % 2 === 0; });

```
如果和代码相关，请在这里粘贴你的全部代码
```

#### 截图（如果有）
![image](https://cloud.githubusercontent.com/assets/25634080/25900585/8095ac9e-35c6-11e7-84e5-96ac110f2a07.png)

**Comment by ylsxch** [comment]
哥们，题目要求【写一个 function，它浏览数组（第一个参数）并返回数组中第一个通过某种方法（第二个参数）验证的元素。】
只返回参数1中满足参数2条件的第一个元素，不是全部满足条件的元素。

**Comment by cunxi1992** [comment]
额，好的，谢谢，我理解错了题目。非常感谢。
