### ISSUE TITLE
codepen无法注册，提交不了https://freecodecamp.cn/challenges/build-a-tribute-page

### ISSUE THREAD

**Issue by was277** [FreeCodeCampChina/freecodecamp.cn#282]
#### FreeCodeCamp.cn Issue 模板
如何使用本模板:
* 尽可能多填些相关信息，方便管理员参考
* 对于无法给出的内容，请删除掉那一行

# 以上内容请在提交 Issue 之前删除

#### 浏览器信息
* 浏览器名称，版本号
* 操作系统

#### 问题描述
* 问题是在什么时候，什么情况下遇到的
* 简要说明如何重现

#### 你的代码

```
如果和代码相关，请在这里粘贴你的全部代码
```

**Comment by S1ngS1ng** [comment]
@was277 
1. **下次再开 issue，麻烦你花点时间看看模板里的说明内容。留下该留的，删掉该删的**
2. 这个貌似和 fcc 没有直接关系
3. 解决方案：VPN
