### ISSUE TITLE
edge浏览器开了油猴护眼插件无法运行

### ISSUE THREAD

**Issue by AlbieRWang** [FreeCodeCampChina/freecodecamp.cn#284]
Challenge [Delete HTML Elements](http://www.freecodecamp.cn/challenges/delete-html-elements#?solution=%0A%3Ch2%3E%E6%88%91%E5%AE%B6%E7%9A%84%E7%8C%AB%E5%92%AA%3C%2Fh2%3E%0A%0A%3Cp%3E%E5%9C%A8%E5%A4%A7%E5%AE%B6%E5%BF%83%E7%9B%AE%E4%B8%AD%EF%BC%8C%E7%8C%AB%E6%98%AF%E6%85%B5%E6%87%92%E7%9A%84%E5%8F%AF%E7%88%B1%E7%9A%84%E5%8C%96%E8%BA%AB%EF%BC%8C%E5%AE%83%E5%8F%AF%E4%BB%A5%E7%9D%A1%E9%A5%B1%E4%BA%86%E5%86%8D%E8%B5%B7%E6%9D%A5%E5%90%83%E9%A5%AD%EF%BC%8C%E5%8F%AF%E4%BB%A5%E9%80%97%E8%B6%A3%E5%B0%8F%E8%80%97%E5%AD%90%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%8D%96%E5%BE%97%E4%BA%86%E8%90%8C%EF%BC%8C%E4%BD%BF%E5%BE%97%E4%BA%86%E5%9D%8F%EF%BC%8C%E8%BF%99%E6%A0%B7%E7%99%BE%E5%8F%98%E7%9A%84%E5%B0%8F%E6%80%AA%E5%85%BD%E5%B0%B1%E9%9B%86%E7%BB%93%E5%9C%A8%E4%B8%80%E5%8F%AA%E5%AE%A0%E7%89%A9%E4%B8%8A%EF%BC%8C%E6%80%8E%E8%83%BD%E4%B8%8D%E6%83%B9%E4%BA%BA%E6%80%9C%E7%88%B1%E3%80%82%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.16188</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h2>我家的猫咪</h2>

<p>在大家心目中，猫是慵懒的可爱的化身，它可以睡饱了再起来吃饭，可以逗趣小耗子，可以卖得了萌，使得了坏，这样百变的小怪兽就集结在一只宠物上，怎能不惹人怜爱。</p>

```
在开了Tampermonkey 护眼脚本时Run Tests无反应
关闭后正常了

**Comment by S1ngS1ng** [comment]
@AlbieRWang 请发一下插件链接。另外，无论是 FreeCodeCamp 还是 FreeCodeCamp.cn，讲道理都不可能为了这一个插件去重写测试函数

**Comment by AlbieRWang** [comment]
https://greasyfork.org/en/scripts/14716-护眼脚本/feedback

**Comment by S1ngS1ng** [comment]
@AlbieRWang 看了下，插件代码中没有节点操作，理论上不是插件的事儿。只能猜测是测试函数或 observer 被阻止或覆盖。试试其他浏览器吧，如果别的浏览器也不行，就只能关掉插件了
