### ISSUE TITLE
I've delete all \ . but it still tells only delete \. what's going on?

### ISSUE THREAD

**Issue by alanwu123** [FreeCodeCampChina/freecodecamp.cn#285]
Challenge [Quoting Strings with Single Quotes](https://www.freecodecamp.cn/challenges/quoting-strings-with-single-quotes#?solution=var%20myStr%20%3D%20'%3Ca%20href%3D%22http%2F%2F%3Awww.example.com%22%20target%3D%22_blank%22%3ELink%3C%2Fa%3E'%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr = '<a href="http//:www.example.com" target="_blank">Link</a>';



```

**Comment by YangPengFe1** [comment]
### you right.

**Comment by S1ngS1ng** [comment]
@alanwu123 
```
'<a href="http//:www.example.com" target="_blank">Link</a>'
                ↑
```

The colon here is misplaced. You are not supposed to modify anything other than the slashes and quotes.

**Comment by asqhay** [comment]
very nice
