### ISSUE TITLE
不明白为什么浏览器一直不能通过呢？

### ISSUE THREAD

**Issue by colin1suntao** [FreeCodeCampChina/freecodecamp.cn#286]
#### 浏览器信息
* 浏览器名称 chrome，版本号 57.0.2987.133
* 操作系统  win10

#### 问题描述
* 问题是在什么时候，什么情况下遇到的
* 简要说明如何重现
I don't understand this question , please help me pass this level.
#### 你的代码
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function update(id, prop, value) {
  if(value != " " && prop != "tracks") {
    collectionCopy[id][prop] = value;
    
  }else if ( value != " " && prop == 'tracks') {
    collectionCopy[id][prop].push(value);
    
  }else if (value == " ") {
    delete colectionCopy[id][prop];
  }

  return collectionCopy;
}

// Alter values below to test your code
update(5439, "artist", "ABBA");

```
如果和代码相关，请在这里粘贴你的全部代码
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function update(id, prop, value) {
  if(value != " " && prop != "tracks") {
    collectionCopy[id][prop] = value;
    
  }else if ( value != " " && prop == 'tracks') {
    collectionCopy[id][prop].push(value);
    
  }else if (value == " ") {
    delete colectionCopy[id][prop];
  }

  return collectionCopy;
}

// Alter values below to test your code
update(5439, "artist", "ABBA");



#### 截图（如果有）

**Comment by S1ngS1ng** [comment]
@colin1suntao 首先你不应该用 `value !== " "` 来判断，应该把空格去掉。
其次，`delete` 那里你有个拼写错误。
另外，这不是 bug。去 gitter 讨论组讨论吧

**Comment by colin1suntao** [comment]
@S1ngS1ng 谢谢，已经通过测试
