### ISSUE TITLE
【119】（Change Text Inside an Element Using jQuery ）满足条件有问题

### ISSUE THREAD

**Issue by lijma** [FreeCodeCampChina/freecodecamp.cn#289]
#### 浏览器信息
* 浏览器名称，版本号
chrome: 58.0.3029.81
* 操作系统
win7

#### 问题描述
* 问题是在什么时候，什么情况下遇到的
在挑战【119】html5 》  Change Text Inside an Element Using jQuery

* 简要说明如何重现
按照guideline我添加了$("#target4").html("<em>target4</em>");
但是第二条件一直无法满足

#### 截图（如果有）
![image](https://cloud.githubusercontent.com/assets/12113780/26134351/92c25722-3ae0-11e7-8429-23c8e6a73847.png)

**Comment by S1ngS1ng** [comment]
我觉得这道题说的还是很清楚的，左边写了：
> 强调id为target4按钮里的文本

如何强调题目描述里有，你没加上。`id` 为 `target4` 的按钮里的文本也是 `#target4`，你漏写了个井号。

测试里的意思是：“确保你更换的按钮 (的 id) 为 `target4`”。显然，`target4` 不是在指内容，因为就没有内容为 `target4` 的按钮
