### ISSUE TITLE
account-creating failed

### ISSUE THREAD

**Issue by raman0716** [FreeCodeCampChina/freecodecamp.cn#29]
Challenge [Save your Code Revisions Forever with Git](https://freecodecamp.cn/challenges/save-your-code-revisions-forever-with-git) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
need a visa card , why

**Comment by zeallean** [comment]
Cloud9 的注册可能需要科学上网，而且还需要有支持VISA的信用卡。这些都是必要条件。如果注册不了，还想体验在线IDE的化。[HyperDev](https://hyperdev.com/)也是一个不错的选择。不过这些国外的在线工具受一部分ISP运营商网络限制使用体验都不会太好。你可以尝试下Coding.net的在线IDE，功能类似。其次，也可以搭建本地的开发环境。[VirtualBox](https://virtualboxes.org/) 和 [vagrant](http://vagrantup.com/) 是不错的组合。

**Comment by loveyoga** [comment]
Cloud9还必须要信用卡，这让学生党怎么破……
