### ISSUE TITLE
聚合接口禁止止跨域

### ISSUE THREAD

**Issue by LunaYJ** [FreeCodeCampChina/freecodecamp.cn#291]
Challenge [Show the Local Weather](https://freecodecamp.cn/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

推荐中的聚合天气接口 现在禁止跨域。。。无法完成课程，能否提供其他可用接口？

**Comment by S1ngS1ng** [comment]
https://openweathermap.org/api

试试这个

**Comment by MichealXie** [comment]
我也遇到了这个问题...折腾了我一天, 后来改用饥人谷免费提供的 API, 地址是:http://api.jirengu.com/
