### ISSUE TITLE
Record Collection关卡bug

### ISSUE THREAD

**Issue by laiyezi** [FreeCodeCampChina/freecodecamp.cn#292]
#### 浏览器信息
* 浏览器名称，版本号
chrome,版本 58.0.3029.81
* 操作系统
win7
#### 问题描述
* 问题是在什么时候，什么情况下遇到的
1.updata函数中我改变的是collectionCopy,最后return  collection;
可以通过Run test,
2.updata函数我改变的是collectionCopy,最后return collectionCopy;
也可以通过测试Run test。

这两个返回的collection都与通过测试要求的（我只复制了第一条要求）不符合：
update(5439, "artist", "ABBA") 之后, artist 应该为 "ABBA"； 

3. 这道题考察的是collectionCopy通过JSON.parse(JSON.stringify(collection))实现深度复制，改变一个不影响另一个。通过测试的要求应该写明是符合collection对象的各个属性。

* 简要说明如何重现

#### 你的代码
function update(id, prop, value) {
  if (value !== '' && prop !== 'tracks'){
    collectionCopy[id][prop] = value;
  } else if (value !== '' && prop === 'tracks') {
    collectionCopy[id][prop].push(value);
  } else if (value === '') {
    delete collectionCopy[id][prop];
  }

  return collection;
}

```
如果和代码相关，请在这里粘贴你的全部代码
```

**Comment by S1ngS1ng** [comment]
@laiyezi 没有问题的噢。reset 一下然后重新提交吧

**Comment by laiyezi** [comment]
我重置测试，这两种情况都可以通过测试。

**Comment by laiyezi** [comment]
@S1ngS1ng 我reset，这两种情况都通过测试了。

**Comment by S1ngS1ng** [comment]
@laiyezi 都能通过测试就行。是这样的，这道题的检测函数比较麻烦。使用的是全局变量去检测的

**Comment by laiyezi** [comment]
@S1ngS1ng update函数中修改collectionCopy,最后return的是 collection,不是应该通不过吗？我刚学不是很确定。Σ( ° △ °|||)︴

**Comment by S1ngS1ng** [comment]
@laiyezi 嗯，你说的没错。这里写成 `return collectionCopy` 显然是更好的，而且在**真正写代码的时候也应该这么写才对**。

所以上面才说，这道题的检测函数比较麻烦，设计的不是很科学。但这是受限于最初的运行环境。

如果你有兴趣，可以把源码 clone 下来，找到这道题，提交前在检测函数上打个断点，看看就明白了。详细说起来得讲好久- -！

**Comment by laiyezi** [comment]
@S1ngS1ng 明白了，谢谢。

**Comment by slowlearnerLspeedup** [comment]
看到这道题是时候我内心是懵逼的。百思不得其姐之后，我决定照着题目里的条件表述直接写函数，写完抱着侥幸心里脑子也没多想直接点了Run，然后马上跳出绿色通过提示！！！一下子我更懵逼了！
然后仔细看了绿色打勾的测试结果，对比结果去理解函数。
然后，仍然不理解这里
var collectionCopy = JSON.parse(JSON.stringify(collection));
超纲了？？？

**Comment by S1ngS1ng** [comment]
@Rodney2012 如果方便的话发一下你的代码。
`var collectionCopy = JSON.parse(JSON.stringify(collection));` 这行的作用是深拷贝。没超纲= =

**Comment by slowlearnerLspeedup** [comment]
@S1ngS1ng 
深拷贝之前的FCC课程好像没提到过，或者我忘了，所以看不太懂那段。
我通关的代码：
```
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// 深拷贝 collection，用于测试
var collectionCopy = JSON.parse(JSON.stringify(collection));

// 请只修改这条注释以下的代码
function update(id, prop, value) {
if(value !=="" && prop !="tracks"){
  collectionCopy[id][prop]=value;
} else if (value !=="" && prop == "tracks"){
  collectionCopy[id][prop].push(value);
} else if (value ===""){
  delete collectionCopy[id][prop];
}

  return collectionCopy;
}
```
// 你可以修改这一行来测试你的代码
update(5439, "artist", "ABBA");

**Comment by S1ngS1ng** [comment]
@Rodney2012 没问题啊。就是这样的

**Comment by zeromeme** [comment]
为什么不可以直接这么写：
// 请只修改这条注释以下的代码
function update(id, prop, value) {
collection[id][prop]=value;
  return collection;
}

// 你可以修改这一行来测试你的代码
它想表达的不就是这么个意思吗？
为什么过不去！！

**Comment by S1ngS1ng** [comment]
@zeromeme 请仔细读题。你这样写，处理不了删除属性和 `push` 到数组的情况啊

**Comment by RillHe** [comment]
这题通倒是通过了，但是左侧的浏览器所显示的内容没变化啊，例如：
代码修改后应显示：update(1245, "tracks", "Addicted to Love") 之后, tracks 的最后一个元素应该是 "Addicted to Love"
而浏览器显示的”tracks“依旧没有"Addicted to Love"
这是什么原因？
新手入学，请大神们多多指导。

**Comment by ayhwtian** [comment]
> 这题通倒是通过了，但是左侧的浏览器所显示的内容没变化啊，例如：
> 代码修改后应显示：update(1245, "tracks", "Addicted to Love") 之后, tracks 的最后一个元素应该是 "Addicted to Love"
> 而浏览器显示的”tracks“依旧没有"Addicted to Love"
> 这是什么原因？
> 新手入学，请大神们多多指导。

我也出现这个情况了 还在想怎么回事 这里也没有大神给回答

**Comment by ayhwtian** [comment]
> 这题通倒是通过了，但是左侧的浏览器所显示的内容没变化啊，例如：
> 代码修改后应显示：update(1245, "tracks", "Addicted to Love") 之后, tracks 的最后一个元素应该是 "Addicted to Love"
> 而浏览器显示的”tracks“依旧没有"Addicted to Love"
> 这是什么原因？
> 新手入学，请大神们多多指导。

好像理解是什么意思了，我在代码中修改collection 然受 返回collectionCopy 我发现collectionCopy的数值也变了，如果我在代码中修改collectionCopy，我发现代码没有变化，不知道是不是就是想让我们练习这个。
// 初始化变量
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// 深拷贝 collection，用于测试
var collectionCopy = JSON.parse(JSON.stringify(collection));

// 请只修改这条注释以下的代码
function update(id, prop, value) {
  if(value !=="" && prop!="tracks"){
     collection[id][prop]= value;
//collectionCopy[id][prop]= value;

  } else if(value !=="" && prop =="tracks"){
    collection[id][prop].push(value);
//collectionCopy[id][prop].push(value);

  } else if(value === ""){
    delete collection[id][prop];
 // delete collectionCopy[id][prop];
  }
  
return collectionCopy;
  //return collection;
}

// 你可以修改这一行来测试你的代码
update(5439, "artist", "ABBA");
