### ISSUE TITLE
写的能通过，但是有一个小疑问

### ISSUE THREAD

**Issue by yinxiaosi** [FreeCodeCampChina/freecodecamp.cn#295]
Challenge [Condense arrays with reduce](http://www.freecodecamp.cn/challenges/condense-arrays-with-reduce#?solution=var%20array%20%3D%20%5B4%2C5%2C6%2C7%2C8%5D%3B%0A%2F%2Fvar%20singleVal%20%3D%200%3B%0A%0A%2F%2F%20%E5%8F%AA%E8%83%BD%E5%9C%A8%E8%BF%99%E4%B8%80%E8%A1%8C%E4%B8%8B%E9%9D%A2%E5%86%99%E4%BB%A3%E7%A0%81%0A%0AsingleVal%20%3D%20array.reduce(function(aa%2Cbb)%7B%0A%20%20return%20aa%2Bbb%3B%0A%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3067.6 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var array = [4,5,6,7,8];
//var singleVal = 0;

// 只能在这一行下面写代码

singleVal = array.reduce(function(aa,bb){
  return aa+bb;
});

```

他案例的函数中那个0是做什么的呢。我不加也是可以通过的

**Comment by S1ngS1ng** [comment]
@yinxiaosi 下次这样的问题直接在 gitter 问就好了噢。不要在这儿开 issue 了。。
那个是 reduce 的初始值。详情：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

**Comment by yinxiaosi** [comment]
谢谢~~    好的我了解了呢




------------------ 原始邮件 ------------------
发件人: "Xing Liu";<notifications@github.com>;
发送时间: 2017年5月25日(星期四) 中午11:40
收件人: "FreeCodeCampChina/freecodecamp.cn"<freecodecamp.cn@noreply.github.com>; 
抄送: "Good尹"<648363458@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [FreeCodeCampChina/freecodecamp.cn] 写的能通过，但是有一个小疑问 (#295)




@yinxiaosi 下次这样的问题直接在 gitter 问就好了噢。不要在这儿开 issue 了。。
 那个是 reduce 的初始值。详情：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
