### ISSUE TITLE
在*里面默认设置了box-sizing:border-box;是否应该提前向用户说明？

### ISSUE THREAD

**Issue by crystalYY** [FreeCodeCampChina/freecodecamp.cn#30]
我是在做第23个任务时发现给img添加了边框，其width并没有改变。看了下控制台，发现使用了bootstrap，默认box-sizing:border-box;
我认为这样对于初学者会有误导，所以是否向用户提前说明（添加一个简单提示）会好一些？

**Comment by huluoyang** [comment]
HTML时代大家用的IE盒模型，经典的如table的width属性包含了填充。
CSS时代大家用的W3C盒模型，引入了margin\padding\border属性。
CSS3.0时代大家用的box-sizing盒模型，引入了全新属性：box-sizing:border-box；
W3C经典的盒模型实际上默认的属性为：box-sizing:content-box。
但这种方式不适合布局和改版，也不符合日常生活中人们的常识。
例如：我们买了一个泡沫箱子，宽度1米，高度1米。
人们通常认为此处的宽度和高度应该等于实际可用空间+泡沫+包装。
所以现在你能看到很多网站CSS都写着：*{box-sizing:border-box}，bootstrap也是如此。
这算不上误导，只是你应该抛弃掉自己陈旧的W3C盒模型知识了。
W3C本身也在不停更新迭代，但国内前端面试总是有人还在考：W3C经典盒模型和IE盒模型有什么不同？
没有任何意义，因为在连IE8都支持box-sizing:content-box的今天，我们应该果断扔掉历史包袱，轻松上阵。
