### ISSUE TITLE
不理解7.8.9的地方，为什么不写if外面的return count+" "+"Bet"; 会影响第4个结果的输出？

### ISSUE THREAD

**Issue by zhangwenhui123** [FreeCodeCampChina/freecodecamp.cn#300]
```
var count = 0;

function cc(card) {
  // Only change code below this line
  switch(card){
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      count++;
      if(count>0){
        return count+" "+"Bet";
      }
      break;
    case 10:
    case 'J':
    case 'Q':
    case 'K':
    case 'A':
      count--;
      if(count<0){
        return count+" "+"Hold";
      }
      break;
    
    case 7:
    case 8:
    case 9:
    if(count===0){
       return count+" "+"Hold";
     }
  }   

}
```
// Add/remove calls to test your function.
// 提示: Only the last will display
cc(7); 
![q 5__9ic fzx2b y _zi b2](https://cloud.githubusercontent.com/assets/26887930/26762071/0d6432de-496e-11e7-803f-dd0fa306d0cc.png)

**Comment by zhangwenhui123** [comment]
var count = 0;

function cc(card) {
  // Only change code below this line
  switch(card){
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      count++;
      if(count>0){
        return count+" "+"Bet";
      }
      break;
    case 10:
    case 'J':
    case 'Q':
    case 'K':
    case 'A':
      count--;
      if(count<0){
        return count+" "+"Hold";
      }
      break;
    
    case 7:
    case 8:
    case 9:
    if(count===0){
       return count+" "+"Hold";
     }
 return count+" "+"Bet";
  }   
  // Only change code above this line
}

// Add/remove calls to test your function.
// 提示: Only the last will display
cc(7); 
![ka7 y76cpvgic nbkysx](https://cloud.githubusercontent.com/assets/26887930/26762103/b43026b8-496e-11e7-871e-c81b56fd1031.png)
如果两个return交换也不对？

![89gyaifs uv8xt 4k_p 5](https://cloud.githubusercontent.com/assets/26887930/26762115/dfeca416-496e-11e7-9ebd-c475a2846fcc.png)
结果也是错的
![c1 03539n4242djd f8yl_j](https://cloud.githubusercontent.com/assets/26887930/26762119/ef457aaa-496e-11e7-89bf-518bf83d0bc0.png)
为什么必须是
    if(count===0){
       return count+" "+"Hold";
     }
 return count+" "+"Bet";
  }   
才对呢？

**Comment by Wesley1993** [comment]
"0"有特殊含义，一般代表“false”，当需要判断是否等于数字“0”时，需要用到强等于“===”，用“==”只会判断为true或者false

**Comment by S1ngS1ng** [comment]
@Wesley1993 感觉跟这个应该没关系。这里不是隐式类型转换的问题，而是逻辑的问题

**Comment by S1ngS1ng** [comment]
@zhangwenhui123 没太看懂你的描述。
首先，我没找到哪个 `if` 外面有 `return count+" "+"Bet";`。其次，从你的截图来看，影响的应该是第五个测试，或者是第五次 `cc` 调用。而不是第四个。

**下次发代码请在外面加上\`\`\`**。

可以点开你上面发的内容，右上角的铅笔图标，就能看到 \`\`\` 加在哪儿。

我修改了一下你的 issue，不知道加上之后缩进跟你原本的一样不一样，请你核对一下。

按照上面的代码来看，怀疑是 `if (count === 0)` 那里解析为 `case` 7、8 或 9 的时候执行的代码。
由于第五个测试用例，最后一次调用是 `cc(7)`，这时 `count` 也不为 0，因此没有输出。

解决方案可以是，在 `switch` 里面只处理 `count` 值的变化，在 `switch` 外面根据 `switch` 之后的 `count` 值来处理输出的字符串。

## 这不是 bug，下次这样的问题请在 gitter 提问。

**Comment by zhangwenhui123** [comment]
@S1ngS1ng Ok ,是我的逻辑问题，已经懂了谢谢:)
我以为这里是在这里提问题，原来是发现bug的地方，尴尬，谢谢解答
