### ISSUE TITLE
a标签

### ISSUE THREAD

**Issue by zguiyang** [FreeCodeCampChina/freecodecamp.cn#301]
为什么这样过不了
![image](https://cloud.githubusercontent.com/assets/24975063/26783110/10e4be68-4a29-11e7-90b4-13978dd9816e.png)

**Comment by zguiyang** [comment]
应该怎样写

**Comment by S1ngS1ng** [comment]
anchor text 和示例图中 the link's text 是一个意思。你的代码中没有。

### 1. 这样的问题下次不要开 issue 了。直接在 gitter 讨论组问就好
### 2. 如果你发现 bug 要开 issue，请按照 issue 模板填写。
### 3. 麻烦你至少给出文字版的代码和题目链接，而不是这样截个图
