### ISSUE TITLE
求教 (关于FCC验证是否要给JS结尾加分号）

### ISSUE THREAD

**Issue by cqj1221** [FreeCodeCampChina/freecodecamp.cn#302]
Challenge [Concatenating Strings with the Plus Equals Operator](http://www.freecodecamp.cn/challenges/concatenating-strings-with-the-plus-equals-operator#?solution=%2F%2F%20%E4%B8%BE%E4%BE%8B%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%3B%0AourStr%20%2B%3D%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%3B%0AmyStr%20%3D%20%22This%20is%20the%20first%20sentence.%20%22%0AmyStr%20%2B%3D%22This%20is%20the%20second%20sentence.%22%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// 举例
var ourStr = "I come first. ";
ourStr += "I come second.";

// Only change code below this line

var myStr;
myStr = "This is the first sentence. "
myStr +="This is the second sentence."

```
这样不对吗？哪里出现错误？？？

**Comment by S1ngS1ng** [comment]
@cqj1221 你只需要在每行结尾加上分号就能通过。因为 FCC 里面，执行测试的时候会把用户代码压缩成一行，所以没有分号就会出现报错。

需要说明的是，你这样的写法（不加分号）在其他环境中肯定是可以的，JS 的规范也没说过必须要给每行都加分号。不过一开始还是养成个好习惯吧，加上分号。熟练了之后你就知道哪儿必须加，哪儿可以不加了

**Comment by wudifeixue** [comment]
这个我们要是去改的话，要触动很多基层的地方吧，感觉会造成很多未知的验证bug..

**Comment by S1ngS1ng** [comment]
@wudifeixue 这部分先不 touch 了。如果上游改了咱们就跟着改吧。我担心把其他测试改出问题 😐
