### ISSUE TITLE
传参不一样，但结果总是输出25.

### ISSUE THREAD

**Issue by wjiaoStudy** [FreeCodeCampChina/freecodecamp.cn#303]
#### 浏览器信息
* 浏览器名称：谷歌，版本号48.0
* 操作系统 win7

#### 问题描述
* 传入不同参数总是输出25.
* 简要说明如何重现

#### 你的代码

function timesFive(times){
  
  return times*=5;
}

//timesFive(5);
//timesFive(2);
var answer=timesFive(2);

输出结果：

timesfive(5)===25

**Comment by S1ngS1ng** [comment]
@wjiaoStudy 
`var answer=timesFive(2);` 这一行是不会输出的。
左边这个 `timesfive(5)===25` 是系统用来测试的

你只需要定义一个 `function timesFive` 就够了。现在这样写应该能通过的吧？

**Comment by wjiaoStudy** [comment]
能通是能通，但是每次传入参数不一样时，都是输出25.

**Comment by S1ngS1ng** [comment]
@wjiaoStudy 嗯，因为你这里只有一个赋值语句，没有输出语句。
你试一下，其他不变，最后一行加上 `console.log(answer)`，然后打开浏览器控制台就能看到输出了。
上面说了，这里的输出 25 是平台的测试语句。

**Comment by wjiaoStudy** [comment]
console.log(answer)我加了这个也还是没变哦。

**Comment by S1ngS1ng** [comment]
@wjiaoStudy 麻烦你再仔细看一下上面说的，应该去哪儿看输出。另外，已经解释了两边为什么那里一直是不变的

**Comment by wjiaoStudy** [comment]
嗯  恩 ，好。不好意思哦，麻烦你了。
