### ISSUE TITLE
te

### ISSUE THREAD

**Issue by swrdlgc** [FreeCodeCampChina/freecodecamp.cn#31]
Challenge [Mutations](https://freecodecamp.cn/challenges/mutations#?solution=function%20mutation%28arr%29%20%7B%0A%20%20flag%20%3D%20%5B%5D%3B%0A%20%20for%28i%20%3D%200%3B%20i%20%3C%20arr%5B0%5D.length%3B%20%2B%2Bi%29%20%7B%0A%20%20%20%20flag%5Barr%5B0%5D%5Bi%5D%5D%20%3D%201%3B%0A%20%20%7D%0A%20%20%0A%20%20for%28i%20%3D%200%3B%20i%20%3C%20arr%5B1%5D.length%3B%20%2B%2Bi%29%20%7B%20%20%20%20%0A%20%20%20%20c%20%3D%20arr%5B1%5D%5Bi%5D%3B%0A%20%20%20%20if%28flag%5Bc%5D%20!%3D%201%20%26%26%20flag%5Bc.toUpperCase%28%29%5D%20!%3D%201%20%26%26%20flag%5Bc.toLowerCase%28%29%5D%20!%3D%201%29%20%7B%0A%20%20%20%20%20%20return%20%22false%22%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%20%20%0A%20%20return%20%22true%22%3B%0A%7D%0A%0Amutation%28%5B%22hello%22%2C%20%22hey%22%5D%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function mutation(arr) {
  flag = [];
  for(i = 0; i < arr[0].length; ++i) {
    flag[arr[0][i]] = 1;
  }

  for(i = 0; i < arr[1].length; ++i) {    
    c = arr[1][i];
    if(flag[c] != 1 && flag[c.toUpperCase()] != 1 && flag[c.toLowerCase()] != 1) {
      return "false";
    }
  }

  return "true";
}

mutation(["hello", "hey"]);

```

**Comment by swrdlgc** [comment]
solved, boolean true & false

**Comment by kinksteven** [comment]
function mutation(arr) {
  // 先全变为小写字母
  var a = arr.join(" ").toLowerCase().split(" ");
 //遍历，创建一个RegExp对象，在第一个元素中查找是否有第二个元素的值。
  for(var i=0;i<a[1].length;i++){                  
    var patt1 = new RegExp(a[1][i]);
 //一旦找不到直接跳出，返回false。
    if(patt1.test(a[0])===false){
      return false;
    }
  }
 //全部查了一遍，符合，返回true。
  return true;
}

mutation(["hello", "hey"]);

因为这里数组中只有两个两个元素，所以这么写。
也能通过。
有什么不对的地方，希望大家多指正，谢谢。

第二种解法

function mutation(arr) {
  // 请把你的代码写在这里
  var  a =arr.join(" ").toLowerCase().split(" ");
  for(var i=0;i<a[1].length;i++){
     var b = a[0].indexOf(a[1][i]);
    if(b===-1){
       return false;
    }
  }
  return true;
}

mutation(["hello", "hey"]);

**Comment by kinksteven** [comment]
``function mutation(arr) {
  // 请把你的代码写在这里
  var  a =arr.join(" ").toLowerCase().split(" ");
  for(var i=0;i<a[1].length;i++){
     var b = a[0].indexOf(a[1][i]);
    if(b===-1){
       return false;
    }
  }
  return true;
}

mutation(["hello", "hey"]);``

**Comment by threegeese** [comment]
var str1=arr[0].toLowerCase();
  var str2=arr[1].toLowerCase().split('');
  for(var i=0;i<str2.length;i++){
   if(str1.indexOf(str2[i])==-1){
     return false;
   }else{
     return true;
   }
为什么不行？

**Comment by S1ngS1ng** [comment]
@threegeese 因为你这个只会判断 `str1.indexOf(str2[0]) == -1`，然后就直接 `return` 了。
对于 `false` 的情况，只要这个判断成立，就可以不用继续遍历，直接返回。但 `true` 不同。要遍历完才能得出 `true` 的结论。因此，`return true` 放到循环外面就可以了。
参考 Profile Lookup 那道题

**Comment by promotion-xu** [comment]
function mutation(arr) {
  // 请把你的代码写在这里
  
  var str = arr[0];    // "hello"
  var arr2 = arr[1].split("");   // ["h", "e", "y"];  
  for(var i = 0; i < arr2.length; i++) {
    if( (str.indexOf(arr2[i].toLowerCase()) == -1) && (str.indexOf(arr2[i].toUpperCase()) == -1) ) {
    // 判断条件, 把函数的第二个参数变成大写或者小写, 都要满足在str中找不到, 就直接返回false
      return false;
    }
  }
  return true;
  
}
mutation("hello", "hey");
判断条件写的有点复杂, 仅当参考

**Comment by ayhwtian** [comment]
function mutation(arr) {
  // 请把你的代码写在这里

  var a = arr[0].toLowerCase();
  var b = arr[1].toLowerCase();
  for(var i=0;i<b.length;i++){
    if(a.indexOf(b[i])===-1){
      return false;
    } 
  }
  return true;
}

mutation(["hello", "hey"]);
