### ISSUE TITLE
#312 Build a JavaScript Calculator 提供的代码不准确

### ISSUE THREAD

**Issue by mayfulq** [FreeCodeCampChina/freecodecamp.cn#313]
#312 Build a JavaScript Calculator 提供的解决代码 https://codepen.io/freeCodeCamp/pen/zrRzMR 存在bug，计算不准确。如 计算 5.2-2%*2，计算无结果；计算 2.5*5+2%+2，计算结果12.5（应该为14.75），望抽空修改，以方便后人学习

**Comment by S1ngS1ng** [comment]
@mayfulq 确认下，`5.2 - 2%2` 这个结果应该是什么？不是很理解这种写法。。
另外，`2.55+2%+2` 我得到的既不是 12.5 也不是 14.75
![image](https://user-images.githubusercontent.com/13592559/27518849-d73ff2ca-59b6-11e7-89b8-e97df6d87465.png)
而是 2.55
![image](https://user-images.githubusercontent.com/13592559/27518850-d916d8a2-59b6-11e7-9443-b9937ac66eb9.png)

**Comment by mayfulq** [comment]
@S1ngS1ng  
sorry, 我测试的计算式上述表述有误，**但总体来说，是对%计算有些异议**；
如计算 `2.5*5+2%+2`，计算结果`12.5`（计算式 `2.5*5+2%+2` 是否应该等价于`2.5*5+0.02+2`，所以应该等于 ` 14.75` ？），计算式 `2.55+2%+2` ，是否也应等价于`2.55+0.02+2`，所以等于`4.57？`
计算式` 5.2 - 2%2`，做补全后为`5.2-2%*2`，下图为华为手机自带计算器计算结果，应该也是将计算式转化为`5.2-0.02*2`，然后再进行计算？
![image](https://user-images.githubusercontent.com/23610328/27723488-e6009868-5d9f-11e7-942e-26bd93733654.png)

**Comment by S1ngS1ng** [comment]
@mayfulq 我觉得，`2.5 * 5 + 2 % + 2` 应该等价于 `(2.5 * 5) * (1 + 2%) + 2`。类似的，`5.2 - 2 % 2` 会补全成 `5.2 - 2 % * 2`，因此相当于 `5.2 * (1 - 2 %) * 2`。我在 Google 页面上的 Calculator 试了，是这个结论。
不过标准的计算器，其实处理百分号，应该也是这样的吧？

参考一下这两个链接：https://blogs.msdn.microsoft.com/oldnewthing/20080110-00/?p=23853
http://www.wikihow.com/Do-Percentages-on-a-Calculator

比如，`200 + 5%` 的执行顺序和输出应该是：
<kbd>2</kbd><kbd>0</kbd><kbd>0</kbd>  => 显示 200
<kbd>+</kbd> => 显示 200
<kbd>5</kbd> => 显示 5
<kbd>%</kbd> => 显示 10。这里是 `200 * 5%` 的计算结果
<kbd>=</kbd> => 显示 210。即 `200 * (1 + 5%)`

**Comment by wudifeixue** [comment]
看freeCodeCamp.com是用的一个新的计算器链接，不然我们换成这个？
https://codepen.io/freeCodeCamp/full/rLJZrA

**Comment by S1ngS1ng** [comment]
@wudifeixue 不过这个没有百分号之类的功能。换成这个我觉得 OK。过一阵儿我再优化吧

**Comment by mayfulq** [comment]
@S1ngS1ng ，
感谢回复，这下对计算器的%有了新认识，学习了，手动比心\(^o^)/~
