### ISSUE TITLE
这是什么BUG

### ISSUE THREAD

**Issue by 0w0k** [FreeCodeCampChina/freecodecamp.cn#32]
Challenge [Sum All Odd Fibonacci Numbers](https://freecodecamp.cn/challenges/sum-all-odd-fibonacci-numbers#?solution=var%20arr%3D%5B1%2C1%5D%2Cresult%20%3D%200%3B%0Afunction%20fibs%28last%2Cnext%29%20%7B%0A%20%20%20%20if%28next%3C10000000%29%7B%0A%20%20%20%20%20%20var%20num%20%3D%20last%2Bnext%3B%0A%20%20%20%20%20%20arr.push%28num%29%3B%0A%20%20%20%20%20%20fibs%28next%2Cnum%29%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20arr%3B%0A%7D%0Afunction%20sumFibs%28num%29%7B%0A%20%20%20%20var%20arr2%20%3D%20fibs%281%2C1%29%3B%0A%20%20%20%20console.log%28arr2%29%3B%0A%20%20%20%20for%28%20var%20i%3D0%3B%20i%3Carr2.length%3B%20i%2B%2B%29%7B%0A%20%20%20%20%20%20%20%20if%28arr%5Bi%5D%252%3D%3D1%20%26%26%20arr2%5Bi%5D%3C%3Dnum%29%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20result%2B%3Darr2%5Bi%5D%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20return%20result%3B%0A%7D%0AsumFibs%2875025%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
var arr=[1,1],result = 0;
function fibs(last,next) {
    if(next<10000000){
      var num = last+next;
      arr.push(num);
      fibs(next,num);
    }
    return arr;
}
function sumFibs(num){
    var arr2 = fibs(1,1);
    console.log(arr2);
    for( var i=0; i<arr2.length; i++){
        if(arr[i]%2==1 && arr2[i]<=num){
            result+=arr2[i];
        }
    }
    return result;
}
sumFibs(75025);

```

**Comment by discountry** [comment]
You should have only one function to pass the challenge:

``` js
function sumFibs(num){
  var arr=[1,1],result = 0;
function fibs(last,next) {
    if(next<10000000){
      var num = last+next;
      arr.push(num);
      fibs(next,num);
    }
    return arr;
}
    var arr2 = fibs(1,1);
    console.log(arr2);
    for( var i=0; i<arr2.length; i++){
        if(arr[i]%2==1 && arr2[i]<=num){
            result+=arr2[i];
        }
    }
    return result;
}

sumFibs(75024);

```
