### ISSUE TITLE
这个怎么解？

### ISSUE THREAD

**Issue by YangPengFe1** [FreeCodeCampChina/freecodecamp.cn#322]
Challenge [Understanding Case Sensitivity in Variables](http://www.freecodecamp.cn/challenges/understanding-case-sensitivity-in-variables#?solution=%2F%2F%20%E5%88%9D%E5%A7%8B%E5%8C%96%E5%8F%98%E9%87%8F%0Avar%20StUdLyCapVaR%3B%0Avar%20properCamelCase%3B%0Avar%20TitleCaseOver%3B%0A%0A%2F%2F%20%E7%BB%99%E5%8F%98%E9%87%8F%E8%B5%8B%E5%80%BC%0ASTUDLYCAPVAR%20%3D%2010%3B%0APRoperCAmelCAse%20%3D%20%22A%20String%22%3B%0AtITLEcASEoVER%20%3D%209000%3B%0A%0Avar%20studlyCapVar%20%3D%2010%3B%0Avar%20properCamelCase%20%3D%20'A%20String'%3B%0Avar%20titleCaseOver%20%20%3D%209000%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// 初始化变量
var StUdLyCapVaR;
var properCamelCase;
var TitleCaseOver;

// 给变量赋值
STUDLYCAPVAR = 10;
PRoperCAmelCAse = "A String";
tITLEcASEoVER = 9000;

var studlyCapVar = 10;
var properCamelCase = 'A String';
var titleCaseOver  = 9000;
```

**Comment by S1ngS1ng** [comment]
请仔细读题。你的代码中，赋值那里的变量都不存在，如何赋值？
前三行是定义变量，后面是赋值。你不应该再后面再加三行

## 另外这不是 bug。以后这样的问题请到 gitter 提问。不要在这儿开 issue 问问题

**Comment by ufo1174** [comment]
所以答案是什么
