### ISSUE TITLE
怎么添加新专辑

### ISSUE THREAD

**Issue by mzlz** [FreeCodeCampChina/freecodecamp.cn#327]
Challenge [Introducing JavaScript Object Notation JSON](https://freecodecamp.cn/challenges/introducing-javascript-object-notation-json#?solution=var%20myMusic%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Billy%20Joel%22%2C%0A%20%20%20%20%22title%22%3A%20%22Piano%20Man%22%2C%0A%20%20%20%20%22release_year%22%3A%201973%2C%0A%20%20%20%20%22formats%22%3A%20%5B%20%0A%20%20%20%20%20%20%22CS%22%2C%20%0A%20%20%20%20%20%20%228T%22%2C%20%0A%20%20%20%20%20%20%22LP%22%20%5D%2C%0A%20%20%20%20%22gold%22%3A%20true%0A%20%20%7D%0A%20%20myMusic.bark%3D%0A%20%20%20%20%0A%20%20%2F%2F%20%E8%AF%B7%E5%9C%A8%E8%BF%99%E9%87%8C%E6%B7%BB%E5%8A%A0%E4%B8%93%E8%BE%91%0A%5D%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  }
  myMusic.bark=
    
  // 请在这里添加专辑
];


```

**Comment by wudifeixue** [comment]
在后面再写一个JSON就行了。
例如
```JSON
{
    "artist": "Takeshi Nakamura",
    "title": "White Album 2",
    "release_year": 2010,
    "formats": [
      "WA",
      "WA2",
      "stomache"
    ]
  }
```

**Comment by S1ngS1ng** [comment]
@mzlz 麻烦你仔细看看开 issue 的说明。这样的问题以后请到 gitter 提问，不要在这里开 issue。

## 注意：Issue 是用来处理代码库中的 bug，不是用来提问题的

**Comment by naivetothink** [comment]
复制大括号内的内容粘贴到大括号后面，并在上一个大括号的结束加个逗号，

**Comment by FEILELAI** [comment]
> 复制大括号内的内容粘贴到大括号后面，并在上一个大括号的结束加个逗号，

现在过不去了。

**Comment by FEILELAI** [comment]
var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  },
  // 请在这里添加专辑
  {
    "artist": "Takeshi Nakamura",
    "title": "White Album 2",
    "release_year": 2010,
    "formats": [
      "WA",
      "WA2",
      "stomache"
    ]
  }
];
需要在第一个大括号后加一个逗号“ ，”
有些题目的例题反而误导。
