### ISSUE TITLE
我在社区用gitter聊天时 发现多了好多两人的私聊房间，而且只能hide不能删除，想知道怎么删除私聊的房间

### ISSUE THREAD

**Issue by ghost** [FreeCodeCampChina/freecodecamp.cn#33]
#### FreeCodeCamp Issue template

To Use this Template:
- Fill out what you can
- Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/chinese
#### Issue Description
- When Issue Happens
- Steps To Reproduce
#### Browser Information
- Browser Name, Version
- Operating System
#### Your Code

``` js
If relevant, paste all of your challenge code in here
```

**Comment by discountry** [comment]
Gitter没有提供这个功能

**Comment by huluoyang** [comment]
重复问题不再复述
