### ISSUE TITLE
i can't find where is wrong

### ISSUE THREAD

**Issue by dafuby** [FreeCodeCampChina/freecodecamp.cn#332]
Challenge [Use Conditional Logic with If Statements](https://freecodecamp.cn/challenges/use-conditional-logic-with-if-statements#?solution=%2F%2F%20%E4%B8%BE%E4%BE%8B%0Afunction%20ourFunction(isItTrue)%20%7B%0A%20%20if%20(isItTrue)%20%7B%20%0A%20%20%20%20return%20%22Yes%2C%20it's%20true%22%3B%0A%20%20%7D%0A%20%20return%20%22No%2C%20it's%20false%22%3B%0A%7D%0A%0A%2F%2F%20%E5%AE%9A%E4%B9%89%20myFunction%0Afunction%20myFunction(wasThatTrue)%20%7B%0A%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8B%0A%20%20if%20(wasThatTrue)%20%7B%0A%20%20%20%20return%20%22That%20was%20true%22%3B%0A%20%20%7D%0A%20%20return%20%22That%20was%20false%22%3B%0A%20%20%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8A%0A%0A%7D%0A%0A%2F%2F%20%E4%BD%A0%E5%8F%AF%E4%BB%A5%E4%BF%AE%E6%94%B9%E8%BF%99%E4%B8%80%E8%A1%8C%E6%9D%A5%E6%B5%8B%E8%AF%95%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%0AmyFunction(true)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// 举例
function ourFunction(isItTrue) {
  if (isItTrue) { 
    return "Yes, it's true";
  }
  return "No, it's false";
}

// 定义 myFunction
function myFunction(wasThatTrue) {

  // 请把你的代码写在这条注释以下
  if (wasThatTrue) {
    return "That was true";
  }
  return "That was false";
  
  // 请把你的代码写在这条注释以上

}

// 你可以修改这一行来测试你的代码
myFunction(true);

```

**Comment by S1ngS1ng** [comment]
@dafuby It looks fine to me. Refresh the page and try again. Or try reset it.

**Comment by wudifeixue** [comment]
Closed for now since no reply and no issue can be reproduced.
