### ISSUE TITLE
I'm bad girl

### ISSUE THREAD

**Issue by georgiawang5332** [FreeCodeCampChina/freecodecamp.cn#333]
#### FreeCodeCamp.cn Issue 模板
如何使用本模板:
* 尽可能多填些相关信息，方便管理员参考
* 对于无法给出的内容，请删除掉那一行

# 以上内容请在提交 Issue 之前删除

#### 浏览器信息
* 浏览器名称，版本号
* 操作系统

#### 问题描述
* 问题是在什么时候，什么情况下遇到的
* 简要说明如何重现

#### 你的代码

```
如果和代码相关，请在这里粘贴你的全部代码
```

**Comment by S1ngS1ng** [comment]
@georgiawang5332 
需要报 bug 就写清楚。这种无意义的 issue 以后请不要开，一点儿也不好玩儿。下次再开这样的直接 block

**Comment by georgiawang5332** [comment]
抱歉我好像測試到錯的地方現在才發現問題~抱歉先忽略我的訊息吧! (( 我那時候初學不太會用，也謝謝您提醒! 我也不會再用了，鞠躬))
