### ISSUE TITLE
使用array对象的splice方法无法得到正确结果

### ISSUE THREAD

**Issue by 123456zzz** [FreeCodeCampChina/freecodecamp.cn#337]
#### 浏览器信息
* 浏览器名称，版本号
firefox 54.0.1

* 操作系统
win10家庭版

#### 问题描述
* 问题是在什么时候，什么情况下遇到的
* 简要说明如何重现
在做前端高级算法No repeats please时，由于得不到排列组合的结果，逐步分析后，
用 return [0,1].splice(0,1)后发现得到的结果为 [0],正确的结果应该是[1]。

#### 你的代码
```js
function permAlone(str) {
  //重复检测
  function isDouble(str) {
    for(var i=1;i<str.length;i++) {
      if(str[i]==str[i-1])
        return true;
    }
    return false;
  }

  //得到排列
  function arrangement(arr1){
    var len=arr1.length;
    if(len==0){
      return [];
    } else if(len==1) {
      return arr1;
    } else if(len==2) {
      return [arr1[0]+arr1[1],arr1[1]+arr1[0]];
    } else {
      var arr2=[];
      for(var j=0;j<len;j++) {
        var arr3=arr1.splice(j,1);
        var arr4=arrangement(arr3);
        for(var k=0;k<arr4.length;k++) {
          arr2.push(arr1[j]+arr4[k]);
        }
      }
      return arr2;
    }
  }
  
  var arr=arrangement(str.split(''));
  var count=0;
  var newArr=arr.filter(function(value){if(isDouble(value)==0) return value;});
  return arr;
} 
permAlone('ab');
```

#### 截图（如果有）
![default](https://user-images.githubusercontent.com/26499018/28299809-d8970d9e-6bad-11e7-954d-c17420696081.png)

**Comment by S1ngS1ng** [comment]
多半是你的代码问题。我传入 `str` 为 `"abcde"` 调试了下，返回值是 ` ["ba", "dc", "undefinede"]`。这个结果中，前两个元素长度为 2，而传入的字符串长度是 5，显然是不对的。

`[0,1].splice(0,1)` 的返回值是 `[0]` 就对了。注意，`push`，`pop`，`shift`，`unshift` 和 `splice` 都不返回操作后的数组。如果不明白，请参考 [文档](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice)

这道题目本身没有问题，这里只负责处理 bug。你还是先看下文档，调试一下你的代码吧。。有问题来 gitter 问
