### ISSUE TITLE
检查对象是否有某属性为什么要用hasOwnProperty

### ISSUE THREAD

**Issue by pyhui** [FreeCodeCampChina/freecodecamp.cn#34]
Challenge [Testing Objects for Properties](https://freecodecamp.cn/challenges/testing-objects-for-properties) 

My code:

``` javascript
// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  if(myObj.hasOwnProperty(checkProp))
  {
    return myObj[checkProp];} 
  else
    {
      return "Not Found";
    }

}

// Test your code by modifying these values
checkObj("gift");

```

//////
该程序中 if(myObj.hasOwnProperty(checkProp))可以直接写成 if(myObj[checkProp])
所以检查对象是否有某属性为什么还要用hasOwnProperty呢？

**Comment by jamesbeme** [comment]
Stop...STOP... STOP...WRITING ME... STOP...STOP...STOP...WRITING ME...STOP..
STOP...STOP...WRITING!!!!!!!

**Comment by discountry** [comment]
当`myObj[checkProp]`为0或者空时，你就没法用这种方式判断了

**Comment by huluoyang** [comment]
@pyhui  尽管在这题用myObj[checkProp]也能通过测试。
但代码并不严谨，所以还是推荐：myObj.hasOwnProperty(checkProp)
