### ISSUE TITLE
为什么这么写能完成提出的条件，但却过不了关？？

### ISSUE THREAD

**Issue by wifiway725** [FreeCodeCampChina/freecodecamp.cn#340]
Challenge [Factorialize a Number](http://www.freecodecamp.cn/challenges/factorialize-a-number#?solution=%20var%20result%20%3D%201%3B%0A%0Afunction%20factorialize(num)%20%7B%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E9%87%8C%0A%20%20if%20(num%20%3D%3D%3D%201)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20return%20num%3B%0A%20%20%20%20%7D%0A%20%20else%20%7B%0A%20%20%20%20for%20(var%20i%20%3D%201%3B%20i%20%3C%3D%20num%20%3B%20i%20%2B%2B)%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20result%20*%3D%20i%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20return%20result%3B%0A%20%20%7D%0A%20%20%0A%7D%0A%0Afactorialize(20)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36 BIDUBrowser/8.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
 var result = 1;

function factorialize(num) {
  // 请把你的代码写在这里
  if (num === 1)
    {
      return num;
    }
  else {
    for (var i = 1; i <= num ; i ++)
      {
        result *= i;
      }
    return result;
  }
  
}

factorialize(20);

```

**Comment by wifiway725** [comment]
求大神慷慨解答，先谢谢了

**Comment by S1ngS1ng** [comment]
@wifiway725 这么写不能通过？
逻辑上来说这段代码没问题啊..问题是什么？

**Comment by wudifeixue** [comment]
这个还是老问题，把var result = 1写在function里面就能通过了。
算是freeCodeCamp检测机制的缺陷了吧。全局定义的东西一般都没办法。
所以注释也会经常要求代码写在这下面或者上面。

**Comment by samsara007** [comment]
function factorial(n){
  if (n==1){
    return 1;
  }
return n*factorial(n-1);
}
用这个方式代码算是比较简单的了吧
