### ISSUE TITLE
结合两个if语句为一个语句，如果val不在10和20之间(包括10和20)，返回 "Outside"。反之，返回 "Inside"。

### ISSUE THREAD

**Issue by yyynnx** [FreeCodeCampChina/freecodecamp.cn#343]
Challenge [Comparisons with the Logical Or Operator](https://freecodecamp.cn/challenges/comparisons-with-the-logical-or-operator#?solution=function%20myTest(val)%20%7B%0A%20%20%2F%2F%20%E8%AF%B7%E5%8F%AA%E4%BF%AE%E6%94%B9%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8B%E7%9A%84%E4%BB%A3%E7%A0%81%0A%0A%20%20if%20(val%3C10%7C%7Cval%3E20)%20%7B%0A%20%20%20%20return%20%22Outside%22%3B%0A%20%20%7D%0A%0A%0A%20%20%2F%2F%20%E8%AF%B7%E5%8F%AA%E4%BF%AE%E6%94%B9%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8A%E7%9A%84%E4%BB%A3%E7%A0%81%0A%20%20return%20%22Inside%22%3B%0A%7D%0A%0A%2F%2F%20%E4%BD%A0%E5%8F%AF%E4%BB%A5%E4%BF%AE%E6%94%B9%E8%BF%99%E4%B8%80%E8%A1%8C%E6%9D%A5%E6%B5%8B%E8%AF%95%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%0AmyTest(10)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.2162.400 QQBrowser/9.5.10218.400</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(val) {
  // 请只修改这条注释以下的代码

  if (val<10||val>20) {
    return "Outside";
  }


  // 请只修改这条注释以上的代码
  return "Inside";
}

// 你可以修改这一行来测试你的代码
myTest(10);

```
居然这样才是对的？

**Comment by S1ngS1ng** [comment]
@yyynnx 这样应该是没问题的啊。。所以问题是什么？你的代码是怎样的？

**Comment by wudifeixue** [comment]
![image](https://user-images.githubusercontent.com/7316929/28764028-9d2582b4-757f-11e7-9c8c-c5bd5214aed2.png)
这么看你明白么？所以 val < 10 或者 val > 20 才是Outside
