### ISSUE TITLE
点击run以后浏览器崩溃

### ISSUE THREAD

**Issue by slowlearnerLspeedup** [FreeCodeCampChina/freecodecamp.cn#344]
Challenge [Reverse a String](https://www.freecodecamp.cn/challenges/reverse-a-string) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

在chrome59中点击运行以下代码遭遇浏览器假死崩溃，随后再载入该页面一直导致浏览器崩溃：
My code:
```javascript
function reverseString(str) {
  var stt=str.split(" ");
var stb=stt.reverse();
var std=stb.join(" ")；
reverseString(std);
  return std;
}

reverseString("hello");

```
最后在IE中更改代码为
  var stt=str.split("");
var stb=stt.reverse();
var std=stb.join("");
 return std;
过关。
但崩溃的chrome59还在一直崩溃ing

**Comment by S1ngS1ng** [comment]
@Rodney2012 麻烦发一下崩溃的浏览器具体版本、操作系统，以及导致崩溃的代码（就是上面这段么？
谢谢

**Comment by slowlearnerLspeedup** [comment]
浏览器是chrome59最后一个版本，崩溃后更新到60了，不记得具体版本号了。
操作系统：win10创意者更新
崩溃代码上面写了

**Comment by wudifeixue** [comment]
首先注意你的代码在join后面的分号，你用的中文输入法输入的 ；  
错误的符号自然会导致问题。  
其次你split和join后面不应该有空格，毕竟你要无间隙拆开string成array。
最后你只需要return std就可以了，不应该在function里面再运行一次reverseString(std);  

最后你这个改进成能用的代码就是：

```JS
function reverseString(str) {
  var stt=str.split("");
  var stb=stt.reverse();
  var std=stb.join("");
  return std;
}
reverseString("hello");
```

然后我简化了下这题的写法这样算是最优吧：
```JS
function reverseString(str) {
  return str.split("").reverse().join("");
}
```

**Comment by S1ngS1ng** [comment]
@Rodney2012 你先修改一下代码。如果还有问题再 repoen 吧。
