### ISSUE TITLE
“Specify How Fonts Should Degrade” 一节中“注释link标签仍无法使字体降级”的问题

### ISSUE THREAD

**Issue by ghost** [FreeCodeCampChina/freecodecamp.cn#345]
#### 题目
* [Specify How Fonts Should Degrade(中文)](https://www.freecodecamp.cn/challenges/specify-how-fonts-should-degrade)
#### 浏览器信息
* 浏览器名称，版本号 
Google Chrome  59.0.3071.115 64位
* 操作系统 
Windows 10 家庭版 64位

#### 问题描述
* 问题是在什么时候，什么情况下遇到的
2017.07.30 按照本节题目步骤执行时遇到的
* 简要说明如何重现
先是重置了代码，重新编辑，发现字体没有按题目说明中发生降级，然后强制清空了浏览器缓存，字体仍未改变，但是run test却可以通过

#### 你的代码

```HTML
<!-- <link href="https://fonts.gdgdocs.org/css?family=Lobster" rel="stylesheet" type="text/css"> -->

<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">在大家心目中，猫是慵懒的可爱的化身，它可以睡饱了再起来吃饭，可以逗趣小耗子，可以卖得了萌，使得了坏，这样百变的小怪兽就集结在一只宠物上，怎能不惹人怜爱。</p>
<p class="red-text">养动物有的时候，就是介于爱与恨之间，当你钦羡别人萌宠这么可爱的时候，你一定没有想过，狗狗和猫猫会到处拉屎，甚至会屯老鼠，啃鞋子，用爪子爬门，你不理它，它就挠你，你要对它发脾气，它会比你更来劲。所以，狗猫慎入，没有一定的准备，切勿随便去侍养动物。它们一旦认定你了，你就是它们的主人，如果你抛弃它们，它们必定心中重创。</p>
```

#### 截图（如果有）
![image](https://user-images.githubusercontent.com/18158191/28752068-90d624a4-7549-11e7-8888-bd224c08ee59.png)

**Comment by wudifeixue** [comment]
这个我试了好几遍，实在是没办法重现，不如你试试incognito(隐私)模式？

**Comment by wudifeixue** [comment]
如果楼主有办法重现就再打开吧。
