### ISSUE TITLE
 JSON APIs and Ajax部分没有翻译

### ISSUE THREAD

**Issue by lwk0228** [FreeCodeCampChina/freecodecamp.cn#348]
267题这部分错误提示没有翻译

**Comment by S1ngS1ng** [comment]
@lwk0228 请在 https://github.com/FreeCodeCampChina/freecodecamp.cn/issues/346 里添加评论就可以，或者修改 issue 描述。同一个问题就不要新开 issue 了，方便我们管理。谢谢
