### ISSUE TITLE
为什么无法通过？

### ISSUE THREAD

**Issue by kinksteven** [FreeCodeCampChina/freecodecamp.cn#349]
function rot13(str) { // LBH QVQ VG!
  // 请把你的代码写在这里
    for(var i=0;i<str.length;i++){
      var patt1=/[A-Z]/;
      var patt2=/str[i]/;
      if(patt2.test(patt1)===true){
        str[i]=str.fromCharCode(str.charCodeAt(i)+13);
      }      
    }
  return str;
}

rot13("SERR PBQR PNZC");  // 你可以修改这一行来测试你的代码

**Comment by S1ngS1ng** [comment]
@kinksteven `正则.test(正则)` 肯定不对。`test` 方法中传入的应该是字符串。下次请不要开 issue 提问
