### ISSUE TITLE
语法错误？

### ISSUE THREAD

**Issue by kinksteven** [FreeCodeCampChina/freecodecamp.cn#350]
![image](https://user-images.githubusercontent.com/28489229/28781219-e9eae280-763b-11e7-9617-548e14ad8ae3.png)

**Comment by liwenkang** [comment]
由于 fromCharCode 是 String 的静态方法，所以应该像这样使用：String.fromCharCode(), 注意你自己创建的string类型是不能使用这个方法的.
你可以考虑写成  str = String.fromCharCode();

可以参考一下[https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode](url)

**Comment by S1ngS1ng** [comment]
@kinksteven `fromCharCode` 不是这么用的。请参考文档。如果还不明白请发代码。另外这不是 issue。下次请移步 gitter 或 QQ 群提问

**Comment by kinksteven** [comment]
谢谢，是我自己没认真学，麻烦你了！！！
十分感谢。




另外我想问能用一个正则去检验另一个正则吗？
  for(var i=0;i<str.length;i++){
    var patt1=/[A-Z]/;
    var patt2=RegExp(str[i]);
    if(patt2.test(patt1)===true){。。。。。。}   类似这样。

patt2是动态的字符，我的目的是想检测这些字符是否在A-Z之间。


虽然我知道可以先转换成字符编码，用65-90来判断。但我想问上面这种方法是否可行。










------------------ 原始邮件 ------------------
发件人: "李文康";<notifications@github.com>;
发送时间: 2017年7月31日(星期一) 晚上11:03
收件人: "FreeCodeCampChina/freecodecamp.cn"<freecodecamp.cn@noreply.github.com>; 
抄送: "阿布"<1419986792@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [FreeCodeCampChina/freecodecamp.cn] 语法错误？ (#350)




由于 fromCharCode 是 String 的静态方法，所以应该像这样使用：String.fromCharCode(), 注意你自己创建的string类型是不能使用这个方法的.
 你可以考虑写成  str = String.fromCharCode();
 
可以参考一下https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode

**Comment by S1ngS1ng** [comment]
@kinksteven 当然不行。说了，正则是用来验证字符串的。。因此你可能需要 `patt1.test(str[i])`
