### ISSUE TITLE
Why  can't I pass this lesson

### ISSUE THREAD

**Issue by magiclalala** [FreeCodeCampChina/freecodecamp.cn#358]
Challenge [Escaping Literal Quotes in Strings](http://www.freecodecamp.cn/challenges/escaping-literal-quotes-in-strings#?solution=var%20myStr%20%3D%20%22I%20am%20a%20%5C%22%20double%20quoted%20%5C%22%20string%20inside%20%5C%22%20double%20quotes%20%5C%22%20%22%3B%20%2F%2F%20%E8%AF%B7%E4%BF%AE%E6%94%B9%E8%BF%99%E4%B8%80%E8%A1%8C%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.3226.400 QQBrowser/9.6.11682.400</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr = "I am a \" double quoted \" string inside \" double quotes \" "; // 请修改这一行



```

**Comment by HYJoe** [comment]
"I am a \"double quoted\" string inside \"double quotes\"";

**Comment by HYJoe** [comment]
可能是引号之间你多加了空格，我是小白，错了莫怪

**Comment by magiclalala** [comment]
确实是多加了空格，谢谢




------------------ 原始邮件 ------------------
发件人: "GQ";<notifications@github.com>;
发送时间: 2017年8月4日(星期五) 下午5:34
收件人: "FreeCodeCampChina/freecodecamp.cn"<freecodecamp.cn@noreply.github.com>; 
抄送: "lalala"<1142143250@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [FreeCodeCampChina/freecodecamp.cn] Why can't I pass this lesson(#358)




可能是引号之间你多加了空格，我是小白，错了莫怪
