### ISSUE TITLE
Chunky Monkey 问题

### ISSUE THREAD

**Issue by masterYiPan** [FreeCodeCampChina/freecodecamp.cn#359]
#### 浏览器信息
Chrome
win10

#### 问题描述
一直都遇到
用浏览器测试输出的结果和练习题的答案是一样的，但是练习题一直提示不对

#### 你的代码
```js
function chunk(arr, size) {
    var j=size;  
    var k=0;
    var arr1=[];
    for(var i=0;i<arr.length/size;i++){
        var arrs=[];
        for(k;k<j;k++){
            arrs.push(arr[k]) 
        }
        j=j+size
        arr1[i]=arrs;
    }
    return arr1;
}

chunk([0, 1, 2, 3, 4, 5], 4);
```

**Comment by S1ngS1ng** [comment]
@masterYiPan 这个不是 bug。你的代码基本实现了功能，但有些小问题。
对于 `chunk([0, 1, 2, 3, 4, 5], 4)`，输出是 `[[0, 1, 2, 3], [4, 5, undefined, undefined]]`，注意第二个子数组中会有两个 `undefined`。
执行到 `k` 为 `5` 时，此时 `j` 为 `8`。在 `arrs` 中存入 `5` 之后，继续遍历，`k` 为 `6` 和 `7` 的时候，`arr[k]` 就都是 `undefined` 了。
解决方式有很多种。可以考虑判断 `k` 是否超出 `arr.length`，或者换其他思路，比如 `splice` 或者 `slice`

**Comment by Sandaydi** [comment]
function chunk(arr, size) {
  // 请把你的代码写在这里
  var arr2 = [];
  var arr1 = arr;
  for(var i=arr.length; i>0; i--){
    if(arr.length>size){
      arr2.push(arr.slice(0,size));
      arr = arr1;
      arr = arr.slice(size-arr.length);
      arr1 = arr;
    }else{
      arr2.push(arr);
      break;
    }
  }
  return arr2;
}
chunk([0, 1, 2, 3, 4, 5, 6, 7, 8], 4);

**Comment by Sandaydi** [comment]
```
function chunk(arr, size) {
  // 请把你的代码写在这里
  var arr2 = [];
  var arr1 = arr;
  for(var i=arr.length; i>0; i--){
    if(arr.length>size){
      arr2.push(arr.slice(0,size));
      arr = arr1;
      arr = arr.slice(size-arr.length);
      arr1 = arr;
    }else{
      arr2.push(arr);
      break;
    }
  }
  return arr2;
}
chunk([0, 1, 2, 3, 4, 5, 6, 7, 8], 4);

```

**Comment by Sandaydi** [comment]
楼主的代码可以将后面的输出改成以下：
```
 if(arr.length%size !== 0){
    arr1[arr1.length-1] = arr1[arr1.length-1].slice(0,arr.length%size);
    return arr1;
  }else{
    return arr1;
  }
```
除去空值，就能过

我的思路：
```
function chunk(arr, size) {
  // 请把你的代码写在这里
  var arr2 = [];
  var arr1 = arr;
  for(var i=arr.length; i>0; i--){
    if(arr.length>size){
      arr2.push(arr.slice(0,size));
      arr = arr1;
      arr = arr.slice(size-arr.length);
      arr1 = arr;
    }else{
      arr2.push(arr);
      break;
    }
  }
  return arr2;
}
chunk([0, 1, 2, 3, 4, 5, 6, 7, 8], 4);

```
