### ISSUE TITLE
who can help me?

### ISSUE THREAD

**Issue by xiezzhui** [FreeCodeCampChina/freecodecamp.cn#36]
Challenge [Create Decimal Numbers with JavaScript](https://www.freecodecamp.cn/challenges/create-decimal-numbers-with-javascript#?solution=var%20ourDecimal%20%3D%205.7%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
var ourDecimal = 5.7;

// Only change code below this line



```

**Comment by discountry** [comment]
Just name your variable `myDecimal`

Solution:

``` js
var myDecimal = 5.7;
```
