### ISSUE TITLE
为什么把value==a 换成value==arguments[l-1] arr就是[],明明我a=arguments[l-1]

### ISSUE THREAD

**Issue by yejunyu** [FreeCodeCampChina/freecodecamp.cn#360]
Challenge [Seek and Destroy](https://www.freecodecamp.cn/challenges/seek-and-destroy#?solution=function%20destroyer(arr)%20%7B%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E9%87%8C%0A%20%20var%20l%20%3D%20arguments.length%3B%0A%20%20console.log(arr)%3B%0A%20%20%2F%2Fconsole.log(arguments%5Bl-1%5D)%3B%0A%20%20var%20a%20%3D%20arguments%5Bl-1%5D%3B%20%0A%20%20arr%20%3D%20arr.filter(function(value)%7Bif%20(value%3D%3Da)%7Breturn%20value%3B%7D%7D)%3B%0A%20%20%20%20%20%20%20%20%2F%2Farr.filter(function(value)%7Bif%20(value%3D%3D3)%7Breturn%20value%3B%7D%7D)%3B%0A%20%20console.log(arr)%3B%0A%20%20return%20arr%3B%0A%7D%0A%0Adestroyer(%5B1%2C%202%2C%203%2C%201%2C%202%2C%203%5D%2C%202%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function destroyer(arr) {
  // 请把你的代码写在这里
  var l = arguments.length;
  console.log(arr);
  //console.log(arguments[l-1]);
  var a = arguments[l-1]; 
  arr = arr.filter(function(value){if (value==a){return value;}});
        //arr.filter(function(value){if (value==3){return value;}});
  console.log(arr);
  return arr;
}

destroyer([1, 2, 3, 1, 2, 3], 2, 3);

```

**Comment by S1ngS1ng** [comment]
@yejunyu 明明就是你写错了=。=
1. `arguments[l-1]` 只能取到 `arguments` 的最后一个元素，你的写法中只能取到 3，取不到 2。
2. 题目要求是把 2 和 3 从数组中删除，现在你写的是保留。`filter` 的用法：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

这不是 bug，以后这样的问题请到 gitter 提问

**Comment by Real-yoyo** [comment]
function destroyer(arr) {
      // 请把你的代码写在这里
      var args = [];
      for (let i = 0; i < arguments.length; i++) {
        args.push(arguments[i]);
      }

      var arr3 = arr.filter(function (value) {
        return args.indexOf(value) < 0;
      });
      return arr3;
    };
    destroyer([1, 2, 3, 1, 2, 3], 2, 3);

**Comment by seakingxc** [comment]
> for (let i = 0; i < arguments.length; i++) {
> args.push(arguments[i]);
> }

thanks for u code!  原本我还想不出要怎么做这道题，看了你的恍然大悟。您也可以把for替换成Array.from(arguments)

**Comment by ceshigong** [comment]
> }

const destroyer = (arr, ...args) => arr.filter(i => !args.includes(i));

**Comment by ceshigong** [comment]
> > for (let i = 0; i < arguments.length; i++) {
> > args.push(arguments[i]);
> > }
> 
> thanks for u code! 原本我还想不出要怎么做这道题，看了你的恍然大悟。您也可以把for替换成Array.from(arguments)

const destroyer = (arr, ...args) => arr.filter(i => !args.includes(i));
