### ISSUE TITLE
第二个函数应该返回数组并且新数组第四位就应该是10

### ISSUE THREAD

**Issue by Annyfeather** [FreeCodeCampChina/freecodecamp.cn#361]
Challenge [Stand in Line](http://freecodecamp.cn/challenges/stand-in-line#?solution=function%20queue(arr%2C%20item%20)%20%7B%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E9%87%8C%0A%20%20testArr%20%3D%20arr.push(item)%3B%0A%20%20oh%20%3D%20arr.shift()%3B%0A%20%0A%20%20return%20oh%3B%2F%2F%20%E8%AF%B7%E4%BF%AE%E6%94%B9%E8%BF%99%E4%B8%80%E8%A1%8C%0A%7D%0A%0A%2F%2F%20%E5%88%9D%E5%A7%8B%E5%8C%96%E6%B5%8B%E8%AF%95%E6%95%B0%E6%8D%AE%0Avar%20testArr%20%3D%20%5B5%2C6%2C7%2C8%2C9%5D%3B%0Avar%20no%20%3D%200%3B%0A%0A%0A%2F%2F%20%E6%8E%A7%E5%88%B6%E5%8F%B0%E8%BE%93%E5%87%BA%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(queue(testArr%2C%2010))%3B%20%2F%2F%20%E4%BD%A0%E5%8F%AF%E4%BB%A5%E4%BF%AE%E6%94%B9%E8%BF%99%E4%B8%80%E8%A1%8C%E6%9D%A5%E6%B5%8B%E8%AF%95%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function queue(arr, item ) {
  // 请把你的代码写在这里
  testArr = arr.push(item);
  oh = arr.shift();
 
  return oh;// 请修改这一行
}

// 初始化测试数据
var testArr = [5,6,7,8,9];
var no = 0;


// 控制台输出
console.log("Before: " + JSON.stringify(testArr));
console.log(queue(testArr, 10)); // 你可以修改这一行来测试你的代码
console.log("After: " + JSON.stringify(testArr));




```

**Comment by Annyfeather** [comment]
I got it

**Comment by helen31115** [comment]
testArr = arr.push(item);改为 arr.push(item);
