### ISSUE TITLE
微信二维码扫描登录

### ISSUE THREAD

**Issue by ZJH9Rondo** [FreeCodeCampChina/freecodecamp.cn#362]
#### 浏览器信息
* Chrome 最新
* Ubuntu 16.04

#### 问题描述
* new feature
> 这个登录是否支持微信二维码扫描直接登陆？

* 如果是，我会关闭并删除问题。

* 如果不是，那么是否有计划开发这一功能。

**Comment by S1ngS1ng** [comment]
@ZJH9Rondo 暂时没有这个计划。用 github 帐号就好啦
