### ISSUE TITLE
I dont know where is wrong? and I did't find the answer in GOOGLE . if I set count = 0; the result is different.

### ISSUE THREAD

**Issue by lily0101** [FreeCodeCampChina/freecodecamp.cn#363]
Challenge [Counting Cards](https://freecodecamp.cn/challenges/counting-cards#?solution=var%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8B%0A%20%20switch(card)%7B%0A%20%20%20%20case%202%3A%0A%20%20%20%20case%203%3A%0A%20%20%20%20case%204%3A%0A%20%20%20%20case%205%3A%0A%20%20%20%20case%206%3A%0A%20%20%20%20%20%20count%20%2B%2B%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%2010%2C'J'%2C'Q'%2C'K'%2C'A'%3A%0A%20%20%20%20%20%20count%20--%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%7D%0A%20%20if(count%20%3E%200)%0A%20%20%20%20return%20count%20%2B%20%22%20Bet%22%3B%0A%20%20else%0A%20%20%20%20return%20count%20%2B%20%22%20Hold%22%3B%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8A%0A%7D%0A%0A%2F%2F%20%E4%BD%A0%E5%8F%AF%E4%BB%A5%E5%9C%A8%E8%BF%99%E9%87%8C%E6%B7%BB%E5%8A%A0%2F%E5%88%A0%E9%99%A4%20cc%20%E6%96%B9%E6%B3%95%E7%9A%84%E8%B0%83%E7%94%A8%E6%9D%A5%E6%B5%8B%E8%AF%95%E7%BB%93%E6%9E%9C%0A%2F%2F%20%E6%8F%90%E7%A4%BA%3A%20%E5%B7%A6%E8%BE%B9%E5%8F%AA%E4%BC%9A%E6%98%BE%E7%A4%BA%E6%9C%80%E5%90%8E%E4%B8%80%E6%AC%A1%E6%89%A7%E8%A1%8C%E7%9A%84%E8%BF%94%E5%9B%9E%E5%80%BC%0Acc(2)%3B%20cc(3)%3B%20cc(7)%3B%20cc('K')%3B%20cc('A')%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var count = 0;

function cc(card) {
  // 请把你的代码写在这条注释以下
//count = 0;
  switch(card){
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      count ++;
      break;
    case 10,'J','Q','K','A':
      count --;
      break;
  }
  if(count > 0)
    return count + " Bet";
  else
    return count + " Hold";
  // 请把你的代码写在这条注释以上
}

// 你可以在这里添加/删除 cc 方法的调用来测试结果
// 提示: 左边只会显示最后一次执行的返回值
cc(2); cc(3); cc(7); cc('K'); cc('A');

```

**Comment by S1ngS1ng** [comment]
Note that `case 10,'J','Q','K','A':` features "comma operator". Here is the [document](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator) you might need to go through.

JavaScript will evaluate `10,'J','Q','K','A'` first. As "comma operator" always return the last operand, which is `'A'` in this case, this snippet works exactly the same as `case 'A':`.

To fix, you need to break these `cases` into multiple lines.

## This is not a bug. Please post your questions in Gitter next time. TY.
