### ISSUE TITLE
Diff Two Arrays 無法通過測試

### ISSUE THREAD

**Issue by ayugioh2003** [FreeCodeCampChina/freecodecamp.cn#370]
Challenge [Diff Two Arrays](https://freecodecamp.cn/challenges/diff-two-arrays#?solution=function%20diffArray(a%2C%20b)%7B%0A%20c%20%3D%20a.concat(b)%3B%0A%20d%20%3D%20%5B%5D%3B%0Avar%20diffarr%20%3D%20c.filter(function(c1)%7B%0A%20%20%20%20%20%20%20if%20(a.indexOf(c1)%20%3D%3D%3D%20-1%20%7C%7C%20b.indexOf(c1)%20%3D%3D%3D%20-1)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20d.push(c1)%3B%0A%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D)%3B%0A%20%20%20%20return%20d%3B%0A%7D%0AdiffArray(%5B1%2C%202%2C%203%2C%205%5D%2C%20%5B1%2C%202%2C%203%2C%204%2C%205%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

我在英文版的 FFC 上的這題能通過測試，但在 cn 版的這題無法通過測試

My code:
```javascript
function diffArray(a, b){
 c = a.concat(b);
 d = [];
var diffarr = c.filter(function(c1){
       if (a.indexOf(c1) === -1 || b.indexOf(c1) === -1){
               d.push(c1);
       }
    });
    return d;
}
diffArray([1, 2, 3, 5], [1, 2, 3, 4, 5]);

```

**Comment by S1ngS1ng** [comment]
@ayugioh2003 当然了。
![image](https://user-images.githubusercontent.com/13592559/29397014-849881a2-82e9-11e7-9cfc-99be14529db1.png)
这是这道题的初始状态。你不仅换了参数名（这个其实没关系），但更重要的是你换了函数名。这样是肯定不行的，因为测试函数找不到 `diff`，没法进行测试。

英文版里就叫 `diffArray`，当然可以通过。

顺便，习惯上，`c` 和 `d` 前面要加上 `var`。

另外，既然用了 `filter` 方法，你就不需要再里面 `push` 了，现在你这样写还不如直接用 `for` 循环或者 `forEach`。`filter` 方法的回调函数，返回值是一个 Boolean，代表这个元素是否应该保留。另外，`filter` 本身就返回过滤以后的数组，你也没必要把它赋值给变量。因此，你只需要：

```js
function diff(arr1, arr2) {
  var c = arr1.concat(arr2);
  return c.filter(function(c1){
    return arr1.indexOf(c1) === -1 || arr2.indexOf(c1) === -1;
  });
}
```

**Comment by ayugioh2003** [comment]
原來如此!

很不好意思回報了不必要的 issue ...
也謝謝你提供的一些建議 ~

**Comment by asqhay** [comment]
这道题不够严谨，如果是`diff([1, 2, 3, 5,6,6], [1, 2, 3, 4, 5]);` 则返回的是[6,6,4];
下面是我写的方法，能避免单个array出现重复；
`function diff(arr1, arr2) {
  var newArr = [];
  var newArr2 = [];

  [...arr1].find((x,y)=>{
      [...arr2].find((a,b)=>{
          if(arr1[y]==a){newArr.push(arr1[y]);}
      });

  });

  var set1 = new Set(arr1);
  var set2 = new Set(arr2);
  for(i in newArr){
    set1.delete(newArr[i]);
    set2.delete(newArr[i]);
  }

  return [...set1].concat([...set2]);
  
}
`

**Comment by S1ngS1ng** [comment]
@asqhay 我的理解：
1. 题目中没要求去重。
2. 你的代码中，`6` 那个元素本身就是 `arr2` 中没有的。所以就算重复输出它，也不违背题意。
3. 虽然你的做法是可以的，但我觉得没必要按照 `找相同 -> 找不同 -> 去重 -> 合并` 的逻辑执行；按照 `找不同 -> 合并 -> 去重` 也是可以的，因为合并之后的数组中，不可能存在分别来自两个原数组的重复数字。

```
function diff(arr1, arr2) {
  return arr1.concat(arr2).filter(function(e){
    return arr1.indexOf(e) === -1 || arr2.indexOf(e) === -1;
  })
    .filter(function(ele, index, arr) {
      return arr.indexOf(ele) === index;
    });
}
```

4. 一点建议，既然你能想到 ES6 方法，也能想到 `new Set` 去重，那么其实合并之后用 `includes` 更简单。觉得看着别扭可以把 `[...new Set()]` 换成 `Array.from(new Set())`

```
function diff(arr1, arr2) {
  return [...new Set(
    arr1.concat(arr2).filter(e => !arr1.includes(e) || !arr2.includes(e))
  )];
}
```

**Comment by asqhay** [comment]
谢谢，我学艺不精，学一点用一点，希望能学以致用
