### ISSUE TITLE
I found a bug in the less "Target Elements by ID Using jQuery"

### ISSUE THREAD

**Issue by vivianmaple** [FreeCodeCampChina/freecodecamp.cn#373]
任务的数字写错了，导致选择的元素不对。

**Comment by wudifeixue** [comment]
![image](https://user-images.githubusercontent.com/7316929/29491869-7c27da74-8526-11e7-81f7-4b74f1165fcb.png)
这里没有写错，只是为了防止直接复制粘贴代码而稍微做了些变动。
