### ISSUE TITLE
拼接出来 应该是对的吧，但是他判断是不对的

### ISSUE THREAD

**Issue by think-TL** [FreeCodeCampChina/freecodecamp.cn#375]
Challenge [Concatenating Strings with the Plus Equals Operator](https://www.freecodecamp.cn/challenges/concatenating-strings-with-the-plus-equals-operator#?solution=%2F%2F%20%E4%B8%BE%E4%BE%8B%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%3B%0AourStr%20%2B%3D%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20%E8%AF%B7%E5%8F%AA%E4%BF%AE%E6%94%B9%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8B%E7%9A%84%E4%BB%A3%E7%A0%81%0A%0Avar%20myStr%20%3D%22This%20is%20the%20first%20sentence.%22%3B%0AmyStr%20%2B%3D%20%22This%20is%20the%20second%20sentence.%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// 举例
var ourStr = "I come first. ";
ourStr += "I come second.";

// 请只修改这条注释以下的代码

var myStr ="This is the first sentence.";
myStr += "This is the second sentence.";



```

**Comment by windyrain** [comment]
第一句话末尾少了空格

"This is the first sentence.(这个地方有个空格)"

注意审题啊，兄弟！

**Comment by wangzhijie90** [comment]
我也加了空格，拼接完也是过不了

**Comment by S1ngS1ng** [comment]
@wangzhijie90 请发代码

**Comment by ZhangyilinCN** [comment]
// 举例
var ourStr = "I come first. ";
ourStr += "I come second.";

// 请只修改这条注释以下的代码

var myStr="This is the first sentence. ";
myStr += "This is the second sentence.";

**Comment by sylvia0815** [comment]
确实是会报错  而且我拼的都是对的。 完全不知道为什么不过。(ノ｀Д)ノ要疯了！
var myStr = "This is the first sentence. ";
myStr += "This is the second sentence.";

好吧  我知道 为什么了。 因为我把上面的举例代码都删除了。
