### ISSUE TITLE
the result is right,but can't  pass through!结果都正确，跟测试用例一样，但不能通过，是我理解的不对么

### ISSUE THREAD

**Issue by baoliehua** [FreeCodeCampChina/freecodecamp.cn#376]
Challenge [Where do I belong](https://freecodecamp.cn/challenges/where-do-i-belong#?solution=function%20where(arr%2C%20num)%20%7B%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E9%87%8C%0A%20%20arr.push(num)%3B%0A%20%20arr.sort(function(a%2Cb)%7Breturn%20a-b%3B%7D)%3B%0A%20%20for(var%20i%20in%20arr)%7B%0A%20%20%20%20if(arr%5Bi%5D%3D%3Dnum)%7B%0A%20%20%20%20%20%20num%3Di%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20num%3B%0A%7D%0A%0Awhere(%5B40%2C%2060%5D%2C%2050)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function where(arr, num) {
  // 请把你的代码写在这里
  arr.push(num);
  arr.sort(function(a,b){return a-b;});
  for(var i in arr){
    if(arr[i]==num){
      num=i;
      break;
    
    }
  }
  return num;
}

where([40, 60], 50);

```

**Comment by baoliehua** [comment]
结果都正确，跟测试用例一样，但不能通过，是我理解的不对么

**Comment by S1ngS1ng** [comment]
@baoliehua 结果并不正确噢。注意，用 `for...in` 遍历的时候，`i` 就是 Object 中的每一个 key。在 JS 中，key 只可以是字符串，因此这里你得到的 `i` 也是字符串。
然而题目要求你返回的是数字。

对于数组遍历，不建议用 `for...in`。否则你还要在最后转换一次，没有必要

**Comment by baoliehua** [comment]
好的，谢谢了

**Comment by leifangqing** [comment]
function where(arr, num) {
  // 请把你的代码写在这里
  var arr1=[];
  arr.push(num);
  arr.sort(function(a,b){
    return a-b;
  });
  arr2=arr.indexOf(num);
  return arr2;
}

where([40, 60], 50);
这样会简单点吧，我没有写for，用indexOf去判断了

**Comment by pioneers01** [comment]
@leifangqing 你这样写不行，如果arr里面没有数字和num相同，就解不出来了

**Comment by ayhwtian** [comment]
function where(arr, num) {
  // 请把你的代码写在这里
  if(arr.includes(num)){
    arr.sort(function(a,b){
      return a - b;
    });
  } else{
    arr.push(num);
  arr.sort(function(a,b){
      return a - b;
    });
  }
   
  return arr.indexOf(num);
}

where([3, 10, 5], 3);
我这个是可以通过的，选判断一下数组中有没这个数字，有的话就直接排序。没有的放就添加进去再排序。
