### ISSUE TITLE
116课

### ISSUE THREAD

**Issue by botaowei** [FreeCodeCampChina/freecodecamp.cn#38]
题干
中文里面是：给所有id为#target1的按钮添加btn-primary class。
但是英文是：
Your #target1 element should have the class animated‚ shake and btn-primary.
貌似有遗漏，请核实谢谢

**Comment by discountry** [comment]
请问是[Target the same element with multiple jQuery Selectors](https://www.freecodecamp.cn/challenges/target-the-same-element-with-multiple-jquery-selectors)这一关么？

**Comment by botaowei** [comment]
是的，好像翻译不大对，一般做题会上下对照看一下，按照下面英文的做法没做对，哈哈~

------------------ 原始邮件 ------------------
发件人: "Disney";notifications@github.com;
发送时间: 2016年10月30日(星期天) 中午1:00
收件人: "FreeCodeCampChina/freecodecamp.cn"freecodecamp.cn@noreply.github.com; 
抄送: "不冷的cool子"botaowei@qq.com; "Author"author@noreply.github.com; 
主题: Re: [FreeCodeCampChina/freecodecamp.cn] 116课 (#38)

请问是Target the same element with multiple jQuery Selectors这一关么？

**Comment by discountry** [comment]
@botaowei 
我看过了没有问题。

**Comment by huluoyang** [comment]
@botaowei  分别用三种选择器来添加样式addClass()，最后的总样式是：animated‚ shake and btn-primary。

**Comment by mentos523** [comment]
$("button").addClass.("animated");
    $(".btn").addClass.("shake");
    $("#target1").addClass.("btn-primary");

点了run tests 后，右边预览里提示 SyntaxError: Unexpected token (  这样一个错误，无法通过

**Comment by stevending1st** [comment]
@mentos523  您的语法好像有问题("#target1").addClass("btn-primary");
@botaowei 同意您的看法
@huluoyang ,谢谢您的帮助。

**Comment by Roxycheng** [comment]
![image](https://user-images.githubusercontent.com/31586469/35218751-bb13729e-ffaa-11e7-9f25-b0b3623cb5dc.png)
为什么会出现这个结果？
