### ISSUE TITLE
举例中.hasOwnProperty("top")带了引号，run tests时不带才能通过

### ISSUE THREAD

**Issue by ghost** [FreeCodeCampChina/freecodecamp.cn#382]
Challenge [Testing Objects for Properties](https://freecodecamp.cn/challenges/testing-objects-for-properties#?solution=%2F%2F%20%E5%88%9D%E5%A7%8B%E5%8C%96%E5%8F%98%E9%87%8F%0Avar%20myObj%20%3D%20%7B%0A%20%20gift%3A%20%22pony%22%2C%0A%20%20pet%3A%20%22kitten%22%2C%0A%20%20bed%3A%20%22sleigh%22%0A%7D%3B%0A%0Afunction%20checkObj(checkProp)%20%7B%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8B%0A%20%20if(myObj.hasOwnProperty(checkProp))%7B%0A%20%20%20%20return%20myObj%5BcheckProp%5D%3B%0A%20%20%7D%0A%20%20return%20%22Not%20Found%22%3B%0A%7D%0A%0A%2F%2F%20%E4%BD%A0%E5%8F%AF%E4%BB%A5%E4%BF%AE%E6%94%B9%E8%BF%99%E4%B8%80%E8%A1%8C%E6%9D%A5%E6%B5%8B%E8%AF%95%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%0AcheckObj(%22gift%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// 初始化变量
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // 请把你的代码写在这条注释以下
  if(myObj.hasOwnProperty(checkProp)){
    return myObj[checkProp];
  }
  return "Not Found";
}

// 你可以修改这一行来测试你的代码
checkObj("gift");

```
举例中.hasOwnProperty("top")带了引号，完成题目时，应该是.hasOwnProperty(checkProp)而不是.hasOwnProperty("checkProp")

**Comment by S1ngS1ng** [comment]
这不是 bug。因为例子中 `"top"` 是字符串，而这里的 `checkProp` 是变量
