### ISSUE TITLE
请问这是哪里出现了问题

### ISSUE THREAD

**Issue by furao1998** [FreeCodeCampChina/freecodecamp.cn#384]
Challenge [Appending Variables to Strings](https://www.freecodecamp.cn/challenges/appending-variables-to-strings#?solution=%2F%2F%20%E4%B8%BE%E4%BE%8B%0Avar%20anAdjective%20%3D%20%22awesome!%22%3B%0Avar%20ourStr%20%3D%20%22Free%20Code%20Camp%20is%20%22%3B%0AourStr%20%2B%3D%20anAdjective%3B%0A%0A%2F%2F%20%E8%AF%B7%E5%8F%AA%E4%BF%AE%E6%94%B9%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8B%E7%9A%84%E4%BB%A3%E7%A0%81%0A%0Avar%20someAdjective%3D%22wo%20shi%20shei%22%3B%0Avar%20myStr%20%3D%20%22Learning%20to%20code%20is%20%22%3B%0AmyStr%20%2B%3D%20someAdjective%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// 举例
var anAdjective = "awesome!";
var ourStr = "Free Code Camp is ";
ourStr += anAdjective;

// 请只修改这条注释以下的代码

var someAdjective="wo shi shei";
var myStr = "Learning to code is ";
myStr += someAdjective;

```

**Comment by zerozhoumi** [comment]
你代码没问题，我运行过了，你看看是不是什么浏览器插件拦截了

**Comment by UltramanAce** [comment]
嗯嗯，谢谢了




------------------ 原始邮件 ------------------
发件人: "周密";<notifications@github.com>;
发送时间: 2017年8月31日(星期四) 晚上7:52
收件人: "FreeCodeCampChina/freecodecamp.cn"<freecodecamp.cn@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [FreeCodeCampChina/freecodecamp.cn] 请问这是哪里出现了问题 (#384)




你代码没问题，我运行过了，你看看是不是什么浏览器插件拦截了

**Comment by S1ngS1ng** [comment]
@UltramanAce 遇到类似的问题，可以刷新一下，或者 Reset，然后重新提交
