### ISSUE TITLE
为什么通过不了

### ISSUE THREAD

**Issue by QiuRui1** [FreeCodeCampChina/freecodecamp.cn#386]
Challenge [Override Class Declarations by Styling ID Attributes](https://www.freecodecamp.cn/challenges/override-class-declarations-by-styling-id-attributes#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%20%20%23orange-text%7B%0A%20%20%20%20color%3Abrown%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%20blue-text%22%20id%3D%22orange-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
  #orange-text{
    color:brown;
  }
</style>
<h1 class="pink-text blue-text" id="orange-text">Hello World!</h1>

```

**Comment by ShadowMonsterYJ** [comment]
You need change
#orange-text{
        color:brown;
    }
to
#orange-text{
        color:orange;
    }

________________________________

**Comment by wudifeixue** [comment]
正如楼上所说，你的 `h1` 元素应该是**橙色的**。
