### ISSUE TITLE
hello.i find error

### ISSUE THREAD

**Issue by tancool** [FreeCodeCampChina/freecodecamp.cn#388]
Challenge [Learn how Script Tags and Document Ready Work](https://www.freecodecamp.cn/challenges/learn-how-script-tags-and-document-ready-work#?solution=%0Afccss%0A%24(document).ready(function()%20%7B%0A%0A%20%20%7D)%3B%20%20%0Afcces%0A%0A%3C!--%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8A%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
$(document).ready(function() {
<script>


</script>
});  
<!-- 请把你的代码写在这条注释以上 -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

$(document).ready(function() {
<script>

</script>
});  

这一块代码提交起来是正确的,但是他们确实是错误的.
The code is submitted correctly, but they are wrong.

**Comment by wudifeixue** [comment]
感谢你提交的issue，我刚测试也确实存在这个问题。  
不过我个人感觉修复意义不大，毕竟大家都知道应该怎么写。而且这个好像很难写测试啊..
@S1ngS1ng 你看呢

**Comment by S1ngS1ng** [comment]
恩，上游也有同样的问题。我这两天看一下，加一个正则就好了，应该不难改。
只是，有没有必要改呢？ @wudifeixue

**Comment by wudifeixue** [comment]
我觉得是没有的233 不过就看你想不想啦

**Comment by ttyhtg** [comment]
我也发现了，哈哈哈

**Comment by xuanjixiaojie** [comment]
请问这道题的正确答案到底应该怎么写啊，求解答~~~~~~~~我写的是<script>
$(document).ready(function() {
                     }); 
</script>
显示错误

**Comment by S1ngS1ng** [comment]
@xuanjixiaojie 你这样写是没错的，可以通过
