### ISSUE TITLE
应该是这两个数字之前所有整数吧，这题目翻译的真不严谨

### ISSUE THREAD

**Issue by pengandpeng** [FreeCodeCampChina/freecodecamp.cn#393]
Challenge [Sum All Numbers in a Range](https://www.freecodecamp.cn/challenges/sum-all-numbers-in-a-range) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function sumAll(arr) {
  return 1;
}

sumAll([1, 4]);

```

**Comment by S1ngS1ng** [comment]
@pengandpeng 
1. 你可以参考一下原文是怎么说的。https://www.freecodecamp.org/challenges/sum-all-numbers-in-a-range
2. 根据底下的测试用例也可以知道是整数
3. 如果不是整数，结果永远都是无穷大
