### ISSUE TITLE
when I apply for a c9 account ,it must be banding a card!

### ISSUE THREAD

**Issue by MssterDouble** [FreeCodeCampChina/freecodecamp.cn#394]
Challenge [Start a Nodejs Server](https://www.freecodecamp.cn/challenges/start-a-nodejs-server) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by wudifeixue** [comment]
C9的账号确实必须要信用卡，这点你可以考虑用国内的[Coding网页ide](https://ide.coding.net) 
或者干脆本地装一个[Webstorm](https://www.jetbrains.com/webstorm/download/)
或者[Visual Studio](https://www.visualstudio.com/downloads/)
