### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by WilliamSkyWalker** [FreeCodeCampChina/freecodecamp.cn#4]
Translation error on https://www.freecodecamp.cn/challenges/import-a-google-font.
Origin Translation:
现在，让我们来导入谷歌字体。

首先，你需要用link标签来引入谷歌Lobster字体。

复制下面的代码片断并将其粘贴到你的代码编辑器的顶部：

It should be:
现在，让我们来导入谷歌字体。

首先，你需要用link标签来引入谷歌Lobster字体。

复制下面的代码片断并将其粘贴到你的代码编辑器的<head>中：

Do as the origin says will just paste the code into the first line of your code, of course it would import nothing.

Thanks Authors, Good day.

**Comment by zeallean** [comment]
此处的`<link>`标签不一定非要加在`<head>`中，放在编辑器的顶部就可以实现效果。虽然这个不太符合语法。但是在这个练习里的任务要求就是如此。另外可能由于GFW，相关的`google font`可能无法访问。可以替换成国内的镜像资源。

`<link href="https://fonts.gmirror.org/css?family=Lobster" rel="stylesheet" type="text/css">`

**Comment by WilliamSkyWalker** [comment]
Thank you very much.

**Comment by xiamingwudi** [comment]
我按照教程中修改为Google font后，看到手机效果h2字体变化了，但是错误提示中还是导入Lobster字体失败；换成国内镜像，字体加载失败了。这个怎么破。。。

**Comment by vegetabird** [comment]
@xiamingwudi 我也遇到同样的问题了，请问你是怎么解决的？

**Comment by kornnet** [comment]
@xiamingwudi @WilliamSkyWalker 请问解决了么？我为什么换成国内镜像地址还是无法引入Lobster字体
