### ISSUE TITLE
代码执行没问题，就是不能通过，新了鲜了，奇了怪了！！

### ISSUE THREAD

**Issue by 364427800** [FreeCodeCampChina/freecodecamp.cn#400]
Challenge [Title Case a Sentence](https://www.freecodecamp.cn/challenges/title-case-a-sentence#?solution=function%20titleCase(str)%20%7B%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%0A%09var%20val%3D%22%22%3B%0A%09var%20res%3Dstr.toLowerCase().split(%22%20%22)%3B%0A%09for%20(var%20i%3D0%3Bi%3Cres.length%3Bi%2B%2B)%7B%0A%09%09var%20a1%3Dres%5Bi%5D.replace(res%5Bi%5D%5B0%5D%2Cres%5Bi%5D%5B0%5D.toUpperCase())%3B%0A%09%09val%2B%3Da1%2B%22%20%22%3B%0A%09%7D%0A%09return%20val%3B%0A%7D%0A%0AtitleCase(%22I'm%20a%20little%20tea%20pOt%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function titleCase(str) {
  // 请把你的代码写在这
	var val="";
	var res=str.toLowerCase().split(" ");
	for (var i=0;i<res.length;i++){
		var a1=res[i].replace(res[i][0],res[i][0].toUpperCase());
		val+=a1+" ";
	}
	return val;
}

titleCase("I'm a little tea pOt");

```

**Comment by immafrady** [comment]
结尾处多了一个空格……

**Comment by wudifeixue** [comment]
是的就像楼上所说你的执行结果看出来几乎没啥问题，但是多了一个空格。  
你想办法让结果大写首字母然后别再添加多余的空格吧。

**Comment by awoooo** [comment]
可以发现这段的问题在哪里吗?

```javascript
function titleCase(str) {
  // 请把你的代码写在这里
  var arr = str.split(" ");
  var newStr = '';
  arr.forEach(function(val) {
    newStr += ' ' + val[0].toUpperCase() + val.substr(1, val.length).toLowerCase();
  });
  return newStr;
}

titleCase("sHoRt AnD sToUt");
```

**Comment by S1ngS1ng** [comment]
@awoooo 先自己试一下，也是多了一个空格

**Comment by ShuangChenGust** [comment]
function titleCase(str) {
  // 请把你的代码写在这里
  var words= str.toLowerCase().split(" ");
  for (var i = 0; i < words.length; i++){
    words[i] = words[i][0].toUpperCase() + words[i].slice[1];
  }
  return words.join(" ");
}

titleCase("I'm a little tea pot");

Why my code cannot pass this task?

**Comment by ayhwtian** [comment]
`function titleCase(str) {
  // 请把你的代码写在这里

  /*
  var str1 = str.toLowerCase().split(" ");

  for(var i=0;i<str1.length;i++){
    str1[i] = str1[i][0].toUpperCase() + str1[i].slice(1);
  }
  
  return str1.join(" ");*/
  
  /*return str.toLowerCase().split(" ").map(function(val){
    return val[0].toUpperCase() + val.slice(1);
  }).join(" ");*/
  
  return str.toLowerCase().replace(/(^|\s)[a-z]/g,function(val){
    return val.toUpperCase();
  });

}

titleCase("I'm a little tea pot");
`
