### ISSUE TITLE
给你的表单添加两个单选按钮，一个叫indoor，另一个叫outdoor。写完之后，我觉得自己的代码没问题，但是没反应

### ISSUE THREAD

**Issue by 13752326065** [FreeCodeCampChina/freecodecamp.cn#402]
#### FreeCodeCamp.cn Issue 模板
如何使用本模板:
* 尽可能多填些相关信息，方便管理员参考
* 对于无法给出的内容，请删除掉那一行

# 以上内容请在提交 Issue 之前删除

#### 浏览器信息
* 浏览器名称，版本号
* 操作系统

#### 问题描述
* 问题是在什么时候，什么情况下遇到的
* 简要说明如何重现

#### 你的代码

```
如果和代码相关，请在这里粘贴你的全部代码
```

**Comment by iycing** [comment]
我之前也出现了这种情况，可能出现了bug了吧，不过我充值一次后就好了。

**Comment by S1ngS1ng** [comment]
@13752326065 
麻烦你发一下代码。

## 另外，麻烦你仔细看看 issue template 里面的说明，看清楚了再提交
