### ISSUE TITLE
求解，怎么获取数组里面的最长值，我只查到最大值和最小值，可是都是弄数字的。。。。

### ISSUE THREAD

**Issue by leifangqing** [FreeCodeCampChina/freecodecamp.cn#404]
Challenge [Find the Longest Word in a String](https://freecodecamp.cn/challenges/find-the-longest-word-in-a-string#?solution=function%20findLongestWord(str)%20%7B%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E9%87%8C%0A%20%20str1%3Dstr.split(%22%20%22)%3B%0A%20%20%20%20%20%0A%20%20return%20str1.length%3B%0A%0A%7D%0A%0AfindLongestWord(%22May%20the%20force%20be%20with%20you%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function findLongestWord(str) {
  // 请把你的代码写在这里
  str1=str.split(" ");
     
  return str1.length;

}

findLongestWord("May the force be with you");

```

**Comment by S1ngS1ng** [comment]
@leifangqing 遍历就行。
如果你知道 `apply` 的话，`split` 之后的数组，先 `map` 一下得到所有元素的 `length`，然后用 `Math.max.apply` 找到最大值。
自己先试试，如果还是不知道怎么写，看这里吧。https://github.com/FreeCodeCampChina/freecodecamp.cn/wiki/find-the-longest-word-in-a-string

另外，以后这样的问题直接来 Q 群或者 Gitter 上提问就行。不要开 Issue

**Comment by asqhay** [comment]
还有一种写法，可以找到最长的字符串的string和字符串的length


function findLongestWord(str) {
  // 请把你的代码写在这里
  let a=[];
  let c=[];
  a=str.split(' ');
   for(let i=0;i<a.length;i++){
          c.push(a[i]);
   }
   
   c.sort((a,b)=>{
      return b.length-a.length;
   })
   return c[0];//加length就找到长度
}

**Comment by unclepaw** [comment]
贴个我的。。
把每个的长度获取出来，然后从大到小排序，第0个肯定是最大的。

```
function findLongestWord(str) {
  // 请把你的代码写在这里
  
  str = str.split(' ');
  
  var arr = [];
  
  for (var i = 0; i < str.length; i++) {
    arr.push(str[i].length);
  }
  
  arr.sort(function(a, b) {
	  return b - a;
	});
    
  return arr[0];
}

findLongestWord("The quick brown fox jumped over the lazy dog");

```

**Comment by unclepaw** [comment]
再贴一个比较简单的。
大的就记录，小的就忽略。

```
function findLongestWord(str) {
  // 请把你的代码写在这里
  
  str = str.split(' ');
  
var length = 0;
  
for ( var i=0; i < str.length; i++) {
  
  if (str[i].length>length) {
    length = str[i].length;
  }
        
}
  
  return length;
   
}

findLongestWord("The quick brown fox jumped over the lazy dog");
```

**Comment by FengXiuli** [comment]
>
> ```我的两种方法
function findLongestWord(str) {
  //方法一
  // 请把你的代码写在这里
 // var arr1=[];
 // var arr=str.split(' ');
 // for(var i=0;i<arr.length;i++){
  //  arr1.push(arr[i].length);
 // }
 // arr1.sort(function(a,b){
 //   return b-a;
//  });
 // return arr1[0];
  
  
  //方法二
  var arr=str.split(' ');
  var newArr=arr.map(function(val){
    return val.length;
  });
  return Math.max.apply(Math,newArr);
  //return Math.max.apply(null,newArr);
}

findLongestWord("The quick brown fox jumped over the lazy dog");
