### ISSUE TITLE
这一题为什么不能添加"+"号了.对之前加号的描述不太理解

### ISSUE THREAD

**Issue by wangxiaoqing5528** [FreeCodeCampChina/freecodecamp.cn#405]
Challenge [Invert Regular Expression Matches with JavaScript](https://freecodecamp.cn/challenges/invert-regular-expression-matches-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3135.4 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// 初始化变量
var testString = "How many non-space characters are there in this sentence?";

// 请只修改这条注释以下的代码

var expression = /\S/g;  // 请修改这一行

// 请只修改这条注释以上的代码

// 用 nonSpaceCount 存储 testString 中匹配到 expression 的次数
var nonSpaceCount = testString.match(expression).length;

```

**Comment by S1ngS1ng** [comment]
@wangxiaoqing5528 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions
请参考文档中对 `+` 的解释。

> Matches the preceding expression 1 or more times. Equivalent to {1,}

`+` 表示数量为 `1~n`。`\S` 只会匹配一个字符，比如 `H`。`\S+` 会尽可能多的匹配，比如 `How`，这些都符合 `\S`，但之后的空格不符合。

## 这不是 bug，请不要开 issue，提问请移步 gitter 或者 QQ 群
