### ISSUE TITLE
为啥没有结果跳出 哪块代码错误了

### ISSUE THREAD

**Issue by gufengbangye** [FreeCodeCampChina/freecodecamp.cn#409]
Challenge [Profile Lookup](https://freecodecamp.cn/challenges/profile-lookup#?solution=%2F%2F%E5%88%9D%E5%A7%8B%E5%8C%96%E5%8F%98%E9%87%8F%0Avar%20contacts%20%3D%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Akira%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Laine%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220543236543%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Pizza%22%2C%20%22Coding%22%2C%20%22Brownie%20Points%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Harry%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Potter%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220994372684%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Hogwarts%22%2C%20%22Magic%22%2C%20%22Hagrid%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Sherlock%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Holmes%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220487345643%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Intriguing%20Cases%22%2C%20%22Violin%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Kristian%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Vos%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%22unknown%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Javascript%22%2C%20%22Gaming%22%2C%20%22Foxes%22%5D%0A%20%20%20%20%7D%0A%5D%3B%0A%0A%0Afunction%20lookUp(firstName%2C%20prop)%7B%0A%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8B%0A%20%20for(var%20i%3D0%3Bi%3Ccontacts.legnth%3Bi%2B%2B)%7B%0A%20%20%20%20if(firstName%20%3D%3D%20contacts%5Bi%5D.firstName%26%26contacts%5Bi%5D.hasOwnProperty(prop))%7B%20%0A%20%20%20%20%20%20return%20contancts%5Bi%5D.prop%3B%0A%20%20%20%20%7D%0A%20%20%20%20%20%20else%20if(firstName!%3Dcontacts%5Bi%5D.firstName)%7B%0A%20%20%20%20%20%20%20%20return%20%22No%20such%20contact%22%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20else%20if(!contacts%5Bi%5D.hasOwnProperty(prop)%26%26firstName%3D%3Dcontacts%5Bi%5D.firstName)%7B%0A%20%20%20%20%20%20return%20%22No%20such%20property%22%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8A%0A%0A%0A%2F%2F%20%E4%BD%A0%E5%8F%AF%E4%BB%A5%E4%BF%AE%E6%94%B9%E8%BF%99%E4%B8%80%E8%A1%8C%E6%9D%A5%E6%B5%8B%E8%AF%95%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%0AlookUp(%22Akira%22%2C%20%22likes%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
//初始化变量
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];


function lookUp(firstName, prop){
// 请把你的代码写在这条注释以下
  for(var i=0;i<contacts.legnth;i++){
    if(firstName == contacts[i].firstName&&contacts[i].hasOwnProperty(prop)){ 
      return contancts[i].prop;
    }
      else if(firstName!=contacts[i].firstName){
        return "No such contact";
      }
    else if(!contacts[i].hasOwnProperty(prop)&&firstName==contacts[i].firstName){
      return "No such property";
    }
  }
}
// 请把你的代码写在这条注释以上


// 你可以修改这一行来测试你的代码
lookUp("Akira", "likes");

```

**Comment by wenzhaoda** [comment]
// 请把你的代码写在这条注释以下
var result="";
for(var i=0;i<contacts.length;i++){
  var lu=contacts[i].hasOwnProperty(prop);
  var ln=contacts[i].firstName;
  if(contacts[i].firstName==firstName&&lu===true){
    return contacts[i][prop];
  }
  else if(lu===false){
    result="No such property";
  }
  else if(ln!=firstName){
    result="No such contact";
  }
}
// 请把你的代码写在这条注释以上
return result;
}
