### ISSUE TITLE
文字描述错误

### ISSUE THREAD

**Issue by cxmSevenlaps** [FreeCodeCampChina/freecodecamp.cn#41]
Challenge [Comparisons with the Logical Or Operator](https://www.freecodecamp.cn/challenges/comparisons-with-the-logical-or-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

“只有当num大于等于5或小于等于10时，函数返回"Yes"。”这句话中的描述应该是：num小于等于5或者大于等于10.
-----

if (num > 10 || num < 5) {
  return "No";
}
return "Yes";

**Comment by discountry** [comment]
请仔细看代码逻辑

**Comment by AzhengTsai** [comment]
這題文字教學怎麼看起來怪怪的

只有当num大于等于5或小于等于10时，函数返回"Yes"。相同的逻辑可以简写成：
if (num > 10 || num < 5) {
  return "No";
}
return "Yes";
----------------------------------------
應該要說成  只有当num大于等于5"而且"小于等于10时，函数返回"Yes"
才能跟舉例的判斷式吻合
