### ISSUE TITLE
cloud 9 注册问题

### ISSUE THREAD

**Issue by gdccwxx** [FreeCodeCampChina/freecodecamp.cn#412]
cloud 9 注册需要card Number，对于学生而言门槛很高。。。能否商量去掉这个选项

**Comment by S1ngS1ng** [comment]
@gdccwxx gitter 里刚说了，C9 不是唯一选项，你可以选择任何你认为合适的平台。本地跑也一样没问题。
@wudifeixue 要不多解释一句？

**Comment by wudifeixue** [comment]
嘛这个问题也是讨论过很多次了 可以参考#66

**Comment by S1ngS1ng** [comment]
@wudifeixue 嗯，那先关闭了
