### ISSUE TITLE
use a CSS Class to Style an Element

### ISSUE THREAD

**Issue by zilongxuan001** [FreeCodeCampChina/freecodecamp.cn#417]
Challenge [Use a CSS Class to Style an Element](https://freecodecamp.cn/challenges/use-a-css-class-to-style-an-element#?solution=%3Cstyle%3E%0A%20.red-text%20%7B%0A%20%C2%A0%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3E%E6%88%91%E5%AE%B6%E7%9A%84%E7%8C%AB%E5%92%AA%3C%2Fh2%3E%0A%0A%3Cp%3E%E5%9C%A8%E5%A4%A7%E5%AE%B6%E5%BF%83%E7%9B%AE%E4%B8%AD%EF%BC%8C%E7%8C%AB%E6%98%AF%E6%85%B5%E6%87%92%E7%9A%84%E5%8F%AF%E7%88%B1%E7%9A%84%E5%8C%96%E8%BA%AB%EF%BC%8C%E5%AE%83%E5%8F%AF%E4%BB%A5%E7%9D%A1%E9%A5%B1%E4%BA%86%E5%86%8D%E8%B5%B7%E6%9D%A5%E5%90%83%E9%A5%AD%EF%BC%8C%E5%8F%AF%E4%BB%A5%E9%80%97%E8%B6%A3%E5%B0%8F%E8%80%97%E5%AD%90%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%8D%96%E5%BE%97%E4%BA%86%E8%90%8C%EF%BC%8C%E4%BD%BF%E5%BE%97%E4%BA%86%E5%9D%8F%EF%BC%8C%E8%BF%99%E6%A0%B7%E7%99%BE%E5%8F%98%E7%9A%84%E5%B0%8F%E6%80%AA%E5%85%BD%E5%B0%B1%E9%9B%86%E7%BB%93%E5%9C%A8%E4%B8%80%E5%8F%AA%E5%AE%A0%E7%89%A9%E4%B8%8A%EF%BC%8C%E6%80%8E%E8%83%BD%E4%B8%8D%E6%83%B9%E4%BA%BA%E6%80%9C%E7%88%B1%E3%80%82%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 4.4.4; MI PAD Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
 .red-text {
    color: red;
  }
</style>

<h2 class="red-text">我家的猫咪</h2>

<p>在大家心目中，猫是慵懒的可爱的化身，它可以睡饱了再起来吃饭，可以逗趣小耗子，可以卖得了萌，使得了坏，这样百变的小怪兽就集结在一只宠物上，怎能不惹人怜爱。</p>

```

**Comment by S1ngS1ng** [comment]
@zilongxuan001 暂时没发现问题。刷新一下重新提交。如果还是不行，截图发一下控制台的输出。谢谢

**Comment by wudifeixue** [comment]
这题可能是你之前提交错误了造成页面出现奇怪的情况保存起来了，最后造成你链接里面的答案不正确通关。。
我建议你去刷新页面或者直接回到这题的
初始链接：https://freecodecamp.cn/challenges/use-a-css-class-to-style-an-element  
再重新填一下答案继续吧。
