### ISSUE TITLE
i do not know

### ISSUE THREAD

**Issue by iOS-Xiaowen** [FreeCodeCampChina/freecodecamp.cn#418]
Challenge [Build a Tribute Page](https://www.freecodecamp.cn/challenges/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by S1ngS1ng** [comment]
@iOS-Xiaowen 下次开 Issue 之前请先阅读说明。这里不是用来让你玩儿的

**Comment by naturerespiro** [comment]
我只是不知道，你第一次也是这么学的，谁又知道，
