### ISSUE TITLE
提供的该网站图片不能被加载

### ISSUE THREAD

**Issue by iycing** [FreeCodeCampChina/freecodecamp.cn#420]
Challenge [Build a Personal Portfolio Webpage](https://www.freecodecamp.cn/challenges/build-a-personal-portfolio-webpage) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by S1ngS1ng** [comment]
@ycboom 哪个图片？你是说右边的视频么？
