### ISSUE TITLE
你的页面上应该有两个单选按钮元素。 设置你的单选按钮的name属性为indoor-outdoor。 你的两个单选按钮中的每一个都应该嵌套进它自己的label元素中。 确保你的每一个label元素都有一个结束标记。 应该有一个indoor单选按钮。 应该有一个outdoor单选按钮。 这个出题有问题，单选按钮name

### ISSUE THREAD

**Issue by gitHubCSS** [FreeCodeCampChina/freecodecamp.cn#422]
#### FreeCodeCamp.cn Issue 模板
如何使用本模板:
* 尽可能多填些相关信息，方便管理员参考
* 对于无法给出的内容，请删除掉那一行

# 以上内容请在提交 Issue 之前删除

#### 浏览器信息
* 浏览器名称，版本号
* 操作系统

#### 问题描述
* 问题是在什么时候，什么情况下遇到的
* 简要说明如何重现

#### 你的代码

```
如果和代码相关，请在这里粘贴你的全部代码
```

**Comment by S1ngS1ng** [comment]
@gitHubCSS 请按照模板填好相关信息。题目链接，及你的代码。
如果你觉得题目有问题，请详细说明
