### ISSUE TITLE
 h2{     color:'blue'; }

### ISSUE THREAD

**Issue by hnkjdx** [FreeCodeCampChina/freecodecamp.cn#423]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.cn/challenges/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
 h2{
    color:'blue';
}
</style> 
<h2>我家的猫咪</h2>

<p>在大家心目中，猫是慵懒的可爱的化身，它可以睡饱了再起来吃饭，可以逗趣小耗子，可以卖得了萌，使得了坏，这样百变的小怪兽就集结在一只宠物上，怎能不惹人怜爱。</p>

```

**Comment by S1ngS1ng** [comment]
@hnkjdx 请仔细审题，仔细看左边的例子。颜色外面为什么加引号
