### ISSUE TITLE
算法题，不识别全局变量

### ISSUE THREAD

**Issue by lisaZhang911** [FreeCodeCampChina/freecodecamp.cn#425]
#### 浏览器信息
* 浏览器名称，版本号：chrome
* 操作系统：Mac OS

#### 问题描述
在中级算法diff two arrays中发现一个问题，
它不识别函数之外的全局变量。一旦出现这样的全局变量，则无法通过测试

#### 代码
    var newArr = [];      //只要出现这样函数外的全局变量，则结果无论如何通过不了，虽然结果都是对的。

    function diff(arr1, arr2) {
      diffSamefLength(arr1,arr2)
      return newArr;
    }

    function diffSamefLength(arr1,arr2){
        arr1.forEach(function(val){
          if (arr2.indexOf(val) <0){
            //console.log(val)
            newArr.push(val)
          }
        });
        arr2.forEach(function(val){
          if(arr1.indexOf(val)<0){
            newArr.push(val)
          }
        });
    }

    diff([1, "calf", 3, "piglet"], [7, "filly"]);

**Comment by S1ngS1ng** [comment]
@lisaZhang911 这个是测试环境的事儿，只会读取你写的 `function`。不读全局变量有两个原因：
1. 对于有些题目，如果可以用全局变量，就不用写代码，直接通过了
2. 所有的算法题，都不需要使用全局变量，换个写法就好。

你的代码思路是没错的，在 `diff` 里面用 `var` 声明一个，最后返回就行了。顺便，`diffSamefLength` 也放到 `diff` 里面去
