### ISSUE TITLE
Arguments Optional 挑战，结果返回的是正确的但是通过不了

### ISSUE THREAD

**Issue by tqs930113** [FreeCodeCampChina/freecodecamp.cn#426]
#### 浏览器信息
* 浏览器名称，版本号：Chrome 版本 61.0.3163.100
* 操作系统 macOS 10.13

#### 问题描述
代码结果正确，但是挑战关卡不能通过。当add(2, "3")此情况时，代码返回的时undefined

#### 你的代码

function add() {
    
    var arr = Array.prototype.slice.apply(arguments);
    var result= arr.every(function(val){
             return typeof val !== 'number';
     });
    if(result){
      return undefined;
    }
    if(arguments.length===1){
        var preVal= arr[0];
      return function(num){
        if( typeof num !== 'number'){
            return  undefined ; 
        }
        return preVal+num;
      };
    }
    return arguments[0]+arguments[1];
  }

#### 截图（如果有）
![image](https://user-images.githubusercontent.com/30656895/32477888-1861c0ae-c347-11e7-9978-e51065e9222c.png)

**Comment by S1ngS1ng** [comment]
@tqs930113 
![image](https://user-images.githubusercontent.com/13592559/32534489-deec4b9a-c423-11e7-97a3-c13cf9983656.png)
我这里得到的是 `23`。请放到浏览器的 Console 里面试试看

**Comment by chenyong88** [comment]
arr.every 改成 arr.some 即可
