### ISSUE TITLE
键盘无法输入

### ISSUE THREAD

**Issue by 18672222629** [FreeCodeCampChina/freecodecamp.cn#43]
Challenge [Say Hello to HTML Element](https://www.freecodecamp.cn/challenges/say-hello-to-html-element#?solution=%3Ch1%3EHelo%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Helo</h1>

```

**Comment by 854907646** [comment]
I have the same question too.
