### ISSUE TITLE
劳烦各位大神看下，哪儿错了

### ISSUE THREAD

**Issue by fuheideMayuyu** [FreeCodeCampChina/freecodecamp.cn#431]
Challenge [Return a Value from a Function with Return](https://www.freecodecamp.cn/challenges/return-a-value-from-a-function-with-return) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// 举例
function minusSeven(num) {
  return num - 7;
}


// 请把你的代码写在这条注释以下
function timeFive(num){ 
  return num*5;
} 
var answer = timeFive(5); 
```

**Comment by S1ngS1ng** [comment]
`timesFive`

**Comment by fuheideMayuyu** [comment]
已解决，谢谢！
