### ISSUE TITLE
bug find

### ISSUE THREAD

**Issue by elsitlte** [FreeCodeCampChina/freecodecamp.cn#433]
Challenge [Search and Replace](https://www.freecodecamp.cn/challenges/search-and-replace#?solution=function%20myReplace(str%2C%20before%2C%20after)%20%7B%0A%20var%20strArr%3Dstr.split(%22%20%22)%3B%0A%20%20for(var%20i%3D0%3Bi%3CstrArr.length%3Bi%2B%2B)%0A%20%20%20%20if(strArr%5Bi%5D%3D%3D%3Dbefore)%20strArr%5Bi%5D%3Dafter%3B%0A%20%20var%20newstr%3DstrArr.join(%22%20%22)%3B%0A%20%20%0A%20%20return%20newstr%3B%0A%7D%0A%0AmyReplace(%22A%20quick%20brown%20fox%20jumped%20over%20the%20lazy%20dog%22%2C%20%22jumped%22%2C%20%22leaped%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myReplace(str, before, after) {
 var strArr=str.split(" ");
  for(var i=0;i<strArr.length;i++)
    if(strArr[i]===before) strArr[i]=after;
  var newstr=strArr.join(" ");
  
  return newstr;
}

myReplace("A quick brown fox jumped over the lazy dog", "jumped", "leaped");

```
如下的测试用例（题目下方的验证示例字母大小写错乱导致代码验证不通过）
eg：myReplace("He is Sleeping on the couch", "Sleeping", "sitting") 应该返回 "He is Sitting on the couch"   
myReplace的arg3是首字母小写的sitting。但是 "He is Sitting on the couch" 却要求返回的是Sitting（首字母大写）

**Comment by sususu3** [comment]
注意：替换时保持原单词的大小写。例如，如果你想用单词 "dog" 替换单词 "Book" ，你应该替换成 "Dog"。
