### ISSUE TITLE
案例没有讲清楚

### ISSUE THREAD

**Issue by Ambersudo** [FreeCodeCampChina/freecodecamp.cn#437]
Challenge [Selecting from many options with Switch Statements](https://www.freecodecamp.cn/challenges/selecting-from-many-options-with-switch-statements#?solution=function%20myTest(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8B%0A%20%20switch%20(val)%20%7B%0A%20%20%20%20%20%20case%201%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20answer%20%3D%20%22alpha%22%3B%0A%20%20%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%202%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20answer%20%3D%20%22beta%22%3B%0A%20%20%20%20%20%20break%3B%20%20%20%20%0A%20%20%20%20%20%20case%203%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20answer%20%3D%20%22gamma%22%3B%0A%20%20%20%20%20%20break%3B%20%20%20%20%0A%20%20%20%20%20%20case%204%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20answer%20%3D%20%22delta%22%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20break%3B%20%20%20%20%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8A%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20%E4%BD%A0%E5%8F%AF%E4%BB%A5%E4%BF%AE%E6%94%B9%E8%BF%99%E4%B8%80%E8%A1%8C%E6%9D%A5%E6%B5%8B%E8%AF%95%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%0AmyTest(1)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(val) {
  var answer = "";
  // 请把你的代码写在这条注释以下
  switch (val) {
      case 1:
              answer = "alpha";
              break;

      case 2:
              answer = "beta";
              break;    

      case 3:
              answer = "gamma";
              break;    

      case 4:
              answer = "delta";
              break;        
  }
  
  // 请把你的代码写在这条注释以上
  return answer;  
}

// 你可以修改这一行来测试你的代码
myTest(1);


```

具体案例参考 

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/switch

https://stackoverflow.com/questions/6114210/in-javascript-is-returning-out-of-a-switch-statement-considered-a-better-practi

**Comment by Zhang-jia-chen** [comment]
**这样可以通过**
```
function myTest(val) {
  var answer = "";
  // 请把你的代码写在这条注释以下
  switch (val){
    case 1:
      answer = "alpha";
      break;
    case 2:
      answer = "beta";
      break;
    case 3:
      answer = "gamma";
      break;
    case 4:
      answer = "delta";
      break;
  }
  
  
  // 请把你的代码写在这条注释以上
  return answer;  
}

// 你可以修改这一行来测试你的代码
myTest(1);
```

**Comment by Zhangyongxu0** [comment]
我说呢，结果越试离得越远了   一开始方向是对的  结果我都加了 var   emmmm...!
