### ISSUE TITLE
第27题中的“你的p元素应该包含文本"View more "，注意more后面有一个空格。 ”，按照它的要求做了，但依旧是错的

### ISSUE THREAD

**Issue by HiJieSun** [FreeCodeCampChina/freecodecamp.cn#438]
这是我所写的那段代码<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a></p>

**Comment by HiJieSun** [comment]
<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a></p>

**Comment by HiJieSun** [comment]
<p.>View more <a href="http://www.freecatphotoapp.com">cat photos</a></p>

**Comment by HiJieSun** [comment]
<p。>View more <a。 href="http://www.freecatphotoapp.com">cat photos</a></p>
上面的句号可以无视

**Comment by wudifeixue** [comment]
我不知道你写的具体咋样了，但是我只能帮你到这里了。
![image](https://user-images.githubusercontent.com/7316929/33844162-b2a61f54-de5c-11e7-86ef-2ba2fd0c85bf.png)

**Comment by xian-sui** [comment]
我之前也一直碰到这个问题，现在解决了，你的写法应该是自己又新建了一个p标签，然后在p标签内嵌套了a标签，实际上a标签代码中本来就已经有了，只需要直接在下面的a标签上嵌套一层p标签就可以了。
