### ISSUE TITLE
闯关105

### ISSUE THREAD

**Issue by lovemegowin** [FreeCodeCampChina/freecodecamp.cn#439]
#### 浏览器信息
* chrome
* windows 10

#### 问题描述
注释闭合却显示没有闭合 无法通过

#### 截图（如果有）
![image](https://user-images.githubusercontent.com/25566683/33513780-849ceb26-d784-11e7-9b67-e36350774b13.png)

**Comment by wudifeixue** [comment]
你的感叹号用的是中文的感叹号：！  
改成英文的：!   
就好啦
