### ISSUE TITLE
257号挑战,在方法体内对参数无任何操作,结果返回的值和传入的值不一致

### ISSUE THREAD

**Issue by siyukok** [FreeCodeCampChina/freecodecamp.cn#441]
#### 浏览器信息
* chrome，62.0.3202.94（正式版本） （32 位）
* 操作系统 :windows10

#### 问题描述
检测传入的字符串是否是回文,传入"0_0 (: /-\ :) 0-0",一直报错,把关键代码注释掉之后直接run test,注意,此时方法体内对传入的参数未做任何操作,直接返回了参数,结果返回的值为     0_0 (: /- :) 0-0
(缺了一个反斜杠)

#### 你的代码
function palindrome(str) {
  // 请把你的代码写在这里
  var temp = false;
  //str = str.replace(/ /g,'');
  //str = str.replace(/,/g,'');
  //str = str.replace('.','');
  //str = str.toLowerCase();
  /*var strs = str.split('');
  for(var i = 0;i<strs.length/2;i++){
    if(strs[i] === strs[strs.length-i-1]){
      temp = true;
    }else{
      temp = false;
      break;
    }
  }
  */
  return str;
}

palindrome("0_0 (: /-\ :) 0-0");

#### 截图
![image](https://user-images.githubusercontent.com/21030561/33645684-fcd43a7c-da86-11e7-9d5d-5e4486a306d6.png)

**Comment by S1ngS1ng** [comment]
@siyukok `\` 会被解析为转义符。但不影响，因为你上面写错了，没有替换掉 `(_:)` 这些符号。
注意题目中说了，忽略符号，大小写，以及空格。你上面的正则只过滤了 ` ` `,` 和 `-`

**Comment by siyukok** [comment]
谢谢您的解答,不过转义的问题我也考虑到了,关卡我也早就过了,只是因为这终究是个bug,如果不解决或者不给个提示的话,以后恐怕还会陆陆续续有人遇见,当然我也只是提出这个issue,怎么解决取决于您

**Comment by S1ngS1ng** [comment]
@siyukok 
先谢谢你的回复。我觉得有必要再补充一些我的看法，欢迎指正。

> 检测传入的字符串是否是回文,传入`"0_0 (: /-\ :) 0-0"`,一直报错

其实，我上面说的内容是在回复你的这句话。既然你说“报错”，我理解的意思是“题目通不过”。但显然，题目通不过和这个 `\` 是否显示无关。因此我才会回复你“你的代码写错了”。

原题目中可能是为了对称的显示效果吧，所以才把字符串定义成 `"0_0 (: /-\ :) 0-0"`。

但至于你认为这是个 “bug”，个人不是很认同。事实上，传入函数的**实际参数**就是不该带 `\` 的。如果咱们把它想成 `var str = '0_0 (: /-\ :) 0-0';`，那只要这个语句执行，`str` 就已经是不带 `\` 的了。对于函数调用 `palindrome("0_0 (: /-\ :) 0-0")` 也是同理，既然咱们这么调用，那只要这个字符串传入了函数，它就不带 `\` 了。因此在我看来，左边输出不带 `\` 的是 make sense 的。

另一方面，因为它不会影响 test 函数对代码的检查，也不会导致其他 `function` break。更不会让本该通过的代码没有通过，或者让本不该通过的代码通过，所以我不觉得这是一个 bug

至于给不给提示，因为这个过程发生在 JS 内部，做到这道题的朋友应该是了解这一点的才对，毕竟前面也提过。之前的题目 Escape sequence 提到 `\` (back slash) 是可以用来转义的。所以，这里在左边显示没有 `\`，个人认为是不需要额外说明的。夸张一点儿说，`palindrome(1 + 1)`，我们需要提示左边会显示 `2` 而不会显示 `1 + 1` 么？

**Comment by siyukok** [comment]
嗯,多谢回复,,想想您说的确实有道理,可能是我想多了
ps:comment里带上0_0 (: /-\ :) 0-0这个,迷之有点萌,哈哈
