### ISSUE TITLE
140 Create Decimal Numbers with JavaScript 发现错别字

### ISSUE THREAD

**Issue by iDevOrz** [FreeCodeCampChina/freecodecamp.cn#442]
#### 浏览器信息
* 浏览器名称，版本号
* 操作系统

#### 问题描述
任务
创建一个变量 myDecimal 并给它复制一个浮点数。 (e.g. 5.7)。

"复制"应为 "赋值"；

#### 你的代码

```
如果和代码相关，请在这里粘贴你的全部代码
```

**Comment by wudifeixue** [comment]
谢谢你提交的issue，不过这个问题已经在 #379 处理了，只是现在服务器依旧在等待更新。

**Comment by LemuelAB** [comment]
您好，您的邮件我已收到，非常感谢
