### ISSUE TITLE
查不出来

### ISSUE THREAD

**Issue by zjsuncheng** [FreeCodeCampChina/freecodecamp.cn#443]
Challenge [Concatenating Strings with the Plus Equals Operator](https://freecodecamp.cn/challenges/concatenating-strings-with-the-plus-equals-operator#?solution=%2F%2F%20%E4%B8%BE%E4%BE%8B%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%3B%0AourStr%20%2B%3D%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20%E8%AF%B7%E5%8F%AA%E4%BF%AE%E6%94%B9%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8B%E7%9A%84%E4%BB%A3%E7%A0%81%0A%0Avar%20myStr%20%3D%20%22This%20is%20the%20first%20sentense.%20%22%3B%0AmyStr%20%2B%3D%22This%20is%20the%20second%20sentense.%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// 举例
var ourStr = "I come first. ";
ourStr += "I come second.";

// 请只修改这条注释以下的代码

var myStr = "This is the first sentense. ";
myStr +="This is the second sentense.";

![1512826003 1](https://user-images.githubusercontent.com/34265879/33796039-c7895a7a-dd27-11e7-90fd-c8780f197d66.jpg)



```

**Comment by wudifeixue** [comment]
注意你的拼写，原要求是```"This is the first sentence. "```   
你把sentence拼错成sentense了。
