### ISSUE TITLE
the chk  of  307th   is wrong

### ISSUE THREAD

**Issue by Zalezale** [FreeCodeCampChina/freecodecamp.cn#444]
#### 浏览器信息
* 浏览器名称，版本号
* 操作系统

#### 问题描述
* 问题是在什么时候，什么情况下遇到的
* 简要说明如何重现

#### 你的代码

```
function checkCashRegister(price, cash, cid) {
  var change = [];
  change.push(cash - price)
  var handrud = getUnitNum(change, 100, cid[8][1]);
  var twenty = getUnitNum(handrud, 20, cid[7][1]);
  var ten = getUnitNum(twenty, 10, cid[6][1]);
  var five = getUnitNum(ten, 5, cid[5][1]);
  var one = getUnitNum(five, 1, cid[4][1]);
  var quarter = getUnitNum(one, 0.25, cid[3][1]);
  var dime = getUnitNum(quarter, 0.1, cid[2][1]);
  var nickel = getUnitNum(dime, 0.05, cid[1][1]);
  var penny = getUnitNum(nickel, 0.01, cid[0][1]);
  if(penny[0] == 'Closed') {
    return 'Closed';
  }
  if(penny[1] > cid[0][1]) {
    return 'Insufficient Funds';
  }
  return change;
}

function getUnitNum(change, unit, max) {
  if(change[0] == 'Closed') {
    return ['Closed']
  }
  var len = Math.round(max / unit);
  unit = unit * 100;
  change[0] = change[0] * 100;
  for(var i = 1; i <= len; i++) {
    if(change[0] - unit < 0) {
      --i;
      break;
    }
    if(change[0] - unit == 0) {
      return ['Closed'];
    }
    change[0] = change[0] - unit;
  }
  return [change[0] / 100, i];
}
```

**Comment by S1ngS1ng** [comment]
@Zalezale 
全局变量会有影响。不太确定全局函数会不会有影响，但你最好把自己定义的函数也放到里面去。

但你的代码本身逻辑上是有问题的，所以放到里面也不会 work。

举个例子：
传入这一组数据：`checkCashRegister(19.50, 20.00, [["PENNY", 1.01], ["NICKEL", 2.05], ["DIME", 3.10], ["QUARTER", 4.25], ["ONE", 90.00], ["FIVE", 55.00], ["TEN", 20.00], ["TWENTY", 60.00], ["ONE HUNDRED", 100.00]])`。

这表示需要找零 `20 - 19.50 = 0.50`，而且零钱柜中 Quarter 总共有 `4.25`，即总共有 `4.25 / 0.25 = 17` 个 Quarter。而找零 `0.50` 需要两个 Quarter。因此这时候应该返回 `[["QUARTER", 0.50]]`，而你的代码返回的是 `"Closed"`，显然是不对的。

断点打在这里：
![image](https://user-images.githubusercontent.com/13592559/34312679-e564c3b6-e733-11e7-9441-317035d05ead.png)

逻辑问题出现在你的迭代过程。
第 29 行的循环，第一次执行没问题，50 和 25，经过 37 行的迭代之后剩 25。
注意图中画圈的部分。相减等于 0，会直接返回 `["Closed"]`。这时候你不应该继续迭代，因为计算找零已经完成，待找的钱已经为 0。你这时候应该做的是直接 return 需要几个 Quarters，而不是 `return ["Closed"]`:
![image](https://user-images.githubusercontent.com/13592559/34312734-44d7792e-e734-11e7-91e5-9364a981d091.png)

否则，继续进行迭代，永远都会有这个 `"Closed"`：
![image](https://user-images.githubusercontent.com/13592559/34312829-cc6dd572-e734-11e7-91f5-531f34c66846.png)

第 14 行，你判断的依据是如果第一个元素是 Closed，那就 return closed，显然是不对的。根据你在循环里的定义，这种情况是刚好可以凑完待找零钱。
