### ISSUE TITLE
有时文字光标会消失

### ISSUE THREAD

**Issue by hunmix** [FreeCodeCampChina/freecodecamp.cn#446]
#### 浏览器信息
* chrome
* windows7

#### 问题描述
* 在输入代码时经常光标会消失，文字能正常输入，但是没有光标用起来多有不便
* 比如刚才输入`class=""`打到双引号时光标消失
（因为是光标无法截图）

**Comment by wudifeixue** [comment]
确实有这个问题存在 #165，而且我们也不知道怎么处理这个情况(尴尬 ，现在只能说去[清理下缓存](https://github.com/FreeCodeCampChina/freecodecamp.cn/wiki/%E5%A6%82%E4%BD%95%E5%BC%BA%E5%88%B6%E6%B8%85%E7%A9%BA%E6%B5%8F%E8%A7%88%E5%99%A8%E7%BC%93%E5%AD%98)看看了。

**Comment by wudifeixue** [comment]
Closed as duplicate.
