### ISSUE TITLE
This is what i did

### ISSUE THREAD

**Issue by hello9307** [FreeCodeCampChina/freecodecamp.cn#451]
Challenge [Search and Replace](https://www.freecodecamp.cn/challenges/search-and-replace#?solution=function%20myReplace(str%2C%20before%2C%20after)%20%7B%0A%20%20var%20arr%20%3D%20str.split(%22%20%22)%3B%0A%20%20for(var%20i%20%3D0%3Bi%3Carr.length%3Bi%2B%2B)%7B%0A%20%20%20%20if(arr%5Bi%5D%3D%3Dbefore)%7B%0A%20%20%20%20%20%20arr%5Bi%5D%3Dafter%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20str%20%3D%20arr.join(%22%20%22)%3B%0A%20%20return%20str%3B%0A%7D%0A%0AmyReplace(%22A%20quick%20brown%20fox%20jumped%20over%20the%20lazy%20dog%22%2C%20%22jumped%22%2C%20%22leaped%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myReplace(str, before, after) {
  var arr = str.split(" ");
  for(var i =0;i<arr.length;i++){
    if(arr[i]==before){
      arr[i]=after;
    }
  }
  str = arr.join(" ");
  return str;
}

myReplace("A quick brown fox jumped over the lazy dog", "jumped", "leaped");

```

**Comment by S1ngS1ng** [comment]
@hello9307 So, what is the issue?
