### ISSUE TITLE
504 error

### ISSUE THREAD

**Issue by ghost** [FreeCodeCampChina/freecodecamp.cn#454]
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0</code>.
这个bug是：有时候我按CTRL+enter组合键想要进入下一章节的时候会出现504错误。

**Comment by ghost** [comment]
哦抱歉，我输错了，应该是504错误

**Comment by ghost** [comment]
你们的服务器为什么连接会这么慢...chrome的小圆圈转了好久还在读取和接受，打开chrome的f12发现TTFB有300ms？？？？然后，还有一个问题就是，经常ctrl+enter想进入下一题之后经常会加载的很慢很慢很慢，并且有时候会有504错误....每当这样内心就很崩溃。。我这里是江苏 电信200兆的网，为什么会这样。。。还有在学校 也是江苏，也是电信的网，也是会出现504错误，dns解析都为8.8.8.8和8.8.4.4。

**Comment by wudifeixue** [comment]
Duplicate as #499 
我看你发了三遍呀，这个问题还是老情况，运营那边服务器选的不够好。。我这边比较无能为力。
