### ISSUE TITLE
为什么判定我<style>里面没有包含一个将color设置为pink的pink-text CSS class？

### ISSUE THREAD

**Issue by Jeonxin** [FreeCodeCampChina/freecodecamp.cn#46]
Challenge [Prioritize One Style Over Another](http://www.w3cschool.cn/codecamp/prioritize-one-style-over-another.html#?solution=%3Cstyle%3E%0Abody%20%7B%0Abackground-color%3A%20black%3B%0Afont-family%3A%20Monospace%3B%0Acolor%3A%20green%3B%0A%7D%0A.pink-text%7Bcolor%3Apink%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
body {
background-color: black;
font-family: Monospace;
color: green;
}
.pink-text{color:pink}
</style>
<h1 class="pink-text">Hello World!</h1>
√ 你的 h1 元素应该包含名为 pink-text 的 class。
× 你的 <style> 包含一个将 color 设置为 pink 的 pink-text CSS class。
√ 你的 h1 元素应该为粉色
请问挑战过关的时候我的第二条不满足？
```

**Comment by Jeonxin** [comment]
在线等，谢谢，一直无法过关！！我觉得没有错啊，是系统后台设置的判定规则错误吗？

**Comment by lasake** [comment]
系统bug吧，我在pink后面加个了';'，就可以过关了

**Comment by Jeonxin** [comment]
哦，我试试

**Comment by Jeonxin** [comment]
是的，必须要加；，但是我开始加了也无法过关啊！0- 0难道是我的网速出了问题！哈哈，谢谢，我重新更正过了。

**Comment by ttyhtg** [comment]
我刚才也卡在这里了，加了个“;”

**Comment by onloner2012** [comment]
我是没有写成.pink-text
