### ISSUE TITLE
Why it's not work

### ISSUE THREAD

**Issue by KritoYui** [FreeCodeCampChina/freecodecamp.cn#465]
Challenge [Inform with the Paragraph Element](https://www.freecodecamp.cn/challenges/inform-with-the-paragraph-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello World</h1>
<h2>我家的猫咪</h2>
<h3>Hello paragraph</h3>
```

**Comment by S1ngS1ng** [comment]
@KritoYui 请仔细看题目要求
