### ISSUE TITLE
How can I pass this lesson?

### ISSUE THREAD

**Issue by Tj1364646663** [FreeCodeCampChina/freecodecamp.cn#467]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.cn/challenges/escaping-literal-quotes-in-strings#?solution=var%20myStr%3D%22I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22%22%3B%20%2F%2F%20%E8%AF%B7%E4%BF%AE%E6%94%B9%E8%BF%99%E4%B8%80%E8%A1%8C%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr="I am a \"double quoted\" string inside \"double quotes\""; // 请修改这一行



```

**Comment by Wanlin-Lu** [comment]
I tried, and your code works.
![fjq9 0deirya1044f cu5u](https://user-images.githubusercontent.com/26218101/35737877-fbcf14b2-0867-11e8-9378-20ca4c0613a8.png)

**Comment by S1ngS1ng** [comment]
@Tj1364646663 Your code works
