### ISSUE TITLE
在arr为empty时，item要么为undefined要么显示为空白，为何为传入的参数值，这符合队列规则吗

### ISSUE THREAD

**Issue by zh1281221520** [FreeCodeCampChina/freecodecamp.cn#469]
Challenge [Stand in Line](https://freecodecamp.cn/challenges/stand-in-line#?solution=function%20queue(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E9%87%8C%0A%20console.log(item)%3B%0A%20%20arr.push(item)%3B%0A%20%20console.log(arr.length)%3B%0A%20%20console.log(item)%3B%0A%20%20item%3Darr.shift()%3B%0A%20%20console.log(item)%3B%0A%20%20%20%2F*%0A%20%20var%20temp%3B%0A%20%20temp%3Ditem%3B%0A%20%20console.log(temp)%3B%0A%20%20temp%3Darr%5B0%5D%3B%0A%20%20console.log(temp)%3B%0A%20%20arr%5Barr.length%5D%3Ditem%3B%0A%20%20item%3Dtemp%3B%0A%20%20arr.shift()%3B%0A%20%20*%2F%0A%20%20return%20item%3B%20%20%2F%2F%20%E8%AF%B7%E4%BF%AE%E6%94%B9%E8%BF%99%E4%B8%80%E8%A1%8C%0A%7D%0A%0A%2F%2F%20%E5%88%9D%E5%A7%8B%E5%8C%96%E6%B5%8B%E8%AF%95%E6%95%B0%E6%8D%AE%0Avar%20testArr%20%3D%20%5B%5D%3B%0A%0A%2F%2F%20%E6%8E%A7%E5%88%B6%E5%8F%B0%E8%BE%93%E5%87%BA%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(queue(testArr%2C%202))%3B%20%2F%2F%20%E4%BD%A0%E5%8F%AF%E4%BB%A5%E4%BF%AE%E6%94%B9%E8%BF%99%E4%B8%80%E8%A1%8C%E6%9D%A5%E6%B5%8B%E8%AF%95%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function queue(arr, item) {
  // 请把你的代码写在这里
 console.log(item);//item为2
  arr.push(item);
  console.log(arr);//这个时候arr显示为“  ”，为何不是[2]
  console.log(item);//item为2
  item=arr.shift();
  console.log(item);//item还为2，为何不是空
  
  return item;  // 请修改这一行
}

// 初始化测试数据
var testArr = [];

// 控制台输出
console.log("Before: " + JSON.stringify(testArr));
console.log(queue(testArr, 2)); // 你可以修改这一行来测试你的代码
console.log("After: " + JSON.stringify(testArr));

```

**Comment by S1ngS1ng** [comment]
@zh1281221520 这道题目是没有问题的。一行一行来解释你的问题。请看底下星号的部分。
首先明确一下，你调用的方式是 `queue([], 2)`。其中，`arr` 是 `[]`，`item` 是 2
```js
function queue(arr, item) {
  // 请把你的代码写在这里
  console.log(item);   //item为2    -- **当然**
  arr.push(item);
  console.log(arr);     //这个时候arr显示为“  ”，为何不是[2]    -- **不会的，我这里显示的是 [2]**
  console.log(item);  //item为2    -- **当然**
  item=arr.shift();
  console.log(item);//item还为2，为何不是空    -- **当然是 2 。请先去了解一下 shift 方法的返回值是什么**
  
  return item;  // 请修改这一行
}
```

这是我尝试的代码：
![image](https://user-images.githubusercontent.com/13592559/36066189-d7b62b4e-0e73-11e8-90c8-76124cae1f4c.png)
以及输出：
![image](https://user-images.githubusercontent.com/13592559/36066194-e653f2e4-0e73-11e8-9572-df509e1fb19a.png)

注意在 `---arr` 底下有一个输出 `2`，那个来自于 `console.log(queue(testArr, 2));`

如果还有问题，回复我就好
