### ISSUE TITLE
pop()与shift()介绍是不是写反了

### ISSUE THREAD

**Issue by seryte** [FreeCodeCampChina/freecodecamp.cn#47]
**shift()并不是移除数组第一个元素，而是保留第一个元素，移除其余的！
pop()则与shift()相反**
![image](https://cloud.githubusercontent.com/assets/17977783/20090373/b69aa450-a5c7-11e6-81f5-032d22debf57.png)

**Comment by seryte** [comment]
```
好像是我弄错了，它这个是先删除，然后再把删除的返回
```

**Comment by huluoyang** [comment]
@cydib [shift]是键盘上的常用键，跑跑卡丁车游戏中漂移必须用到此键。
原因就是[shift]本身就有漂移、移出的意思，而[pop]是抛出的意思。
一个从头部移除元素，一个从尾部移除元素。
