### ISSUE TITLE
“Build a Personal Portfolio Webpage”  这个挑战的项目给的页面“https://codepen.io/freeCodeCamp/full/YqLyXB/”加载不出图片，因为该页面使用的图片链接为HTTP链接，所以图片会加载失败，我已经Fork了这个页面，并且将此页面所有HTTP链接图片替换为digitalocean的镜像存储的HTTPS图片

### ISSUE THREAD

**Issue by ghost** [FreeCodeCampChina/freecodecamp.cn#471]
“Build a Personal Portfolio Webpage”  这个挑战的项目给的页面https://codepen.io/freeCodeCamp/full/YqLyXB/   
加载不出图片，因为该页面使用的图片链接为HTTP链接，所以图片会加载失败，我已经Fork了这个页面，并且将此页面所有HTTP链接图片替换为digitalocean的镜像存储的HTTPS图片。
地址为：
https://codepen.io/Madman7/full/yvgWEE

Challenge [Build a Personal Portfolio Webpage](https://freecodecamp.cn/challenges/build-a-personal-portfolio-webpage) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by S1ngS1ng** [comment]
@RivenNero 我这儿显示没问题

![image](https://user-images.githubusercontent.com/13592559/36036298-867c5c72-0d87-11e8-9655-475d83349cdc.png)

**Comment by ghost** [comment]
![tim 20180210100740](https://user-images.githubusercontent.com/35187885/36057536-436bcb16-0e4a-11e8-996e-b018df142f55.jpg)

**Comment by ghost** [comment]
我这里 chrome版本是 64.0.3282.140（正式版本） （64 位）  江苏苏州电信  DNS 为 8.8.8.8和8.8.4.4
后台挂着S,,S,,,R pac代理 ，没有将codepan放入pac代理名单。

**Comment by ghost** [comment]
@S1ngS1ng 我这儿显示有问题。
我这里 chrome版本是 64.0.3282.140（正式版本） （64 位） 江苏苏州电信 DNS 为 8.8.8.8和8.8.4.4
后台挂着S,,S,,,R pac代理 ，没有将codepan放入pac代理名单。

**Comment by ghost** [comment]
s,,,s,r  开了全局还是加载不出来图片

**Comment by wudifeixue** [comment]
我这边也是没有问题的呀

**Comment by ghost** [comment]
@wudifeixue ....为什么只有我显示不出。。。。都已经恢复过网络初始设置了，系统用的是
https://www.microsoft.com/zh-cn/software-download/windows10
微软官网下的系统，用kmspico激活的，然后杀软用的是系统自带WD+火绒。浏览器是chrome64.0.3282.140（正式版本） （64 位），江苏苏州电信，DNS为8.8.8.8  8.8.4.4   后台有SSR代理 pac模式，全局也是加载不出。我自己替换成https的图片可以加载的出。

**Comment by S1ngS1ng** [comment]
@RivenNero 看下 chrome://settings/content 这里，image 的 Show All 有没有打开。
如果已经打开了，多半是 DNS 的问题了

**Comment by ghost** [comment]
好的  我看一下 谢谢

**Comment by ghost** [comment]
@S1ngS1ng 我找到原因了，不是DNS问题，是chrome中我启用的一个插件，叫Ghostery – Privacy Ad Blocker，会屏蔽跟踪器、广告等等很多不安全的因素，然后就会导致HTTP协议的图片加载不出来。现在我信任了这个网站，就可以加载了。谢谢啦。
