### ISSUE TITLE
I don't know how

### ISSUE THREAD

**Issue by alwaysJim** [FreeCodeCampChina/freecodecamp.cn#472]
Challenge [Fill in the Blank with Placeholder Text](https://freecodecamp.cn/challenges/fill-in-the-blank-with-placeholder-text#?solution=%3Ch1%3E%E8%A5%BF%E6%B8%B8%E8%AE%B0%3C%2Fh1%3E%0A%0A%3Ch2%3E%E9%BD%90%E5%A4%A9%E5%A4%A7%E5%9C%A3%3C%2Fh2%3E%0A%0A%3Ch2%3E%E5%AD%99%E6%82%9F%E7%A9%BA%3C%2Fh2%3E%0A%0A%3Cp%3EMonky%20code%20%E7%8C%B4%E5%93%A5%E7%8C%B4%E5%93%A5%EF%BC%8C%E4%BD%A0%E7%9C%9F%E4%BA%86%E4%B8%8D%E5%BE%97%EF%BC%8C%E9%87%91%E7%AE%8D%E6%A3%92%E5%9C%A8%E6%89%8B%EF%BC%8C%E9%97%AE%E4%B8%96%E9%97%B4%E8%B0%81%E6%98%AF%E8%8B%B1%E9%9B%84%E3%80%82%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>西游记</h1>

<h2>齐天大圣</h2>

<h2>孙悟空</h2>

<p>Monky code 猴哥猴哥，你真了不得，金箍棒在手，问世间谁是英雄。</p>

```

**Comment by S1ngS1ng** [comment]
Monkey 拼写错误
