### ISSUE TITLE
哪里出错了，，，想不通，能不能告诉我怎么改

### ISSUE THREAD

**Issue by hexiaoneuq** [FreeCodeCampChina/freecodecamp.cn#474]
Challenge [Style the HTML Body Element](https://www.freecodecamp.cn/challenges/style-the-html-body-element#?solution=%3Cstyle%3E%0A%20%20body%7B%0A%20%20%20%20back%0A%20%20%7D%0A%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body{
    background-color:black;
  }
</style>

```

**Comment by Wanlin-Lu** [comment]
```html
<style>
  body{
    background-color:black;
  }
</style>
```
你的分号看起来是中文的哦！

**Comment by S1ngS1ng** [comment]
@hexiaoneuq 你的链接给出的是这样的代码。
![image](https://user-images.githubusercontent.com/13592559/36651903-4efde2d0-1a79-11e8-9ca6-1f6e87a0b373.png)

上面你贴的那段就没问题。Reset 一下重新提交
