### ISSUE TITLE
’Show the Local Weather‘ 该挑战的样例已过期

### ISSUE THREAD

**Issue by chrysophoron** [FreeCodeCampChina/freecodecamp.cn#475]
Challenge [Show the Local Weather](https://www.freecodecamp.cn/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

https://codepen.io/huluoyang/full/bedeBR
这是该挑战的样例，没有任何数据被显示

**Comment by S1ngS1ng** [comment]
@chrysophoron 谢谢。请参考：#336 
~~不过这里面用的那个 cors 有点儿问题。我今晚更新一下。~~
已测试。没有问题

**Comment by Eunknight** [comment]
@S1ngS1ng #336 失效了...

挑战地址:
Show the Local Weather | FreeCodeCamp中文社区 https://www.freecodecamp.cn/challenges/show-the-local-weather

#336 参考项目地址:
CodePen - freeCodeCamp: Show the Local Weather https://codepen.io/S1ngS1ng/full/WORqxP

挑战地址参考项目地址:
CodePen - fcc-weather https://codepen.io/huluoyang/full/bedeBR

**Comment by S1ngS1ng** [comment]
@Eunknight 我这儿看着没问题的
![image](https://user-images.githubusercontent.com/13592559/38373989-97d60cb6-38c0-11e8-9c5b-2f2c18163d1d.png)

**Comment by Eunknight** [comment]
@S1ngS1ng ok  可能是api每日限额了...
