### ISSUE TITLE
是不是例子翻译错了？

### ISSUE THREAD

**Issue by mingsky1987** [FreeCodeCampChina/freecodecamp.cn#477]
#### 浏览器信息
* 浏览器名称chrome，版本号
* 操作系统win7

#### 问题描述
![image](https://user-images.githubusercontent.com/9895854/36881093-50d53a18-1e07-11e8-9703-bdc93b23adf8.png)
我按照图中的例子，写了下面的代码，但是有语法错误

#### 你的代码
var oldArray = [1,2,3,4,5];

// 只能在这一行下面写代码

var newArray = oldArray.map(fuction(val){
                            return val+3;
                            });

**Comment by S1ngS1ng** [comment]
@mingsky1987  你的 function 拼错了
