### ISSUE TITLE
所有条件都符合还是没法通过

### ISSUE THREAD

**Issue by dan506** [FreeCodeCampChina/freecodecamp.cn#488]
Challenge [Symmetric Difference](https://www.freecodecamp.cn/challenges/symmetric-difference#?solution=function%20sym(args)%20%7B%0A%20%20var%20arr1%3D%5B%5D%3B%0A%20%20var%20n%3D0%3B%0A%20%20args%3D%5B%5D%3B%0A%20%20for(var%20i%3D0%3Bi%3Carguments.length%3Bi%2B%2B)%7B%0A%20%20%20%20arr1%3Darguments%5Bi%5D%3B%0A%20%20%20%20for(var%20j%3D0%3Bj%3Cargs.length%3Bj%2B%2B)%7B%0A%20%20%20%20%20%20n%3Darr1.length%3B%0A%20%20%20%20%20%20for(var%20k%3D0%3Bk%3Carr1.length%3Bk%2B%2B)%7B%0A%20%20%20%20%20%20%20%20if(args%5Bj%5D%3D%3Darr1%5Bk%5D)%7B%0A%20%20%20%20%20%20%20%20%20%20arr1.splice(k--%2C1)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20if(n%3Earr1.length)%7B%0A%20%20%20%20%20%20%20%20args.splice(j--%2C1)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%20%20%20%0A%20%20%20%20args%3Dargs.concat(arr1)%3B%20%20%20%20%0A%20%20%7D%20%20%20%0A%20%20args%3Dargs.reduce(function(a%2C%20b)%7B%0A%20%20%20%20if(a.length%3D%3D%3D0%20%7C%7C%20a%5Ba.length-1%5D!%3D%3Db)%7B%0A%20%20%20%20%20%20%20%20a.push(b)%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20a%3B%0A%20%20%20%20%7D%2C%20%5B%5D)%3B%0A%20%20return%20args.sort()%3B%0A%7D%0A%0Asym(%5B3%2C%203%2C%203%2C%202%2C%205%5D%2C%20%5B2%2C%201%2C%205%2C%207%5D%2C%20%5B3%2C%204%2C%206%2C%206%5D%2C%20%5B1%2C%202%2C%203%5D%2C%20%5B5%2C%203%2C%209%2C%208%5D%2C%20%5B1%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function sym(args) {
  var arr1=[];
  var n=0;
  args=[];
  for(var i=0;i<arguments.length;i++){
    arr1=arguments[i];
    for(var j=0;j<args.length;j++){
      n=arr1.length;
      for(var k=0;k<arr1.length;k++){
        if(args[j]==arr1[k]){
          arr1.splice(k--,1);
        }
      }
      if(n>arr1.length){
        args.splice(j--,1);
      }
    }   
    args=args.concat(arr1);    
  }   
  args=args.reduce(function(a, b){
    if(a.length===0 || a[a.length-1]!==b){
        a.push(b);
    }
    return a;
    }, []);
  return args.sort();
}

sym([3, 3, 3, 2, 5], [2, 1, 5, 7], [3, 4, 6, 6], [1, 2, 3], [5, 3, 9, 8], [1]);

```

**Comment by S1ngS1ng** [comment]
@danger0258 你的代码输出本身是错的，请放到 Console 里跑一下试试。比如：
![image](https://user-images.githubusercontent.com/13592559/38268433-16b645bc-374c-11e8-8b64-6fd81b91b528.png)

后续的逻辑我还没看，但至少，你的代码中第三行 `args=[];` 会造成问题，不同运行环境/引擎下对这个的解析是有区别的。测试环境中认为你创建了一个新的变量。
但在 Chrome （V8 引擎）中，由于 `sym` 函数的参数也叫 `args`，因此会认为你给传入的第一个参数重新赋值为空。

暂且不说哪个环境有问题，这样写肯定是不好的。考虑 `var` 新建一个不重名的变量吧

**Comment by dan506** [comment]
谢谢，输出是没问题的，昨天跑了好多次，输出都是和题目要求一样，然后看了您的建议，我把第三行 args=[]删掉就通过了，循环换成了从arguments的第二个变量开始




------------------ 原始邮件 ------------------
发件人: "Xing Liu"<notifications@github.com>;
发送时间: 2018年4月4日(星期三) 凌晨2:40
收件人: "FreeCodeCampChina/freecodecamp.cn"<freecodecamp.cn@noreply.github.com>;
抄送: "梦回还"<1178975467@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [FreeCodeCampChina/freecodecamp.cn] 所有条件都符合还是没法通过 (#488)




@danger0258 你的代码输出本身是错的，请放到 Console 里跑一下试试。比如：
 
 
后续的逻辑我还没看，但至少，你的代码中第三行 args=[]; 会造成问题，不同运行环境/引擎下对这个的解析是有区别的。测试环境中认为你创建了一个新的变量。
 但在 Chrome （V8 引擎）中，由于 sym 函数的参数也叫 args，因此会认为你给传入的第一个参数重新赋值为空。
 
暂且不说哪个环境有问题，这样写肯定是不好的。考虑 var 新建一个不重名的变量吧
