### ISSUE TITLE
nesting for loop

### ISSUE THREAD

**Issue by leedonsn** [FreeCodeCampChina/freecodecamp.cn#49]
When I study the 'nesting for loop' chapter, I wrote my code and clicked submit, and there exist some problem so do not print the result, and give the advise that add //no protect.

Now I could not open that page.

**Comment by juneybw** [comment]
SAME PROBLEM ,DID U SOLVE ? I THINK WE WRITE A INFINITE LOOP CRASH THE EVN

**Comment by juneybw** [comment]
I solve the problem,change your broswer,login and the code area is reset.i think code stored in broswer's cache or sth .

**Comment by leedonsn** [comment]
I solve the prob by your solution too, thanks @juneybw
