### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by ghost** [FreeCodeCampChina/freecodecamp.cn#499]
#### 浏览器信息
Win10 x64 1803 
Chrome:Chrome版本 66.0.3359.139（正式版本） 

#### 问题描述
经常会时不时的有504Gateway错误.
#### 截图（如果有）
![504](https://user-images.githubusercontent.com/35187885/39577529-2be6ebd2-4f14-11e8-89f2-058cb7251a26.png)

**Comment by wudifeixue** [comment]
很遗憾这个问题是服务器撑不住的情况，只能等主要组织升级服务器了

**Comment by Becavalier** [comment]
@RivenNero We have updated the server configuration to serve the static files directly by Nginx, so the issue should have been fixed at this time, please try again later. Feel free to ask us if you already have the same issue, thanks!
