### ISSUE TITLE
怎么过不去啊0..

### ISSUE THREAD

**Issue by chennqqi** [FreeCodeCampChina/freecodecamp.cn#5]
Challenge [Local Scope and Functions](https://freecodecamp.cn/challenges/local-scope-and-functions#?solution=function%20myFunction%28%29%20%7B%0A%20%20var%20myVar%20%3D%20'use%20strict'%3B%0A%20%20%0A%20%0A%20%20console.log%28myVar%29%3B%0A%7D%0AmyFunction%28%29%3B%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0A%0A%2F%2F%20now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function myFunction() {
  var myVar = 'use strict';


  console.log(myVar);
}
myFunction();
// run and check the console 
// myVar is not defined outside of myFunction

// now remove the console log line to pass the test


```

**Comment by huluoyang** [comment]
代码是正确的，点击reset 重置下，然后重新输入即可。

**Comment by chennqqi** [comment]
重新打开就OK了.................
