### ISSUE TITLE
页面的测试中有一条应该显示为false的，虽然能正常通过挑战

### ISSUE THREAD

**Issue by LvShCh** [FreeCodeCampChina/freecodecamp.cn#50]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/chinese

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

#### Screenshot
https://freecodecamp.cn/challenges/confirm-the-ending

**Comment by discountry** [comment]
请详细说明，并附上代码
Please add your code and more details

**Comment by LvShCh** [comment]
在confirm the ending 这个挑战中，有一个测试用例是confirmEnding("He has to give me a new name", "me") 应该返回 true. 这里应该是返回false，虽然在页面提交的时候验证为正确。

------------------ 原始邮件 ------------------
发件人: "Disney";notifications@github.com;
发送时间: 2016年11月12日(星期六) 下午2:02
收件人: "FreeCodeCampChina/freecodecamp.cn"freecodecamp.cn@noreply.github.com; 
抄送: "Mr_根号3"975795609@qq.com; "Author"author@noreply.github.com; 
主题: Re: [FreeCodeCampChina/freecodecamp.cn] 页面的测试中有一条应该显示为false的，虽然能正常通过挑战 (#50)

请详细说明，并附上代码

**Comment by zeallean** [comment]
@LvShCh 应该是你会错了题目意思。`confirmEnding("He has to give me a new name", "me")`  这个返回值应该就是true。测试用例没有错。
下面是参考代码？可以通过全部的测试用例。

```
function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  if (target.length > str.length) return false;
  return str.substr(0-target.length) == target;
}

confirmEnding("Bastian", "tan");
```

**Comment by TheFlashinchina** [comment]
function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  var contant = str.substr(str.length-target.length);
  var result = contant == target;
  return result;
}

confirmEnding("hu", "hu ming");

我觉得这样做是比较好理解的做法了

**Comment by S1ngS1ng** [comment]
@TheFlashinchina 为啥不直接 `return str.substr(str.length - target.length) === target`。。。
另外，也可以 `return str.slice(-target.length) === target`。`slice` 支持负向索引。从结尾开始找

**Comment by slowlearnerLspeedup** [comment]
我的，刚开始的方案虽然不简洁，但更容易被初学者理解：
方案一：
function confirmEnding(str, target) {
  for(var i=1;i<=str.length;i++){
  if(str.substr(-i,i)===target){
    return true;
  } 
  }
  return false;
}
confirmEnding("Bastian", "n");
然而，前面FCC的课程表明，其实比较运算符已经自带了true or false属性，所以为什么不利用好这点呢：
方案二：
function confirmEnding(str, target) {
  return str.substr(-target.length,target.length)===target;
}
confirmEnding("Bastian", "n");

关键是只要确定好如何表述末尾的字符串字符就好。

**Comment by S1ngS1ng** [comment]
@Rodney2012 个人觉得，如果决定遍历，就不需要再用字符串方法了，用 index 直接获取可能会更容易理解。因为讲道理，如果用了字符串方法，那就没必要遍历了。

这道题用 `substr` 虽然可以实现，但会比较麻烦。建议去了解下 `slice` 方法。`return str.slice(-target.length) === target`

**Comment by asqhay** [comment]
用ES6就一句话，，

**Comment by asqhay** [comment]
return str.endsWith(target);
