### ISSUE TITLE
cant submit

### ISSUE THREAD

**Issue by hejunyi123** [FreeCodeCampChina/freecodecamp.cn#500]
Challenge [Generate Random Fractions with JavaScript](https://www.freecodecamp.cn/challenges/generate-random-fractions-with-javascript#?solution=function%20myFunction()%20%7B%0A%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8B%0A%0A%20%20return%200%3B%0A%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8A%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {

  // 请把你的代码写在这条注释以下

  return Math.random();

  // 请把你的代码写在这条注释以上
}

```

**Comment by S1ngS1ng** [comment]
@hejunyi123 Looks fine. Refresh and give it another shot please

**Comment by hejunyi123** [comment]
the problem has been solved thanks for  your advice
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Xing Liu"<notifications@github.com>;
 发送时间: 2018年5月10日(星期四) 上午8:54
 收件人: "FreeCodeCampChina/freecodecamp.cn"<freecodecamp.cn@noreply.github.com>;
 抄送: "435592760"<435592760@qq.com>; "Mention"<mention@noreply.github.com>; 
 主题: Re: [FreeCodeCampChina/freecodecamp.cn] cant submit (#500)

 

 
@hejunyi123 Looks fine. Refresh and give that another shot please
