### ISSUE TITLE
这题最下面的要求里的翻译是否有些欠妥

### ISSUE THREAD

**Issue by Wood-Cube** [FreeCodeCampChina/freecodecamp.cn#501]
Challenge [Word Blanks](https://www.freecodecamp.cn/challenges/word-blanks#?solution=function%20wordBlanks(myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8B%0A%20%0Aresult%3D%22That%20%22%2B%20myAdjective%20%2B%20%22brown%20%22%20%2BmyNoun%2B%20%22just%20%22%2B%20myVerb%20%2B%20myAdverb%3B%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8A%0A%20%20return%20result%3B%0A%7D%0A%0AwordBlanks(%22dog%20%22%2C%20%22big%20%22%2C%20%22ran%20%22%2C%20%22quickly%20%22)%3B%20%20%2F%2F%20%E4%BD%A0%E5%8F%AF%E4%BB%A5%E4%BF%AE%E6%94%B9%E8%BF%99%E4%B8%80%E8%A1%8C%E6%9D%A5%E6%B5%8B%E8%AF%95%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // 请把你的代码写在这条注释以下
 
result="That "+ myAdjective + "brown " +myNoun+ "just "+ myVerb + myAdverb;
  // 请把你的代码写在这条注释以上
  return result;
}

wordBlanks("dog ", "big ", "ran ", "quickly ");  // 你可以修改这一行来测试你的代码

```
英文网页里的  wordBlanks("dog", "big", "ran", "quickly") **_should contain all of the passed in words separated by non-word characters_** (and any additional words in your madlib).
咱们中文版翻译是    wordBlanks("dog", "big", "ran", "quickly") **_应该包含所有传入的单词并且单词之间要有间隔_**(可以添加任意修饰的单词).
是否可以翻译成类似于 **_应该包含所有传入的单词并且单词之间被 非字词字符（英语渣non-word characters不知道怎么翻译，百度non-word有个例句正好有这个词组）所分隔_**  更贴切一些？
没看英文网页之前做出的答案如上，最后得到的结果在外观上看跟正确答案差不多但是一直不过，或者说是这个答案表面上看着差不多但是实际上没有理解题目的本意，谢谢。

**Comment by S1ngS1ng** [comment]
@Wood-Cube 个人觉得，其实 `non-word characters` 在中文里很难找到对应的描述。

英文单词 (word) 由字母构成，而字母和符号同属于字符 (character)。

而对于计算机来说，一个中文字就是一个字符 (全角)，同样，标点符号也是一个字符 (全角)。由于中文任何元素都是 character，所以根本不存在 `non-word characters`。

其实 “非字词字符” 意思上确实说得过去，但个人觉得这也不是很贴切的描述。但如果说成 “标点符号” 可能更好些？或者我觉得，不如我们干脆指明 “空格” 好了。

至于你上面写的代码，`myVerb + myAdverb` 显然这里没有满足 `单词之间要有间隔`。`myAdjective + "brown "` 这里也是一样

“添加修饰词” 是补充说明，就算你添加了，也要符合 “单词之间要有间隔” 这个条件。所以我觉得描述并没有太大的误导成分

**Comment by S1ngS1ng** [comment]
@wudifeixue Thoughts?
