### ISSUE TITLE
一直跑不过

### ISSUE THREAD

**Issue by qqxiarui** [FreeCodeCampChina/freecodecamp.cn#502]
Challenge [Golf Code](https://freecodecamp.cn/challenges/golf-code#?solution=function%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20%E8%AF%B7%E5%8F%AA%E4%BF%AE%E6%94%B9%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8B%E7%9A%84%E4%BB%A3%E7%A0%81%0A%20%20if%20(strokes%20%3D%3D%201)%20%7B%0A%20%20%20%20return%20%22Hole-in-one%22%3B%0A%20%20%7D%0A%20%20else%20if%20(strokes%20%3C%3D%20par%20-%202)%20%7B%0A%20%20%20%20return%20%22Eagle%22%3B%0A%20%20%7D%0A%20%20else%20if%20(strokes%20%3D%3D%20par%20-%201)%20%7B%0A%20%20%20%20return%20%22Birdie%22%3B%0A%20%20%7D%0A%20%20else%20if%20(strokes%20%3D%3D%20par)%20%7B%0A%20%20%20%20return%20%22Par%22%3B%0A%20%20%7D%0A%20%20else%20if%20(strokes%20%3D%3D%20par%20%2B%201)%20%7B%0A%20%20%20%20return%20%22Bogey%22%3B%0A%20%20%7D%0A%20%20else%20if%20(strokes%20%3D%3D%20par%20%2B%202)%20%7B%0A%20%20%20%20return%20%22Double%20Bogey%22%3B%0A%20%20%7D%0A%20%20else%20if(strokes%20%3E%3D%20par%20%2B%203)%20%7B%0A%20%20%20%20return%20%22Go%20Home%22%3B%0A%20%20%7D%0A%20%20else%7B%0A%20%20%20%20return%20%22Winner%22%3B%0A%20%20%7D%0A%20%20%2F%2F%20%E8%AF%B7%E5%8F%AA%E4%BF%AE%E6%94%B9%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8A%E7%9A%84%E4%BB%A3%E7%A0%81%0A%7D%0A%0A%2F%2F%20%E4%BD%A0%E5%8F%AF%E4%BB%A5%E4%BF%AE%E6%94%B9%E8%BF%99%E4%B8%80%E8%A1%8C%E6%9D%A5%E6%B5%8B%E8%AF%95%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function golfScore(par, strokes) {
  // 请只修改这条注释以下的代码
  if (strokes == 1) {
    return "Hole-in-one";
  }
  else if (strokes <= par - 2) {
    return "Eagle";
  }
  else if (strokes == par - 1) {
    return "Birdie";
  }
  else if (strokes == par) {
    return "Par";
  }
  else if (strokes == par + 1) {
    return "Bogey";
  }
  else if (strokes == par + 2) {
    return "Double Bogey";
  }
  else if(strokes >= par + 3) {
    return "Go Home";
  }
  else{
    return "Winner";
  }
  // 请只修改这条注释以上的代码
}

// 你可以修改这一行来测试你的代码

```

**Comment by NidusP** [comment]
should be  return "Hole-in-one!"  or return "Go Home!" , you lost the "!".

**Comment by objcat** [comment]
function golfScore(par, strokes) {
  // 请只修改这条注释以下的代码
  
  if(strokes == 1) {
    return "Hole-in-one!";
  } else if(strokes == par - 1) {
    return "Birdie";
  } else if(strokes == par) {
    return 	"Par";
  } else if(strokes == par + 1) {
    return "Bogey";
  } else if(strokes == par + 2) {
    return "Double Bogey";
  } else if(strokes <= par - 2) {
    return 	"Eagle";
  } else if(strokes >= par + 3) {
    return "Go Home!";
  }
  
  // 请只修改这条注释以上的代码
}

// 你可以修改这一行来测试你的代码
golfScore(5, 4);

**Comment by dimixian** [comment]
function golfScore(par, strokes) {
  // 请只修改这条注释以下的代码
  if(strokes == 1){
    return "Hole-in-one!";
  }else if(strokes <= par -2){
    return "Eagle";
  }else if(strokes == par-1){
    return "Birdie";
  }else if(strokes == par){
    return "par";
  }else if(strokes == par+1){
    return "Bogey";
  }else if(strokes == par+2){
    return "Docuble Bogey";
  }else if(strokes >= par+3){
    return "Go Home!";
  }
  
  return "修改这里";
  // 请只修改这条注释以上的代码
}

// 你可以修改这一行来测试你的代码
golfScore(5, 4);
