### ISSUE TITLE
出现这个问题最后连个无论怎样都显示×

### ISSUE THREAD

**Issue by qingshanlantian** [FreeCodeCampChina/freecodecamp.cn#507]
Challenge [Replacing If Else Chains with Switch](https://freecodecamp.cn/challenges/replacing-if-else-chains-with-switch) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3423.2 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(val) {
  var answer = "";
  // 请只修改这条注释以下的代码
  switch (val){
    case "bob":
      answer = "Marley";
      break;
    case 42:
      answer = "The Answer";
      break;
    case 1:
      answer = "There is no #1";
      break;
    case 99:
      answer = "Missed me by this much!";
      break;
    case 7:
      answer = "Ate Nine";
      break;
    case "John":
      answer = "empty string";
      break;
    case 156:
      answer = "empty string";
      break;
    default:
      answer = "完犊子货";
  }
  // 请只修改这条注释以上的代码
  return answer;  
}

// 你可以修改这一行来测试你的代码
myTest("John");


```

**Comment by S1ngS1ng** [comment]
@qingshanlantian 
![image](https://user-images.githubusercontent.com/13592559/40083043-dd80e5b4-5847-11e8-9310-197af44af939.png)

`empty string` 的意思是 “空字符串”。。所以 `"John"` 和 `156` 应该是 `answer = ""`。。。

**Comment by Rocky1932373216** [comment]
case "John":
      answer = "";
      break;
    case 156:
      answer = "";
      break;
  }
