### ISSUE TITLE
怎么搞？undefined能输出，但是系统还是提示错误？怎么更改更好的能解决这个问题？

### ISSUE THREAD

**Issue by qingshanlantian** [FreeCodeCampChina/freecodecamp.cn#508]
Challenge [Return Early Pattern for Functions](https://freecodecamp.cn/challenges/return-early-pattern-for-functions#?solution=%2F%2F%20%E5%AE%9A%E4%B9%89%20abTest%0Afunction%20abTest(a%2C%20b)%20%7B%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8B%0A%20%20if(a%3C0%7C%7Cb%3C0)%7B%0A%20%20%20%20return%20%22undefined%22%3B%0A%20%20%7D%0A%20%20%20%20%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8A%0A%0A%20%20return%20Math.round(Math.pow(Math.sqrt(a)%20%2B%20Math.sqrt(b)%2C%202))%3B%0A%7D%0A%0A%2F%2F%20%E4%BD%A0%E5%8F%AF%E4%BB%A5%E4%BF%AE%E6%94%B9%E8%BF%99%E4%B8%80%E8%A1%8C%E6%9D%A5%E6%B5%8B%E8%AF%95%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%0AabTest(-2%2C2)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3423.2 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// 定义 abTest
function abTest(a, b) {
  // 请把你的代码写在这条注释以下
  if(a<0||b<0){
    return "undefined";
  }
    
  // 请把你的代码写在这条注释以上

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// 你可以修改这一行来测试你的代码
abTest(-2,2);

```

**Comment by S1ngS1ng** [comment]
@qingshanlantian 
![image](https://user-images.githubusercontent.com/13592559/40135387-163e8f5c-58fa-11e8-843e-485e62438f71.png)

**Comment by JAVA-WO** [comment]
直接返回值就可以了，undefined是空值的意思，就是什么都没有

**Comment by zanwei** [comment]
> Challenge [Return Early Pattern for Functions](https://freecodecamp.cn/challenges/return-early-pattern-for-functions#?solution=%2F%2F%20%E5%AE%9A%E4%B9%89%20abTest%0Afunction%20abTest(a%2C%20b)%20%7B%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8B%0A%20%20if(a%3C0%7C%7Cb%3C0)%7B%0A%20%20%20%20return%20%22undefined%22%3B%0A%20%20%7D%0A%20%20%20%20%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8A%0A%0A%20%20return%20Math.round(Math.pow(Math.sqrt(a)%20%2B%20Math.sqrt(b)%2C%202))%3B%0A%7D%0A%0A%2F%2F%20%E4%BD%A0%E5%8F%AF%E4%BB%A5%E4%BF%AE%E6%94%B9%E8%BF%99%E4%B8%80%E8%A1%8C%E6%9D%A5%E6%B5%8B%E8%AF%95%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%0AabTest(-2%2C2)%3B%0A) has an issue.
> User Agent is: `Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3423.2 Safari/537.36`.
> Please describe how to reproduce this issue, and include links to screenshots if possible.
> 
> My code:
> 
> ```js
> // 定义 abTest
> function abTest(a, b) {
>   // 请把你的代码写在这条注释以下
>   if(a<0||b<0){
>     return "undefined";
>   }
>     
>   // 请把你的代码写在这条注释以上
> 
>   return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
> }
> 
> // 你可以修改这一行来测试你的代码
> abTest(-2,2);
> ```

// 定义 abTest
function abTest(a, b) {
  // 请把你的代码写在这条注释以下
  if (a < 0 || b < 0) {
    return undefined;
  } else {
    return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
  }
  
  // 请把你的代码写在这条注释以上

  
}

// 你可以修改这一行来测试你的代码
abTest(2,-2);
