### ISSUE TITLE
条件使用 12==var 也是对的，但是无法通过测试。

### ISSUE THREAD

**Issue by stk-tianwen** [FreeCodeCampChina/freecodecamp.cn#51]
Challenge [Comparison with the Equality Operator](https://www.freecodecamp.cn/challenges/comparison-with-the-equality-operator#?solution=%2F%2F%20Setup%0Afunction%20myTest(val)%20%7B%0A%20%20if%20(val%3D%3D12)%20%7B%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%22Equal%22%3B%0A%20%20%7D%0A%20%20return%20%22Not%20Equal%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(12)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function myTest(val) {
  if (12 == val) { // Change this line
    return "Equal";
  }
  return "Not Equal";
}

// Change this value to test
myTest(12);

```
条件使用 12==var 也是对的，但是无法通过测试。

**Comment by juneybw** [comment]
建议携程val == 12 ，可读性较好。

**Comment by discountry** [comment]
可以通过

**Comment by stk-tianwen** [comment]
我这里怎么显示 最后一项（你应该使用 == 运算符）不能通过？ 不能贴图。:(
