### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by hmz3510** [FreeCodeCampChina/freecodecamp.cn#514]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.cn/challenges/escaping-literal-quotes-in-strings#?solution=var%20myStr%3D%22I%20am%20a%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22%22%3B%20%2F%2F%20%E8%AF%B7%E4%BF%AE%E6%94%B9%E8%BF%99%E4%B8%80%E8%A1%8C%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr="I am a\"double quoted\" string inside \"double quotes\""; // 请修改这一行



```

**Comment by S1ngS1ng** [comment]
@hmz3510 
这是你代码的输出：
![image](https://user-images.githubusercontent.com/13592559/40316299-bb538b42-5cd2-11e8-80b1-80df17d9405f.png)
对比一下要求：
![image](https://user-images.githubusercontent.com/13592559/40316306-c4ccf816-5cd2-11e8-8501-fbc729cc4a46.png)

`a` 之后少了个空格
