### ISSUE TITLE
测试不能通过   已经证明是当前浏览器的问题     使用Edge可以提交

### ISSUE THREAD

**Issue by rourrr** [FreeCodeCampChina/freecodecamp.cn#522]
Challenge [Style the HTML Body Element](https://www.freecodecamp.cn/challenges/style-the-html-body-element#?solution=%3Cstyle%3E%0A%20body%20%7B%0A%20%20background-color%3A%20black%3B%0A%7D%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
 body {
  background-color: black;
}
</style>

```

**Comment by S1ngS1ng** [comment]
@rourrr 推荐使用 chrome。其他浏览器可能会遇到问题
