### ISSUE TITLE
it did not work as it suppose to be /the blue-text didn't override the pink text

### ISSUE THREAD

**Issue by whenjune** [FreeCodeCampChina/freecodecamp.cn#523]
Challenge [Override Styles in Subsequent CSS](https://www.freecodecamp.cn/challenges/override-styles-in-subsequent-css#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%20%20.blue-text%7B%0A%20%20%20%20color%3Ablue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%22%20%22blue-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text{
    color:blue;
  }
</style>
<h1 class="pink-text" "blue-text">Hello World!</h1>

```

**Comment by S1ngS1ng** [comment]
Dup of #524

**Comment by IUIUIU** [comment]
[
![class](https://user-images.githubusercontent.com/29515399/45017581-83d32c00-b05a-11e8-86a1-7d60140bc433.png)
](url)

**Comment by IUIUIU** [comment]
Please write the contents of "pink-text blue-text" in a double quotation mark, separated by spaces in the middle.( class="pink-text blue-text")
