### ISSUE TITLE
class blue-text didn't override class pink-text

### ISSUE THREAD

**Issue by whenjune** [FreeCodeCampChina/freecodecamp.cn#524]
Challenge [Override Styles in Subsequent CSS](https://www.freecodecamp.cn/challenges/override-styles-in-subsequent-css) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text{
    color: blue;
  }
 
</style>

<h1 class="pink-text" "blue-text">Hello World!</h1>

```

<img width="1259" alt="2018-05-29 12 42 37" src="https://user-images.githubusercontent.com/39612966/40639440-79779cdc-6343-11e8-9ef5-d8ac66a6dd7f.png">

**Comment by whenjune** [comment]
fixed. thanks

**Comment by IUIUIU** [comment]
Please write the contents of "pink-text blue-text" in a double quotation mark, separated by spaces in the middle.( class="pink-text blue-text")
