### ISSUE TITLE
不懂我为什么不能通过，测试的结果没错啊

### ISSUE THREAD

**Issue by fnlearner** [FreeCodeCampChina/freecodecamp.cn#526]
Challenge [Missing letters](https://www.freecodecamp.cn/challenges/missing-letters#?solution=%20function%20fearNotLetter(str)%20%7B%0A%20%20%20%20%20%20%20%20var%20num%3D%5B%5D%3B%0A%20%20%20%20%20%20%20%20var%20letter%3D%5B%5D%3B%0A%20%20%20%20%20%20%20%20for(var%20object%20in%20str)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20num.push(str.charCodeAt(object))%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20for(var%20i%3D0%3Bi%3Cnum.length-1%3Bi%2B%2B)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if(num%5Bi%5D%2B1%3D%3Dnum%5Bi%2B1%5D)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20continue%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20else%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20letter.push(String.fromCharCode(num%5Bi%5D%2B1))%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20if(letter.length%3D%3D%3D0)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20letter.push('undefined')%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20return%20letter.join(%22%22)%3B%0A%0A%20%20%20%20%7D%0AfearNotLetter(%22bcd%22)%3B%0A%20) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3423.2 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
 function fearNotLetter(str) {
        var num=[];
        var letter=[];
        for(var object in str){
            num.push(str.charCodeAt(object));
        }
        for(var i=0;i<num.length-1;i++){
                if(num[i]+1==num[i+1]){
                    continue;
                }
                else{
                    letter.push(String.fromCharCode(num[i]+1));
                }
        }
       if(letter.length===0){
            letter.push('undefined');
        }
        return letter.join("");

    }
fearNotLetter("bcd");
 
```

**Comment by S1ngS1ng** [comment]
@24KPureHandSome 你的执行结果：
![image](https://user-images.githubusercontent.com/13592559/40928559-a8e17adc-67d6-11e8-8c9b-320f0bf3cf4d.png)
这结果显然是错的，`undefined` 和 `"undefined"` 不是一个东西。。
直接 `return` 就好了
