### ISSUE TITLE
随机输出一个范围内的整数有问题

### ISSUE THREAD

**Issue by BluceLee1** [FreeCodeCampChina/freecodecamp.cn#528]
Challenge [Generate Random Whole Numbers within a Range](https://www.freecodecamp.cn/challenges/generate-random-whole-numbers-within-a-range#?solution=%2F%2F%20%E4%B8%BE%E4%BE%8B%0Afunction%20ourFunction(ourMin%2C%20ourMax)%20%7B%0A%0A%20%20return%20Math.floor(Math.random()%20*%20(ourMax%20-%20ourMin%20%2B%201))%20%2B%20ourMin%3B%0A%7D%0A%0AourFunction(1%2C%209)%3B%0A%0A%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E6%9D%A1%E6%B3%A8%E9%87%8A%E4%BB%A5%E4%B8%8B%0A%0Afunction%20randomRange(myMin%2C%20myMax)%20%7B%0A%0A%20%20return%20ourFunction(myMin%2CmyMax)%3B%20%2F%2F%20%E8%AF%B7%E4%BF%AE%E6%94%B9%E8%BF%99%E4%B8%80%E8%A1%8C%0A%0A%7D%0A%0A%2F%2F%20%E4%BD%A0%E5%8F%AF%E4%BB%A5%E4%BF%AE%E6%94%B9%E8%BF%99%E4%B8%80%E8%A1%8C%E6%9D%A5%E6%B5%8B%E8%AF%95%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%0Avar%20myRandom%20%3D%20randomRange(5%2C%2015)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// 举例
function ourFunction(ourMin, ourMax) {

  return Math.floor(Math.random() * (ourMax - ourMin + 1)) + ourMin;
}

ourFunction(1, 9);

// 请把你的代码写在这条注释以下

function randomRange(myMin, myMax) {

  return ourFunction(myMin,myMax); // 请修改这一行

}

// 你可以修改这一行来测试你的代码
var myRandom = randomRange(5, 15);

```

**Comment by S1ngS1ng** [comment]
@BluceLee1 你的思路和代码都没错。只是 fcc 平台上，出于安全考虑，测试函数会忽略所有人为添加的全局变量/function。
这也就是为什么题目中说了，“请把你的代码写在这条注释以下”，以及 “请修改这一行”，其他地方你添加任何东西都会被忽略
