### ISSUE TITLE
导入Lobster字体。尝试使用link @font-face都不能正确通过挑战，请问是哪里问题

### ISSUE THREAD

**Issue by wangzhenalex** [FreeCodeCampChina/freecodecamp.cn#53]
Challenge [Import a Google Font](https://www.freecodecamp.cn/challenges/import-a-google-font#?solution=%3Clink%20href%3D%22https%3A%2F%2Ffonts.gdgdocs.org%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%20%20h2%20%7B%0A%20%20%20%20%20font-family%3A%20Lobster%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3E%E5%9C%A8%E5%A4%A7%E5%AE%B6%E5%BF%83%E7%9B%AE%E4%B8%AD%EF%BC%8C%E7%8C%AB%E6%98%AF%E6%85%B5%E6%87%92%E7%9A%84%E5%8F%AF%E7%88%B1%E7%9A%84%E5%8C%96%E8%BA%AB%EF%BC%8C%E5%AE%83%E5%8F%AF%E4%BB%A5%E7%9D%A1%E9%A5%B1%E4%BA%86%E5%86%8D%E8%B5%B7%E6%9D%A5%E5%90%83%E9%A5%AD%EF%BC%8C%E5%8F%AF%E4%BB%A5%E9%80%97%E8%B6%A3%E5%B0%8F%E8%80%97%E5%AD%90%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%8D%96%E5%BE%97%E4%BA%86%E8%90%8C%EF%BC%8C%E4%BD%BF%E5%BE%97%E4%BA%86%E5%9D%8F%EF%BC%8C%E8%BF%99%E6%A0%B7%E7%99%BE%E5%8F%98%E7%9A%84%E5%B0%8F%E6%80%AA%E5%85%BD%E5%B0%B1%E9%9B%86%E7%BB%93%E5%9C%A8%E4%B8%80%E5%8F%AA%E5%AE%A0%E7%89%A9%E4%B8%8A%EF%BC%8C%E6%80%8E%E8%83%BD%E4%B8%8D%E6%83%B9%E4%BA%BA%E6%80%9C%E7%88%B1%E3%80%82%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3E%E5%85%BB%E5%8A%A8%E7%89%A9%E6%9C%89%E7%9A%84%E6%97%B6%E5%80%99%EF%BC%8C%E5%B0%B1%E6%98%AF%E4%BB%8B%E4%BA%8E%E7%88%B1%E4%B8%8E%E6%81%A8%E4%B9%8B%E9%97%B4%EF%BC%8C%E5%BD%93%E4%BD%A0%E9%92%A6%E7%BE%A1%E5%88%AB%E4%BA%BA%E8%90%8C%E5%AE%A0%E8%BF%99%E4%B9%88%E5%8F%AF%E7%88%B1%E7%9A%84%E6%97%B6%E5%80%99%EF%BC%8C%E4%BD%A0%E4%B8%80%E5%AE%9A%E6%B2%A1%E6%9C%89%E6%83%B3%E8%BF%87%EF%BC%8C%E7%8B%97%E7%8B%97%E5%92%8C%E7%8C%AB%E7%8C%AB%E4%BC%9A%E5%88%B0%E5%A4%84%E6%8B%89%E5%B1%8E%EF%BC%8C%E7%94%9A%E8%87%B3%E4%BC%9A%E5%B1%AF%E8%80%81%E9%BC%A0%EF%BC%8C%E5%95%83%E9%9E%8B%E5%AD%90%EF%BC%8C%E7%94%A8%E7%88%AA%E5%AD%90%E7%88%AC%E9%97%A8%EF%BC%8C%E4%BD%A0%E4%B8%8D%E7%90%86%E5%AE%83%EF%BC%8C%E5%AE%83%E5%B0%B1%E6%8C%A0%E4%BD%A0%EF%BC%8C%E4%BD%A0%E8%A6%81%E5%AF%B9%E5%AE%83%E5%8F%91%E8%84%BE%E6%B0%94%EF%BC%8C%E5%AE%83%E4%BC%9A%E6%AF%94%E4%BD%A0%E6%9B%B4%E6%9D%A5%E5%8A%B2%E3%80%82%E6%89%80%E4%BB%A5%EF%BC%8C%E7%8B%97%E7%8C%AB%E6%85%8E%E5%85%A5%EF%BC%8C%E6%B2%A1%E6%9C%89%E4%B8%80%E5%AE%9A%E7%9A%84%E5%87%86%E5%A4%87%EF%BC%8C%E5%88%87%E5%8B%BF%E9%9A%8F%E4%BE%BF%E5%8E%BB%E4%BE%8D%E5%85%BB%E5%8A%A8%E7%89%A9%E3%80%82%E5%AE%83%E4%BB%AC%E4%B8%80%E6%97%A6%E8%AE%A4%E5%AE%9A%E4%BD%A0%E4%BA%86%EF%BC%8C%E4%BD%A0%E5%B0%B1%E6%98%AF%E5%AE%83%E4%BB%AC%E7%9A%84%E4%B8%BB%E4%BA%BA%EF%BC%8C%E5%A6%82%E6%9E%9C%E4%BD%A0%E6%8A%9B%E5%BC%83%E5%AE%83%E4%BB%AC%EF%BC%8C%E5%AE%83%E4%BB%AC%E5%BF%85%E5%AE%9A%E5%BF%83%E4%B8%AD%E9%87%8D%E5%88%9B%E3%80%82%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="https://fonts.gdgdocs.org/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  h2 {
     font-family: Lobster;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">在大家心目中，猫是慵懒的可爱的化身，它可以睡饱了再起来吃饭，可以逗趣小耗子，可以卖得了萌，使得了坏，这样百变的小怪兽就集结在一只宠物上，怎能不惹人怜爱。</p>
<p class="red-text">养动物有的时候，就是介于爱与恨之间，当你钦羡别人萌宠这么可爱的时候，你一定没有想过，狗狗和猫猫会到处拉屎，甚至会屯老鼠，啃鞋子，用爪子爬门，你不理它，它就挠你，你要对它发脾气，它会比你更来劲。所以，狗猫慎入，没有一定的准备，切勿随便去侍养动物。它们一旦认定你了，你就是它们的主人，如果你抛弃它们，它们必定心中重创。</p>

```

**Comment by AI-Ying** [comment]
把链接换成这个就可以了。
`<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lobster">`

**Comment by pbxrt** [comment]
为什么文中提到的链接不行呢？你的这个链接的内容跟文中提到的链接的网页内容好像是一样的呀？

**Comment by mougua** [comment]
在chrome下，题目里面按F12，调出Dev Tools。检查Sources，可以发现challenges/import-a-google-font里面有一行：

```
common.tests = 
  ["assert(new RegExp(\"googleapis\", \"gi\").test(code), 'message: 导入<code>Lobster</code>字体。');",
  "assert($(\"h2\").css(\"font-family\").match(/lobster/i), 'message: 你的副标题应该使用字体<code>Lobster</code>。');",
  "assert($(\"p\").css(\"font-family\").match(/monospace/i), 'message: 你的段落仍旧使用字体<code>Monospace</code>。');
  "];
```

说明这一题的第一个条件会检测做题人的整份代码里面是否包含googleapis，所以这个是一个bug。可以换链接，也可以在任意地方加上googleapis字样，就可以通过了。

**Comment by huluoyang** [comment]
@mougua 感谢你的回答。
因为谷歌字体在中国的不稳定情况，偶尔能用，偶尔又不能用。
所以我们把谷歌字体替换为了GDG字体，当然，GDG只是一个代理，实际上的字体存在七牛云上。
但测试部分忘记更改了，为了兼容大家喜好。此处会修改为：

```
assert(new RegExp(\"googleapis|gdgdocs\", \"gi\").test(code)
```

**Comment by Shisanyue8023** [comment]
为什么我的还是不可以啊,换了上面这个Link也不行啊

**Comment by wlxfx** [comment]
我的代码用开始的的链接的话，h2 标签可以正常显示新字体，但是应用在p标签上就不行。这到底是怎么回事？奇了怪了。如果换成大家说的googleapi这个链接根本不起作用，连h2标签都不能正常显示了。我用的是360安全浏览器极速模式，电信网络

**Comment by xuezechao2012** [comment]
学前端，我建议用Chrome 浏览器，各种牛逼不解释


发自网易邮箱大师
在2016年12月17日 16:04，网络小飞侠 写道:

我的代码用开始的的链接的话，h2 标签可以正常显示新字体，但是应用在p标签上就不行。这到底是怎么回事？奇了怪了。如果换成大家说的googleapi这个链接根本不起作用，连h2标签都不能正常显示了。我用的是360安全浏览器极速模式，电信网络

**Comment by wlxfx** [comment]
就算用chrome 不能翻墙也没用啊，chrome我也有，但是一样没反应，不能解决问题。你能不能帮我？如果不能也不用过来炫耀下自己用chrome就走是不是？何必呢？

**Comment by Rockelbel** [comment]
请贴一下这节课程的标题  #53不太好找

**Comment by sausagehwx** [comment]
这里不管p标签，只需单独写 h2 { font-family:Lobster;}

**Comment by chipchh** [comment]
<link href="https://fonts.gdgdocs.org/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
    font-family:Lobster;
  }

  
  p {
    font-size: 16px;
    color:black;
    font-family:Lobster;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>在大家心目中，猫是慵懒的可爱的化身，它，怎能不惹人怜爱。</p>
<p>养动物有的时候，就是介心中重创。</p>


没错吧？为什么P标签字体还是没有变化？！
