### ISSUE TITLE
就ww不知道为啥。。不能通过第二个用例

### ISSUE THREAD

**Issue by fnlearner** [FreeCodeCampChina/freecodecamp.cn#537]
Challenge [Make a Person](https://www.freecodecamp.cn/challenges/make-a-person#?solution=var%20Person%20%3D%20function(firstAndLast)%20%7B%0A%20%20%20%20%20%20%20var%20first%3DfirstAndLast.split(%22%20%22)%5B0%5D%2Clast%3DfirstAndLast.split(%22%20%22)%5B1%5D%3B%0A%20%20%20%20%20%20%20%20return%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20getFirstName%3Afunction()%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20first%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20getLastName%3Afunction()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20last%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20getFullName%3Afunction()%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20first%2B'%20'%2Blast%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20setFirstName%3Afunction(str)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20first%3Dstr%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20setLastName%3Afunction(str)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20last%3Dstr%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20setFullName%3Afunction(firstLast)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20first%3DfirstLast.split('%20')%5B0%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20last%3DfirstLast.split('%20')%5B1%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%7D%0A%7D%3B%0A%0Avar%20bob%20%3D%20new%20Person('Bob%20Ross')%3B%0Abob.getFullName()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3423.2 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Person = function(firstAndLast) {
       var first=firstAndLast.split(" ")[0],last=firstAndLast.split(" ")[1];
        return {
            getFirstName:function(){
                return first;
            },
            getLastName:function() {
                return last;
            },
            getFullName:function(){
                return first+' '+last;
            },
            setFirstName:function(str){
                first=str;
            },
            setLastName:function(str){
               last=str;
            },
            setFullName:function(firstLast){
              first=firstLast.split(' ')[0];
              last=firstLast.split(' ')[1];
            }
       }
};

var bob = new Person('Bob Ross');
bob.getFullName();

```

**Comment by S1ngS1ng** [comment]
@24KPureHandSome 
请先读一下 `new` 操作符的文档：https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new 。请注意这里：

![image](https://user-images.githubusercontent.com/13592559/42233673-0c815a80-7ea7-11e8-8bae-891bd853f10a.png)

你的代码就是符合这种情况的，因此 `bob` 其实是没有继承 `Person.prototype` 的。

再读一下 `instanceof` 的文档：https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof

`bob instanceof Person` 的作用是在 `bob`  的原型链上找是否存在 `Person.prototype`。由于没有继承 `Person.prototype`，这里显然是 `false`。

由于返回的是一个 Object Literal，那么显然 `bob instanceof Object` 是会返回 `true` 的。

所以，这道题，你需要的是用 `this` 来绑定那些 `method`，这种写法习惯上叫做 "Constructor function" （注意不要和 ES6 的 `constructor` 关键字混淆）。你的这种写法，最后返回 Object Literal 的，习惯上叫做 Factory function。

这不是题目问题。以后请到 https://gitter.im/FreeCodeCamp/chinese 提问

**Comment by seakingxc** [comment]
使用new Foo()的时候，如果构造函数没显示返回一个对象，就会创建返回一个继承Foo. prototype的新对象
