### ISSUE TITLE
stand in line

### ISSUE THREAD

**Issue by ZiHan2016** [FreeCodeCampChina/freecodecamp.cn#54]
队列问题：
原文中这样描述：在计算机科学中 队列（queue）是一个抽象的数据结构，队列中的条目都是有秩序的。新的条目会被加到 队列 的末尾，旧的条目会从 队列 的头部被移出。

实际是：旧的条目会被添加到底部，新的条目会被添加到头部。如果需要移除的时候，从上至下移除，应该新的头目会先被移除，而旧的条目会后移除，故称”先进先出“。

**Comment by huluoyang** [comment]
@ZiHan2016 
原文的翻译我不觉得有什么问题，语句流畅，清晰易懂。
队列 类似于军训中的站队，只有入队和出队2个操作。
从尾部入队，从头部出队。
