### ISSUE TITLE
Sum All Odd Fibonacci Numbers 中的 BUG

### ISSUE THREAD

**Issue by Jhinsama** [FreeCodeCampChina/freecodecamp.cn#541]
#### 问题描述
* Sum All Odd Fibonacci Numbers
* 在任务要求里面有一个   sumFibs(75024) 应该返回 60696
* 在 斐波纳契数列中 第 75024 个数怎么可能比 75024 还小

**Comment by S1ngS1ng** [comment]
@Jhinsama 请仔细读一下题目的描述：
![image](https://user-images.githubusercontent.com/13592559/42957936-e56e7b50-8b38-11e8-9edc-f8b90c25f584.png)
因此传入的参数不是代表“第 `num` 个”，而是不大于 `num` 的意思。`sumFibs(75024)` 意思是斐波纳契数列中，小于等于 `75024` 的奇数
