### ISSUE TITLE
求教哪里错了？

### ISSUE THREAD

**Issue by wenshaofeng** [FreeCodeCampChina/freecodecamp.cn#543]
Challenge [Chunky Monkey](https://freecodecamp.cn/challenges/chunky-monkey#?solution=%0Afunction%20chunk(arr%2C%20size)%20%7B%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E9%87%8C%0A%20%20var%20x%20%3D%20arr.length%20%25%20size%20%3B%0A%20%20var%20y%20%3D%20arr.length%20%2F%20size%20%3B%0A%20%20var%20nArr%20%3D%5B%5D%20%3B%0A%20%20for(var%20i%3D0%3Bi%3Cy%3Bi%2B%2B)%7B%0A%20%20%20%20nArr%5Bi%5D%20%3D%20arr.slice(i*size%2C(i%2B1)*size)%3B%0A%20%20%7D%0A%20%20if(x!%3D%3D0)%20%7BnArr%5By%5D%3Darr.push(arr.slice((i%2B1)*size%2Carr.length))%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20nArr%3B%20%20%7D%0A%20%20%20%20%20else%20return%20nArr%3B%20%20%20%20%0A%7D%0Achunk(%5B0%2C%201%2C%202%2C%203%2C%204%2C%205%2C%206%5D%2C%203)%20%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3486.0 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function chunk(arr, size) {
  // 请把你的代码写在这里
  var x = arr.length % size ;
  var y = arr.length / size ;
  var nArr =[] ;
  for(var i=0;i<y;i++){
    nArr[i] = arr.slice(i*size,(i+1)*size);
  }
  if(x!==0) {
    nArr[y]=arr.push(arr.slice((i+1)*size,arr.length));
    return nArr;
  }
  else return nArr;    
}
chunk([0, 1, 2, 3, 4, 5, 6], 3) ;



```

my answer
`
function chunk(arr, size) {
  // 请把你的代码写在这里
  var x = arr.length % size ;
  var y = arr.length / size ;
  var nArr =[] ;
  for(var i=0;i<y;i++){
    nArr[i] = arr.slice(i*size,(i+1)*size);
  }
  if(x!==0) nArr[y]=arr.push(arr.slice((i+1)*size,arr.length));
   
}
chunk([0, 1, 2, 3, 4, 5, 6], 3) ;

`

编译器说后三个不通过，但是自己试的时候是通过的。

**Comment by S1ngS1ng** [comment]
自己运行结果也是错的：
![image](https://user-images.githubusercontent.com/13592559/43216998-4498a518-8ff5-11e8-8845-c617184ab52a.png)

你这里多了个 `1.5: 7`

请注意 `push` 方法的返回值是数组长度。文档：https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push

**Comment by xuzhh941006** [comment]
function chunk(arr, size) {
  // 请把你的代码写在这里
  var arrSize = arr.length/size;
  var newArr = [];
  for (var i = 0; i < arrSize; i++) {
    newArr.push(arr.slice(i * size,(i+1) * size));
  }
  
  return newArr;
}
