### ISSUE TITLE
"Build a Pomodoro Clock"

### ISSUE THREAD

**Issue by H-zk** [FreeCodeCampChina/freecodecamp.cn#544]
Challenge [Build a Pomodoro Clock](https://www.freecodecamp.cn/challenges/build-a-pomodoro-clock) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
"Build a Pomodoro Clock"在CodePen.io的实例已不能正常工作

**Comment by S1ngS1ng** [comment]
@H-zk 谢谢你的 issue。https://codepen.io/freeCodeCamp/pen/VemPZX/ 这样是 work 的。但 full mode  就不行。感觉这个多半是 codepen 那边的问题。先用这个链接吧，或者：
![image](https://user-images.githubusercontent.com/13592559/43216583-37ff968c-8ff4-11e8-9a3e-e7ad4e3a2676.png)
点 Change View

**Comment by H-zk** [comment]
好的，谢谢你。
