### ISSUE TITLE
给主标题添加了注释，但该项编译总是不通过

### ISSUE THREAD

**Issue by zuzheng** [FreeCodeCampChina/freecodecamp.cn#546]
Challenge [Comment out HTML](https://freecodecamp.cn/challenges/comment-out-html#?solution=%3C!--%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A--%3E%0A%0A%3Ch2%3E%E6%88%91%E5%AE%B6%E7%9A%84%E7%8C%AB%E5%92%AA%3C%2Fh2%3E%0A%0A%3C!--%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A--%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6</code>.
给主标题添加了注释，但该项编译总是不通过

My code:
```html
<!--
<h1>Hello World</h1>
-->

<h2>我家的猫咪</h2>

<!--
<p>Hello Paragraph</p>
-->

```

**Comment by S1ngS1ng** [comment]
@zuzheng 我试了下是可以的= =你 reset 一下然后再试试？

**Comment by zuzheng** [comment]
换了Chrome浏览器，几个有同样问题的题目都提交成功了。看来问题只是出来Safari上。

**Comment by S1ngS1ng** [comment]
@zuzheng 好。那先关了

**Comment by Noah-will** [comment]
用firefox 也出现这个问题，换成谷歌浏览器就通过了
