### ISSUE TITLE
项目为什么没有fork FreeCodeCamp？

### ISSUE THREAD

**Issue by caiqinghua** [FreeCodeCampChina/freecodecamp.cn#55]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/chinese

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by huluoyang** [comment]
中文社区是独立版本，仅仅是fork不能满足需求。
