### ISSUE TITLE
Javascript escaps character Result Wrong

### ISSUE THREAD

**Issue by CinYung** [FreeCodeCampChina/freecodecamp.cn#56]
Challenge [Escape Sequences in Strings](http://www.w3cschool.cn/codecamp/escape-sequences-in-strings.html#?solution=var%20myStr%3D%20%22%5C%5C%20%5Ct%20%5Cb%20%5Cn%20%5Cr%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 UBrowser/5.7.16400.16 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr = "\\";
```
Result:
```javascript
myStr = "\\"
```
My code:
```javascript
var myStr= "\\ \t \b \n \r"; // Change this line
```

**Comment by Kiewie** [comment]
The last code is OK, try again.

**Comment by yukingcome** [comment]
Problems still exist.

**Comment by fangner** [comment]
这题刷不过去了，怎么做都不正确，也没有正确答案

**Comment by xiaopf** [comment]
不行呀，搞不过去呀

**Comment by shendengnian** [comment]
争对这个问题，本人琢磨了半天，终于找到解决的办法了，现在分享出来让各位小伙伴能少走弯路，不用花那么多时间在这些小事上   var myStr = "\\ \t \b \r \n";

**Comment by shendengnian** [comment]
争对这个问题，本人琢磨了半天，终于找到解决的办法了，现在分享出来让各位小伙伴能少走弯路，不用花那么多时间在这些小事上 var myStr = "\\ \t \b \r \n";

**Comment by Virdo** [comment]
这类题目对空格的要求很严格啊 var myStr = "\\ \t \b \r \n";  第一个双引号的后面 最后一个双引号的前面不能有空格就对了，相似问题在前面的题中出现过。
