### ISSUE TITLE
有没有更好的写法？

### ISSUE THREAD

**Issue by seakingxc** [FreeCodeCampChina/freecodecamp.cn#562]
Challenge [Chunky Monkey](https://www.freecodecamp.cn/challenges/chunky-monkey#?solution=function%20chunk(arr%2C%20size)%20%7B%0A%20%20%2F%2F%20%E8%AF%B7%E6%8A%8A%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%86%99%E5%9C%A8%E8%BF%99%E9%87%8C%0A%20%20var%20newarr%3D%5B%5D%3B%0A%20%20%2F%2F%E6%AF%8Fsize%E4%B8%AA%E5%85%83%E7%B4%A0%E4%B8%BA%E4%B8%80%E7%BB%84%20%E5%8F%AF%E4%BB%A5%E5%88%86%E4%B8%BAarr.length%2Fsize%E7%BB%84%0A%20%20var%20arrcount%20%3D%20parseInt(arr.length%2Fsize)%3B%0A%20%20%2F%2F%E5%88%A4%E6%96%AD%E6%98%AF%E5%90%A6%E5%8F%AF%E4%BB%A5%E6%95%B4%E9%99%A4%0A%20%20if(arr.length%25size%3E0)%7B%0A%20%20%20%20arrcount%20%2B%3D1%3B%0A%20%20%7D%0A%20%20%2F%2F%E5%BE%AA%E7%8E%AFarrcount%E6%AC%A1%E7%BB%84%E8%A3%85%E6%96%B0%E6%95%B0%E7%BB%84%20%20%E7%AC%AC%E4%B8%80%E7%BB%84%E5%9D%90%E6%A0%87%E6%98%AF0-size%20%E6%AF%8F%E4%B8%B4%E8%BF%912%E7%BB%84%E5%9D%90%E6%A0%87%E7%9B%B8%E5%AF%B9%E5%A2%9E%E5%8A%A0size%0A%20%20for(var%20i%20%3D%200%3Bi%3Carrcount%3Bi%2B%2B)%7B%0A%20%20%20%20%2F%2F%E7%94%A8slice%E6%96%B9%E6%B3%95%E5%88%87%E7%89%87%0A%20%20%20%20var%20x%20%3D%20i*size%3B%0A%20%20%20%20newarr.push(arr.slice(0%2Bx%2Csize%2Bx))%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20newarr%3B%0A%7D%0A%0Achunk(%5B%22a%22%2C%20%22b%22%2C%20%22c%22%2C%20%22d%22%2C%22e%22%5D%2C%202)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function chunk(arr, size) {
  // 请把你的代码写在这里
  var newarr=[];
  //每size个元素为一组 可以分为arr.length/size组
  var arrcount = parseInt(arr.length/size);
  //判断是否可以整除
  if(arr.length%size>0){
    arrcount +=1;
  }
  //循环arrcount次组装新数组  第一组坐标是0-size 每临近2组坐标相对增加size
  for(var i = 0;i<arrcount;i++){
    //用slice方法切片
    var x = i*size;
    newarr.push(arr.slice(0+x,size+x));
  }
  
  return newarr;
}

chunk(["a", "b", "c", "d","e"], 2);

```

**Comment by S1ngS1ng** [comment]
@seakingxc https://singsing.io/blog/fcc/basic-chunky-monkey/
可以参考最后的那个方法，用 `splice`

**Comment by tlviviana** [comment]
function chunk(arr, size) {
  // 请把你的代码写在这里
  var newArr = [];
  for(var i = 0;i < arr.length;i += size){
    var num = arr.slice(i,i + size);
    newArr.push(num);
  }
  return newArr;
}
