### ISSUE TITLE
如何用到给的条件math.max和math.min？

### ISSUE THREAD

**Issue by seakingxc** [FreeCodeCampChina/freecodecamp.cn#564]
Challenge [Sum All Numbers in a Range](https://www.freecodecamp.cn/challenges/sum-all-numbers-in-a-range#?solution=function%20sumAll(arr)%20%7B%0A%20%20%2F%2F%E5%8E%9F%E6%95%B0%E7%BB%84%E5%8F%AA%E6%9C%892%E4%B8%AA%E5%85%83%E7%B4%A0%2C%E5%85%88%E6%8E%92%E5%BA%8F%0A%20var%20newarr%20%3D%20%20arr.sort(function(a%2Cb)%7B%0A%20%20%20%20return%20b-a%3B%2F%2F%E4%BB%8E%E5%A4%A7%E5%88%B0%E5%B0%8F%E6%8E%92%E5%BA%8F%0A%20%20%7D)%3B%0A%20%20%2F%2F%E6%8A%8A%E8%BF%99%E4%B8%AA%E6%95%B0%E7%BB%84%E5%8F%98%E6%88%90%E5%8C%85%E5%90%AB2%E4%B8%AA%E5%85%83%E7%B4%A0%E5%92%8C%E4%BB%96%E4%BB%AC%E4%B9%8B%E9%97%B4%E6%89%80%E6%9C%89%E6%95%B0%E5%AD%97%E7%9A%84%E6%95%B0%E7%BB%84%0A%20%20var%20count%20%3D%20newarr%5B0%5D-newarr%5B1%5D-1%3B%0A%20%20var%20i%20%3D%201%3B%0A%20%20while(count)%7B%0A%20%20%20%20%2F%2F%E7%AC%A8%E6%96%B9%E6%B3%95%E5%8F%AF%E4%BB%A5%E5%BE%AA%E7%8E%AF-1%E6%88%96%E8%80%85%2B1%E6%9D%A5%E8%8E%B7%E5%8F%96%0A%20%20%20%20newarr.splice(i%2C0%2Cnewarr%5Bi-1%5D-1)%3B%0A%20%20%20%20i%2B%2B%3B%0A%20%20%20%20count--%3B%0A%20%20%20%20%0A%20%20%7D%0A%20%20var%20sum%20%3D%20newarr.reduce(function(all%2Cx)%7B%0A%20%20%20%20return%20all%2Bx%3B%0A%20%20%7D)%3B%0A%20%20%0A%20%20return%20sum%3B%0A%7D%0A%0AsumAll(%5B1%2C%204%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function sumAll(arr) {
  //原数组只有2个元素,先排序
 var newarr =  arr.sort(function(a,b){
    return b-a;//从大到小排序
  });
  //把这个数组变成包含2个元素和他们之间所有数字的数组
  var count = newarr[0]-newarr[1]-1;
  var i = 1;
  while(count){
    //笨方法可以循环-1或者+1来获取
    newarr.splice(i,0,newarr[i-1]-1);
    i++;
    count--;
    
  }
  var sum = newarr.reduce(function(all,x){
    return all+x;
  });
  
  return sum;
}

sumAll([1, 4]);

```

**Comment by S1ngS1ng** [comment]
用 `Math.max.apply(null, arr)` 和 `Math.min.apply(null, arr)` 可以分别取到较大数和较小数。不需要给 `arr` 排序。
ES6 写法是 `Math.max(...arr)` 和 `Math.min(...arr)`
