### ISSUE TITLE
我没有用到提示给的Array.slice()，是不是思路还不够简便？

### ISSUE THREAD

**Issue by seakingxc** [FreeCodeCampChina/freecodecamp.cn#565]
Challenge [Diff Two Arrays](https://www.freecodecamp.cn/challenges/diff-two-arrays#?solution=function%20diff(arr1%2C%20arr2)%20%7B%0A%20%20%0A%20%20%2F%2F%20Same%2C%20same%3B%20but%20different.%0A%20%20%2F%2F%E5%88%A4%E6%96%AD%E4%B8%80%E4%B8%AA%E6%95%B0%E7%BB%84%E4%B8%AD%E6%98%AF%E5%90%A6%E5%8C%85%E5%90%AB%E6%9F%90%E4%B8%80%E4%B8%AA%E5%85%83%E7%B4%A0%E7%94%A8indexOf%E6%96%B9%E6%B3%95%0A%20%20%0A%20%20var%20mergarr%20%3D%20arr1.concat(arr2)%3B%0A%20%20%0A%20%20return%20mergarr.filter(function(x)%7B%0A%20%20%20%20return%20arr1.indexOf(x)%20%3D%3D%3D%20-1%20%7C%7C%20arr2.indexOf(x)%20%3D%3D%3D-1%3B%0A%20%20%7D)%3B%0A%7D%0A%0Adiff(%5B1%2C%202%2C%203%2C%205%2C6%5D%2C%20%5B1%2C%202%2C%203%2C%204%2C%205%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function diff(arr1, arr2) {
  
  // Same, same; but different.
  //判断一个数组中是否包含某一个元素用indexOf方法
  
  var mergarr = arr1.concat(arr2);
  
  return mergarr.filter(function(x){
    return arr1.indexOf(x) === -1 || arr2.indexOf(x) ===-1;
  });
}

diff([1, 2, 3, 5,6], [1, 2, 3, 4, 5]);

```

**Comment by S1ngS1ng** [comment]
已经很简便了。不过 `mergarr` 不需要创建，因为 `concat` 返回数组，因此可以连用
提示中的方法并不是要全用

**Comment by wenzhaoda** [comment]
function diff(arr1, arr2) {
  var num=0;
  var newArrp=arr1.concat(arr2);
  for(var i=arr1.length;i>-1;i--){
    for(var j=arr2.length;j>-1;j--){
      if(arr1[i]===arr2[j]){
        arr1.splice(i,1);
        arr2.splice(j,1);
      }  
    }
  }
  // Same, same; but different.
  return arr1.concat(arr2);
}
