### ISSUE TITLE
Can not cross!!!

### ISSUE THREAD

**Issue by tairenzhen** [FreeCodeCampChina/freecodecamp.cn#58]
Challenge [Find the Length of a String](https://freecodecamp.cn/challenges/find-the-length-of-a-string#?solution=%2F%2F%20%E4%B8%BE%E4%BE%8B%0Avar%20firstNameLength%20%3D%200%3B%0Avar%20firstName%20%3D%20%22Ada%22%3B%0A%0AfirstNameLength%20%3D%20firstName.length%3B%0A%0A%2F%2F%20Setup%0Avar%20lastNameLength%20%3D%200%3B%0Avar%20lastName%20%3D%20%22Lovelace%22%3B%0AlastNameLength%20%3D%20lastName.length%3B%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AlastNameLength%20%3D%20lastName%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2859.0 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// 举例
var firstNameLength = 0;
var firstName = "Ada";

firstNameLength = firstName.length;

// Setup
var lastNameLength = 0;
var lastName = "Lovelace";
lastNameLength = lastName.length;
// Only change code below this line.

lastNameLength = lastName;



```

**Comment by discountry** [comment]
去掉最后一行

**Comment by xieyangfight** [comment]
//setup 后面代码改为
var lastNameLength=0;
var lastName="Lovelace";
//Only change code below this line.

lastNameLength=lastName.length;

这样就可以了
