### ISSUE TITLE
题目中的错误

### ISSUE THREAD

**Issue by dwk715** [FreeCodeCampChina/freecodecamp.cn#59]
在Use Hex Code to Color Elements Red这个题目中的这句话
会有多少种可能的颜色？16 个值和 6 个位置意味着我们有 16 的 6 次方，或者说超过 1600 万种可能的颜色。
应该是6的16次方。

**Comment by huluoyang** [comment]
@dwk715  恩，确实如此，感谢反馈。

**Comment by S1ngS1ng** [comment]
@dwk715 为什么是 6 的 16次方呢？
HEX Code 有六个位置，每个位置有 16 种可能，而且可以重复。
所以总共的可能性就是 `16 * 16 * 16 * 16 * 16 * 16`，也就是 16 的 6 次方

**Comment by wudifeixue** [comment]
...我犯傻了
