### ISSUE TITLE
Falsy Bouncer

### ISSUE THREAD

**Issue by njueszzy** [FreeCodeCampChina/freecodecamp.cn#6]
Challenge [Falsy Bouncer](https://www.freecodecamp.cn/challenges/falsy-bouncer#?solution=function%20bouncer%28arr%29%20%7B%0A%20%20%2F%2F%20Don't%20show%20a%20false%20ID%20to%20this%20bouncer.%0A%20%20return%20arr.filter%28function%20isTrue%28str%29%7B%0Areturn%20str!%3D%3Dfalse%26%26str!%3D%3Dnull%26%26str!%3D%3D0%26%26str!%3D%3D%22%22%26%26isNaN%28str%29!%3D%3D0%3B%0A%7D%29%3B%0A%7D%0A%0A%0Abouncer%28%5B1%2C%20null%2C%20NaN%2C%202%2C%20undefined%5D%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36 SE 2.X MetaSr 1.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function bouncer(arr) {

  return arr.filter(function isTrue(str){
return str!==false&&str!==null&&str!==0&&str!==""&&isNaN(str)!==0;
});
}


bouncer([1, null, NaN, 2, undefined]);

```

运行其他的都给删掉了，就NaN变成null了，求大神指导

另外，我想问问这些题有没有个官方的解答，这样的话可以自己写完后再借鉴下更好的思路

**Comment by huluoyang** [comment]
先弄清filter的用法，课程下面有文档啊。
一句话就搞定弄这么复杂，没弄清原理啊。

**Comment by JinChengneng** [comment]
function bouncer(arr) {
  return arr.filter(function(val){
    return Boolean(val);
  }); 
}

**Comment by JinChengneng** [comment]
`function bouncer(arr) {
  return arr.filter(function(val){
    return Boolean(val);
  }); 
} `

**Comment by inetsurfer** [comment]
function bouncer(arr) {
  arr=arr.filter(Boolean);
  return arr;}

**Comment by inetsurfer** [comment]
`function bouncer(arr) {
arr=arr.filter(Boolean);
return arr;}`

**Comment by inetsurfer** [comment]
我的代码，还有更短的吗？
`function bouncer(arr) {
  return arr.filter(Boolean);
  }`

**Comment by theRedHands** [comment]
我太单纯,还到处找怎么判断NaN

**Comment by Nydia07** [comment]
请问能具体解释一下那个最短的代码吗？？Boolean直接作为filter判断的参数是怎么回事？？

**Comment by S1ngS1ng** [comment]
@Nydia07 [filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) 接收一个回调函数作为参数，这个回调函数的返回值为 `true` 或 `false`，用来决定元素是否保留。[Boolean](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean) 是一个 function，返回值是 `true` 或者 `false`。

`filter` 的回调函数有三个参数，按顺序分别是数组元素、index 和数组本身。而 `Boolean` 方法只接收一个参数。因此，这里就把数组元素传给了 `Boolean()`，然后返回 `true` 或者 `false`

**Comment by seakingxc** [comment]
> 请问能具体解释一下那个最短的代码吗？？Boolean直接作为filter判断的参数是怎么回事？？

new Boolean([value])
参数
value
 可选，用来初始化 Boolean 对象的值。
描述Section
如果第一个参数不是布尔值，则会将其转换为布尔值。如果省略该参数，或者其值为 0、-0、null、false、NaN、undefined、或者空字符串（""），则生成的 Boolean 对象的值为 false。
不要用创建 Boolean 对象的方式将一个非布尔值转化成布尔值，直接将 Boolean 当做转换函数来使用即可：

var x = Boolean(expression);     // 推荐
var x = new Boolean(expression); // 不太好
直接写成Boolean的原因是因为function即使没有定义形参，入参也是可以传的。

**Comment by realcore110** [comment]
最简单做法  return arr.filter( item => {return item ; }
