### ISSUE TITLE
Heed little help on "Escaping Literal Quotes in Strings"

### ISSUE THREAD

**Issue by WilliamSkyWalker** [FreeCodeCampChina/freecodecamp.cn#60]
// need to console.log        ("I am a "double quoted" string inside "double quotes"").
my code:
mystr = "(\"I am a \"double quoted\" string inside \"double quotes\"\").";
console.log(mystr);
It doesn't pass.

**Comment by S1ngS1ng** [comment]
Sure this won't pass.
First, you should use the correct variable, which is `myStr`.
Second, read the instrution please.

![image](https://cloud.githubusercontent.com/assets/13592559/22966032/0c3e7ae8-f326-11e6-9f9d-4bd746207e6b.png)
