### ISSUE TITLE
Sum All Primes

### ISSUE THREAD

**Issue by UxieVerity** [FreeCodeCampChina/freecodecamp.cn#607]
> #### 问题描述
> 在Sum All Primes当中
>结果比正确结果少1
> 如sumPrimes(10)应该为18，但是这里却是17.
> #### 截图> ![test](https://user-images.githubusercontent.com/27985668/54529551-2893d600-49bb-11e9-9f16-9532c0df5c8a.png)

**Comment by UxieVerity** [comment]
> #### 问题描述
> 在Sum All Primes当中
>结果比正确结果少1
> 如sumPrimes(10)应该为18，但是这里却是17.
> #### 截图> ![test](https://user-images.githubusercontent.com/27985668/54529551-2893d600-49bb-11e9-9f16-9532c0df5c8a.png)

**Comment by S1ngS1ng** [comment]
![image](https://user-images.githubusercontent.com/13592559/54552514-7681ed00-496d-11e9-90d7-693cd0ece274.png)
`2 + 3 + 5 + 7 = 17`
