### ISSUE TITLE
翻译容易产生误导

### ISSUE THREAD

**Issue by gricn** [FreeCodeCampChina/freecodecamp.cn#615]
Challenge [Create a Bootstrap Row](https://www.freecodecamp.cn/challenges/create-a-bootstrap-row#?solution=%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%20%20jQuery%20Playground%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fh3%3E%0A%20%0A%3C%2Fdiv%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<div class="container-fluid">
  
  <h3 class="text-primary text-center">
    <div class="row">
      jQuery Playground
    </div>
  </h3>
 
</div>


```
“在 h3 标签**下**创建一个 div 元素”翻译成“在 h3 标签**下方/下面**创建一个 div 元素”是否会更妥当些呢？

**Comment by ghost** [comment]
同样这么认为，翻译修正一下比较好。
