### ISSUE TITLE
字符串怎么就过不去？

### ISSUE THREAD

**Issue by zombieEnginner** [FreeCodeCampChina/freecodecamp.cn#62]
Challenge [Make Instances of Objects with a Constructor Function](https://freecodecamp.cn/challenges/make-instances-of-objects-with-a-constructor-function#?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%201%3B%0A%7D%3B%0A%0A%2F%2F%20%E5%8F%AA%E8%83%BD%E5%9C%A8%E8%BF%99%E4%B8%80%E8%A1%8C%E4%B8%8B%E9%9D%A2%E5%86%99%E4%BB%A3%E7%A0%81%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0Avar%20string%20%3D%20%22string%22%3B%0AmyCar.nickName%20%3D%20string%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

// 只能在这一行下面写代码

var myCar = new Car();
var string = "string";
myCar.nickName = string;

```

**Comment by sunjiaxing1992** [comment]
在我电脑上能实现

**Comment by T2009608** [comment]
你好。string属于js保留字，不要使用保留字作为变量名，这是基本的code素养。当然string被用作变量名能不能通过编译是取决于你的编译环境，不同的编译环境对于关键字和保留字的编译检测有不同的处理方式。建议不要使用string这种意境被用作基本类型的字符作为标识符，以免在不同的编译环境中出现错误。
最后，欢迎交流。

**Comment by liushibuju** [comment]
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

// 只能在这一行下面写代码

var myCar=new Car();
myCar.nickname="sss";  //string不能作为变量名

**Comment by S1ngS1ng** [comment]
跟 `string` 作不作为变量名没关系，`string` 也不是关键词或保留字段。
问题在于 `nickName` 写错了，题目要求的是 `nickname`
