### ISSUE TITLE
Nesting For Loops 正确的代码提交无反应

### ISSUE THREAD

**Issue by ogxqbcyje** [FreeCodeCampChina/freecodecamp.cn#63]
Challenge [Nesting For Loops](https://freecodecamp.cn/challenges/nesting-for-loops#?solution=function%20multiplyAll(arr)%20%7B%0A%20%20var%20product%20%3D%201%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%20%20%2F%2Ffor%20(var%20i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%2F%2Ffor%20(var%20j%20%3D%200%3B%20j%20%3C%20arr%5Bi%5D.length%3B%20j%2B%2B)%20%0A%20%20%20%20%20%20%2F%2Fproduct%20*%3D%20arr%5Bi%5D%5Bj%5D%3B%0A%20%20%20%20%20%20%2F%2Fproduct%20%3D%20product%20*%20arr%5Bi%5D%5Bj%5D%3B%0A%20%20%20%20%20%20%0A%20%20%2F%2F%7D%0Afor%20(var%20i%20%3D%200%3Bi%20%3C%20arr.length%3Bi%2B%2B%20)%7B%0A%20%20%20%20for%20(var%20j%20%3D%200%3Bj%20%3C%20arr%5Bi%5D.length%3Bj%2B%2B%20)%0A%20%20product%3Dproduct*arr%5Bi%5D%5Bj%5D%3B%0A%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20product%3B%0A%7D%0A%0A%2F%2F%20Modify%20values%20below%20to%20test%20your%20code%0AmultiplyAll(%5B%5B1%2C2%5D%2C%5B3%2C4%5D%2C%5B5%2C6%2C7%5D%5D)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function multiplyAll(arr) {
  var product = 1;
  // Only change code below this line
    for (var i = 0; i < arr.length; i++) {
    for (var j = 0; j < arr[i].length; j++) {
      product *= arr[i][j];
      //product = product * arr[i][j];
    }
  }
  // Only change code above this line
  return product;
}

// Modify values below to test your code
multiplyAll([[1,2],[3,4],[5,6,7]]);


```

**Comment by discountry** [comment]
请确认网页加载完毕后重新提交
