### ISSUE TITLE
Build a Tribute Page |观看不了右边视频，是否有其他视频源

### ISSUE THREAD

**Issue by xxlccl** [FreeCodeCampChina/freecodecamp.cn#644]
Challenge [Build a Tribute Page](https://www.freecodecamp.cn/challenges/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

好像VIMEO把GOOGLE的云服务器IP拉黑了，始终打不开视频。想问问是否有其他视频源可以观看

**Comment by LemuelAB** [comment]
您好，您的邮件我已收到，非常感谢
