### ISSUE TITLE
 cloud9注册要绑信用卡，根本用不了

### ISSUE THREAD

**Issue by ShootToThrill** [FreeCodeCampChina/freecodecamp.cn#66]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/chinese

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by cylim** [comment]
@ShootToThrill  练习题并没有强制要求使用Cloud9，网络编辑器速度会有些卡。
如果你真的想要尝试使用Cloud9，可以通过edx上的cs50课程申请。

目前英文版的建议用户使用[HyperDev](http://hyperdev.com)。
参考资料： https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9826

**Comment by discountry** [comment]
可以使用国内云服务商Coding提供的
[Coding WebIDE](https://ide.coding.net/)
