### ISSUE TITLE
有几个jQuery的挑战的检查点没有中文翻译

### ISSUE THREAD

**Issue by ranforce** [FreeCodeCampChina/freecodecamp.cn#68]
有几个jQuery的挑战的检查点没有中文翻译

Challenge [Disable an Element Using jQuery](http://www.freecodecamp.cn/challenges/disable-an-element-using-jquery#?

从《Target Elements by ID Using jQuery 》
到《Disable an Element Using jQuery》

**Comment by S1ngS1ng** [comment]
Addressed in #143
