### ISSUE TITLE
it appears #target5 twice when run tests

### ISSUE THREAD

**Issue by sakuraki777** [FreeCodeCampChina/freecodecamp.cn#7]
Clone an Element Using jQuery

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    _$("#target5").clone().appendTo("#left-well");_

  });
</script>

it does work well when i add the code $("#target5").clone().appendTo("#left-well");
but when i clicked the button {run tests} it appeared the #target5 twice in the #left-well in the display area

**Comment by huluoyang** [comment]
是的，确实会运行两次。
编辑器中的代码会自动运行，效果实时显示在右边。
当你点击run tests后，代码还会运行一次，所以#target5出现了两次。

能通过测试就说明你的代码没问题了。
感谢反馈。^_^
