### ISSUE TITLE
无法提交运行

### ISSUE THREAD

**Issue by gameogre** [FreeCodeCampChina/freecodecamp.cn#71]
Challenge [Generate Random Fractions with JavaScript](http://www.freecodecamp.cn/challenges/generate-random-fractions-with-javascript#?solution=function%20myFunction()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%20%20return%20Math.random()%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/5.0.1.3000 Chrome/47.0.2526.73 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {

  // Only change code below this line.

  return Math.random();

  // Only change code above this line.
}

```

**Comment by discountry** [comment]
请刷新浏览器或清除缓存后再次尝试

**Comment by qsbit** [comment]
换用其他的返回值都可以运行，就是换成这个 return Math.random();不能运行......原因是什么？
