### ISSUE TITLE
这道题有问题 问题是让输出大于5的，可是输出小于5才能完成

### ISSUE THREAD

**Issue by gkilyar** [FreeCodeCampChina/freecodecamp.cn#72]
Challenge [Filter Arrays with filter](https://www.freecodecamp.cn/challenges/filter-arrays-with-filter#?solution=var%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%5D%3B%0A%0A%2F%2F%20%E5%8F%AA%E8%83%BD%E5%9C%A8%E8%BF%99%E4%B8%80%E8%A1%8C%E4%B8%8B%E9%9D%A2%E5%86%99%E4%BB%A3%E7%A0%81%0A%0Avar%20newArray%20%3D%20oldArray.filter(function(val)%20%7B%0A%20%20return%20val%20%3C%3D%205%3B%0A%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// 只能在这一行下面写代码

var newArray = oldArray.filter(function(val) {
  return val <= 5;
});

```

**Comment by loliconer** [comment]
楼主没理解题目的意思，题目是让过滤掉大于5的。

**Comment by gkilyar** [comment]
好吧

**Comment by Rocky1932373216** [comment]
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// 只能在这一行下面写代码

filter = oldArray.filter(function(val) {
  return val<6;
});
var newArray = filter;
