### ISSUE TITLE
这里括号取值什么意思，我总是运行失败

### ISSUE THREAD

**Issue by Wild-Sword** [FreeCodeCampChina/freecodecamp.cn#73]
Challenge [Access MultiDimensional Arrays With Indexes](https://www.freecodecamp.cn/challenges/access-multidimensional-arrays-with-indexes#?solution=%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B1%2C2%2C3%5D%2C%20%5B4%2C5%2C6%5D%2C%20%5B7%2C8%2C9%5D%2C%20%5B%5B10%2C11%2C12%5D%2C%2013%2C%2014%5D%5D%3B%0AmyArray%5B0%5D%3B%0AmyArray%5B0%5D%5B0%5D%3B%0AmyArray%5B0%5D%5B0%5D%20%3D%208%3B%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Avar%20myData%20%3D%20myArray%5B0%5D%5B0%5D%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2896.3 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var myArray = [[1,2,3], [4,5,6], [7,8,9], [[10,11,12], 13, 14]];

myArray[0][0] = 8;
// Only change code below this line.
var myData = myArray[0][0];


```

**Comment by loliconer** [comment]
意思就是让你用索引从myArray里获取到8这个数字。
比如myArray[0]就是[1,2,3]

**Comment by ivcr** [comment]
这tm的神经病的一道题目，fuck!

**Comment by Chrisiven** [comment]
var myData = myArray[0][0];
myData = myArray[2][1];
