### ISSUE TITLE
只是输出顺序不对 不能算错吧

### ISSUE THREAD

**Issue by pflhm2005** [FreeCodeCampChina/freecodecamp.cn#75]
Challenge [Inventory Update](https://www.freecodecamp.cn/challenges/inventory-update#?solution=function%20updateInventory(arr1%2C%20arr2)%20%7B%0A%20%20%20%20%20%20%20%20%2F%2F%20All%20inventory%20must%20be%20accounted%20for%20or%20you're%20fired!%0A%20%20%20%20%20%20%20%20var%20hascontent%3Dfalse%3B%0A%20%20%20%20%20%20%20%20for(var%20i%3D0%3Bi%3Carr2.length%3Bi%2B%2B)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20for(var%20j%3D0%3Bj%3Carr1.length%3Bj%2B%2B)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if(arr2%5Bi%5D%5B1%5D%3D%3Darr1%5Bj%5D%5B1%5D)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hascontent%3Dtrue%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20arr1%5Bj%5D%5B0%5D%2B%3Darr2%5Bi%5D%5B0%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20if(!hascontent)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20arr1.push(arr2%5Bi%5D)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20hascontent%3Dfalse%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20return%20arr1%3B%0A%20%20%20%20%7D%0A%0A%2F%2F%20Example%20inventory%20lists%0Avar%20curInv%20%3D%20%5B%0A%20%20%20%20%5B21%2C%20%22Bowling%20Ball%22%5D%2C%0A%20%20%20%20%5B2%2C%20%22Dirty%20Sock%22%5D%2C%0A%20%20%20%20%5B1%2C%20%22Hair%20Pin%22%5D%2C%0A%20%20%20%20%5B5%2C%20%22Microphone%22%5D%0A%5D%3B%0A%0Avar%20newInv%20%3D%20%5B%0A%20%20%20%20%5B2%2C%20%22Hair%20Pin%22%5D%2C%0A%20%20%20%20%5B3%2C%20%22Half-Eaten%20Apple%22%5D%2C%0A%20%20%20%20%5B67%2C%20%22Bowling%20Ball%22%5D%2C%0A%20%20%20%20%5B7%2C%20%22Toothpaste%22%5D%0A%5D%3B%0A%0AupdateInventory(%5B%5B21%2C%20%22Bowling%20Ball%22%5D%2C%20%5B2%2C%20%22Dirty%20Sock%22%5D%2C%20%5B1%2C%20%22Hair%20Pin%22%5D%2C%20%5B5%2C%20%22Microphone%22%5D%5D%2C%20%5B%5B2%2C%20%22Hair%20Pin%22%5D%2C%20%5B3%2C%20%22Half-Eaten%20Apple%22%5D%2C%20%5B67%2C%20%22Bowling%20Ball%22%5D%2C%20%5B7%2C%20%22Toothpaste%22%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function updateInventory(arr1, arr2) {
        // All inventory must be accounted for or you're fired!
        var hascontent=false;
        for(var i=0;i<arr2.length;i++){
            for(var j=0;j<arr1.length;j++){
                if(arr2[i][1]==arr1[j][1]){
                    hascontent=true;
                    arr1[j][0]+=arr2[i][0];
                    break;
                }
            }
            if(!hascontent){
                arr1.push(arr2[i]);
            }
            hascontent=false;
        }
        return arr1;
    }

// Example inventory lists
var curInv = [
    [21, "Bowling Ball"],
    [2, "Dirty Sock"],
    [1, "Hair Pin"],
    [5, "Microphone"]
];

var newInv = [
    [2, "Hair Pin"],
    [3, "Half-Eaten Apple"],
    [67, "Bowling Ball"],
    [7, "Toothpaste"]
];

updateInventory([[21, "Bowling Ball"], [2, "Dirty Sock"], [1, "Hair Pin"], [5, "Microphone"]], [[2, "Hair Pin"], [3, "Half-Eaten Apple"], [67, "Bowling Ball"], [7, "Toothpaste"]]);

```

**Comment by loliconer** [comment]
没排序当然过不了测试。
