### ISSUE TITLE
题目错误

### ISSUE THREAD

**Issue by VZIKL** [FreeCodeCampChina/freecodecamp.cn#76]
check-for-palindromes的palindrome("0_0 (: /-\ :) 0-0")

**Comment by discountry** [comment]
原题目确实是这样的袄

**Comment by VZIKL** [comment]
@discountry  我是想说这个字符串怎么看都不是回文吧？ :D 一个0-0 一个0_0

**Comment by discountry** [comment]
@VZIKL 你没有完整理解题目意思袄。

**Comment by AnClark** [comment]
题目确实没有问题，但是，“\”在字符串里会被认成转义字符的前导符，所以才会导致这个例子通不过。

**Comment by S1ngS1ng** [comment]
@AnClark 如果例子通不过，那多半是代码中的正则写的有问题。换个思路写就可以了。
另外，就算是“前导符”也不影响，因为反正后面是一个空格

**Comment by Lilysunstrider** [comment]
Same problem. The expression "0_0 (: /-\ :) 0-0" is in fact 0_0 (: /- :) 0-0, therefore not symmetric. A correct function will return false.

**Comment by S1ngS1ng** [comment]
@Lilysunstrider Please post your "correct" function here.
According to the description, you should only check for alphabets (case insensitive) and numbers. Hence all symbols (including spaces) should be removed.
