### ISSUE TITLE
从2016年8月份开始twichtv的API调用需要使用Client-Id作为身份验证

### ISSUE THREAD

**Issue by YQ-Jiang** [FreeCodeCampChina/freecodecamp.cn#77]
Challenge [Use the Twitchtv JSON API](https://www.freecodecamp.cn/challenges/use-the-twitchtv-json-api) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
从2016年8月份开始twichtv的API调用需要使用Client-Id作为身份验证，如果没有将会出现如下返回：
{"error":"Bad Request","status":400,"message":"No client id specified"}
关于Client-Id的申请：https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843#.bc64i4ukn
注：示例中所有的API调用都挂了，错误均如上所示。

**Comment by zhu-xiaoming** [comment]
@YQ-Jiang 那个 client-id 注册的时候，要填写 Redirect URI ，我应该填什么？codepen的链接？

**Comment by hanjinjun** [comment]
@little-tomorrow 我用的是新建的pen的链接，已经可以成功请求，如果你懒得再注册，可以使用我的
`'Client-ID': 'q443o8gke0lrzh0bhvlzhv4wd1kw6v'`
应该是没有问题的。

**Comment by S1ngS1ng** [comment]
@hanjinjun 请添加到 wiki。感谢
