### ISSUE TITLE
按照教程中使用gdgdocs的链接可以正常引入字体，但是设置class属性后，仍然提示p标签内字体不正确。

### ISSUE THREAD

**Issue by wlxfx** [FreeCodeCampChina/freecodecamp.cn#78]
Challenge [Import a Google Font](https://www.freecodecamp.cn/challenges/import-a-google-font#?solution=%3Clink%20href%3D%22https%3A%2F%2Ffonts.gdgdocs.org%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3Bfont-family%3ALobster%3B%0A%20%20%7D%0A%0A%20%20.op%7Bcolor%3Ablue%3B%0A%20%20%20%20font-size%3A16px%3B%0A%20%20%20%20font-family%3ALobster%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20%20class%3D%22red-text%22%3E%E5%9C%A8googleapi%3C%2Fp%3E%0A%3Cp%20%20class%3D%22red-text%22%3E%E9%87%8D%E5%88%9B%E3%80%82abcdefg%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="https://fonts.gdgdocs.org/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;font-family:Lobster;
  }

  .op{color:blue;
    font-size:16px;
    font-family:Lobster;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p  class="red-text">在googleapi</p>
<p  class="red-text">重创。abcdefg</p>

```

**Comment by discountry** [comment]
仔细看题目的报错，段落的字体仍需设置为`Monospace`
```css
p {
    font-family: Monospace;
  }
```
