### ISSUE TITLE
HOW IS GOING ON?

### ISSUE THREAD

**Issue by yesusu9527** [FreeCodeCampChina/freecodecamp.cn#8]
Challenge [Inform with the Paragraph Element](https://freecodecamp.cn/challenges/inform-with-the-paragraph-element#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3E%E6%88%91%E5%AE%B6%E7%9A%84%E7%8C%AB%E5%92%AA%3C%2Fh2%3E%0A%3Ch3%3EHello%20Paragrah%3C%2Fh3%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html
<h1>Hello World</h1>
<h2>我家的猫咪</h2>
<h3>Hello Paragrah</h3>
```

**Comment by yesusu9527** [comment]
I DON'T KNOW WHY ITS NOT WORK

**Comment by zeallean** [comment]
不是太明白你的问题。这个练习就是了解<p>段落标签的用法。只需要在下方添加一个段落标签就可以了。有什么问题呢？

**Comment by Zhongwei1986** [comment]
<h1>Hello World</h1>
<h2>我家的猫咪</h2>
<p>Hello Paragraph</p>

---

<h3></h3>is wrong，please use <p></p>instead.
