### ISSUE TITLE
不清楚为啥,反正就是错误的,这么简单的问题

### ISSUE THREAD

**Issue by BestHYC** [FreeCodeCampChina/freecodecamp.cn#81]
Challenge [Chaining If Else Statements](https://www.freecodecamp.cn/challenges/chaining-if-else-statements#?solution=function%20myTest(num)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20%09%09%20%20if(num%20%3C%205)%7Breturn%20%22Tiny%22%3B%7D%0A%09%09%20%20else%20if(num%20%3C%2010)%7Breturn%20%22Small%22%3B%7D%0A%09%09%20%20else%20if(num%20%3C%2015)%7Breturn%20%22Medium%22%3B%7D%0A%09%09%20%20else%20if(num%20%3C%2020)%7Breturn%20%22large%22%3B%7D%0A%09%09%20%20else%7Breturn%20%22Huge%22%3B%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(7)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(num) {
  // Only change code below this line
  
  		  if(num < 5){return "Tiny";}
		  else if(num < 10){return "Small";}
		  else if(num < 15){return "Medium";}
		  else if(num < 20){return "large";}
		  else{return "Huge";}
  // Only change code above this line
}

// Change this value to test
myTest(7);

```

**Comment by IMDAS** [comment]
large开头应该是大写Large

**Comment by S1ngS1ng** [comment]
拼写错误，不是 issue
