### ISSUE TITLE
野狗云没有GitHub第三方登录啊？

### ISSUE THREAD

**Issue by yukingcome** [FreeCodeCampChina/freecodecamp.cn#82]
Challenge [Design a danmu app](https://freecodecamp.cn/challenges/design-a-danmu-app) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by JoyceYueHu** [comment]
![capture](https://user-images.githubusercontent.com/30109018/29506279-749a8060-867d-11e7-9c99-309cfa82bced.JPG)
可否更多解释一下如何  “//在www.wildog.com 创建一个应用，自动生成一个url,替换下边url”？

**Comment by xifanmitang** [comment]
貌似创业公司停止运营了  
 注册关闭了
