### ISSUE TITLE
代码编译已通过，但提交失败

### ISSUE THREAD

**Issue by NotFinally** [FreeCodeCampChina/freecodecamp.cn#83]
Challenge [No repeats please](https://freecodecamp.cn/challenges/no-repeats-please#?solution=var%20result%20%3D%20%5B%5D%3B%0Avar%20a%20%2Cb%2Cnum%20%3D%200%3B%0Afunction%20fun(arg%2Ci)%0A%7B%0A%20%20if(arg.length-1%20%3D%3D%20i)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20result.push(arg)%3B%0A%20%20%20%20%7D%0A%20%20else%0A%20%20%20%20%7B%0A%20%20%20%20%20%20for(var%20j%20%3D%20i%3Bj%3Carg.length%3Bj%2B%2B)%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20a%20%3D%20arg.split(%22%22)%3B%0A%20%20%20%20%20%20%20%20%20%20b%20%3D%20a%5Bj%5D%3B%0A%20%20%20%20%20%20%20%20%20%20a%5Bj%5D%20%3D%20a%5Bi%5D%3B%0A%20%20%20%20%20%20%20%20%20%20a%5Bi%5D%20%3D%20b%3B%0A%20%20%20%20%20%20%20%20%20%20arg%20%3D%20a.join(%22%22)%3B%0A%20%20%20%20%20%20%20%20%20%20fun(arg%2Ci%2B1)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D%0Afunction%20permAlone(str)%20%7B%0A%20%20fun(str%2C0)%3B%0A%20%20for(var%20x%20%3D0%3Bx%3Cresult.length%3Bx%2B%2B)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20for(var%20y%20%3D%200%3By%3Cresult%5Bx%5D.length-1%3By%2B%2B)%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20if(result%5Bx%5D%5By%5D%3D%3Dresult%5Bx%5D%5By%2B1%5D)%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20if(result%5Bx%5D.length%20-1%3D%3D%20y)%0A%20%20%20%20%20%20%20%20num%20%2B%3D1%3B%0A%20%20%20%20%7D%0A%20%20return%20num%3B%0A%7D%0ApermAlone(%22aab%22)%20%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.1708.400 QQBrowser/9.5.9635.400</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var result = [];
var a ,b,num = 0;
function fun(arg,i)
{
  if(arg.length-1 == i)
    {
      result.push(arg);
    }
  else
    {
      for(var j = i;j<arg.length;j++)
        {
          a = arg.split("");
          b = a[j];
          a[j] = a[i];
          a[i] = b;
          arg = a.join("");
          fun(arg,i+1);
        }
    }
}
function permAlone(str) {
  fun(str,0);
  for(var x =0;x<result.length;x++)
    {
      for(var y = 0;y<result[x].length-1;y++)
        {
          if(result[x][y]==result[x][y+1])
            {
              break;
            }
        }
      if(result[x].length -1== y)
        num +=1;
    }
  return num;
}
permAlone("aab") ;
```

**Comment by xuezechao2012** [comment]
多刷新几次页面ctrl ＋f5，再不行重新打开这个页面，再提交，我一般都这样解决了，目前做到第一个小项目了。


发自网易邮箱大师
在2016年12月22日 22:01，NotFinally 写道:

Challenge No repeats please has an issue.
User Agent is: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.1708.400 QQBrowser/9.5.9635.400.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

var result = [];
var a ,b,num =0;
functionfun(arg,i)
{
  if(arg.length-1== i)
    {
      result.push(arg);
    }
  else
    {
      for(var j = i;j<arg.length;j++)
        {
          a =arg.split("");
          b = a[j];
          a[j] = a[i];
          a[i] = b;
          arg =a.join("");
          fun(arg,i+1);
        }
    }
}
functionpermAlone(str) {
  fun(str,0);
  for(var x =0;x<result.length;x++)
    {
      for(var y =0;y<result[x].length-1;y++)
        {
          if(result[x][y]==result[x][y+1])
            {
              break;
            }
        }
      if(result[x].length-1== y)
        num +=1;
    }
  return num;
}
permAlone("aab") ;

**Comment by wudifeixue** [comment]
这种算是题的检测没办法处理的情况吧。首先不能在全局定义变量，其次必须在一个function内完成题目。这样就可以成功提交了。
