### ISSUE TITLE
提示和答案不一样

### ISSUE THREAD

**Issue by ghost** [FreeCodeCampChina/freecodecamp.cn#84]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/chinese

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by wudifeixue** [comment]
请好好叙述你遇到的问题。
