### ISSUE TITLE
这道题的返回一定要标准顺序？我是倒序遍历的

### ISSUE THREAD

**Issue by yiyunShm** [FreeCodeCampChina/freecodecamp.cn#85]
Challenge [Return Largest Numbers in Arrays](http://www.freecodecamp.cn/challenges/return-largest-numbers-in-arrays#?solution=function%20largestOfFour(arr)%20%7B%0A%20%20%2F%2F%20You%20can%20do%20this!%0A%20%20var%20len%2C%20maxOne%2C%20res%20%3D%20%5B%5D%3B%0A%20%20%0A%20%20len%20%3D%20arr.length%3B%0A%20%20while(len--)%20%7B%0A%20%20%20%20maxOne%20%3D%20Math.max.apply(null%2C%20arr%5Blen%5D)%3B%0A%20%20%20%20res.push(maxOne)%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20res.reverse()%3B%0A%7D%0A%0AlargestOfFour(%5B%5B4%2C%205%2C%201%2C%203%5D%2C%20%5B13%2C%2027%2C%2018%2C%2026%5D%2C%20%5B32%2C%2035%2C%2037%2C%2039%5D%2C%20%5B1000%2C%201001%2C%20857%2C%201%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function largestOfFour(arr) {
  // You can do this!
  var len, maxOne, res = [];
  
  len = arr.length;
  while(len--) {
    maxOne = Math.max.apply(null, arr[len]);
    res.push(maxOne);
  }
  
     // return res;
     return res.reverse();
}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

```

**Comment by S1ngS1ng** [comment]
@yiyunShm 我测试了下，是可以通过的。清除下缓存再试试吧。如果有问题的话，reopen 就好
