### ISSUE TITLE
Pass the challenge uncorrectly

### ISSUE THREAD

**Issue by leolieo** [FreeCodeCampChina/freecodecamp.cn#86]
Challenge [Slasher Flick](https://freecodecamp.cn/challenges/slasher-flick#?solution=function%20slasher(arr%2C%20howMany)%20%7B%0A%20%20%2F%2F%20it%20doesn't%20always%20pay%20to%20be%20first%0A%20%20var%20arr1%20%3Darr.slice(howMany)%3B%0A%20%20return%20arr1%3B%0A%7D%0A%0Aslasher(%5B1%2C%202%2C%203%5D%2C%202)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function slasher(arr, howMany) {
  // it doesn't always pay to be first
  var arr1 =arr.slice(howMany);
  return arr1;
}

slasher([1, 2, 3], 2);

```
I can pass this challenge by the code above,but I think it's not the right answer.
Maybe the requirement should be change.

**Comment by S1ngS1ng** [comment]
Well, I believe this answer is correct. This is exactly how `.slice` work in JavaScript.

Here is the [reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice). You might notice that both parameters of `.slice` are optional.

**Comment by Sandaydi** [comment]
```
  arr.splice(0, howMany);
  return arr;
```
 or
`  return arr.slice(howMany, arr.length);`
