### ISSUE TITLE
I can not use how-to-npm.

### ISSUE THREAD

**Issue by strange-life** [FreeCodeCampChina/freecodecamp.cn#89]
Challenge [Manage Packages with NPM](https://freecodecamp.cn/challenges/manage-packages-with-npm) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
When I run how-to-npm, I saw this "(node:6496) DeprecationWarning: Calling an asynchronous function without callback is deprecated."

**Comment by wudifeixue** [comment]
Follow the instructions, everything works fine. I have just tested it. 
![image](https://cloud.githubusercontent.com/assets/7316929/23003593/124a9f6e-f3af-11e6-928a-f6ef38405955.png)
