### ISSUE TITLE
修改的颜色提示是red  不是blue

### ISSUE THREAD

**Issue by ms66** [FreeCodeCampChina/freecodecamp.cn#90]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/chinese

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by S1ngS1ng** [comment]
上面的内容全是模板，请填入相关信息。至少，填上题目链接和你的代码。谢谢

**Comment by wudifeixue** [comment]
这不是错误，是为了测试学生理解而专门改了颜色
