### ISSUE TITLE
为什么第一个参数arr的length用作for循环会报错，说是一个无限循环

### ISSUE THREAD

**Issue by orikan** [FreeCodeCampChina/freecodecamp.cn#91]
Challenge [Drop it](https://www.freecodecamp.cn/challenges/drop-it#?solution=function%20drop(arr%2C%20func)%20%7B%0A%20%20%2F%2F%20Drop%20them%20elements.%0A%20%20var%20arrEle%20%3D%20arr%3B%0A%20%20for(var%20i%20%3D%200%3Bi%20%3C%20arr.length%3Bi%2B%2B)%7B%0A%20%20%20%20arrEle.push(1)%3B%0A%20%20%7D%0A%20%20return%20arrEle%3B%0A%7D%0A%0Adrop(%5B1%2C%202%2C%203%2C%204%5D%2C%20function(n)%20%7Breturn%20n%20%3E%3D%203%3B%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function drop(arr, func) {
  // Drop them elements.
  var arrEle = arr;
  for(var i = 0;i < arr.length;i++){
    arrEle.push(1);
  }
  return arrEle;
}

drop([1, 2, 3, 4], function(n) {return n >= 3;});

```

**Comment by T2009608** [comment]
你好。在js中关于复合类型的复制是址传递的。上述代码中，var arrEle = arr 使得两个数组型的复合变量关联到了一起，其中一个改变另外一个跟着改变。
使用arrEle.push（1）不仅仅改变了arrEle同时也改变了arr。所以arr.length是不断增加的。既然如此，无限循环也就产生了。

**Comment by wudifeixue** [comment]
你写了个死循环，死循环机制保护了，当在顶部添加了//noprotect 来去掉死循环保护的时候，成功崩掉了页面
