### ISSUE TITLE
怎么删除最后一行的-->

### ISSUE THREAD

**Issue by lotus0099** [FreeCodeCampChina/freecodecamp.cn#92]
Challenge [Uncomment HTML](http://www.freecodecamp.cn/challenges/uncomment-html#?solution=%3C!----%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3E%E6%88%91%E5%AE%B6%E7%9A%84%E7%8C%AB%E5%92%AA%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A%3C!--%3E%0A%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
怎么删除最后一行的-->
My code:
```html
<!---->
<h1>Hello World</h1>

<h2>我家的猫咪</h2>

<p>Hello Paragraph</p>
-->





```

**Comment by S1ngS1ng** [comment]
![image](https://cloud.githubusercontent.com/assets/13592559/22966371/90f65ee4-f327-11e6-858f-42e9b2e1fcb1.png)

所以你要把所有的注释都删除

**Comment by hjwe123** [comment]
<h1>Hello World</h1>

<h2>我家的猫咪</h2>

<p>Hello Paragraph</p>


may anyone can tell me how to correct？thanks！
