### ISSUE TITLE
JavaScript 不等于比较运算符!=  答案不全 val != 99 或者 val !="99" 都可以

### ISSUE THREAD

**Issue by KaapoMarcus** [FreeCodeCampChina/freecodecamp.cn#95]
Challenge [Comparison with the Inequality Operator](http://www.w3cschool.cn/codecamp/comparison-with-the-inequality-operator.html#?solution=%2F%2F%20Setup%0Afunction%20myTest(val)%20%7B%0Aif%20(val%20!%3D%2099)%20%7B%20%2F%2F%20Change%20this%20line%0Areturn%20%22Not%20Equal%22%3B%0A%7D%0Areturn%20%22Equal%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(1)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function myTest(val) {
if (val != 99) { // Change this line
return "Not Equal";
}
return "Equal";
}

// Change this value to test
myTest(1);

```

**Comment by wudifeixue** [comment]
我明白你意思，确实 if (val != “99”) 也应该过测试，不过你给的链接并不是freecodecamp.cn
我等下就发个PR改了这个问题

**Comment by wudifeixue** [comment]
#153 will fix this after merge.
