### ISSUE TITLE
Friendly Date Ranges

### ISSUE THREAD

**Issue by standself** [FreeCodeCampChina/freecodecamp.cn#96]
这个挑战里面的test输出是以2016年为当前年份来计算的，现在的年份是2017。这样test就过不了。

**Comment by S1ngS1ng** [comment]
我试着写了下，是可以通过的。方便的话，请把你的代码发到这里。谢谢

**Comment by standself** [comment]
你好，抱歉晚回。我找了下代码，原来没有测试通过的代码，网站上没有保存。。。现在我也不知道哪里没通过了。只记得如果是通过new Date()来获取当前时间，得到今年年份，可能是会和题目默认的今年年份有冲突。如果没有的话，那就是当时我的代码没考虑全。有时间的话，我再试试。谢谢。

 




------------------ 原始邮件 ------------------
发件人: "Sing Liu";<notifications@github.com>;
发送时间: 2017年2月16日(星期四) 中午11:24
收件人: "FreeCodeCampChina/freecodecamp.cn"<freecodecamp.cn@noreply.github.com>; 
抄送: "习志辉"<799533994@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [FreeCodeCampChina/freecodecamp.cn] Friendly Date Ranges (#96)




我试着写了下，是可以通过的。方便的话，请把你的代码发到这里。谢谢

**Comment by acfasj** [comment]
对的，只好改成了2016，刚好也是这题
