### ISSUE TITLE
检索JSON对象 myStorage 中嵌套属性 glove box 的值。 求助以下写法。

### ISSUE THREAD

**Issue by KaapoMarcus** [FreeCodeCampChina/freecodecamp.cn#97]
json 对象如下******

var myStorage = {
"car": {
"inside": {
"glove box": "maps",
"passenger seat": "crumbs"
 },
"outside": {
"trunk": "jack"
}
}
};

var gloveBoxContents = myStorage.car.inside["glove box"];  //提供的标准答案

下面俩答案也符合规则吧 不知道为啥运行处结果 却不通过？？？
//////  myStorage["car"].inside["glove box"];
////// myStorage.car["inside"]["glove box"];

**Comment by S1ngS1ng** [comment]
确实是符合规则的。不过一般来说，都是能用 `.` 的时候就不用 `[]`，原因有两点。一是性能原因，`.` 会比 `[]` 稍快。二是安全性，你可以试试，如果中括号里面加上某段代码，比如 `[alert(1)]`，是会执行的

因此，更推荐用 `.`
