### ISSUE TITLE
这是不是又一个bug呀？格式不是这样的吗

### ISSUE THREAD

**Issue by shendengnian** [FreeCodeCampChina/freecodecamp.cn#99]
Challenge [Style the HTML Body Element](http://www.freecodecamp.cn/challenges/style-the-html-body-element#?solution=%3Cstyle%20type%3D%22text%2Fcss%22%3E%0A%20%20body%7B%0A%20%20%20%20background-color%3Ablack%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style type="text/css">
  body{
    background-color:black;
  }
</style>

```

**Comment by shendengnian** [comment]
这是不是BUG呢

**Comment by shendengnian** [comment]
已解决了，建议有点基础的，不用在style元素中加type，不然会过不了

**Comment by ghost** [comment]
新的css3和js已经不需要再额外声明type,默认就是css和javascript,。随着浏览器版本的升级，有时候添加了反倒是会报错

**Comment by wudifeixue** [comment]
这个你都一定要改也是佩服，但是何苦呢
